[android] Refactor external storage scanning
organicmaps/organicmaps pull request #1000
Opened 2021-08-04 08:49 UTC by rtsisyk

- Add verbose logging.
- Add Framework.nativeGetWritableDir() into consideration.
- Set mCurrentStorageIndex if a default directory is selected.
- Remove unneeded getAnbsolutePath() from setStoragePath().
- Don't call updateExternalStorages() on failure.
- Don't call updateExternalStorages() twice on success.

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2021-08-04 08:52 UTC, rtsisyk commented
```
2021-08-04 11:38:09.101 7262-7262/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Scanning storages:
2021-08-04 11:38:09.113 7262-7262/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Accepted /storage/6AC5-9345/Android/data/app.organicmaps.debug/files/: 62618730496 bytes available
2021-08-04 11:38:09.114 7262-7262/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Accepted /data/data/app.organicmaps.debug/files/: 42423873536 bytes available
2021-08-04 11:38:09.115 7262-7262/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Rejected /data/data/app.organicmaps.debug/files/: a duplicate
2021-08-04 11:38:09.116 7262-7262/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Rejected /data/data/app.organicmaps.debug/files/: a duplicate
2021-08-04 11:38:09.116 7262-7262/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: DONE
2021-08-04 11:38:11.764 7262-11964/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Moving maps from /data/data/app.organicmaps.debug/files/ to /storage/6AC5-9345/Android/data/app.organicmaps.debug/files/
2021-08-04 11:38:11.779 7262-11964/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Moving /data/data/app.organicmaps.debug/files/WorldCoasts.mwm to /storage/6AC5-9345/Android/data/app.organicmaps.debug/files/WorldCoasts.mwm
2021-08-04 11:38:12.082 7262-11964/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Moving /data/data/app.organicmaps.debug/files/World.mwm to /storage/6AC5-9345/Android/data/app.organicmaps.debug/files/World.mwm
2021-08-04 11:38:14.141 7262-11964/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Moving /data/data/app.organicmaps.debug/files/210703/Russia_Moscow Oblast_West.mwm to /storage/6AC5-9345/Android/data/app.organicmaps.debug/files/210703/Russia_Moscow Oblast_West.mwm
2021-08-04 11:38:21.330 7262-11964/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Moving /data/data/app.organicmaps.debug/files/210703/Russia_Moscow.mwm to /storage/6AC5-9345/Android/data/app.organicmaps.debug/files/210703/Russia_Moscow.mwm
2021-08-04 11:38:24.804 7262-11964/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Moving /data/data/app.organicmaps.debug/files/210703/UK_England_Greater London.mwm to /storage/6AC5-9345/Android/data/app.organicmaps.debug/files/210703/UK_England_Greater London.mwm
2021-08-04 11:38:31.816 7262-11964/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: DONE
2021-08-04 11:38:32.188 7262-7262/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Scanning storages:
2021-08-04 11:38:32.208 7262-7262/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Accepted /storage/6AC5-9345/Android/data/app.organicmaps.debug/files/: 62413078528 bytes available
2021-08-04 11:38:32.212 7262-7262/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Accepted /data/data/app.organicmaps.debug/files/: 42629001216 bytes available
2021-08-04 11:38:32.232 7262-7262/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Rejected /storage/6AC5-9345/Android/data/app.organicmaps.debug/files/: a duplicate
2021-08-04 11:38:32.250 7262-7262/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: Rejected /storage/6AC5-9345/Android/data/app.organicmaps.debug/files/: a duplicate
2021-08-04 11:38:32.250 7262-7262/app.organicmaps.debug I/com.mapswithme.maps.settings.StoragePathManager: DONE
```

2021-08-04 09:00 UTC, vng requested changes

2021-08-04 09:00 UTC, vng commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
>          if (!TextUtils.isEmpty(configDir) && configDir.equals(path))
Или если я не так понимаю, чем отличаются:
- String configDir = Config.getStoragePath();
- String currentDir = Framework.nativeGetWritableDir();

2021-08-04 09:18 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +          LOGGER.i(TAG, "Rejected " + path + ": not a directory");
Зачем?

2021-08-04 09:18 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
>          if (!TextUtils.isEmpty(configDir) && configDir.equals(path))
Да по идее не должны как раз таки отличаться. Единственный кейс который я вижу - на старте  Framework.nativeGetWritableDir() должен быть пустым, а  Config.getStoragePath() нет.

2021-08-04 09:18 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +          throw new IOException("Failed to move " + oldFiles[i].getPath() + " to " + newFiles[i].getPath());
ТАкое ощущение, что нет.

2021-08-04 09:18 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +    LOGGER.i(TAG, "DONE");
ОК

2021-08-04 09:36 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
>          if (!TextUtils.isEmpty(configDir) && configDir.equals(path))
Поменял.

2021-08-04 09:36 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
>      if (!TextUtils.isEmpty(configDir) && mCurrentStorageIndex == -1)
Поменял, смотри выше.

2021-08-04 09:36 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +          throw new IOException("Failed to move " + oldFiles[i].getPath() + " to " + newFiles[i].getPath());
Вообще не понятно нахрена там try catch был и эксепшен кидался. Переделал.

2021-08-04 09:37 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
>        StorageUtils.removeFilesInDirectory(newDir, newFiles);
Стоит. Проблема в том, что File.delete() вообще ничего не выкидывает и ошибку получить невозможно. Надо удалять файлы как-то по-другому. 

```
Note that the java.nio.file.Files class defines the delete method to throw an IOException when a file cannot be deleted. This is useful for error reporting and to diagnose why a file cannot be deleted.
```

java.nio.file.Files  на нашей версии недоступен.

2021-08-04 10:12 UTC, vng commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +          LOGGER.i(TAG, "Rejected " + path + ": not a directory");
Ну типа фильтр по severity логов. Info этоткогда штатный лог

2021-08-04 10:16 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +          LOGGER.i(TAG, "Rejected " + path + ": not a directory");
Я запустил adb на релизном приложении из стора и почему-то вижу там даже дебаг...

2021-08-04 10:41 UTC, vng commented
Xxx

2021-08-04 10:42 UTC, vng commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +    LOGGER.i(TAG, "End moving maps");
Почему решил убрать обработку exception?

2021-08-04 10:42 UTC, vng commented on android/src/com/mapswithme/util/StorageUtils.java
> +    for (File file : files)
Почему убрал exception?

2021-08-04 11:26 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +    LOGGER.i(TAG, "End moving maps");
File.delete() не бросает IOException, а тупо возвращает true/false. Такой дизайн апишки сделали в Java. SecurityException не то, что там реально могло вылетать. Фактически, там вставили catch на не понятно что, тогда как реальная ошибка удаления игнорируется.

2021-08-04 11:41 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +      // Framework.nativeGetWritableDir() is empty on the start.
Это не должно быть возможным. Что за кейз?

WritableDir должна инициализироваться до вызова этого кода, в недрах конструирования фреймворка. А если это не так, тогда инициализация должна быть всегда в одном месте, например здесь.

2021-08-04 11:41 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +    LOGGER.i(TAG, "Begin scanning storages");
Этот код всегда вызывается при инициализации? Или только когда входим в сеттинги?

Какая сейчас логика если я мувну карты на СД, затем достану карту, запущу аппу. А потом снова вставлю СД и запущу аппу.

2021-08-04 11:41 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +          LOGGER.i(TAG, "Rejected " + path + ": not a directory");
В ведре все логи пишутся всегда. Разделение для удобства визуальной фильтрации, чтобы на мусор не смотреть.

Например, `adb logcat -v color` подсветит, можно вообще не выводить.

2021-08-04 11:42 UTC, vng commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +          LOGGER.i(TAG, "Rejected " + path + ": not a directory");
Фильтровать потом будем мы. Ну смотри сам. Я считаю что если ситуация нештатная (диск полон или неписабельно) - надо Warning. Info - это типа Start scanning ..

2021-08-04 11:48 UTC, vng commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +    LOGGER.i(TAG, "Begin scanning storages");
Кстати да, нам надо еще залогировать просто инициализацию storage из settings.ini
Кейз что я говорил сегодня - юзер стартует прилагу, а она "забыла" где лежат карты.

2021-08-04 11:48 UTC, vng commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +    LOGGER.i(TAG, "End moving maps");
mkdirs тоже не кидает?

2021-08-04 14:33 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
>        StorageUtils.removeFilesInDirectory(newDir, newFiles);
У нас в коде StorageUtils есть `file.delete();` без проверки возвращаемого значения. А проверять нужно.

2021-08-04 20:29 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +    LOGGER.i(TAG, "End moving maps");
mkdirs кидает SecurityException

2021-08-04 20:30 UTC, biodranik commented on android/src/com/mapswithme/util/StorageUtils.java
> +    for (File file : files)
Тут для File.delete() не нужно, а вот bool возвращаемый проверять нужно, и хотя бы в лог ругаться.

2021-08-05 06:35 UTC, vng commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +    LOGGER.i(TAG, "End moving maps");
Ок, тогда убираем, да

2021-08-05 07:20 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
>        StorageUtils.removeFilesInDirectory(newDir, newFiles);
Решили что не будем это сейчас менять.

2021-08-05 07:21 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +          LOGGER.i(TAG, "Rejected " + path + ": not a directory");
так тут штатная ситуация в целом

2021-08-05 07:23 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +    LOGGER.i(TAG, "End moving maps");
>mkdirs кидает SecurityException

В нашем случае это несуществующая ситуация.

2021-08-05 07:23 UTC, rtsisyk commented on android/src/com/mapswithme/util/StorageUtils.java
> +    for (File file : files)
Не будем сейчас это место трогать.

2021-08-05 07:24 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +      // Framework.nativeGetWritableDir() is empty on the start.
>WritableDir должна инициализироваться до вызова этого кода, в недрах конструирования фреймворка. А если это не так, тогда инициализация должна быть всегда в одном месте, например здесь.

Интересно чем же она должна инициализировать, если инициализируемое значение возвращается findMapsStorage, которая зовёт эту функцию.

2021-08-05 07:25 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +    LOGGER.i(TAG, "Begin scanning storages");
>Этот код всегда вызывается при инициализации? Или только когда входим в сеттинги?

Всегда вызывается.

2021-08-05 07:45 UTC, vng approved these changes

2021-08-05 09:50 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
>          if (!TextUtils.isEmpty(configDir) && configDir.equals(path))
Разобрались, починили.

2021-08-05 09:50 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +    LOGGER.i(TAG, "End moving maps");
https://github.com/organicmaps/organicmaps/issues/1010

2021-08-05 09:50 UTC, rtsisyk commented on android/src/com/mapswithme/util/StorageUtils.java
> +    for (File file : files)
https://github.com/organicmaps/organicmaps/issues/1010

2021-08-05 09:50 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +    LOGGER.i(TAG, "Begin scanning storages");
Разобрались, починили.

2021-08-05 10:08 UTC, vng requested changes

2021-08-05 10:08 UTC, vng commented on android/src/com/mapswithme/util/Config.java
> -  }
Ты убрал функцию set, но путь ты читаешь из Config.getStoragePath()
- Кто-то еще устанавливает где-то по ключу KEY_APP_STORAGE ?
- Может лучше убрать и getStoragePath а путь получать из nativeGetWritableDir ?

2021-08-05 10:15 UTC, rtsisyk commented on android/src/com/mapswithme/util/Config.java
> -  }
Config.getStoragePath() читает из settings.ini, не так ли? Мы также обновили SetWritableDir чтобы оно всегда обновляло этот самый settings.ini. Проблема с nativeGetWritableDir() в том, что при старте он пустой. Ничего не инициализировано. Есть только конфиг. Раньше там бралось из nativeGetWritableDir(), потом из конфига. Я подумал, и мне показалось, что брать только из конфига более логично тогда.

2021-08-05 11:10 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +        if (!dir.canWrite() || !StorageUtils.isDirWritable(path))
Эта проверка нужна ТОЛЬКО в одном случае: когда показываем юзеру список, куда можно мувнуть карты.

Проверка на свободное место не нужна вообще, т.к. юзер увидит глазами, что мало места, и пойдёт чистить.

А в случае, когда в сеттингах уже выбрана папка, и происходит запуск проги, эти проверки НЕ нужны. Потому что место на флешке может закончиться по разным причинам. Но карты будут работать дальше, пока юзер его не почистит. В этом случае нужно просто выводить юзеру тост "нет свободного места там-то" и работать дальше с этим диском.

2021-08-05 11:10 UTC, biodranik commented on android/src/com/mapswithme/util/Config.java
> -  }
При каком именно старте пустой? Только при самом первом?

2021-08-05 11:32 UTC, vng commented on android/src/com/mapswithme/util/Config.java
> -  }
Я перепутал, да. getString(KEY_APP_STORAGE) читает то что надо!

2021-08-05 11:32 UTC, vng approved these changes

2021-08-05 11:46 UTC, vng commented on android/src/com/mapswithme/maps/settings/StoragePathManager.java
> +        if (!dir.canWrite() || !StorageUtils.isDirWritable(path))
Я про это писал в чате, сейчас такой фикс усложнит код. Оставим на один из след релизов когда будем брать путь всегда из настроек?

2021-08-05 14:36 UTC, biodranik commented on android/src/com/mapswithme/util/Config.java
> -  }
@rtsisyk отпишись потом на мой вопрос выше, пожалуйста.

2021-08-05 14:37 UTC, merged