[android][ios] Upload metadata and screenshots to AppStore / GooglePlay
organicmaps/organicmaps pull request #1035
Opened 2021-08-07 19:13 UTC by rtsisyk

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2021-08-07 21:22 UTC, biodranik requested changes

2021-08-07 21:22 UTC, biodranik commented on .github/workflows/appstore-check-metadata.yaml
> +        run: ./fastlane.sh check_metadata
Тут будет проверка на длину?

2021-08-07 21:22 UTC, biodranik commented on .github/workflows/appstore-upload-metadata.yaml
> +      - master
А валидация на длину будет проходить до мержа в мастер?

2021-08-07 21:22 UTC, biodranik commented on .github/workflows/googleplay-upload-metadata.yaml
> +      - android/src/google/play/**
Обязательно в src? Почему нельзя, например, android/metadata?

2021-08-07 21:22 UTC, biodranik commented on .gitignore
> +android/src/google/play/listings/??-??/graphics
А что тут?

2021-08-07 21:22 UTC, biodranik commented on android/src/google/play/listings/en-US/full-description.txt
> +Organic Map is <b>free from trackers and other bad stuff</b>:
Это четвёртое место, где я прошу исправить. Хватит плодить копипасту плохого текста. Все комменты из другого PR валидны и здесь. Можно, кстати, просто было сделать симлинк.

2021-08-07 21:22 UTC, biodranik commented on docs/GOOGLEPLAY.md
> +mv -f src/google/play/release-notes/en-US/production.txt src/google/play/release-notes/en-US/default.txt
Что за альфа и продакшн?

2021-08-07 21:22 UTC, biodranik commented on iphone/metadata/en-US/description.txt
> +Organic Map is free from trackers and other bad stuff:
Я 100% исправлял это в эпл сторе. И ниже текст не тот, что был.

2021-08-07 21:22 UTC, biodranik commented on xcode/fastlane.sh
> +    set +e
Разве bash умеет +e внутри функций? Не надо ли назад -e в конце?

2021-08-07 21:22 UTC, biodranik commented on xcode/fastlane.sh
> +        check_length "$locale/name.txt" 30; err=$((err + $?))
Перенос строки будет игнорироваться?

2021-08-08 05:23 UTC, rtsisyk commented on .gitignore
> +android/src/google/play/listings/??-??/graphics
Скриншоты и какие-то иконки. Вынесено в отдельную репу, чтобы не засирать общую.

2021-08-08 05:24 UTC, rtsisyk commented on android/src/google/play/listings/en-US/full-description.txt
> +Organic Map is <b>free from trackers and other bad stuff</b>:
Я это выгрузил из гугл стора 10 часов назад. Задачи править сами тексты в данном PR не стояло.
Симлинк - это в целом примерно то, что я хотел сделать в итоге, чтобы не копипастить.

2021-08-08 05:36 UTC, rtsisyk commented on .github/workflows/appstore-check-metadata.yaml
> +        run: ./fastlane.sh check_metadata
К сожалению только на длину и будет. Остальные проверки по неведомой причине требуют ключ от аппстора.

2021-08-08 05:37 UTC, rtsisyk commented on .github/workflows/appstore-upload-metadata.yaml
> +      - master
Чек на длину стоит на каждый pull request.

2021-08-08 05:38 UTC, rtsisyk commented on .github/workflows/googleplay-upload-metadata.yaml
> +      - android/src/google/play/**
Можем сделать симлинк. Плагин как-то не хотелось бы патчить, если честно.

Мы хотим шарить мету с f-droid?

2021-08-08 05:38 UTC, rtsisyk commented on android/src/google/play/listings/en-US/full-description.txt
> +Organic Map is <b>free from trackers and other bad stuff</b>:
Поменял в фдроид ПР. Давайте его вольем сначала, потом я эти тексты симлинкну или скопирую (как хотим?)

2021-08-08 05:39 UTC, rtsisyk commented on docs/GOOGLEPLAY.md
> +mv -f src/google/play/release-notes/en-US/production.txt src/google/play/release-notes/en-US/default.txt
production - это публичное в сторе
beta - open testing
alpha - closed testing
internal - internal testing

Я пока еще разбираюсь в какой момент changelog заливается. Вроде бы с заливкой апкшки.

2021-08-08 05:40 UTC, rtsisyk commented on iphone/metadata/en-US/description.txt
> +Organic Map is free from trackers and other bad stuff:
Ок, поменяю здесь. Может перезатерло в процессе тестирования скриптов.

2021-08-08 05:43 UTC, rtsisyk commented on xcode/fastlane.sh
> +        check_length "$locale/name.txt" 30; err=$((err + $?))
Глянь код выше - пришлось python вызвать из оригинального патча. Если есть идеи на как на баше длину строки в юникоде проверить и проигнорировать "\n" в конце - расскажи, я быстрого решения не нашел. Ну разве что вызывать awk/perl, но тут уже и python можно тогда. 

>  len=$(python3 -c "import sys; print(len(sys.stdin.read().rstrip('\n')))" < $1)

2021-08-08 05:44 UTC, rtsisyk commented on xcode/fastlane.sh
> +    set +e
Можем поставить -e в конце. Хотелось, чтобы проверялось всё  и падало в конце, а не на первой ошибке.

2021-08-08 05:45 UTC, rtsisyk commented
Давайте #1035 зальем, я в этом PR тогда Android попробую симликнуть или около того.

2021-08-08 06:27 UTC, biodranik commented on android/src/google/play/listings/en-US/full-description.txt
> +Organic Map is <b>free from trackers and other bad stuff</b>:
Я пишу комменты потому, что не хочу потом снова возвращаться к этой проблеме. На сайте эти штуки исправлял тоже, просто каждый раз видно, как можно сделать ещё лучше.

2021-08-08 06:28 UTC, biodranik commented on docs/GOOGLEPLAY.md
> +mv -f src/google/play/release-notes/en-US/production.txt src/google/play/release-notes/en-US/default.txt
Надо будет разные файлы для разных билдов? А что будет триггерить билды тогда? Может давай сделаем изменение этих файлов чтобы заливало нужный билд?

2021-08-08 06:56 UTC, biodranik commented on .github/workflows/googleplay-upload-metadata.yaml
> +      - android/src/google/play/**
Шарить не хотим, но решение прятать метаданные глубоко в исходники выглядит очень странным как минимум.

2021-08-08 06:57 UTC, biodranik commented on .github/workflows/googleplay-upload-metadata.yaml
> +      - android/src/google/play/**
Симлинк сможет помочь, если плагин штатно не умеет.

2021-08-08 07:22 UTC, biodranik commented on xcode/fastlane.sh
> +        check_length "$locale/name.txt" 30; err=$((err + $?))
`${#var}` или `wc -m` показывают длину. Для игнора \n достаточно читать через read. При наличии верной UTF-8 локали, конечно же.

2021-08-08 07:23 UTC, biodranik commented on xcode/fastlane.sh
> +        check_length "$locale/name.txt" 30; err=$((err + $?))
Переносы строки нужно игнорить только в однострочных метаданных, конечно же.

2021-08-08 10:20 UTC, biodranik commented on xcode/fastlane.sh
> +    set +e
Я к тому, что этот +e не выключит ли ошибки ПОСЛЕ вызова функции?

2021-08-08 10:57 UTC, rtsisyk commented on .github/workflows/appstore-check-metadata.yaml
> +        run: ./fastlane.sh check_metadata
AppStore, GooglePlay и F-Droid теперь проверяются в Pull Requests при изменении соответствующих директорий:

https://github.com/organicmaps/organicmaps/runs/3273269781?check_suite_focus=true#step:3:1
https://github.com/organicmaps/organicmaps/runs/3273269780?check_suite_focus=true#step:3:1

2021-08-08 10:57 UTC, rtsisyk commented on .github/workflows/appstore-upload-metadata.yaml
> +      - master
AppStore, GooglePlay и F-Droid теперь проверяются в Pull Requests при изменении соответствующих директорий:

https://github.com/organicmaps/organicmaps/runs/3273269781?check_suite_focus=true#step:3:1
https://github.com/organicmaps/organicmaps/runs/3273269780?check_suite_focus=true#step:3:1

2021-08-08 10:59 UTC, rtsisyk commented on .github/workflows/googleplay-upload-metadata.yaml
> +      - android/src/google/play/**
Можем сделать симлинк из `android/src/google/play/` в `android/metadata`. Обрати внимание, что теперь есть `android/src/google/play/` и `android/src/fdroid/play/` - две копии, чтобы иметь разный текст.

2021-08-08 11:00 UTC, rtsisyk commented on .gitignore
> +android/src/google/play/listings/??-??/graphics
Скриншоты вынесены в [отдельную репу](https://github.com/organicmaps/screenshots) чтобы не забить здесь всё окончательно. Скриншоты мы меняем редко, поэтому проблемы не вижу.

2021-08-08 11:01 UTC, rtsisyk commented on android/src/google/play/listings/en-US/full-description.txt
> +Organic Map is <b>free from trackers and other bad stuff</b>:
Я поправил это место. Гугл плей синхронизировал с последними правками F-Droid. Хочу доделать инфраструктуру для работы с метой в гите, а дальше уже можно будет править там как угодно что угодно.

2021-08-08 11:02 UTC, rtsisyk commented on iphone/metadata/en-US/description.txt
> +Organic Map is free from trackers and other bad stuff:
Поменял здесь. Для этого и делаем в git всё!

2021-08-08 11:03 UTC, rtsisyk commented on xcode/fastlane.sh
> +        check_length "$locale/name.txt" 30; err=$((err + $?))
Я переделал скрипт полностью. Игнорируется только последний "\n". Требуем его наличия в файле, т.к. это наиболее привычное поведение при работе в любом редакторе. При проверке длины не учитываем.

2021-08-08 12:43 UTC, biodranik commented on .github/workflows/googleplay-upload-metadata.yaml
> +      - android/src/google/play/**
Я хорошенько подумал, давай пока сделаем симлинки на все идентичные поля, чтобы не усложнять себе жизнь (кроме whats new, там могут релизы слегка различаться, можно в фдроид вообще чаще фиксы для теста кидать). А как только понадобится форкнуть, просто симлинки заменим файлами.

2021-08-08 12:48 UTC, biodranik commented on xcode/fastlane.sh
> +        check_length "$locale/name.txt" 30; err=$((err + $?))
Фейлитьс из-за пропущенного конца строки тоже очень странно. Должно работать и так и так. Кейз: я создаю ПР с мобильного гитхаб редактора.

2021-08-08 13:32 UTC, rtsisyk commented on xcode/fastlane.sh
> +        check_length "$locale/name.txt" 30; err=$((err + $?))
Я могу убрать эту проверку, но мне кажется более правильным форсировать наличие пустой строки вообще во всех файлах. В противном случае постоянно будем иметь левые диффы в зависимости от настроек редактора.

2021-08-08 14:29 UTC, rtsisyk commented on .github/workflows/googleplay-upload-metadata.yaml
> +      - android/src/google/play/**
Сделал симлинки из фдроида в гуглплей. Надеюсь, что у них это всё будет работать.

2021-08-08 14:30 UTC, rtsisyk commented on xcode/fastlane.sh
> +    set +e
Этот скрипт уничтожен.

2021-08-08 14:37 UTC, rtsisyk commented on .github/workflows/android-release-metadata.yaml
> +name: Android Metadata
@biodranik  Я закончил с этим патчей в целом. Нюансы следующие:

1. Заливка скриншотов в AppStore возможна только при наличии черновика билда, который при этом не на ревью. Создать новый черновик пока есть существующий билд на ревью нельзя. По крайне мере в гуи я это не нашел. План - попробовать после прохождения ревью создать черновик и дернуть пайплайн. Пока что он стоит на ручном запуске. В целом думаю тупо интегрировать его в заливку билдов в iOS. Будем заливать билд,  обновлять скриншоты, отправлять на ревью.

2. Скачивания метаданных из гуглплея очень мутное. Оно делает rm -rf на всю папку и всё выкачивает заново. Вместо .jpg почему-то оказываются .png, хотя в реальности там JPEG. Я написал скрипт, учитывающий нюансы, но юзать его надо с осторожностью.

3. Сделал симлинки из fdroid в gplay. Предлагаю точечно вручную рулить где нужен симлинк, а где будет свой файл.

4. Скриншоты в андроиде также точечно симликнуты в отдельную репу. Фдроид юзает 4 скрина из README прямо из основного репо. Гугл плей юзает скрины из отдельной репы. Изначально я пытался в build.gradle написать правильную расстановку симлинков, но там это всё делает очень неудобно и я решил проставить симлинки прямо в репе. Может не самое элегантное решение, но зато очень дуракоупорное и точно работающее.

---

Очень хочется закрыть эти вопросы уже. Планирую еще ребейзнуть заливку iOS поверх этого и потестировать с новым xcode проектом.

2021-08-09 06:34 UTC, biodranik commented on .github/workflows/android-release-metadata.yaml
> +name: Android Metadata
1. Норм.
2. Норм но надо зарепортить баг или пофиксить в апстриме.
3. Норм.
4. Норм.

2021-08-09 06:41 UTC, rtsisyk commented on .github/workflows/android-release-metadata.yaml
> +name: Android Metadata
баг https://github.com/Triple-T/gradle-play-publisher/issues/992

2021-08-11 20:47 UTC, biodranik requested changes
В целом ок, но не понятно откуда вылезли изменения в twine.

2021-08-11 20:47 UTC, biodranik commented on .github/workflows/android-beta.yaml
> +      - rt-upload-metadata # TODO: remove
Если разрешать ручной триггер, тогда можно будет выбрать явно бранч для запуска.

2021-08-11 20:47 UTC, biodranik commented on .github/workflows/android-release-metadata.yaml
> +      - rt-upload-metadata # TODO: remove
С ручным триггером это не нужно.

2021-08-11 20:47 UTC, biodranik commented on .github/workflows/android-release-metadata.yaml
> +#      - android/src/*/play/**
Почему закомменчено?

2021-08-11 20:47 UTC, biodranik commented on .github/workflows/android-release-metadata.yaml
> +      - name: Checkout private keys
Выше уже есть этот шаг.

2021-08-11 20:47 UTC, biodranik commented on .github/workflows/android-release-metadata.yaml
> +        timeout-minutes: 10
Зачем так долго?

2021-08-11 20:47 UTC, biodranik commented on .github/workflows/ios-release-metadata.yaml
> +      - rt-upload-metadata # TODO: remove
Убрать перед мержем.

2021-08-11 20:47 UTC, biodranik commented on .github/workflows/ios-release-metadata.yaml
> +        timeout-minutes: 10
Так долго?

2021-08-11 20:47 UTC, biodranik commented on .github/workflows/ios-release-screenshots.yaml
> +  push: # TODO: remove
Если работает, убирай )

2021-08-11 20:47 UTC, biodranik commented on android/src/google/play/listings/en-US/full-description.txt
> +• Dark mode to protect your eyes
• Detailed offline maps with places that don't exist on other maps, thanks to OpenStreetMap
• Cycling routes, hiking trails, and walking paths
• Contour lines, elevation profiles, peaks, and slopes
• Turn-by-turn walking, cycling, and car navigation with voice guidance
• Fast offline search on the map
• Bookmarks export and import in KML/KMZ formats (GPX is planned)
• Dark Mode to protect your eyes
• Countries and regions don't take a lot of space
• Free and open-source

2021-08-11 20:47 UTC, biodranik commented on android/src/google/play/listings/en-US/full-description.txt
> +• Purely organic
Вставь зачёркивание если работает.

2021-08-11 20:47 UTC, biodranik commented on android/src/google/play/listings/en-US/full-description.txt
> +• Purely organic
- ~~No pesticides~~ Purely organic! (только не отсюда, я в другом месте копировал)

2021-08-11 20:47 UTC, biodranik commented on docs/RELEASE_MANAGEMENT.md
> +Use [GitHub Actions](../.github/workflows/android-release.yaml).
Эти ссылки рабочие?

2021-08-11 20:47 UTC, biodranik commented on iphone/metadata/en-US/description.txt
> +• Turn-by-turn walking, cycling, and car navigation with voice guidance
Вставь то же что и выше, тут car замени на CarPlay

2021-08-11 20:47 UTC, biodranik commented on tools/android/download_googleplay_metadata.sh
> +cd "$(dirname "$0")/../../android"
Это ненадёжно, лучше `SCRIPT_DIR="$( cd "$(dirname "$0")" && pwd -P )"`

2021-08-11 20:47 UTC, biodranik commented on tools/android/download_googleplay_metadata.sh
> +        echo >&2 "Missing keys/"
Лучше писать полный путь к keys, скрипт можно ранить из любой диры.

2021-08-11 20:47 UTC, biodranik commented on tools/android/download_googleplay_metadata.sh
> +        echo >&2 "Please checkout screenshots to ../screenshots"
И тут лучше логать полный путь.

2021-08-11 20:47 UTC, biodranik commented on tools/android/download_googleplay_metadata.sh
> +check_screenshots
Зачем это для загрузки данных из стора?

2021-08-11 20:47 UTC, biodranik commented on tools/python/check_store_metadata.py
> +# for locale in glob.glob('android/src/{google,fdroid}/??-??/play/'):
Почему закомменчено?

2021-08-12 08:21 UTC, rtsisyk commented on .github/workflows/android-beta.yaml
> +      - rt-upload-metadata # TODO: remove
Список допустимых бранчей для деплоя в бету/прод всё равно ограничен в GitHub Environments. Я уберу этот хак, он только для тестирования нужен был.

2021-08-12 08:21 UTC, rtsisyk commented on .github/workflows/android-release-metadata.yaml
> +      - rt-upload-metadata # TODO: remove
Уберу это.

2021-08-12 08:22 UTC, rtsisyk commented on .github/workflows/android-release-metadata.yaml
> +#      - android/src/*/play/**
Не срабатывало потому что. Это всё временное, я уберу из финального патча.

2021-08-12 08:22 UTC, rtsisyk commented on .github/workflows/android-release-metadata.yaml
> +      - name: Checkout private keys
ок

2021-08-12 08:22 UTC, rtsisyk commented on .github/workflows/android-release-metadata.yaml
> +        timeout-minutes: 10
Можем меньше поставить, не проблема.

2021-08-12 08:23 UTC, rtsisyk commented on tools/android/download_googleplay_metadata.sh
> +cd "$(dirname "$0")/../../android"
Так `cd "$(dirname "$0")/../../android"` тоже самое, что `cd "$(dirname "$0")"` внутри. Я просто делаю chdir в эту папку, сама переменная мне не нужна.

2021-08-12 08:23 UTC, rtsisyk commented on tools/android/download_googleplay_metadata.sh
> +        echo >&2 "Missing keys/"
Там выше chdir стоит же, чтобы везде эти пути не прописывать.

2021-08-12 08:24 UTC, rtsisyk commented on tools/android/download_googleplay_metadata.sh
> +check_screenshots
Оно сразу в репу со скринами подпихивает скачанные файлы.

2021-08-12 08:24 UTC, rtsisyk commented on tools/python/check_store_metadata.py
> +# for locale in glob.glob('android/src/{google,fdroid}/??-??/play/'):
Артефакт, удалю.

2021-08-12 08:28 UTC, rtsisyk commented on tools/python/check_store_metadata.py
> +# for locale in glob.glob('android/src/{google,fdroid}/??-??/play/'):
Удалил.

2021-08-12 08:28 UTC, rtsisyk commented on .github/workflows/android-release-metadata.yaml
> +        timeout-minutes: 10
Поставил 5 минут. Меньше рисковано, все же там весьма немаленкие скриншоты.

2021-08-12 08:32 UTC, rtsisyk commented
Twine попал случайно, забыл обновить сабмодуль и он добавился на git add.

#1085

Перепушал.

2021-08-12 12:12 UTC, biodranik reviewed
Многие комменты без ответа

2021-08-12 12:12 UTC, biodranik commented on tools/python/check_store_metadata.py
> +            text = text[:-1]
А в сторы такие переносы строк сверх лимита стрипаются и тоже не учитываются? Проверял на макс.длине текста?

2021-08-12 20:48 UTC, rtsisyk commented on docs/GOOGLEPLAY.md
> +mv -f src/google/play/release-notes/en-US/production.txt src/google/play/release-notes/en-US/default.txt
Давай по android/src/google/play/ триггерить. Ну то есть когда поменялась мета для гугл плея.

2021-08-12 20:49 UTC, rtsisyk commented on tools/android/download_googleplay_metadata.sh
> +        echo >&2 "Missing keys/"
Хорошо, поменя здесь.

2021-08-12 20:49 UTC, rtsisyk commented on tools/android/download_googleplay_metadata.sh
> +        echo >&2 "Please checkout screenshots to ../screenshots"
Хорошо, поменяю здесь.

2021-08-12 20:50 UTC, rtsisyk commented on tools/python/check_store_metadata.py
> +            text = text[:-1]
Надо попробовать.

2021-08-12 20:50 UTC, rtsisyk commented
Вроде везде ответил. Поправлю оставшуюся мелочь. Посмотри что еще осталось.

2021-08-14 05:39 UTC, rtsisyk commented on tools/android/download_googleplay_metadata.sh
> +        echo >&2 "Missing keys/"
Добавил $PWD в вывод ошибки. chdir убирать не хочу, неудобно в каждой строчке полный путь писать.

2021-08-14 05:42 UTC, rtsisyk commented on tools/python/check_store_metadata.py
> +            text = text[:-1]
title.txt "Organic Maps Offline Hike Bike Trails & Navigation" как раз 50 символов + "\n" и всё заливается.

https://github.com/Triple-T/gradle-play-publisher/blob/b02ced7f277a68ddfa8bd83b12508ad5beed3c14/common/utils/src/main/kotlin/com/github/triplet/gradle/common/utils/Io.kt#L55-L56

2021-08-14 05:43 UTC, rtsisyk commented on tools/python/check_store_metadata.py
> +            text = text[:-1]
Они сами стрипают там всё.

2021-08-14 06:54 UTC, merged

2021-08-14 06:54 UTC, rtsisyk commented
Discussed offline. Please feel free to improve in master.