Removed obsolete MetadataIndex.
organicmaps/organicmaps pull request #1069
Opened 2021-08-11 18:51 UTC by vng

2021-08-11 19:13 UTC, biodranik approved these changes

2021-08-11 19:13 UTC, biodranik commented on indexer/feature.cpp
> +  ASSERT(m_loadInfo->GetMWMFormat() > version::Format::v10 && m_metadataDeserializer,
Значит можно вычистить весь код для формата <= 10? По коду много где находится. Если чистить генератор и начинать "с нуля", то лучше тогда сразу сейчас рубануть, дальше будет легче и тестить и поддерживать.

2021-08-11 19:13 UTC, biodranik commented on indexer/feature.cpp
> -        // Before v11 we used the same metadata serialization for mwm and mwm.tmp
А сейчас разная сериализация для этих кейзов? Где-то задокументировано?

2021-08-11 19:13 UTC, biodranik commented on indexer/feature.cpp
> -        // Before v11 we used the same metadata serialization for mwm and mwm.tmp
Зачем надо было это оптимизировать? Для сжатия строчек?

2021-08-11 19:19 UTC, vng commented on indexer/feature.cpp
> +  ASSERT(m_loadInfo->GetMWMFormat() > version::Format::v10 && m_metadataDeserializer,
Да, можно вырезать все. Это то, что бросилось в глаза и больше всего было кода на условиях. Остальное - там достаточно прямолинейно.

2021-08-11 19:20 UTC, vng commented on indexer/feature.cpp
> -        // Before v11 we used the same metadata serialization for mwm and mwm.tmp
Я не смотрел там сжатия, но видимо что-то интересное добавлено.

2021-08-11 20:23 UTC, biodranik requested changes
Тесты надо починить.

2021-08-12 06:18 UTC, vng commented on indexer/feature.cpp
> +  ASSERT(m_loadInfo->GetMWMFormat() > version::Format::v10 && m_metadataDeserializer,
Выпилил, оставил пару CHECK в ключевых местах.

2021-08-12 07:56 UTC, biodranik approved these changes

2021-08-12 07:56 UTC, biodranik commented on map/map_tests/feature_getters_tests.cpp
> +    "psurface|paved_good|",
Выше уже есть. И зачем переносы строк?

2021-08-12 07:56 UTC, biodranik commented on platform/mwm_traits.cpp
> +bool MwmTraits::HasOffsetsTable() const { return true; }
Может вообще выпилить этот метод и ниже? Если вдруг понадобится что-то подобное, снова впилим.

2021-08-12 07:56 UTC, biodranik commented on search/search_tests/house_detector_tests.cpp
> +  /// @todo HouseDetector used in tests only, so do not want to waste time here ..
Интересно, а почему HouseDetector не используется в проде? Какую именно он проблему решал, и почему его отключили?

2021-08-12 07:56 UTC, biodranik commented on search/search_tests/house_detector_tests.cpp
> +  /// @todo HouseDetector used in tests only, so do not want to waste time here ..
И что тут за ошибка? Может там что-то важное?

2021-08-12 08:14 UTC, vng commented on indexer/feature.cpp
> +  CHECK(m_loadInfo, ());
CHECK падает с нормальным логом. AV падает молча и невнятно. Не переживай за скорость тут.

2021-08-12 08:15 UTC, vng commented on indexer/feature.cpp
> +    UNUSED_VALUE(m_metadataDeserializer->Get(m_id.m_index, m_metadata));
Эта функция записывает в m_metadata

2021-08-12 08:15 UTC, vng commented on indexer/feature.cpp
> +    UNUSED_VALUE(m_metadataDeserializer->GetIds(m_id.m_index, m_metaIds));
Эта функция записывает в m_metaIds

2021-08-12 08:16 UTC, vng commented on indexer/features_vector.cpp
> +  CHECK(m_loadInfo.GetMWMFormat() >= version::Format::v11, ("Old mwm format is not supported"));
FeaturesVector как раз и создается один раз при "подготовке" карты.

2021-08-12 08:17 UTC, vng commented on indexer/features_vector.cpp
> +          (base::Underlying(header.m_version)));
Это другая m_version, нежели была выше. Оставил как было в коде до. Скорее всего было вставлено для вылета на "битых" файлах.

2021-08-12 08:18 UTC, vng commented on indexer/features_vector.hpp
> +  /// Didn't find a better solution without big refactoring.
Я не думаю что тут он нужен. Специально сюда нет смысла возвращаться.

2021-08-12 08:20 UTC, vng commented on map/map_tests/feature_getters_tests.cpp
> +    "psurface|paved_good|",
Первый относится к footway, второй к service. Тест проверяет каждое вхождение.
Переносы строк - чтобы логически видеть типы 4 разных объектов, они все пересекаются в одной точке.

2021-08-12 08:22 UTC, vng commented on search/search_tests/house_detector_tests.cpp
> +  /// @todo HouseDetector used in tests only, so do not want to waste time here ..
Это был эмпирический класс матчинга домов на улицу до того, как мы стали явно это хранить.
В целом я не хочу его выпиливать, может что-то оттуда пригодится когда буду смотреть поиск.
Важное там не сломалось, просто поменялись minsk-pass данные (но дома есть), а копать сейчас нет смысла. todo достаточно.

2021-08-12 21:23 UTC, merged