[android] Add Welcome screen and Help button
organicmaps/organicmaps pull request #1101
Opened 2021-08-14 17:38 UTC by rtsisyk

Need help with ic_menu_help and text!

2021-08-14 18:24 UTC, Endem10n commented on data/countries-strings/be.json/localize.json
> +"Abkhazia":"Abkhazia",
Wrong file for this data.

2021-08-14 21:58 UTC, biodranik requested changes

2021-08-14 21:58 UTC, biodranik commented on android/AndroidManifest.xml
> +        android:configChanges="orientation|screenLayout|screenSize"
Как будет выглядеть диалог после поворота в лендскейп?

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +                                                     HelpFragment.class.getName()
Почему называется Help? Это диалог с текстом и кнопками?

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    builder.append(" <b>");
Не пойдёт. Надо форматирование выносить в строку перевода тоже. Потом замучаемся менять.

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    builder.append(" <b>");
Или если хочется красиво, давай перевод будем писать в markdown со `\n` и тут будем строку парсить и подменять теги. Но лучше сразу теги.

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +      Intent intent = new Intent(getActivity(), HelpActivity.class);
Ты не любишь слово final?

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/FeedbackDialog.java
> +
Лишний перенос.

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/FeedbackDialog.java
> +    public static void show(Activity activity)
Почему тут отступ 4? Везде в проекте 2.

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/FeedbackDialog.java
> +        DialogInterface.OnClickListener clickListener = new DialogInterface.OnClickListener() {
Решили новый код со скобками на той же строке писать? Я не против, но надо было хотя бы обсудить.

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/FeedbackDialog.java
> +        DialogInterface.OnClickListener clickListener = new DialogInterface.OnClickListener() {
Форматтеры, между прочим, лежат в tools/android/formatter

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/FeedbackDialog.java
> +                        sendGeneralFeedback();
Очень корявое форматирование.

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/FeedbackDialog.java
> +            private void github() {
Однострочные методы нет смысла создавать, лучше сразу дёргать в месте вызова.

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/HelpActivity.java
> +        return HelpFragment.class;
Ради этой строчки файл заводить?

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/util/Config.java
> +  public static void acceptTerms()
Это у нас не terms, а скорее disclaimer. terms может появятся в будущем ещё и тогда будет путаница.

2021-08-14 21:58 UTC, biodranik commented on android/src/com/mapswithme/util/Config.java
> +    return getBool(KEY_MISC_TERMS_ACCEPTED);
Сохраняй строку из даты акцепта и версии приложения. Тогда потом сможем менять строки и показывать снова, если понадобится.

2021-08-14 21:58 UTC, biodranik commented on data/strings/strings.txt
> +  [dialog_welcome_accepted]
Так всё-таки Help, Terms (Disclaimer) или Welcome? Давай определимся с названием и не будем плодить сущности. Welcome наверное лучше всего подходит.

2021-08-14 21:58 UTC, biodranik commented on data/strings/strings.txt
> +    en = Contact human
Не надо. У нас нет роботов на любые пункты.

2021-08-14 21:58 UTC, biodranik commented on data/strings/strings.txt
> +    en = Organic Maps is an offline maps app for travelers, tourists, hikers, and cyclists. Maps and navigation work <b>fully offline</b> without Internet connection to save your battery! Please wait
Тексты не решают задачу. Надо менять.
Суть кратко:
- Аппа, навигация, фичи в разработке, могут глючить.
- Данных на карте может не быть из-за ОСМ(линк)
- Нас мало и работаем в свободное время за донейшны.
- Помогите обратной связью и хорошими оценками, пожалуйста.

2021-08-14 21:58 UTC, biodranik commented on data/strings/strings.txt
> +    en = Organic Maps is an offline maps app for travelers, tourists, hikers, and cyclists. Maps and navigation work <b>fully offline</b> without Internet connection to save your battery! Please wait
И не надо разбивать на много строчек, писал выше. Давай сразу с форматированием тут.

2021-08-15 16:05 UTC, rtsisyk commented on data/countries-strings/be.json/localize.json
> +"Abkhazia":"Abkhazia",
Removed.

2021-08-15 16:06 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +                                                     HelpFragment.class.getName()
Help это диалог с WebView и FAQ. Фрагмент называля HelpFragment.

2021-08-15 16:07 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    builder.append(" <b>");
А bold как вставить? В strings.xml нельзя просто так html тэги вставлять, надо извращаться как-то.

2021-08-15 16:07 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +      Intent intent = new Intent(getActivity(), HelpActivity.class);
Оно абсолютно бесполезное, но специально для тебя буду писать. Если что, этот кусок скопирован из кода выше и там тоже его не было.

2021-08-15 16:08 UTC, rtsisyk commented on android/src/com/mapswithme/util/Config.java
> +  public static void acceptTerms()
ок

2021-08-15 16:10 UTC, rtsisyk commented on android/src/com/mapswithme/util/Config.java
> +    return getBool(KEY_MISC_TERMS_ACCEPTED);
ок

2021-08-15 16:20 UTC, rtsisyk commented on android/src/com/mapswithme/util/Config.java
> +  public static void acceptTerms()
private static final String KEY_MISC_DISCLAIMER_ACCEPTED = "IsDisclaimerApproved";
  тут уже такой есть для роутинга...

2021-08-15 17:55 UTC, closed without merging

2021-08-15 19:14 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +      Intent intent = new Intent(getActivity(), HelpActivity.class);
В таких коротких кусках да, не полезное. В целом полезно, видно сразу, что константа. Привычка с плюсов, упрощает чтение кода когда сразу видишь константу.