[android] Add a help button to the main toolbar
organicmaps/organicmaps pull request #1464
Opened 2021-10-24 16:40 UTC by rtsisyk

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

##

![Screenshot_20211026-093205](https://user-images.githubusercontent.com/1799054/138821383-7efa3787-1289-40c9-8b12-b2e390c159ff.png)

![Screenshot_20211026-093214](https://user-images.githubusercontent.com/1799054/138821395-706f5d27-e915-419f-83a9-ef3ca66db468.png)

2021-10-24 17:44 UTC, biodranik requested changes
- [x] Иконку бери отсюда https://fonts.google.com/icons?selected=Material+Icons&icon.query=help+
- [x] Если не сложно, переделай верхнюю часть так, чтобы иконка была слева, не очень большой, а справа писались две версии, одинаково жирным. Тогда больше строчек из списка будет видно на экране.
- [ ] Заголовки для секций сложно добавить? На айфоне они красиво смотрятся
- [x] Tell a friend выпилить, прошлый век

2021-10-29 20:38 UTC, biodranik commented on android/AndroidManifest.xml
> +        android:configChanges="orientation|screenLayout|screenSize"
Инсайды с прошлых проектов — убедительный довод?

2021-10-29 20:40 UTC, biodranik commented on android/AndroidManifest.xml
> +        android:configChanges="orientation|screenLayout|screenSize"
Фейсбук - для получения поддержки и для новостей. Поделиться с друзьями - маркетинг. Поясни, что общего.

2021-10-29 20:54 UTC, biodranik commented on android/AndroidManifest.xml
> +        android:name="com.mapswithme.maps.help.HelpActivity"
Ежу не понятно. Долгое время соцсети вели на "лайки" страниц. Кликнуть примерно равнялось полайкать.

А нужен прямой посыл: нужна от нас обратная связь - вот инструменты.

2021-10-31 06:45 UTC, rtsisyk commented on android/AndroidManifest.xml
> +        android:configChanges="orientation|screenLayout|screenSize"
Короче я убрал, иначе  к 2050 году не доделаем.

2021-10-31 07:08 UTC, rtsisyk commented on android/AndroidManifest.xml
> +        android:name="com.mapswithme.maps.help.HelpActivity"
Нужно передизайнивать весь диалог. Вставление заголовка как в примере выше выглядит немного не к месту.

2021-11-01 06:49 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +  /*
Это код предыдущей кнопки. Удаляю.

2021-11-01 06:49 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> -      getActivity().startLocationToPoint(null, false);
Код предыдущей кнопки на тулбаре. Кнопку мы заменили на другую.

2021-11-01 06:50 UTC, rtsisyk commented on android/src/com/mapswithme/maps/help/HelpActivity.java
> +    getSupportFragmentManager().beginTransaction()
Я здесь вынес общий код в базовый класс и удалил дублирование.

2021-11-01 06:50 UTC, rtsisyk commented on android/src/com/mapswithme/maps/help/HelpActivity.java
> +      getToolbar().setTitle(mLastTitle);
Я здесь вынес общий код в базовый класс и удалил дублирование.

2021-11-01 06:52 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +  /*
Этот код оказался еще нужен. Хотел вычистить, но нашел место, где еще нужен. Возвращаю.

2021-11-01 06:52 UTC, rtsisyk commented on android/src/com/mapswithme/util/SharingUtils.java
> +    text.append('\n');
Этого кода больше нет.

2021-11-01 08:19 UTC, rtsisyk commented on data/strings/strings.txt
> +    bg = Organic Maps е безплатно приложение за офлайн карти с отворен код за пътешественици, туристи, туристи и велосипедисти. Без реклами. Без проследяване.  Никакви любопитни очи на Big Tech Co.
Переводы старые, потому что гугл транслейт возвращает полное говно. Я вставил новый переведенный текст, но ИМХО, лучше оставить тупо английский, чем ЭТО.

2021-11-01 08:19 UTC, rtsisyk commented on android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
> +      // TODO: xxx
Нету.

2021-11-01 22:22 UTC, biodranik commented on data/strings/strings.txt
> +    en-GB = How to support us?
GB не надо, если идентичен. И MX и BR

2021-11-01 22:22 UTC, biodranik commented on data/strings/strings.txt
> +  [how_to_support_us]
Почему так мало языков в списке? Нужны те же, что и выше.

2021-11-01 22:24 UTC, biodranik commented on data/strings/strings.txt
> +    en = Organic Maps is a free and open-source offline maps app, developed by a few geeks in their free time. All map data is from OpenStreetMap. No ads. No tracking and personal data collection.
давай поправим на in our free time, будет более персонально звучать.

2021-11-01 22:29 UTC, biodranik commented on data/strings/strings.txt
> +    en = Organic Maps is a free and open-source offline maps app, developed by a few geeks in their free time. All map data is from OpenStreetMap. No ads. No tracking and personal data collection.
Для переводов на другие языки надо подсовывать нейтральную базовую версию, типа такого:
Organic Maps is a free application. It is developed by a few engineers in our free time. All map data is from OpenStreetMap. No ads. No tracking. Your personal data is not collected.

2021-11-02 08:23 UTC, rtsisyk commented on data/strings/strings.txt
> +    en = Organic Maps is a free and open-source offline maps app, developed by a few geeks in their free time. All map data is from OpenStreetMap. No ads. No tracking and personal data collection.
Вот так выглядит на русском после гуглтранслейта:

```
Organic Maps - это бесплатное приложение.Он разработан несколькими инженерами в нашем свободном времени.Все данные карты из OpenStreetMap.Без рекламы.Нет отслеживания.Ваши личные данные не собираются.
```

Если на других языках примерно также, то мне весьма стрёмно это пушать

2021-11-02 08:24 UTC, rtsisyk commented on data/strings/strings.txt
> +  [how_to_support_us]
Перегенерил новым скриптом.

2021-11-02 08:24 UTC, rtsisyk commented on data/strings/strings.txt
> +    en = Organic Maps is a free and open-source offline maps app, developed by a few geeks in their free time. All map data is from OpenStreetMap. No ads. No tracking and personal data collection.
Еще после точки нет пробела. Это прям раздражает.

2021-11-02 08:32 UTC, rtsisyk commented on data/strings/strings.txt
> +    en = Organic Maps is a free and open-source offline maps app, developed by a few geeks in their free time. All map data is from OpenStreetMap. No ads. No tracking and personal data collection.
Обновил. Мне кажется, что лучше английский оставить, чем этот выхлоп из гугл транслейта.

2021-11-02 11:05 UTC, biodranik commented on data/strings/strings.txt
> +    en = Organic Maps is a free application.  It is developed by a few engineers in our free time.  All map data is from OpenStreetMap.  No ads.  No tracking.  Your personal data is not collected.
Да нет же, упрощённый английский НЕ НУЖНО вбивать сюда. Он нужен ТОЛЬКО для исходника переводов. А тут должен быть предыдущий, живой английский.

2021-11-03 07:29 UTC, rtsisyk commented on data/strings/strings.txt
> +    en = Organic Maps is a free application.  It is developed by a few engineers in our free time.  All map data is from OpenStreetMap.  No ads.  No tracking.  Your personal data is not collected.
Блин, при копировании из скрипта случайно заменил.

2021-11-03 07:35 UTC, rtsisyk commented on android/res/drawable/ic_rate.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
@biodranik а зачем мы иконку туда-сюда-обратно меняем? Там и была звездочка, хоть и не векторная. По твоей же просьбе поменял на другую. Ну да ладно, будем считать, что заменили на вектор. Тоже полезно.

2021-11-03 14:18 UTC, rtsisyk commented on data/strings/strings.txt
> +    en = <a href="https://organicmaps.app">Organic Maps</a> is a free and open-source offline maps application. No ads. No tracking. If you see an error on the map, please fix it in <a href="https://
Не надо вставлять HTML в строки переводов. Это плохая идея. Делай форматирование в самом приложении, а не в i18n.

2021-11-03 14:18 UTC, rtsisyk commented on android/res/drawable/ic_question_mark.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Я не понял что здесь происходит и зачем меняются иконки.

2021-11-03 14:18 UTC, rtsisyk commented on android/src/com/mapswithme/util/Constants.java
> +    public static final String SUPPORT_US = "https://organicmaps.app/support-us";
Ссылка битая.

2021-11-03 14:18 UTC, rtsisyk commented on android/res/drawable/ic_rate.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Так ты сам попросил стандартную иконку для rate вставить и даже показал какую. Ну ладно.

2021-11-03 15:48 UTC, biodranik commented on data/strings/strings.txt
> +    en = <a href="https://organicmaps.app">Organic Maps</a> is a free and open-source offline maps application. No ads. No tracking. If you see an error on the map, please fix it in <a href="https://
Надо. Обоснуй, почему плохая идея. Всё работает как часы, без изменений в коде.

2021-11-03 15:48 UTC, biodranik commented on android/res/drawable/ic_question_mark.xml
> +<vector xmlns:android="http://schemas.android.com/apk/res/android"
Я поменял кружок с вопросиком на просто вопросик. Потестировал, так выглядит гораздо лучше.

2021-11-03 15:49 UTC, biodranik commented on android/src/com/mapswithme/util/Constants.java
> +    public static final String SUPPORT_US = "https://organicmaps.app/support-us";
Знаю, доделаю позже. Это не блокер.

2021-11-03 15:50 UTC, biodranik commented
> Так ты сам попросил стандартную иконку для rate вставить и даже показал какую. Ну ладно.

Попросил, посмотрел вживую, выглядело плохо. Выбрал иконку живее и красивее.

2021-11-03 20:59 UTC, vng commented on data/strings/strings.txt
> +    en = <a href="https://organicmaps.app">Organic Maps</a> is a free and open-source offline maps application. No ads. No tracking. If you see an error on the map, please fix it in <a href="https://
Сейчас в iOS ссылки не работают и не отображаются корректно. В ведре они нажимаются очень странно с большим лагом. Я за убирать.

2021-11-03 22:59 UTC, biodranik commented on android/src/com/mapswithme/util/Constants.java
> +    public static final String SUPPORT_US = "https://organicmaps.app/support-us";
Сделал.

2021-11-03 23:00 UTC, biodranik approved these changes

2021-11-03 23:00 UTC, merged