Translations update from Hosted Weblate
organicmaps/organicmaps pull request #1579
Opened 2021-11-20 08:53 UTC by weblate

Translations update from [Hosted Weblate](https://hosted.weblate.org/projects/organicmaps/apple-appstore-metadata/)
for OrganicMaps/Apple AppStore Metadata.

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widgets/organicmaps/-/apple-appstore-metadata/horizontal-auto.svg)

2021-11-20 11:16 UTC, vng approved these changes

2021-11-20 14:45 UTC, biodranik commented on iphone/metadata/de/name.txt
> +Organische Karten Offline Hike&Bike
Нам не нужно переводить название на местные языки, всегда надо оставлять Organic Maps для кейвордов.

2021-11-20 14:46 UTC, biodranik commented on iphone/metadata/de/promotional_text.txt
> +Bitte melden Sie alle Kartenprobleme direkt an OpenStreetMap. Und lassen Sie uns über Fehler oder Probleme wissen, unser kleines Team freut sich, von Ihnen zu hören. Merci!
Мерси я писал для французов когда-то, на немецком надо Dankeschön!

2021-11-20 14:47 UTC, biodranik commented on iphone/metadata/de/name.txt
> +Organische Karten Offline Hike&Bike
Не только здесь, но и в остальных местах поменять тоже.

2021-11-20 14:51 UTC, biodranik commented on iphone/metadata/de/release_notes.txt
> +• Neue OSM-Kartendaten ab 22.10.2021
Я не смогу оперативно делать переводы для whats new. Надо видимо делать симлинк на английский, и потом их добавлять, после релиза. Кстати, если полностью убрать de/release_notes.txt, и задеплоить, подхватится ли автоматом английский вариант?

2021-11-20 14:52 UTC, biodranik requested changes
См. комментарии.

2021-11-23 06:40 UTC, rtsisyk commented on iphone/metadata/de/name.txt
> +Organische Karten Offline Hike&Bike
Походу это гугл транслейт был, а не человек. Я напутал.

2021-11-23 06:40 UTC, rtsisyk commented on iphone/metadata/de/release_notes.txt
> +• Neue OSM-Kartendaten ab 22.10.2021
Делай их пока как есть.

2021-11-23 06:40 UTC, rtsisyk commented
Я закрываю, т.к. это был гугл транслейт по факту.

2021-11-23 06:40 UTC, closed without merging