[strings] Added natural.water.* and natural.beach.* types
organicmaps/organicmaps pull request #1623
Opened 2021-11-27 12:18 UTC by pastk

@vng 
Is it better to add `generate_localizations.sh` changes to this PR or as a separate one?

2021-11-27 22:34 UTC, biodranik requested changes

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
> +    cs = Pláž
be = Пяшчаны пляж
Перевод скриптом? Надо беларуский вставить, и на всех языках тогда тип пляжа писать.

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
> +    cs = Pláž
be = Галечны пляж

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
> +    cs = Rybník
be = Сажалка

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
> +    de = Reservoir
be = Вадасховішча

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
> +    ru = Резервуар
uk = Резервуар

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
> +    en = Basin
be = Рэзервуар

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
> +    ar = نهر
be = Рака

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
>      ru = Земля
Этот таг депрекейтед, и вроде как по смыслу это "суша" https://wiki.openstreetmap.org/wiki/Tag:natural%3Dland

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
>      ru = Земля
Суша по укр. и бел.

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
>      en = Meadow
be = Луг

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
> +    uk = Гай
Луг? Разве гай — не роща?

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
> +    uk = Гай
И в бел. тоже Луг

2021-11-27 22:34 UTC, biodranik commented on data/strings/types_strings.txt
> +    uk = Фруктовий сад
Судя по [тегу](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dorchard), это не только фруктовый сад. Кофе точно не фрукт )

Тут на ру бел и укр лучше Сад

2021-11-27 22:35 UTC, biodranik commented
Чтобы эти типы искались поиском, их надо вставить в categories.txt (можно в уже существующие там обобщённые типы).

2021-11-28 08:44 UTC, pastk commented on data/strings/types_strings.txt
> +    cs = Pláž
Тут я просто скопировал строки из [type.natural.beach] в надежде, что потом переводчики добавят песчаность..
Возможно лучше оставить тогда только en,ru,uk,be.

2021-11-28 08:57 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Резервуар
ещё добавил be = Рэзервуар

2021-11-28 09:26 UTC, pastk commented
> Чтобы эти типы искались поиском, их надо вставить в categories.txt (можно в уже существующие там обобщённые типы).

Я правильно понимаю, что, скажем, `natural-water` трактуется как префикс и будет включать `natural-water-pond`, `natural-water-basin`, etc? (если конечно для `natural-water-basin` нет своей отдельной строки)

2021-11-28 09:40 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Резервуар
Тут на самом деле лучше бы подошло "Искуственный водоём", но длинновато как-то...
Как вариант можно сделать "Пруд" (очень даже может быть техническим, очистным и т.п.).
https://wiki.openstreetmap.org/wiki/RU:Tag:water%3Dbasin

Как думаешь?

2021-11-28 10:16 UTC, biodranik commented on data/strings/types_strings.txt
> +    cs = Pláž
Или можно попробовать рубануть скриптом tools/unix/translate_categories.sh

2021-11-28 10:17 UTC, biodranik commented on data/strings/types_strings.txt
> +    ru = Резервуар
Всегда надо читать осм вики на английском. Если я правильно понимаю, тут именно резервуар, в т.ч. без воды, но куда при ливнях может набираться вода. Искусственный водоём — более широкое понятие, включающее, например, водохранилище.

2021-11-28 10:18 UTC, biodranik commented
> Я правильно понимаю, что, скажем, `natural-water` трактуется как префикс и будет включать `natural-water-pond`, `natural-water-basin`, etc? (если конечно для `natural-water-basin` нет своей отдельной строки)

Для поиска в categories.txt? Нет, тут надо явно прописывать все типы.

2021-11-28 10:23 UTC, biodranik commented on data/categories.txt
> +be:Сажалка
|вадаём

2021-11-28 10:23 UTC, biodranik commented on data/categories.txt
> +en:Reservoir
|water по аналогии здесь и ниже

2021-11-28 10:23 UTC, biodranik commented on data/categories.txt
> +en:Reservoir
Или лучше может сделать water в поиске только для питьевой воды?

2021-11-28 11:03 UTC, pastk commented on data/categories.txt
> +be:Сажалка
Ок!
Если скажем "водоём" прописан и для 
```
natural-water-lake
en:Lake|water
ru:Озеро|водоём
```
и для 
```
natural-water-pond
en:Pond|water
ru:Пруд|водоём
```
то по поиску "водоём" найдутся и пруды, и озёра?

2021-11-28 11:04 UTC, pastk commented on data/categories.txt
> +en:Reservoir
Непитьевая вода тоже нужна в поиске, имхо.
Думаю поиском воды лучше заняться комплексно отдельно в https://github.com/organicmaps/organicmaps/issues/1621

2021-11-28 11:11 UTC, pastk commented
> > Я правильно понимаю, что, скажем, `natural-water` трактуется как префикс и будет включать `natural-water-pond`, `natural-water-basin`, etc? (если конечно для `natural-water-basin` нет своей отдельной строки)
> 
> Для поиска в categories.txt? Нет, тут надо явно прописывать все типы.

Ок, добавил новые виды пляжей.

Тогда если сравнить `categories.txt` и `types_strings.txt`, то в поиске много чего нет.
Например, в категориях есть `highway-path|highway-footway|highway-steps|highway-cycleway`, но если `highway-path` не матчит субкатегории, то вот эти из `types_strings.txt` не будут искаться?
```
[type.highway.path.alpine_hiking]
[type.highway.path.bicycle]
[type.highway.path.demanding_mountain_hiking]
[type.highway.path.hiking]
[type.highway.path.horse]
[type.highway.path.permissive]
etc.
```

2021-11-28 14:05 UTC, biodranik commented on data/categories.txt
> +be:Сажалка
Верно.

2021-11-28 14:06 UTC, biodranik commented
> Тогда если сравнить `categories.txt` и `types_strings.txt`, то в поиске много чего нет.
> Например, в категориях есть `highway-path|highway-footway|highway-steps|highway-cycleway`, но если `highway-path` не матчит субкатегории, то вот эти из `types_strings.txt` не будут искаться?

Адресный поиск работает по-другому. Категории используются для матчинга именно типов. В поиске же никто не ищет "пешая тропа".

2021-11-28 16:55 UTC, pastk commented
@biodranik мне кажется в этом PR я уже всё поправил, что обсуждали
или что-то пропустил?

2021-11-28 22:05 UTC, biodranik approved these changes

2021-11-28 22:06 UTC, merged

2021-11-29 19:18 UTC, pastk commented
> > Тогда если сравнить `categories.txt` и `types_strings.txt`, то в поиске много чего нет.
> > Например, в категориях есть `highway-path|highway-footway|highway-steps|highway-cycleway`, но если `highway-path` не матчит субкатегории, то вот эти из `types_strings.txt` не будут искаться?
> 
> Адресный поиск работает по-другому. Категории используются для матчинга именно типов. В поиске же никто не ищет "пешая тропа".

Хм, вот например (36.8529386, 28.2709148)[https://www.openstreetmap.org/node/1654481241]
`historic=memorial & memorial=statue`. Т.е. в OM он `historic-memorial-statue` (есть в types_strings.txt).
Ищется в OM по запросу "monument" и "sights", хотя в categories.txt
```
historic-monument|@tourism
en:Monument

historic-memorial|@tourism
en:Memorial|monument
```
а `historic-memorial-statue` в нём нет! (как и других `historic-memorial-*`)
Если `historic-memorial` не матчит `historic-memorial-statue`, то и найтись эта статуя не должна...

2021-11-29 23:23 UTC, biodranik commented
> Если `historic-memorial` не матчит `historic-memorial-statue`, то и найтись эта статуя не должна...

@vng глянешь, пожалуйста, на текущую реализацию? Может я что-то путаю?

2021-11-30 06:15 UTC, vng commented
Все верно.
- матчинг идет по categories.txt
- подтипы матчатся надтипами. historic-memorial-statue будет находится, достаточно описать только historic-monument. Иначе в иерархии нет смысла.

2021-11-30 08:32 UTC, pastk commented
> Все верно.
> 
>     * матчинг идет по categories.txt
> 
>     * подтипы матчатся надтипами. historic-memorial-statue будет находится, достаточно описать только historic-monument. Иначе в иерархии нет смысла.

"достаточно описать только historic-memorial" имелось в виду, наверное?

Спасибо, включу это в описание categories.txt!