[android] Fix Google Maps, 2GIS, OSM geo urls
organicmaps/organicmaps pull request #1815
Opened 2022-01-09 16:01 UTC by rtsisyk

Test cases:

- https://maps.google.com/maps?z=16&q=Mezza9%401.3067198,103.83282
- https://maps.google.com/maps?z=16&q=House+of+Seafood+%40+180%401.356706,103.87591
- https://www.google.com/maps/place/Falafel+M.+Sahyoun/@33.8904447,35.5044618,16z
- https://www.google.com/maps?q=55.751809,37.6130029
- https://www.openstreetmap.org/#map=16/33.89041/35.50664
- https://openstreetmap.org/#map=16/33.89041/35.506641
- https://www.openstreetmap.org/search?query=Falafel%20Sahyoun#map=19/33.89041/35.50665
- https://openstreetmap.org/search?query=Falafel%20Sahyoun#map=19/33.89041/35.50665
- https://2gis.ru/moscow/firm/4504127908589159/center/37.6186,55.7601/zoom/15.9764
- https://2gis.ru/moscow/firm/4504127908589159?m=37.618632%2C55.760069%2F15.232

Limitations:

- goo.gl and other URL shorteners are not supported yet
- Google links with Plus Codes (OLC) are not supported

In context of #475

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2022-01-09 17:21 UTC, biodranik requested changes

2022-01-09 17:21 UTC, biodranik commented on coding/url.cpp
> +  VERIFY(strings::to_double(m[lati].str(), lat), ());
Неверно, надо везде return false если ошибка. VERIFY в релизе выпиливается и оставляет код без проверки. А в дебаге упадёт, но мы можем не протестить эти падающие кейзы.

2022-01-09 17:21 UTC, biodranik commented on coding/url.cpp
> +    // Try m=$lon,$lat/$zoom first
Точки в конце комментов.

2022-01-09 17:21 UTC, biodranik commented on coding/url.cpp
> +}; // Class DoubleGISParser
Убрать.

2022-01-09 17:21 UTC, biodranik commented on coding/url.cpp
> +    : m_pathRe("/(\\d+\\.?\\d*),(\\d+\\.?\\d*)/zoom/(\\d+\\.?\\d*)"),
Все regex лучше задавать как raw C++ string literal, тогда будут нормально читаться слеши:
`R"/(\d+\.?\d*),(\d+\.?\d*)/zoom/(\d+\.?\d*)"`

2022-01-09 17:21 UTC, biodranik commented on coding/url.cpp
> +  regex m_pathRe;
std::regex, так понятнее.

2022-01-09 17:21 UTC, biodranik commented on coding/url.cpp
> +    // Check if "#map=" fragment is attached to the last param in Url
.

2022-01-09 17:21 UTC, biodranik commented on coding/url.cpp
> +  regex m_regex;
std::, убрать внизу коммент.

2022-01-09 17:21 UTC, biodranik commented on coding/url.cpp
> +    // Check if "#map=" fragment is attached to the last param in Url
Он может быть и не последним, строго говоря. Надо доработать Url класс, чтобы он парсил отдельно решётку, а в params оставлял только query params, которые через амперсанд после вопросика.

2022-01-09 17:21 UTC, biodranik commented on coding/url.cpp
> +    if (!url.Params().empty() && MatchLatLonZoom(url.Params().back().m_value, m_regex, 2, 3, 1, info))
Надёжнее ForEachParam запускать с лямбдой. Лучше всего переделать, чтобы ForEachParam возвращал bool из лямбды, @vng может помочь.

2022-01-09 17:21 UTC, biodranik commented on coding/url.hpp
> +  const std::vector<Param> & Params() const { return m_params; }
Есть ForEachParam, не надо сырые кишки наружу выставлять. См. мой коммент выше.

2022-01-09 19:21 UTC, vng commented
У нас GeoURLInfo вызывается при поиске search::Processor::SearchCoordinates()
Так что тут не надо крепко нагружать парсер. Я завтра гляну как оно.

2022-01-09 19:38 UTC, vng reviewed
В целом, это можно забирать, но отдельно надо подрефакторить (потом) АПИ url::GeoURLInfo. В поиске его инстанс создается каждый раз на итерации поиска, а там инициализируются regex. Логично создавать инстанс (инициализировать) один раз и вызывать функцию парсинга.

2022-01-09 19:38 UTC, vng commented on android/AndroidManifest.xml
> +        <data android:host="2gis.cl"/>
дубль

2022-01-09 19:38 UTC, vng commented on android/AndroidManifest.xml
> +        <data android:host="m.2gis.cl"/>
дубль

2022-01-09 19:38 UTC, vng commented on coding/url.cpp
>    LatLonParser parser(url, *this);
А google парсится тут?

2022-01-09 20:22 UTC, biodranik commented
> В целом, это можно забирать, но отдельно надо подрефакторить (потом) АПИ url::GeoURLInfo. В поиске его инстанс создается каждый раз на итерации поиска, а там инициализируются regex. Логично создавать инстанс (инициализировать) один раз и вызывать функцию парсинга.

Давай сразу делать нормально, потом точно не до этого. А поиск у всех юзеров 100% будет жрать больше батареи. Всегда.

2022-01-09 20:27 UTC, vng commented
Ок. Не мержим, я могу завтра взять PR и допилить как я вижу с нормальным АПИ.

2022-01-09 20:34 UTC, rtsisyk commented on android/src/com/mapswithme/maps/intent/Factory.java
> +      return host.contains("google") || host.contains("2gis") || host.contains("openstreetmap");
Эта проверка для выбора какой IntentProcessor запускать. В коде списка из десятка IntentProcessor и код определяет какой запускать по вызову isSupported().

2022-01-09 20:34 UTC, rtsisyk commented on android/src/com/mapswithme/maps/intent/Factory.java
> +    OpenHttpMapsUrlTask(@NonNull String url)
Попробую убрать, но вообще это копипаста из аналогичного класса.

2022-01-09 20:34 UTC, rtsisyk commented on coding/coding_tests/url_tests.cpp
> +  info = GeoURLInfo("https://www.google.com/maps/place/Falafel+M.+Sahyoun/@33.8904447,35.5044618,16z");
Это не сделано сейчас вообще ни для какого формата. В частности, из-за этого и не работает Instagram. Думаю смотреть это в следущий заход. Гугл парсится существующим парсером, я новый не добавлял.

2022-01-09 20:34 UTC, rtsisyk commented on coding/coding_tests/url_tests.cpp
> +  // Sic: zoom is not parsed
Потому что код существующего парсера настолько universal и generic, что конкретно этот кейс парсить не умеет. Я думаю писать для гугла отдельный специализированный вариант, который а) Сможет парсить Plus Code b) Будет извлекать названия. Пока что гугл парсится на существуем коде как есть. Я лишь добавил новый тесткейс и починил в Android захват данного url.

2022-01-09 20:34 UTC, rtsisyk commented on coding/coding_tests/url_tests.cpp
> +  info = GeoURLInfo("https://2gis.ru/moscow/firm/4504127908589159?m=37.618632%2C55.760069%2F15");
При шаринге из Google Maps, Yandex Maps, 2GIS и прочих выдается короткая ссылка, которая работает через сервис. В самой ссылке координат нет. Я пока что сделал парсинг urls из адресной строки браузера которые выдаются после разыменования ссылки (в поле Location:). На следущем этапе собираюсь добавлять разыменовывание через обращение к сервису.

В любом случае, с патчем хотя бы из браузера можно скопировать, вставить в телегу, отправить себе и открыть в приложении. Это уже лучше, чем переписывать адрес на арабском "побуквенно".

2022-01-09 20:34 UTC, rtsisyk commented on coding/coding_tests/url_tests.cpp
> +  info = GeoURLInfo("https://www.openstreetmap.org/search?query=Falafel%20Sahyoun#map=16/33.89041/35.50664");
Надо. Поэтому и инстаграмм не работает. В следущий заход. Там очень овенинженирнтый код с кучей прослоек, достаточно трудно сразу сделать переадачу query.

2022-01-09 20:34 UTC, rtsisyk commented on coding/url.cpp
> +}; // class LatLongParser
Мне было очень трудно найти где конец. Я посмотрю как сделано в других местах.

2022-01-09 20:34 UTC, rtsisyk commented on coding/url.cpp
> +  VERIFY(strings::to_double(m[lati].str(), lat), ());
Этот код скопирован из этого же файла несколькими экранами вниз. Там сделано именно также.

2022-01-09 20:34 UTC, rtsisyk commented on coding/url.cpp
> +    : m_pathRe("/(\\d+\\.?\\d*),(\\d+\\.?\\d*)/zoom/(\\d+\\.?\\d*)"),
Я попробую. Однако чуть выше было сделано с обычной строкой.

2022-01-09 20:34 UTC, rtsisyk commented on coding/url.cpp
> +  regex m_pathRe;
В этом же файле сделано также без std.

2022-01-09 20:34 UTC, rtsisyk commented on coding/url.cpp
> +    // Check if "#map=" fragment is attached to the last param in Url
Ну надо, но на за 10 лет никто не доработал. Я могу предложить написать этот парсер на Java с уменьшением кода в 10 раз.

2022-01-09 20:34 UTC, rtsisyk commented on coding/url.cpp
> +    if (!url.Params().empty() && MatchLatLonZoom(url.Params().back().m_value, m_regex, 2, 3, 1, info))
Тут берется последнее значение. Какая лямбда и зачем она тут?

2022-01-09 20:34 UTC, rtsisyk commented on coding/url.cpp
>    LatLonParser parser(url, *this);
Да, текущие ссылки гугла парсятся пока что здесь. Точнее этот парсер типа универсальный и пытается парсить все возможные форматы во вселенной, но это получается очень херово с потерей информации.

2022-01-09 20:34 UTC, rtsisyk commented on coding/url.hpp
> +  const std::vector<Param> & Params() const { return m_params; }
Не вижу проблемы почему нельзя получать доступ к распарсенным query strings без всяких лямбд. В текущем коде вот написан целый класс чтобы просто проитерироваться по массиву со строчками. Мало того, что это вместо 5 строчек делает 50, так еще и читабельность на нуле.

2022-01-09 20:53 UTC, biodranik commented on android/src/com/mapswithme/maps/intent/Factory.java
> +    OpenHttpMapsUrlTask(@NonNull String url)
Давай новый код писать не копипастом, а головой, и вычищать старые костыли.

2022-01-09 20:55 UTC, biodranik commented on coding/url.cpp
> +    // Check if "#map=" fragment is attached to the last param in Url
Спасибо, не нужно. А вот что нужно: если браться, то делать хорошо, и доводить до конца.

2022-01-09 20:55 UTC, biodranik commented on coding/url.cpp
> +    if (!url.Params().empty() && MatchLatLonZoom(url.Params().back().m_value, m_regex, 2, 3, 1, info))
Порядок параметров может в теории меняться.

2022-01-09 20:56 UTC, biodranik commented on coding/url.hpp
> +  const std::vector<Param> & Params() const { return m_params; }
Текущий класс проюниттестирован и проверен. Если у тебя есть решение получше, велкам, сделай с юнит тестами свою реализацию, чтобы нигде ничего не сломалось.

2022-01-09 21:00 UTC, biodranik commented
> UPD: Тут кстати мы можем пересмотреть, надо ли в поиске пытаться парсить урлы.

Иногда это бывает удобно. Можно парсить, если это не сильно затратно. Например, если не гоняются регекспы там, где не нужно. Текущий код, к сожалению, не умеет нестандартные урлы типа geo, нашего om и т.п., и заточен только под http(s) ссылки. Да и то не до конца.

2022-01-09 21:01 UTC, biodranik commented on coding/url.cpp
>    LatLonParser parser(url, *this);
Мне не нравится такой "универсальный" подход, где коряво парсятся ссылки. Лучше добавлять по одной, но поддерживать полностью и нормально, а не потом ловить жалобы юзеров и тратить время на поддержку и фиксы.

2022-01-09 21:04 UTC, biodranik commented
Основная важность этого PR в том, чтобы подготовиться к воскрешению API.

2022-01-09 21:07 UTC, biodranik commented on coding/url.cpp
>    LatLonParser parser(url, *this);
По гуглу: @rtsisyk закодированные гуглоссылки сейчас же пока не будут открываться? Это следующий шаг?
Если ты над ним работаешь, то обязательно делай через наш CF worker proxy, можно даже заюзать текущий паблик https://github.com/organicmaps/url-processor
Нельзя, чтобы закодированные ссылки лезли сразу на гугл. Пускай гугл собирает статистику с наших Workers, а не с реальных пользователей.

2022-01-22 21:15 UTC, biodranik commented on ge0/geo_url_parser.cpp
> +: m_pathRe("/(\\d+\\.?\\d*),(\\d+\\.?\\d*)/zoom/(\\d+\\.?\\d*)")
Те же замечания к regex что и выше.

2022-01-22 21:15 UTC, biodranik commented on ge0/geo_url_parser.cpp
> +: m_regex("#map=(\\d+\\.?\\d*)/(\\d+\\.\\d+)/(\\d+\\.\\d+)")
Тоже поправить.

2022-01-22 21:15 UTC, biodranik commented on ge0/geo_url_parser.hpp
> +  std::regex m_regex;
Это должны быть статические переменные внутри тел Parse, тогда будет кеширование.

2022-01-22 21:15 UTC, biodranik commented on map/framework.cpp
> +    geo::GeoURLInfo const info = geo::UnifiedParser().Parse(url);
Зачем вообще делать классы? Почему бы не geo::ParseGeo(url)?

2022-01-22 21:15 UTC, biodranik commented on map/mwm_url.cpp
> +  auto const path = url.GetHost();
Некрасиво получилось. Переименуй path в type или cmd

2022-01-22 21:20 UTC, biodranik commented on ge0/geo_url_parser.cpp
> +int LatLonParser::GetCoordinatesPriority(string const & token)
Честно, эта штука выглядит стрёмной магией. Попытка всё обобщить, на мой взгляд, только усложнила код и возможно приведёт к ошибкам. Я даже не до конца понял, как оно работает.

Я бы парсил в лоб, по if проходясь по каждому урлу, который мы хотим поддержать, оставляя комментарии с примерами. Тогда было бы очень просто отлаживать, и добавлять новые кейзы.

2022-01-22 21:42 UTC, vng commented on base/string_utils.cpp
> +  std::transform(s.begin(), s.end(), s.begin(), [](char in)
Тут больше для читабельности/лаконичности. Есть godbolt.org, можно экспериментировать если интересно.

2022-01-22 21:43 UTC, vng commented on coding/coding_tests/url_tests.cpp
> +UNIT_TEST(Url_Encode)
У нас есть --filter="Url_" для запуска тестов. В целом, это сложившееся нотация, где префикс до _ определяет семейство тестов.

2022-01-22 21:46 UTC, vng commented on coding/coding_tests/url_tests.cpp
>    TEST_EQUAL(Url("mapswithme:").GetScheme(), "mapswithme", ());
Этот тест можно убрать, там ниже все такое будет.

2022-01-22 21:48 UTC, vng commented on coding/coding_tests/url_tests.cpp
> +  TestUrl("nopathnovalues://?key1&key2=val2").Scheme("nopathnovalues").Host("").Path("")
- KV есть же ниже
- добавил

2022-01-22 21:49 UTC, vng commented on coding/url.cpp
> +    ASSERT(m_scheme.empty() && m_host.empty() && m_path.empty() && !IsValid(), ());
В итоге будут ли valid или invalid. Убирать конструктор, это коцать много кода и не вижу преимуществ.

2022-01-22 21:49 UTC, vng commented on coding/url.cpp
> +  if (start == std::string::npos)
Ну вот такой например есть:

  TestUrl("om:M&M/path?q=q&w=w")
      .Scheme("om")
      .Host("M&M")
      .Path("path")
      .KV("q", "q")
      .KV("w", "w");

2022-01-22 21:50 UTC, vng commented on coding/url.cpp
> +  start = url.find_first_not_of('/', start + 1);
Хм, ну я посчитал что первый параметр будет всегда host для определенности. Иначе клиентский код сложнее

2022-01-22 21:52 UTC, vng commented on coding/url.hpp
> +// Url in format: 'scheme://host/path?key1=value1&key2&key3=&key4=value4'
Для удобства текущего кода host - это первый параметр после схемы. Неважно какой он там. Может быть 2gis.ru, а может просто map

2022-01-22 21:53 UTC, vng commented on coding/url.hpp
>    static Url FromString(std::string const & url);
if (res) vs if (res.IsValid), то же самое, имхо, а мороки будет больше.

2022-01-22 21:54 UTC, vng commented on coding/url.hpp
> +  std::string const & GetHost() const { return m_host; }
Непонятно про оверлоад. Ну тут наши договоренности. Как бы принято функции начинать с глагола было всегда ..

2022-01-22 21:54 UTC, vng commented on coding/url.hpp
> +  std::string GetHostAndPath() const { return m_host + m_path; }
Хм, нет. Добавлю слеш

2022-01-22 21:55 UTC, vng commented on coding/url.hpp
> +      fn(p);
Сейчас вектор пар. p - считай пара

2022-01-22 21:56 UTC, biodranik commented on coding/coding_tests/url_tests.cpp
> +UNIT_TEST(Url_Encode)
Так можно было и без подчёркивания ) Ну ок.

2022-01-22 21:56 UTC, vng commented on coding/url.hpp
> +  std::string const * GetParamValue(std::string const & name) const
optional на что? Здесь без копирования возвращается указатель на элемент

2022-01-22 21:57 UTC, vng commented on ge0/ge0_tests/geo_url_tests.cpp
> +  GeoURLInfo info = UnifiedParser().Parse("geo:0,0?z=14&q=54.683486138,25.289361259 (Forto%20dvaras)");
он переприсваивается в дальнейших тестах

2022-01-22 21:58 UTC, vng commented on ge0/ge0_tests/geo_url_tests.cpp
> +  TEST_ALMOST_EQUAL_ABS(info.m_zoom, 0.0, kEps, ());
так на входе был плохой -1, который корректируется на дефолтный 0

2022-01-22 21:59 UTC, biodranik commented on coding/url.cpp
> +    ASSERT(m_scheme.empty() && m_host.empty() && m_path.empty() && !IsValid(), ());
Преимущество при использовании std::optional - можно писать scoped if:
```
if (auto url = url::FromString(str)) {
   // … 
}
```

2022-01-22 21:59 UTC, biodranik commented on coding/url.hpp
>    static Url FromString(std::string const & url);
Выше показал, почему будет проще код.

2022-01-22 22:00 UTC, biodranik commented on coding/url.hpp
> +  std::string GetHostAndPath() const { return m_host + m_path; }
А как оно работало?..

2022-01-22 22:00 UTC, vng commented on ge0/geo_url_parser.hpp
> +  std::regex m_regex;
Кэширование уже есть в объекте. Не нужно здесь статически.

2022-01-22 22:01 UTC, vng commented on map/framework.cpp
> +    geo::GeoURLInfo const info = geo::UnifiedParser().Parse(url);
Хранить инициализированное состояние.

2022-01-22 22:02 UTC, biodranik commented on coding/url.hpp
> +      fn(p);
Ну, такое. Наружу выставлять url::Param некрасиво, тем более, что это не нужно.

2022-01-22 22:02 UTC, vng commented on map/mwm_url.cpp
> +  auto const path = url.GetHost();
Не понял. Тут именно первое после схемы.

2022-01-22 22:03 UTC, biodranik commented
Объект же не нужен вообще.

2022-01-22 22:03 UTC, vng commented on ge0/geo_url_parser.cpp
> +int LatLonParser::GetCoordinatesPriority(string const & token)
Скорее всего, это все можно сделать красивее. Сейчас есть вход, есть ожидаемый выход - и оно работает. Можно потратить еще времени ..

2022-01-22 22:06 UTC, biodranik commented
Один кейз с зумом уже не работает. Потом надо будет добавлять ещё разных урлов, ещё что-то всплывёт.

2022-01-22 22:30 UTC, biodranik commented on coding/url.cpp
> +    ASSERT(m_scheme.empty() && m_host.empty() && m_path.empty() && !IsValid(), ());
Конечно, можно и так:
```
if (auto const url = url::FromString(str); url.IsValid()) {
}
```

2022-01-22 22:32 UTC, biodranik commented on coding/url.cpp
> +  if (start == std::string::npos)
Имел ввиду scheme с двоеточием.

2022-01-22 22:33 UTC, biodranik commented on coding/url.hpp
> +// Url in format: 'scheme://host/path?key1=value1&key2&key3=&key4=value4'
Напиши в комменте, что host может быть что угодно, а не только валидные домены.

2022-01-23 05:46 UTC, vng commented on coding/url.cpp
> +  if (start == std::string::npos)
ага, ок

2022-01-23 05:54 UTC, vng commented on coding/coding_tests/url_tests.cpp
> +  TestUrl("mapswithme://map?ll=1.2,3.4&z=15").Scheme("mapswithme").Host("map").Path("")
Возможно, тут я делал так, как было до.

2022-01-23 05:56 UTC, vng commented on coding/url.hpp
> +  std::string GetHostAndPath() const { return m_host + m_path; }
Эта функция вызывается только для find(подстрока)

2022-01-23 06:05 UTC, vng commented
- Объект нужен для инициализации состояния. Состояние - это как раз все regex, которые _тяжело_ инициализируются. Вариант со static мне не нравится, мы как-то очень давно это обсуждали. Там будет как минимум созданная компилятором ненужная синхронизация. Ну и имхо static - это недостаток в дизайне. Если есть возможность явно отделить инициализацию и использование, то лучше так и делать. Иначе весь код можно завести в парадигму static объекты + функции :)
- Один кейз с зумом не работает - это как раз то, что завезли недавно и что должно матчится regex, но что-то идет не так :) Простыня странного кода сидит давно и вычисляет те случаи, что не совсем хорошо матчатся на regex.

2022-01-23 07:37 UTC, biodranik commented on map/mwm_url.cpp
> +  auto const path = url.GetHost();
Ниже код работает с path, а теперь это не path, а host. Но по логике лучше назвать type или command.

2022-01-23 07:40 UTC, biodranik commented
> * Один кейз с зумом не работает - это как раз то, что завезли недавно и что должно матчится regex, но что-то идет не так :) Простыня странного кода сидит давно и вычисляет те случаи, что не совсем хорошо матчатся на regex.

Этот кейз не ловится regex, Рома не смог сразу сделать. Дальше будет больше таких примеров. Нулевой или дефолтный зум при открытии метки — это плохо.

2022-01-23 11:00 UTC, vng commented on ge0/geo_url_parser.cpp
> +, m_regexp("-?\\d+\\.{1}\\d*, *-?\\d+\\.{1}\\d*")
Хм, тут как бы простое "10, 10" не матчится

2022-01-23 11:07 UTC, vng commented on ge0/geo_url_parser.cpp
> +, m_regexp("-?\\d+\\.{1}\\d*, *-?\\d+\\.{1}\\d*")
Я предлагаю простой R"(-?\d+\.?\d*, *-?\d+\.?\d*)"

2022-01-23 21:15 UTC, biodranik approved these changes
Можно некоторые оставшиеся комменты глянуть и мержить.

2022-01-23 21:15 UTC, biodranik commented on coding/url.hpp
> +//std::string Make(std::string const & baseUrl, Params const & params);
Удалить.

2022-01-23 21:15 UTC, biodranik commented on ge0/ge0_tests/geo_url_tests.cpp
> +  TEST_ALMOST_EQUAL_ABS(info.m_zoom, 0.0, kEps, ());
Так давай может дефолтный изменим на не 0?

2022-01-24 13:25 UTC, merged