Location sharing text format update
organicmaps/organicmaps pull request #1821
Opened 2022-01-09 19:00 UTC by pastk

The new format:
* bookmark / poi / place name if available and except "Unknown Place" and "My Position"
* address if available
* https://omaps.app/XYZ/Name link
* decimal Lat, Lot coords

iOS code was edited naively without any testing, so needs attention of iOS devs (or I can exclude it from the PR).

2022-01-09 20:06 UTC, biodranik commented
```
/Users/runner/work/organicmaps/organicmaps/iphone/Maps/Classes/Share/MWMShareActivityItem.mm:97:16: error: no visible @interface for 'MWMShareActivityItem' declares the selector 'subjectDefault'
  return [self subjectDefault];
          ~~~~ ^~~~~~~~~~~~~~
/Users/runner/work/organicmaps/organicmaps/iphone/Maps/Classes/Share/MWMShareActivityItem.mm:118:21: error: cannot initialize a variable of type 'NSMutableString *__strong' with an lvalue of type 'const char [1]'
  NSMutableString * result = "";
                    ^        ~~
2 errors generated.
```

2022-01-09 20:16 UTC, pastk commented
I need help with iOS changes (I edit naively, I have no means to build it even).
Otherwise I'll drop iOS changes from this PR.

2022-01-09 20:18 UTC, biodranik reviewed
How does email sharing look now? Which is the subject and the body text?

2022-01-09 20:51 UTC, pastk commented
subject пустой
текст такой же, как и при отправке в мессенджер (см. описание выше)

2022-01-09 21:08 UTC, biodranik commented
> subject пустой текст такой же, как и при отправке в мессенджер (см. описание выше)

Это плохо. Раньше был не пустой. Текст сабжекта можно менять, но убирать его полностью мне кажется очень плохой идеей.

2022-01-09 21:13 UTC, pastk commented
вот так:
![Screenshot_20220110-010916](https://user-images.githubusercontent.com/18434508/148701151-a2b878a9-a92a-4106-9ce5-8d089322f05c.jpg)
можно и вернуть его, просто он никакой смысловой нагрузки не несёт
а поскольку ещё и по электронке сейчас редко кто шарит, то я решил совсем его убрать

2022-01-09 21:18 UTC, biodranik commented
> можно и вернуть его, просто он никакой смысловой нагрузки не несёт

Туда можно вставлять имя метки и/или адрес, если они есть. А если нет, то заглушку типа Open in Organic Maps

2022-01-09 21:20 UTC, pastk commented
Хорошая идея с именем! Завтра сделаю

2022-01-09 21:36 UTC, biodranik commented
> Хорошая идея с именем! Завтра сделаю

Если бы была возможность программно различать и подставлять разные тексты в зависимости от того, шарится в емейл или нет, то можно было бы рассмотреть что-то такое:

1. Для емейлов вставлять в сабж адрес и имя, если они есть, или Open in Organic Maps если нет (текст можно продумать более полезный). При этом в идеале различать случаи шаринга своей текущей позиции и просто любой позиции. Чтобы просто по взгляду на сабж было видно, что это за точка (своя позиция чаще всего будет без имени и адреса). Например, I'm here now, или My position in Organic Maps.
2. Для емейлов в бади можно вставлять больше текста и ссылок. Начиная с альтернативных geo:// урлов и заканчивая прямой ссылкой на установку OM, как было раньше.
3. Для не-емейлов оставлять всё максимально кратко, но по возможности тоже различать случай шаринга текущей позиции. Почему это важно? Чтобы при взгляде на сообщение было понятно, что "ага, он(а) сейчас вон там", без дополнительных действий при отправке и при прочтении. I'm here: https://omaps.app/xxx, или I'm at Cafe Numi, Zergstrasse 12, Zumikon https://omaps.app/xxx

2022-01-10 07:51 UTC, pastk commented
> Хорошая идея с именем! Завтра сделаю

Различать способ пересылки динамически не нашёл как.
Так что тогда получится дублирование имени точки и в теме, и в теле, что не очень, имхо.

2022-01-10 10:09 UTC, pastk commented
Переделал для андроида, вот примеры:
(subj используется только для емейлов, тело одинаковое и для емейлов, и для мессенджеров)

```
subj = Chechevitsa

Chechevitsa
Первомайская улица, 148А
https://omaps.app/w5gSA2uMPP/Chechevitsa
56.63404, 47.88158
```

если названия нет, то используется адрес:
```
subj = Первомайская улица, 148А

Первомайская улица, 148А
https://omaps.app/w5gSA2uMPP/Первомайская улица%2C_148А
56.63404, 47.88158
```

если и адреса нет, то дефолтный subj
```
subj = Hey, check out my pin in Organic Maps!

https://omaps.app/w5gSA2uMPP
56.63404, 47.88158
```

Unknown Place фильтруется, как непонятный и бесполезный
```
subj = Hey, check out my pin in Organic Maps!

https://omaps.app/w5gSA2uMPP
56.63404, 47.88158
```

my position
```
subj = Hey, check out my current location on the Organic Maps map!

Hey, check out my current location on the Organic Maps map!
https://omaps.app/w5gSA2uMPP/Hey%2C_check_out_my_current_location_on_the_Organic_Maps_map%21
56.63404, 47.88158
```
можно текст сменить на покороче, например `I am here`

2022-01-10 10:24 UTC, biodranik commented
> Так что тогда получится дублирование имени точки и в теме, и в теле, что не очень, имхо.

Дублировать точно не надо. На сколько я понял, при отправке в мессенджеры subject склеивается с телом, так что можно не дублировать. Должно само работать верно, хотя бы в урезанном виде (без if (email) then …)

2022-01-10 10:45 UTC, pastk commented
> > Так что тогда получится дублирование имени точки и в теме, и в теле, что не очень, имхо.
> 
> Дублировать точно не надо. На сколько я понял, при отправке в мессенджеры subject склеивается с телом, так что можно не дублировать. Должно само работать верно, хотя бы в урезанном виде (без if (email) then …)

Нет, не так. Сейчас дублирует мой код.
Андроидом сабжект используется только для емейла, в остальных случаях он просто игнорируется.
Т.е. не получится сделать так, чтобы название/адрес были для емейла только в сабжекте, а для остальных - в теле.

Если не дублировать название/адрес в сабжекте, то вариант только дефолтный текст в нём иметь, например
```
subj = Hey, check out my pin in Organic Maps!

Chechevitsa
Первомайская улица, 148А
https://omaps.app/w5gSA2uMPP/Chechevitsa
56.63404, 47.88158
```

для my position логичнее всё же продублировать текст, имхо
(чем делать `subj = Hey, check out my pin in Organic Maps!`)
```
subj = Hey, check out my current location on the Organic Maps map!

Hey, check out my current location on the Organic Maps map!
https://omaps.app/w5gSA2uMPP/Hey%2C_check_out_my_current_location_on_the_Organic_Maps_map%21
56.63404, 47.88158
```

2022-01-10 10:55 UTC, biodranik commented
> Андроидом сабжект используется только для емейла, в остальных случаях он просто игнорируется.

Как тогда в текущем мастере подставляется для емейла сабжект, а для месенджеров адрес?

2022-01-10 11:43 UTC, pastk commented
> > Андроидом сабжект используется только для емейла, в остальных случаях он просто игнорируется.
> 
> Как тогда в текущем мастере подставляется для емейла сабжект, а для месенджеров адрес?

В сабжект ложится дефолтная строка, а в тело адрес.
Андроид для мессенджеров отбрасывает сабжект, остаётся только тело с адресом.
А в емейле отправляется и сабжект со строкой, и тело с адресом.

```
    final String subject = MapObject.isOfType(MapObject.MY_POSITION, object) ?
                           context.getString(R.string.my_position_share_email_subject) :
                           context.getString(R.string.bookmark_share_email_subject);
    intent.putExtra(Intent.EXTRA_SUBJECT, subject);

...

    final String address = TextUtils.isEmpty(object.getAddress()) ? object.getName() : object.getAddress();
    final String text = context.getString(R.string.my_position_share_email, address, geoUrl, httpUrl);
    intent.putExtra(Intent.EXTRA_TEXT, text);
```

2022-01-10 12:14 UTC, biodranik commented
Почти идеально:

> Переделал для андроида, вот примеры: (subj используется только для емейлов, тело одинаковое и для емейлов, и для мессенджеров)
> 
> ```
> subj = Chechevitsa
> 
> Chechevitsa
> Первомайская улица, 148А
> https://omaps.app/w5gSA2uMPP/Chechevitsa
> 56.63404, 47.88158
> ```

Поменять сабж и убрать пробел после запятой, чтобы даблкликом сразу выбирались обе координаты.
```
subj = Chechevitsa в Organic Maps

Chechevitsa
Первомайская улица, 148А
https://omaps.app/w5gSA2uMPP/Chechevitsa
56.63404,47.88158
```

> если названия нет, то используется адрес:
> 
> ```
> subj = Первомайская улица, 148А
> 
> Первомайская улица, 148А
> https://omaps.app/w5gSA2uMPP/Первомайская улица%2C_148А
> 56.63404, 47.88158
> ```
> 
> если и адреса нет, то дефолтный subj
> 
> ```
> subj = Hey, check out my pin in Organic Maps!
> 
> https://omaps.app/w5gSA2uMPP
> 56.63404, 47.88158
> ```
> 
> Unknown Place фильтруется, как непонятный и бесполезный
> 
> ```
> subj = Hey, check out my pin in Organic Maps!
> 
> https://omaps.app/w5gSA2uMPP
> 56.63404, 47.88158
> ```
> 
> my position
> 
> ```
> subj = Hey, check out my current location on the Organic Maps map!
> 
> Hey, check out my current location on the Organic Maps map!
> https://omaps.app/w5gSA2uMPP/Hey%2C_check_out_my_current_location_on_the_Organic_Maps_map%21
> 56.63404, 47.88158
> ```
> 
> можно текст сменить на покороче, например `I am here`

2022-01-10 13:53 UTC, pastk commented
Всё сделал.

> > если и адреса нет, то дефолтный subj
> > ```
> > subj = Hey, check out my pin in Organic Maps!
> > 
> > https://omaps.app/w5gSA2uMPP
> > 56.63404, 47.88158
> > ```
> 
> Слишком длинно, лучше Shared location on the Organic Maps

На три символа короче :)
Сделал `My pin in Organic Maps`.

```
subj = My pin in Organic Maps

https://omaps.app/w5gSA2uMPP
56.63404,47.88158
```

my position
```
subj = I am here on Organic Maps

I am here on Organic Maps
https://omaps.app/w5gSA2uMPP/I_am_here_on_Organic Maps
56.63404,47.88158
```

```
subj = Chechevitsa on Organic Maps

Chechevitsa
Первомайская улица, 148А
https://omaps.app/w5gSA2uMPP/Chechevitsa
56.63404,47.88158
```

2022-01-10 14:19 UTC, pastk commented
Немного причесал iOS версию, может даже будет работать :) Логика там всё равно не совсем как в андроиде сейчас.

2022-01-10 14:29 UTC, biodranik commented
> Сделал `My pin in Organic Maps`.

Когда я получаю емейл с таким текстом, выглядит не очень понятно. Плюс люди же могут шарить не только букмарки, но и что угодно. Это "Объект на карте Organic Maps". Но можно оставить и my pin пока. Хотя my чуть смущает, близко к my location.

2022-01-10 22:03 UTC, biodranik commented
Почему в Android 33 файла с локализациями, а в iOS — 38?

2022-01-11 08:47 UTC, pastk commented
> Почему в Android 33 файла с локализациями, а в iOS — 38?

Я в андроиде 39 папок насчитал, а в айос 38 - потому что fr-CA нет.

2022-01-11 11:53 UTC, biodranik commented
Удалить коммит с генерацией, отребейзить, перегенерить без af и hi

2022-01-11 11:57 UTC, pastk commented on data/strings/strings.txt
> +    ru = Моя точка на картах Organic Maps
Предложения?

2022-01-11 11:58 UTC, biodranik commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> -      return data.previewData.subtitle;
Здесь возвращалась строчка с типами фичи, то, что под названием пишется в PP (restaurant * italian). Полезная инфа для шаринга, если она есть. Для ведра тоже можно добавить, пускай после имени пишется в скобках, или через запятую.

2022-01-11 11:59 UTC, biodranik commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> -      return L(@"core_my_position");
Почему не share_my_position? Если выбрана текущая позиция на карте, то этот кейз вернёт пустую строку. А внизу share_my_position

2022-01-11 11:59 UTC, pastk commented on android/src/com/mapswithme/util/SharingUtils.java
> +    text.append(Framework.nativeFormatLatLon(lat, lon, CoordinatesFormat.LatLonDecimal.getId()).replace(" ", ""));
думаю в PP точно используется для вывода координат, мож и ещё где
страшновато в ядре менять

2022-01-11 12:00 UTC, pastk commented on android/src/com/mapswithme/util/SharingUtils.java
> +                  true, "", "");
туду вставлю

2022-01-11 12:03 UTC, pastk commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> -      return data.previewData.subtitle;
Я думал над этим. Перегруза не получится? Там многие в чате вообще без текста хотели бы.

2022-01-11 12:04 UTC, pastk commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> -      return L(@"core_my_position");
Потому что так было :)
Я не знаю, как оно реально в айфоне отображается, правлю вслепую :)

2022-01-11 12:05 UTC, pastk commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> -      return L(@"core_my_position");
Лучше чтоб кто-нибудь другой за айфон взялся, мои правки разве что как заготовку использовать можно.

2022-01-11 13:17 UTC, pastk commented on android/src/com/mapswithme/util/SharingUtils.java
> +    text.append(Framework.nativeFormatLatLon(lat, lon, CoordinatesFormat.LatLonDecimal.getId()).replace(" ", ""));
ещё в андроиде в RoutingController для чего-то используется, в ядро и айфон даже не заглядывал
scope расползается, хочется ограничить уже

2022-01-11 13:39 UTC, biodranik commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
>    std::vector<NSString *> strings{self.data.previewData.title,
```
  std::string result;
  PlacePagePreviewData * pd = self.data.previewData;
  for (auto const & str : {pd.title, pd.subtitle, pd.address, self.data.infoData.phone, url})
  {
    if (str.length)
      result += "\n" + str;
  }
  return @(result.c_str());
```

2022-01-11 13:42 UTC, biodranik commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> -      return data.previewData.subtitle;
По названию не всегда понятно, что за фича. Если текст будет компактный, и неплохо смотреться как одна строка/предложение, то нужно вставлять. Например:
Siniola (cafe * vegetarian * WiFi), Bahnhof strasse 12, Zurich https://omaps.app/XXXXX/Siniola

2022-01-11 13:44 UTC, biodranik commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> -      return data.previewData.subtitle;
Для емейлов, конечно же, переносы строк лучше. Они автоматом в пробелы превратятся в обычных мессенджерах?

2022-01-11 13:44 UTC, pastk commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> +  NSMutableString * result = [@""];
спасибо за знания!
в последней версии я даже с `[@"" mutableCopy]` угадал :)

2022-01-11 13:47 UTC, pastk commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
>    std::vector<NSString *> strings{self.data.previewData.title,
тут только лишний перевод строки в начале будет, ничего?

2022-01-11 13:51 UTC, pastk commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> -      return data.previewData.subtitle;
в андроиде думаю не превратятся
это если только сам мессенджер полученную строку захочет переформатировать

2022-01-11 13:54 UTC, pastk commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> -      return data.previewData.subtitle;
если текст на непонятном языке из какой-нибудь страны, то даже можно спутать, где кончается название, а где начинается адрес :)
мне кажется с переносом строк попонятнее структура

2022-01-11 14:01 UTC, pastk commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> -      return data.previewData.subtitle;
а если шарить метку, то в субте название списка не вылезет?
вобщем мне кажется тут надо будет хорошо так тестить и исключения делать (например, для unknown place в субте координаты убирать)
можно отдельным pr потом, если желание появится

2022-01-11 14:04 UTC, pastk commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
>    std::vector<NSString *> strings{self.data.previewData.title,
добавил этот код

2022-01-11 16:06 UTC, pastk commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
>    std::vector<NSString *> strings{self.data.previewData.title,
```
error: invalid operands to binary expression ('const char [2]' and 'NSString *__strong const')
      result += "\n" + str;
                ~~~~ ^ ~~~
```

2022-01-11 20:44 UTC, biodranik commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> +      return [NSString stringWithFormat:@"%@", url];
```suggestion
      return url;
```

2022-01-11 20:44 UTC, biodranik commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> +      return [NSString stringWithFormat:@"%@", url];
```suggestion
      return url;
```

2022-01-11 20:45 UTC, biodranik commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> -      return data.previewData.subtitle;
Надо тестировать )

2022-01-11 20:46 UTC, biodranik commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
> -      return data.previewData.subtitle;
> мне кажется с переносом строк попонятнее структура

Да, верно, особенно для RTL языков.

2022-01-11 20:57 UTC, biodranik commented on iphone/Maps/Classes/Share/MWMShareActivityItem.mm
>    std::vector<NSString *> strings{self.data.previewData.title,
> тут только лишний перевод строки в начале будет, ничего?

Он был и в изначальном коде. Надо поменять на `result += result.empty() ? str : "\n" + str;`

2022-01-11 23:15 UTC, biodranik commented on android/src/com/mapswithme/util/SharingUtils.java
> +    //TODO: try to obtain address of the currect position
```suggestion
    // TODO: try to obtain the address of the current position.
```

2022-01-11 23:15 UTC, biodranik commented on data/strings/strings.txt
> +    en = My pin on Organic Maps
```suggestion
    en = A place on Organic Maps
```

2022-01-11 23:15 UTC, biodranik commented on data/strings/strings.txt
> +    ru = Моя точка на картах Organic Maps
```suggestion
    ru = Координаты в Organic Maps
```

2022-01-11 23:15 UTC, biodranik commented on data/strings/strings.txt
>      be = Гэй, глядзі маю метку на Organic Maps!
```suggestion
    be = Каардынаты ў Organic Maps
```

2022-01-11 23:15 UTC, biodranik commented on data/strings/strings.txt
> +    uk = Моя точка на мапах Organic Maps
```suggestion
    uk = Координати у Organic Maps
```

2022-01-11 23:15 UTC, biodranik commented on data/strings/strings.txt
> +    en = %1$@ on Organic Maps
```suggestion
    en = %1$@ on Organic Maps
    be = %1$@ ў Organic Maps
```

2022-01-11 23:15 UTC, biodranik commented on data/strings/strings.txt
> +    be = Гэй, глядзі дзе я зараз на мапе Organic Maps
```suggestion
    be = Я зараз тут на мапе Organic Maps
```

2022-01-12 18:00 UTC, vng requested changes
- iOS crashes now
- No need to append share_my_position to the sharing url

2022-02-05 09:37 UTC, rtsisyk requested changes
Folks, could you please illustrate proposed changes?  For example,

Before this patch:

```
Hey, check out my current location on the Organic Maps map!
https://omaps.app/w5gSA2uMPP/Hey%2C_check_out_my_current_location_on_the_Organic_Maps_map%21
56.63404, 47.88158
```

After this patch:

```
https://omaps.app/w5gSA2uMPP/%21
56.63404, 47.88158
```

2022-02-05 10:05 UTC, pastk commented
The current state of this PR is
Android change is done
iOS change is half done (its being worked on `pastk-loc-share` branch in the main repo) - waiting for someone to finish it @biodranik or @vng ?
after iOS is done we'll merge them together

2022-02-10 13:50 UTC, biodranik commented
Don't hurry. Let's do it properly.

2022-10-22 20:31 UTC, LaoshuBaby commented on android/res/values-zh/strings.xml
> +	<string name="share_my_position">嗨，到 Organic Maps 查看我的当前位置</string>
Sorry, do you already changed `share_my_position`'s English string to `I am here on Organic Maps`?

`share_my_position`'s new zh translation is for old English string `Hi, check out my current location in Organic Maps!`, which in `my_position_share_sms`.

2022-10-22 20:31 UTC, LaoshuBaby commented on android/res/values-zh/strings.xml
> +	<string name="share_coords_subject_default">嘿，在 Organic Maps 上查看我标注的图钉吧！</string>
Your current Chinese translation is for deleted `bookmark_share_email_subject`, not for new `share_coords_subject_default`. Is this excepted? I don't know.

2022-10-22 20:31 UTC, LaoshuBaby commented on android/res/values-zh-rTW/strings.xml
> +	<string name="share_coords_subject_default">嘿，看看我在 Organic Maps 地圖上的圖釘！</string>
zh-TW have same problem with zh-CN version

2022-10-22 22:04 UTC, matheusgomesms approved these changes
I made small fixed into PT strings

2022-10-23 15:37 UTC, jimcarst approved these changes

2023-07-11 08:22 UTC, bam80 commented
What's left to be accepted?

2023-07-22 07:09 UTC, Zack-83 commented on android/res/values-it/strings.xml
> +	<!-- Text preceding shared "my position" coordinates -->
```suggestion
	<string name="share_coords_subject_default">Guarda il mio luogo salvato sulla mappa Organic Maps!</string>
	<!-- Text preceding shared "my position" coordinates -->
```
Being an Italian mother tongue, I replaced "You can see" with "watch" and "my favorite place" with "my place saved on"

2023-11-23 07:57 UTC, rtsisyk commented
I will try to finish this one because I hate how it works currently. Two links for some reason, non of them works properly on Android.

2024-04-16 07:45 UTC, Zack-83 commented on iphone/Maps/LocalizedStrings/it.lproj/Localizable.strings
> +"share_coords_subject_default" = "Puoi vedere il mio luogo preferito sulla mappa Organic Maps!";
```suggestion
"share_coords_subject_default" = "Guarda il mio luogo salvato sulla mappa Organic Maps!";
```

2024-04-16 07:48 UTC, Zack-83 requested changes
I find it good, but it does not solve #2261 . Please adjust the Italian language as from suggestions

2024-06-06 13:21 UTC, biodranik commented
@kirylkaveryn can you please help to summarize the different sharing formats (by dropping om:// links and changing other text), and then implement it after the discussion/review of all possible cases?

2024-06-21 09:31 UTC, Zack-83 commented on android/res/values-it/strings.xml
> +	<!-- Text preceding shared "my position" coordinates -->
I would appreciate if someone with writing privileges implemented my language correction :)

2024-06-21 13:01 UTC, pastk commented
> The current state of this PR is
> Android change is done
> iOS change is half done

Still there is an option to de-couple Android changes from iOS and release for one platform at least (if somebody is keen to do it).

(this PR is not in my priorities atm)

2024-06-21 14:16 UTC, kirylkaveryn commented
For some reason I cannot even checkout to the latest commit... @pastk can you please rebase the branch and I'll finish and test the ios part?

2024-06-21 15:30 UTC, biodranik commented
I can help to rebase this PR.

2026-08-22 13:47 UTC, closed without merging