[strings] Bookmark lists updates for #343
organicmaps/organicmaps pull request #1826
Opened 2022-01-10 11:35 UTC by pastk

2022-01-10 14:37 UTC, biodranik approved these changes
be = Дадаць новы спіс
be = Назва спісу закладак
be = Спісы закладак
be = Спіс

2022-01-10 22:01 UTC, biodranik requested changes

2022-01-11 09:06 UTC, pastk commented on android/res/values-ar/strings.xml
> -	<!-- Add Bookmark dialog/Bookmark list; Bookmarks dialog/Bookmark list cell. TODO: sync with [search_in_table] if all languages will be renamed consistently. -->
контекст очень разный
в одном случае список букмарков, а в другом вывод результатов списком
я бы не стал объединять, перевод вполне может разойтись в дальнейшем или для каких-то языков
например, в русском для результатов допустимо перевести "Списком"

вообще сейчас просто "list" / "список" внизу экрана не очевидно, что делает
место там есть, лучше было бы поменять потом на, например "Show results as list / Вывести результаты списком"

2022-01-11 09:06 UTC, pastk commented on android/res/values-ar/strings.xml
> +	<!-- A button used to show search results in list form -->
поправлю

2022-01-11 09:22 UTC, pastk commented on data/strings/strings.txt
> +    fi = Luettelo
Это точно лучше, чем было.
Потому что была "группа" на всех языках (или как там её перевели).
Теперь почти везде "список".

Что касается Luettelo, то согласно гугл транслейту одно из значений "list". И именно luettelo используется во всех остальных случаях для букмарков, типа create new list, please enter list name и т.д.
Т.е. для финнов всё будет очень даже consistent.

2022-01-11 09:27 UTC, biodranik commented on android/res/values-ar/strings.xml
> -	<!-- Add Bookmark dialog/Bookmark list; Bookmarks dialog/Bookmark list cell. TODO: sync with [search_in_table] if all languages will be renamed consistently. -->
Тогда надо убрать туду, но оставить два разных перевода, убрав из коммита правки других языков. И добавить больше контекста в комментарии, чтобы переводчики не запутались.

2022-01-11 09:38 UTC, pastk commented on data/strings/strings.txt
> +    fi = Luettelo
я проверил все остальные языки гугл транслейтом - везде перевод list
кроме `he = קבוצה` (группа)
но я его и не менял :) он такой и был в [list], а в [search_in_table] его вообще неи

2022-01-11 11:21 UTC, biodranik approved these changes

2022-01-11 11:21 UTC, merged