[classifier] Refactored recycling; removed boundary=4-state.
organicmaps/organicmaps pull request #1868
Opened 2022-01-16 12:50 UTC by vng

@pastk

2022-01-16 13:43 UTC, pastk commented on data/mapcss-mapping.csv
> +boundary|administrative|4|state;[boundary=administrative][admin_level=4][border_type=state];x;name;int_name;736;boundary|administrative|4
можно вкратце объяснить, что какие поля значат?
второе это явно теги ОСМ
первое это тип ОМ, но и последнее тоже, причём последнее редко когда используется
что ещё значит `x`?
name/int_name - импорт названия, если оно есть в соответствующих тегах?

2022-01-16 13:57 UTC, vng commented on data/mapcss-mapping.csv
> +boundary|administrative|4|state;[boundary=administrative][admin_level=4][border_type=state];x;name;int_name;736;boundary|administrative|4
x - значит что тип удаляем (boundary|administrative|4|state) и заменяем его на то что в конце (boundary|administrative|4) при чтении старых данных.

name, name_int матчится в стилях отрисовки *.mapcss, но тут это копипаст и смысла не имеет особо, ибо 
парсер этого файла ожидает 2, 3, 6 или 7 токенов.

2022-01-16 23:05 UTC, biodranik approved these changes

2022-01-16 23:05 UTC, biodranik commented on editor/xml_feature.cpp
> +    if (k == "amenity" && v == "recycling" && xml.HasTag("recycling_type"))
Надо глянуть тагинфо, скорее всего если тип - не центр и не контейнер, то надо матчить его как контейнер.

2022-01-16 23:05 UTC, biodranik commented on feature_list/feature_list.cpp
> +  f.ForEachType([&](uint32_t type)
&result нагляднее

2022-01-17 07:13 UTC, vng commented on data/classificator.txt
> +        organic  -
Взял топ типов из taginfo. В целом, могу "объединить" organic в green_waste. Здесь я хотел сохранить максимальную преемственность из OSM типов, чтобы в будущем завести это в редактор и удовлетворить зеленых ребят по ссылке из описания.

2022-01-17 07:14 UTC, vng commented on data/strings/types_strings.txt
> +  [type.amenity.recycling]
Не вижу проблем. Копипасты нет, по поведению recycling ведет себя как контейнер, в этом и есть задумка.

2022-01-17 07:15 UTC, vng commented on data/visibility.txt
> +        recycling  00000000000000000000  +
Это отдельный вопрос, зачем этот файл вообще. Когда-то отрефакторится, надеюсь.

2022-01-17 07:17 UTC, vng commented on editor/xml_feature.cpp
> +    if (k == "amenity" && v == "recycling" && xml.HasTag("recycling_type"))
Конечно смотрел. Для согласованности базовый тип остается, без него никак в иерархии, но в приложении он ведет себя как контейнер. А наш редактор будет создавать только полные типы или centre или container.

2022-01-17 07:21 UTC, vng commented
Еще я хочу убрать type.recycling.toxic и вернуть как в ОСМ batteries. Нет контейнеров для "ядовитых отходов". Это именно батарейки, что сейчас и берется из ОСМ. Нужны будут адекватные переводы.

2022-01-17 07:22 UTC, vng commented on data/classificator.txt
> +        organic  -
Объединить в одну категорию? Я подумал и склоняюсь что лишнее держать 2 категории по сути одного и того же ..

2022-01-17 07:23 UTC, biodranik commented on data/classificator.txt
> +        organic  -
Просто в редакторе будет путаница у обычных людей, выбирать green waste или organic. Надо спросить у osmеров.

2022-01-17 07:39 UTC, biodranik commented on data/classificator.txt
> +        organic  -
> Еще я хочу убрать type.recycling.toxic и вернуть как в ОСМ batteries. Нет контейнеров для "ядовитых отходов". Это именно батарейки, что сейчас и берется из ОСМ. Нужны будут адекватные переводы.

$ tools/unix/translate_categories.sh 'Batteries'
en:Batteries
ar:ﺕﺎﻳﺭﺎﻄﺑ
be:Батарэі
bg:Батерии
cs:Baterie
da:Batterier
de:Batterien
el:Μπαταρίες
es:Baterías
fa:ﺎﻫ ﯼﺮﺗﺎﺑ
fi:Paristot
fr:Batteries
he:תוללוס
hu:Elemek
id:Baterai
it:Batterie
ja:バッテリー
ko:배터리
nb:Batterier
nl:Batterijen
pl:Baterie
pt:Baterias
pt-BR:Baterias
ro:Baterii
ru:Батареи
sk:Batérie
sv:Batterier
sw:Betri
th:แบตเตอรี่
tr:Piller
uk:Батареї
vi:Ắc quy
zh-Hans:电池
zh-Hant:電池

2022-01-17 07:47 UTC, biodranik commented
Наверное надо сразу пройтись по всей таблице типов и вставить большинство из них, слегка отфильтровав (заматчив) дубликаты. А то получится недофича и недоредактор. Или может лучше просто в метаданные вставить эти теги? Тогда не придётся возиться с классификатором. Хотя в метаданных сразу несколько типов придётся хранить достаточно хитро.

Сейчас нам, получается, придётся различать контейнеры от перерабатывающих центров, и дальше отображать весь список подтипов, что именно там ресайклится.

Просто если мы сделаем удобно и хорошо, то те типы, которых мало, будут более активно добавляться. И можно стать "самой подробной картой ресайклинга в мире". А это тренд сейчас во многих странах.

2022-01-17 08:18 UTC, vng commented
- Сейчас это лучше вешать на типы, потому что только с ними работает поиск и редактор.
- Список в UI при добавлении отображать эквивалентно кухням теперь. И почему "придется отличать"? Тут нет проблем, все так же как и с кафе/ресторан/фастфуд сейчас ..
- Я прошелся по топ recycling типам. Посмотрю еще, объединю "однотипные" https://wiki.openstreetmap.org/wiki/Tag:amenity%3Drecycling и пушну. Пусть там останется 10, но самые самые, без заморочек.

2022-01-17 10:12 UTC, biodranik commented
```
en:Batteries
ar:ﺕﺎﻳﺭﺎﻄﺑ
be:Батарэйкі
bg:Батерии
cs:Baterie
da:Batterier
de:Batterien
el:Μπαταρίες
es:Baterías
fa:ﺎﻫ ﯼﺮﺗﺎﺑ
fi:Paristot
fr:Batteries
he:תוללוס
hu:Elemek
id:Baterai
it:Batterie
ja:バッテリー
ko:배터리
nb:Batterier
nl:Batterijen
pl:Baterie
pt:Baterias
pt-BR:Baterias
ro:Baterii
ru:Батарейки
sk:Batérie
sv:Batterier
sw:Betri
th:แบตเตอรี่
tr:Piller
uk:Батарейки
vi:Ắc quy
zh-Hans:电池
zh-Hant:電池
```

Надо в английском вписать Small Batteries, и в комменте добавить Household batteries, NOT large car accumulators

2022-01-17 11:49 UTC, pastk requested changes
как вариант я потом могу по текстовкам в отдельном pr пройтись, мне эта тема довольно близка

2022-01-17 11:49 UTC, pastk commented on data/categories.txt
> +ru:Прием банок|Утилизация банок|Переработка банок
тут путаница со стеклянными банками будет
можно "жестянки", "жестяные банки", "консервные банки"
в английский можно добавить "tin cans", "tins", "tincans"

2022-01-17 11:49 UTC, pastk commented on data/categories.txt
> +ru:Старая обувь|Сдать обувь
'+ приём обуви

2022-01-17 11:49 UTC, pastk commented on data/categories.txt
> +en:Organic Waste|Green Waste
++ food waste, garden waste

2022-01-17 11:49 UTC, pastk commented on data/categories.txt
> +en:Cartons Recycling
Carton это как правило композитная упаковка типа тетрапака, соки например в них обычно. С т.з. переработки это не картон!
Картон по-английски cardboard, он либо к бумаге, либо вообще отдельной категорией должен быть.
Устоявшегося русского термина для carton нет, зачастую их все вцелом так и называют тетрапаками, так что можно "Переработка тетрапаков", наверное.

2022-01-17 11:49 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Банки
Консервные банки
или Жестяные

2022-01-17 11:49 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Старая обувь
Мне кажется лучше без "старой".
Я не уверен, но скорее всего тут переработка будет смешана с повторным использованием, и этим тегом будут помечать контейнеры по приёму обуви и одежды в хорошем состоянии.

2022-01-17 11:49 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Картон
Тетрапаки
ну или более длинный вариант - "картонная упаковка для напитков"

2022-01-17 11:51 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Картон
или "Тетрапак и аналоги"

2022-01-17 12:17 UTC, vng commented on data/mapcss-mapping.csv
> +recycling|small_appliances;[recycling:small_appliances=yes];;name;int_name;1345;
See replaced_tags.txt. All this "appliances" goes to recycling|small_appliances type.

2022-01-17 12:17 UTC, vng commented on data/mapcss-mapping.csv
> -recycling|glass_bottles;[amenity=recycling][recycling:glass_bottles=yes];;name;int_name;1340;
Probably, now glass is merged into glass_bottles.

2022-01-18 08:31 UTC, vng commented on data/categories.txt
> +en:Cartons Recycling
Понял. cardboard мержится с paper

2022-01-18 11:21 UTC, biodranik requested changes
Предлагаю вынести из этого PR и вмержить всё, что не касается recycling:
- noexit
- borders
- форматирование и тесты

Так же выпилить коммит со сгенерированными строками.

А дальше @pastk может взять себе ветку и докинуть на неё нормальные переводы (и заодно потестить, как оно работает в UI и редакторе, если это возможно).
Мержить недоделанное не хочется.

2022-01-18 11:21 UTC, biodranik commented on data/categories.txt
> +ru:Жестяные банки|Консервные банки
Давайте сразу беларуский и украинский добавлять. Гуглтранслейтом если что, он хорошо справляется.

2022-01-18 11:21 UTC, biodranik commented on data/categories.txt
> +en:Cartons Recycling
Нельзя мержить paper и cardboard! Везде его отдельно собирают. Cardboard это упаковки от больших коробок, плотный картон, не связанный с едой. Paper это газеты, журналы, писчая бумага.

2022-01-18 11:21 UTC, biodranik commented on data/classificator.txt
> +        cartons  -
Тут s в конце?

2022-01-18 11:38 UTC, pastk commented
> Нельзя мержить paper и cardboard! Везде его отдельно собирают. Cardboard это упаковки от больших коробок, плотный картон, не связанный с едой. Paper это газеты, журналы, писчая бумага.

Тогда glass и glass bottles сразу тоже разделить заодно.

2022-01-18 12:00 UTC, biodranik commented
> > Нельзя мержить paper и cardboard! Везде его отдельно собирают. Cardboard это упаковки от больших коробок, плотный картон, не связанный с едой. Paper это газеты, журналы, писчая бумага.
> 
> Тогда glass и glass bottles сразу тоже разделить заодно.

ОСМеры пишут, что сейчас большинство glass это glass bottles. Это близко к правде, т.к. "необычное" стекло принимают обычно только в специальных местах, и очень мало где. Хороший фильтр скорее всего был бы оставить glass, если это не контейнер, и конвертнуть его в glass_bottle, если это контейнер.

Ещё важно поддерживать (хотя бы общим типом) разноцветные контейнеры для стекла. В Швейцарии они всегда отдельные, для каждого цвета свой контейнер: `recycling:glass_bottles:colour`

2022-01-18 13:13 UTC, pastk commented
Could you please fix https://github.com/organicmaps/organicmaps/issues/1839#issuecomment-1015390153 also while you are at it.
Also adding `amenity=waste transfer station` could be useful for environmental activism.
And dump stations `amenity=sanitary_dump_station` / `waterway=sanitary_dump_station` are not related to recycling, but are very important to campervan/motorhome/boat users!

2022-01-18 18:28 UTC, vng commented
Предлагаю оставить мерж glass и glass_bottles.

Судя по [этому](https://taginfo.openstreetmap.org/search?q=glass) цветов мало но есть, задаются разными способами и все равно самый частый "white;green;brown". Мы это типами красиво не поддержим, я предлагаю не заморачиваться тут. Ну и это совсем оверкилл отмечать каждый контейнер, они же стоят группами и на карте ставится одна точка для всей группы.

2022-01-19 07:17 UTC, vng commented on data/classificator.txt
> +        cartons  -
сохраняем написание как в ОСМ

2022-01-19 09:17 UTC, biodranik commented
Ок, подчисти бранч, @pastk допилит переводы.

2022-01-19 13:34 UTC, vng commented
Можно переводы и категории скинуть мне сюда файлом, я все вставлю.

2022-01-19 16:43 UTC, pastk commented
> Можно переводы и категории скинуть мне сюда файлом, я все вставлю.

Да, можно попробовать так, после того, как функциональные правки будут закончены.

Иконку у `landuse=landfill` поменяете заодно? https://github.com/organicmaps/organicmaps/issues/1839#issuecomment-1015390153

2022-01-19 16:58 UTC, vng commented
Да, и добавлю waste_transfer_station, sanitary_dump_station, mast, flagpole

2022-01-20 12:19 UTC, vng commented
PTAL

2022-01-20 13:27 UTC, pastk commented on data/styles/clear/include/Icons.mapcss
> +area|z17-[amenity=sanitary_dump_station],
Let's make it visible at lower zoom levels.
E.g. `amenity=fuel` is visible from z14 - dump stations are also used by motorists and its not a lot of them and usually they're located off dense areas like city centers so they won't clog up the map -  I suggest making it z15- at least.

2022-01-20 13:27 UTC, pastk commented on data/styles/clear/include/Icons.mapcss
> +node|z16-[man_made=flagpole],
`flagpole` is a more significant landmark compared to power towers and masts - let's make it more visible, e.g. z15- like a lighthouse

2022-01-20 13:32 UTC, pastk commented
LGTM
(please consider my minor comments)

I'll do the strings.

2022-01-20 13:53 UTC, biodranik approved these changes

2022-01-20 13:53 UTC, biodranik commented on data/categories.txt
> +ru:Сбор батареек|Утилизация батареек
Просто Батарейки будет тоже нормально, если иконка ресайклинга.

2022-01-20 13:53 UTC, biodranik commented on data/editor.config
> +      <type id="amenity-recycling-container">
Всякие новые типы не вставляем в редактор? Батарейки там например.

2022-01-20 13:53 UTC, biodranik commented on data/editor.config
> +      <type id="amenity-recycling-container">
Кстати, тут возникает необходимость в редакторе показывать иконки для добавляемых фич, такие же, как на карте. А мы вроде как пока этого не умеем. Надо будет завести issue.

2022-01-20 13:53 UTC, biodranik commented on data/strings/types_strings.txt
> +    uk = Санітарна звалища
```suggestion
    en = Holding Tank Dump Station
    be = Зліўны рэзервуар для нечыстот
    de = VE-Station
    fr = Station de vidange
    it = Camper service
    ru = Сливной резервуар для нечистот
    uk = Зливний резервуар для нечистот
```

2022-01-20 14:02 UTC, vng commented on data/editor.config
> +      <type id="amenity-recycling-container">
Не вставляются, но это все надо будет делать по аналогии (прям точь-в-точь) с cuisine.

2022-01-20 14:03 UTC, vng commented on data/categories.txt
> +ru:Сбор батареек|Утилизация батареек
Наименование "Батарейки" в types.strings
Если не против что поиск "батарейки" тоже будет вести в урну, я исправлю.

2022-01-20 14:57 UTC, vng commented
PTAL

2022-01-20 15:29 UTC, pastk approved these changes

2022-01-20 15:51 UTC, pastk commented
Please add `waterway=sanitary_dump_station` (merge into `amenity=sanitary_dump_station`).

2022-01-20 17:37 UTC, merged

2022-01-21 06:48 UTC, pastk commented
https://www.openstreetmap.org/way/884317426
Recycling centre is displayed as landuse=commercial
![Screenshot_1642747363](https://user-images.githubusercontent.com/18434508/150479649-0c93c9a2-eda6-4bd2-8ae2-e87cf3d4137a.png)

Could it be because maps need to be regenerated with new type changes?
Or type display priorities just need to be adjusted

2022-01-21 08:01 UTC, vng commented
"Could it be because maps need to be regenerated with new type changes?"
Exactly! Now you can't test this changes in full.