[strings] Improve recycling and dump stations search and translations
organicmaps/organicmaps pull request #1922
Opened 2022-01-20 22:39 UTC by pastk

Needed-for: #1868

![Screenshot_1642718025](https://user-images.githubusercontent.com/18434508/150433332-9dcc1b65-8e8d-4211-954b-f8ad4e7f6917.png)

![Screenshot_1642717985](https://user-images.githubusercontent.com/18434508/150433341-37f4c735-009c-4ddb-9666-3100715a0153.png)

2022-01-21 00:35 UTC, biodranik requested changes

2022-01-21 00:35 UTC, biodranik commented on data/categories.txt
> +ru:5Приём одежды|Старая одежда|Сдать ненужные вещи|Сдать вещи|5Сдать одежду
На слово приём выскочит несколько разных подсказок сразу.

2022-01-21 00:35 UTC, biodranik commented on data/categories.txt
> +ru:5Приём одежды|Старая одежда|Сдать ненужные вещи|Сдать вещи|5Сдать одежду
Надо протестить, как это будет выглядеть.

2022-01-21 00:35 UTC, biodranik commented on data/categories.txt
> +be:5Прыём шклотары|Прыём шкла|5Перапрацоўка шкла|5Здаць шклотару|Здаць бутэлькі|4Збор шклотары|5Шклотара|Шклабало|Шкляныя бутэлькі
Гугл врёт, правильно шклАтара. В Беларуском О всегда ударные.

2022-01-21 00:35 UTC, biodranik commented on data/categories.txt
> +be:5Прыём пластыка|5Перапрацоўка пластыка|5Здаць пластык|4Збір пластику|5Пластык
Збор

2022-01-21 00:35 UTC, biodranik commented on data/categories.txt
> +be:5Прыём металалому|5Перапрацоўка металалому|Утылізацыя металалому|5Здаць металалому|4Збор металалому|5Металалом
Здаць металалом

2022-01-21 00:35 UTC, biodranik commented on data/categories.txt
> +ru:5Приём жестяных и алюминиевых банок|5Переработка жестяных и алюминиевых банок|5Сдать жестяные и алюминиевые банки|4Сбор жестяных и алюминиевых банок|6Консервные банки|5Жестяные банки|5Алюминиевые
Что в русском будет отображаться по слову сдать? Скрин глянуть бы.

2022-01-21 00:35 UTC, biodranik commented on data/categories.txt
> +ru:4Слив нечистот для автодомов|слив туалета автодомов|нечистоты|канализация|5автодом
Не надо в первой и второй подсказке автодома. Для яхт же тоже будет находить.

2022-01-21 00:35 UTC, biodranik commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
Для яхт же тоже есть.

2022-01-21 06:50 UTC, pastk commented on data/categories.txt
> +ru:5Приём одежды|Старая одежда|Сдать ненужные вещи|Сдать вещи|5Сдать одежду
На это и был расчёт :) выше скриншоты

2022-01-21 06:52 UTC, pastk commented on data/categories.txt
> +ru:5Приём жестяных и алюминиевых банок|5Переработка жестяных и алюминиевых банок|5Сдать жестяные и алюминиевые банки|4Сбор жестяных и алюминиевых банок|6Консервные банки|5Жестяные банки|5Алюминиевые
То же, что и по "приём" или "переработка", скрины выше

2022-01-21 07:02 UTC, pastk commented on data/categories.txt
> +ru:4Слив нечистот для автодомов|слив туалета автодомов|нечистоты|канализация|5автодом
да, не подумал об этом
с другой стороны, просто "Слив нечистот" тоже непонятно, могут подумать и химию туда сливать, и сельскохозяйственные отходы
можно
в поиске можно и коротко обойтись

2022-01-21 07:05 UTC, pastk commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
а тут тогда
"Слив нечистот для автодомов/яхт"
хотя в середине континента это будет странно выглядеть
"Слив для туалетов транспортных средств"?

2022-01-21 07:26 UTC, biodranik commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
Слишком длинно наверное. Чем плох слив нечистот? Если иконка будет понятной, должно быть ок.

2022-01-21 07:28 UTC, biodranik commented on data/categories.txt
> +ru:5Приём одежды|Старая одежда|Сдать ненужные вещи|Сдать вещи|5Сдать одежду
А самих результатов поиска ниже меньше не стало? Просто если у нас есть recycling категория, большинство людей будет тыкать туда, и даже не будет знать о "приёме" и прочих ключевиках. Это отдельная UX проблема, которую надо решить: как научить людей искать.
Т.е. подсказки не должны мешать находить реальный объект, который начинается с recycling.

2022-01-21 08:11 UTC, pastk commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
У меня ассоциация, как со свалкой - такая канава или открытый отстойник с фекалиями, куда все подряд всё подряд сливают :)
Длина в данном случае в PP вряд ли помешает сильно. Эти фичи довольно изолированные обычно, разве что внутри кемпа будет показываться не основной, но внутри кемпа у нас вряд ли ещё много каких-то субтипов будет..

2022-01-21 08:16 UTC, pastk commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
в идеале бы спросить в каком-нибудь русскоязычном автодомном коммьюнити...

2022-01-23 09:49 UTC, pastk commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
"Станция слива нечистот"?

2022-01-23 09:53 UTC, pastk commented on data/categories.txt
> +ru:5Приём одежды|Старая одежда|Сдать ненужные вещи|Сдать вещи|5Сдать одежду
Если назвать категорию в UI "Переработка", то поиск будет работать как надо с подсказками про стекло, батарейки и т.д. При этом вкупе с иконкой будет понятно, что это.

По-нормальному в перспективе можно было бы решить, если сделать related search suggestions.

2022-01-23 11:03 UTC, pastk commented on data/categories.txt
> +ru:5Приём одежды|Старая одежда|Сдать ненужные вещи|Сдать вещи|5Сдать одежду
Чтобы также работало с английским надо переназвать специфичные категории из "recycle batteries" в "recycling of batteries". Тогда при выборе категории "Recycling" будет и общая срабатывать и специфичные будут подсказываться.

2022-01-23 11:03 UTC, biodranik commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
Это чаще всего дырка в земле (США). Какая же это станция? )

2022-01-23 11:04 UTC, biodranik commented on data/categories.txt
> +ru:5Приём одежды|Старая одежда|Сдать ненужные вещи|Сдать вещи|5Сдать одежду
categories.txt как раз и создавался под такой тюнинг

2022-01-23 11:09 UTC, pastk commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
Да, но это пока лучший синоним, который мне пришёл в голову, чтобы показать, что это оборудованное место, а не стихийное.

2022-01-23 11:29 UTC, biodranik commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
На карту не добавляются стихийные места обычно. Ну и иконка должна быть "говорящей".

2022-01-23 11:29 UTC, biodranik commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
Предлагаю оставить как есть, и потом исправить после обратной связи от пользователей.

2022-01-23 16:26 UTC, pastk commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
мне кажется лучшим вариантом было бы выделить waterway-based в отдельный тип - тогда и иконки можно будет сделать более стандартные и всеми узнаваемые;
к тому же в поиск RV facilities нелогично включать дампы, которые недоступны с земли

2022-01-23 16:29 UTC, pastk commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
из 579 `waterway=sanitary_dump_station` 384 также содержат `amenity=sanitary_dump_station`
т.е. всего 195 чисто водных
может тогда вообще их не включать пока?

2022-01-23 21:20 UTC, biodranik approved these changes

2022-01-23 21:21 UTC, biodranik commented on data/strings/types_strings.txt
> +    ru = Слив для туалетов транспортных средств
А из биотуалетов грузовики могут вывозить сюда отходы?

2022-01-23 22:25 UTC, biodranik commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
Проще замапить на отдельный тип наверное. @vng ?

2022-01-24 08:42 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Слив для туалетов транспортных средств
вообще для этого дамп стейшены не предназначены по идее
"оптом" должно в другие места идти

2022-01-24 08:43 UTC, pastk commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
я могу переделать

2022-01-24 09:49 UTC, pastk commented on data/strings/types_strings.txt
> +    be = Зліў нечыстотаў для аўтадамоў
в #1921 займусь

2022-01-24 09:56 UTC, pastk commented
Поправил поиск по "recycling", перегенерировал строки.
Предлагаю замёржить, категорию поиска и разделение дамп стейшнов сделать в #1921.

![Screenshot_1643017924](https://user-images.githubusercontent.com/18434508/150760979-424ddc15-fd6a-4365-ab9d-8e0befef6d85.png)

2022-01-24 10:51 UTC, biodranik approved these changes

2022-01-24 10:51 UTC, merged