[android] Update to Gradle 7.0.0 alpha
organicmaps/organicmaps pull request #198
Opened 2021-02-28 06:58 UTC by rtsisyk

Fixes compilation on Apple Silicon.

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2021-02-28 12:00 UTC, vng requested changes
Doesn't work with current stable Android Studio. Do not merge ..

2021-02-28 13:01 UTC, biodranik approved these changes
LGTM с комментариями

2021-02-28 13:01 UTC, biodranik commented on android/gradle.properties
> -android.enableR8=false
Почему было выключено? В истории коммитов что написано?

2021-02-28 13:03 UTC, biodranik commented
С таким подходом удобнее накидывать коммиты сверху, а потом их сквошнуть в 1 при мерже

2021-03-03 08:36 UTC, rtsisyk commented on android/build.gradle
> +    classpath 'com.google.gms:google-services:4.3.5'
Пока нет. Давайте отдельно это упражнение проведем.

2021-03-03 08:37 UTC, rtsisyk commented on android/flavors/debug/AndroidManifest.xml
> -    tools:remove="sharedUserId, sharedUserLabel">
Проблема в следующем. Мы используем разные сертификаты для подписи дебага, беты и релиза в сторе. С разными сертификатами эта фича толком не работает.

2021-03-03 08:39 UTC, rtsisyk commented on android/gradle.properties
> -android.enableR8=false
Смотри 2c6fb9a1853726ccc2d7a81e4aacf49d8b3961dc
Поразбираюсь что это такое.

2021-03-03 09:08 UTC, biodranik commented
Надо разобраться и вернуть. 
Это нормально, что сертификаты разные для разных версий. Но шаред надо оставить. Какие именно у тебя ошибки?

> On 3 Mar 2021, at 09:37, Roman Tsisyk <notifications@github.com> wrote:
> 
> ﻿
> @rtsisyk commented on this pull request.
> 
> In android/flavors/debug/AndroidManifest.xml:
> 
> > @@ -1,7 +1,5 @@
>  <?xml version="1.0" encoding="utf-8"?>
>  <manifest xmlns:android="http://schemas.android.com/apk/res/android"
> -    xmlns:tools="http://schemas.android.com/tools"
> -    tools:remove="sharedUserId, sharedUserLabel">
> Проблема в следующем. Мы используем разные сертификаты для подписи дебага, беты и релиза в сторе. С разными сертификатами эта фича толком не работает.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-03 09:10 UTC, biodranik commented
Видимо не могли декодить обфусцированные креши.

> On 3 Mar 2021, at 09:39, Roman Tsisyk <notifications@github.com> wrote:
> 
> ﻿
> @rtsisyk commented on this pull request.
> 
> In android/gradle.properties:
> 
> > @@ -26,4 +26,3 @@ org.gradle.caching=true
>  org.gradle.jvmargs=-Xmx8g
>  android.useAndroidX=true
>  android.enableJetifier=true
> -android.enableR8=false
> Смотри 2c6fb9a
> Поразбираюсь что это такое.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-03-06 08:25 UTC, rtsisyk commented on android/gradle.properties
> -android.enableR8=false
```
A problem occurred evaluating root project 'android'.
> Failed to apply plugin 'com.android.internal.application'.
   > The option 'android.enableR8' is deprecated.
     It was removed in version 7.0 of the Android Gradle plugin.
     Please remove it from `gradle.properties`.
```

https://imstudio.medium.com/android-journey-proguard-d8-r8-what-are-they-e8f2bfe079a7

Ну, видимо, не отключить этот R8 уже теперь никак. Гугл один хрен рано или поздно релизнет новую Android студию с Gradle 7.0.0 и всеми теми версиями, что я тут проталкиваю в альфе....

2021-03-06 08:30 UTC, rtsisyk commented on android/flavors/debug/AndroidManifest.xml
> -    tools:remove="sharedUserId, sharedUserLabel">
Конкретно в этом манифесте как раз наоборот для дебаг версии шаринг отключался. По сути шаринг был только между бетой (собиратся на ci и выкладывается в Firebase AppDistribution) и релизом (AppStore). 
Я открыл тикет, что мы хотим это почнить. Скорее всего, надо тогда одинаковые ключи использовать.
https://github.com/omapsapp/omapsapp/issues/201

2021-03-08 22:27 UTC, biodranik reviewed
Какая польза от перехода на альфу? Не наловим ли багов?

2021-03-08 22:27 UTC, biodranik commented on android/build.gradle
> -  ndkVersion = "21.4.7075529"
А почем убрал?

2021-03-14 20:30 UTC, rtsisyk commented
Suddenly 6.8.3 has started to work on Mac. I keep this PR open until new Android Studio is released.

2021-04-10 14:50 UTC, rtsisyk commented
This PR is not actual anymore. We merged almost all changes except the gradle version itself.

2021-04-10 14:50 UTC, closed without merging