strings: add separate text for bridges and tonnels
organicmaps/organicmaps pull request #2077
Opened 2022-02-10 22:42 UTC by alatarum

Show Bridge and Tonnel labels for this kind of objects.

Signed-off-by: Andrei Kartashev <a.s.kartashev@gmail.com>

2022-02-11 10:03 UTC, pastk commented
Thanks a lot for the PR!!!

Some translations look too long e.g. `en = Bridge with Cycle Path`/`ru = Мост с велодорожкой` compare to the `Pedestrian Bridge` / `Пешеходный мост` which is nice.

Overall I lean towards naming all the bridges just `Bridge` and similar for tunnels. The type of the bridge (bridleway, motorway, etc.) is available from the map context.
(except maybe `Pedestrian Bridge` / `Пешеходный мост` which is a very nice and natural translation)

If we agree on this then we can avoid duplicating same `Bridge`/`Мост` translation for all types - just change the refs to point to one bridge/tunnel type e.g. `[type.highway.path.bridge]`.

2022-02-11 11:00 UTC, alatarum commented
I thought about this but failed to decide which of them should be reference one: type.highway.path.bridge, type.highway.primary.bridge, type.highway.road.bridge, etc - they all looks to be the same level ). But yes, we can take path as main one.

Other thing is should I change "living_street" and "xxx_link"? I decide to keep the translation as is for this elements, but probably they also should be changed to "Bridge".

2022-02-11 12:26 UTC, pastk commented
Yeap highway link bridges/tunnels should be changed as well, and living_street too.

Re using references I have one doubt actually.
We usually use them to point to the parent type in cases where children types don't need specific translations or translations are not done yet.
But this case is different - we want to avoid duplication, which is good, but pointing e.g. primary_road bridge to the path bridge could have unwanted side effects. E.g. in case someone changes translation for the path bridge it will also change for the primary road bridge which is not what we might want...

2022-02-11 15:29 UTC, pastk commented
> Yep, that is why I asked you about if we can add something like "type.default.bridge" in tg. Would be nice to have such fallback.

The biggest downside of this approach is that it won't be possible to "unref" the file easily (e.g. if we migrate to weblate) as the "type.default.bridge" would remain there as unused definition. Overall it seems to adds extra complexity for a quite small change in strings we want to do.

My suggestion is to:
1. add Bridge and Tunnel translations for all languages to existing `[type.highway.road.bridge/tunnel]`
2. add there a comment like "These translations are used for all type.highway.* bridges"
(to make translators aware of it being referenced)
3. add refs from all other highway bridges/tunnels

@biodranik  what do you think?

2022-02-11 18:11 UTC, biodranik commented
> @biodranik what do you think?

ok

2022-02-12 09:11 UTC, pastk requested changes

2022-02-12 09:11 UTC, pastk commented on data/strings/types_strings.txt
> +    en = Bridge
Please add also
be,bg,es-MX,he,sw

2022-02-12 09:11 UTC, pastk commented on data/strings/types_strings.txt
>      ref = type.highway.road
please remove too

2022-02-12 09:23 UTC, alatarum commented on data/strings/types_strings.txt
>      ref = type.highway.road
ooups

2022-02-12 10:05 UTC, pastk approved these changes

2022-02-12 10:05 UTC, pastk commented
Looks great!

2022-02-12 17:40 UTC, biodranik approved these changes

2022-02-18 21:38 UTC, pastk commented
Ready to merge

2022-02-19 06:28 UTC, biodranik approved these changes

2022-02-19 06:28 UTC, merged