Fixed writable/resource dir candidates for desktop.
organicmaps/organicmaps pull request #2179
Opened 2022-02-22 21:18 UTC by vng

Do not set default writable/resource path as root "/" for Linux. If any test or toolchain doesn't set it properly, then strange things may happen in root "/".

If platform can't find any valid path now, make it equal with unique string like "OM_Unexisting_ResourceDir_path". It helps better grep logs and find bugs.

2022-02-22 21:46 UTC, biodranik requested changes
Это очень стрёмные изменения, которые могут сломать всё.

1. Зачем удалён privatePath?
2. В чём на самом деле корень проблемы с тестами, которые не инициализируют пути? Предлагаю сделать такой фикс, чтобы тесты всегда корректно инициализировали пути, не затрагивая имеющиеся продакшн/девелопмент кейзы.

2022-02-22 21:46 UTC, biodranik commented on platform/platform_mac.mm
> +    // check symlink in the current folder
```suggestion
    // Сheck symlink in the current folder.
```

2022-02-22 21:46 UTC, biodranik commented on platform/platform_mac.mm
> +    // check if we are in the 'build' folder inside repo
```suggestion
    // Сheck if we are in the 'build' folder inside repo.
```

2022-02-22 21:46 UTC, biodranik commented on platform/platform_mac.mm
> +    // check development environment without a git repo
```suggestion
    // Сheck development environment without a git repo.
```

2022-02-22 21:46 UTC, biodranik commented on platform/platform_mac.mm
> -    m_resourcesDir = resourcesPath + "/";
Нет, нельзя удалять старую логику. Это работало раньше для отдельно собранных и распространяемых в dmg приложений. Сейчас не будет работать.

2022-02-22 21:46 UTC, biodranik commented on track_analyzing/track_analyzer/cmd_unmatched_tracks.cpp
> -  storage.RegisterAllLocalMaps(false /* enableDiffs */);
Эти вызовы на самом деле не нужны? Зачем их тогда вставляли?

2022-02-22 21:58 UTC, vng commented on platform/platform_mac.mm
> -    m_resourcesDir = resourcesPath + "/";
Хм, у нас и опции такой нет. Или она устанавливалась при сборке? Может тогда ее стоит добавить в cmake?

2022-02-22 21:58 UTC, vng commented on track_analyzing/track_analyzer/cmd_unmatched_tracks.cpp
> -  storage.RegisterAllLocalMaps(false /* enableDiffs */);
хз

2022-02-22 22:03 UTC, vng commented
1. private path нигде не используется
2. именно это изменение помогло быстро найти проблему, когда я в логе просто видел "Can't remove indexes directory: /libx32 Access failed".
А после, сразу видно ошибку кто-где-что пытался не то прочитать. Потому и удалил ненужные RegisterAllLocalMaps.
3. По сути тут удаляется старое omim и устанавливается дефолтный путь на невалидную строку, а не в корень

Если STANDALONE_APP - это рабочая логика (как это проверить?), могу вернуть

2022-02-22 22:24 UTC, biodranik commented
Вопрос, почему не произошло дефолтной, правильной инициализации в каких-то случаях? Хотелось бы разобраться и починить этот кейз, вместо невалидных затычек-папок, которые к тому же могут каким-то кодом и создаться, особенно если будут права на запись.

2022-02-22 22:30 UTC, vng commented
У нас так построен тулчейн, что не всегда выполняется инициализация на запуске (в конструкторе), а _когда-то_ потом вызывается SetResourceDir, SetWritableDir в зависимости от входных параметров.

PR определенно делает лучше и уже нашел одну ошибку. Лучше невалидная затычка, чем "/".

Предложи свой вариант.

2022-02-22 22:34 UTC, biodranik commented
1. Всегда валидно инициализировать пути.
2. Позволять потом их менять, если нужно. Этот кейз, к слову, нужен был только для хитрого ведра, где инициализация проводилась из Java и не могла быть сделана в конструкторе с текущей архитектурой.

2022-02-23 05:59 UTC, vng commented
1. "Всегда валидно инициализировать" зависит не от кода, а от того как юзер настроил окружение. Мы не можем физически предусмотреть все многообразие того, как будет лежать генератор и data/writable. До изменений код вел себя плохо если оно не настроено. С изменениями будет вести себя безопасно.
2. Этот кейз, к слову, использовался всегда в генераторе, где пути передавались через командную строку. А также в некоторых тестах.

Еще рах повторю, что это затрагивает только linux/mac пути.

2022-03-21 08:03 UTC, closed without merging