Sync steps visibility with footways
organicmaps/organicmaps pull request #2207
Opened 2022-03-02 13:27 UTC by pastk

by promoting steps from z16- to z14-.

Stairs are basically footways on a slope, so there is no sense to display one and don't display the other.
It creates confusing gaps in the middle of footways and gives wrong picture of pedestrian network (especially with longer stairs which are common in hilly cities).

around https://www.openstreetmap.org/way/219812664
![steps2](https://user-images.githubusercontent.com/18434508/156369821-25b83e72-4c85-4547-9b30-9c9700a12964.png)

around https://www.openstreetmap.org/way/546439211
![steps3](https://user-images.githubusercontent.com/18434508/156369797-69fe40e8-3aa7-42c1-b5f5-16468c77fd6d.png)

More samples of long stairs:
https://www.openstreetmap.org/way/454828316
https://www.openstreetmap.org/way/377222081

Originally proposed and discussed in https://github.com/organicmaps/organicmaps/pull/2134

2022-03-02 18:11 UTC, biodranik commented
It doesn't look good on 14 zoom.

2022-03-03 06:35 UTC, vng requested changes
Interferes with https://github.com/organicmaps/organicmaps/pull/2209
Here promoting to z14, reducing to z15 there.

Should we unite this PRs into one?

2022-03-03 08:21 UTC, pastk commented
> Interferes with #2209 Here promoting to z14, reducing to z15 there.
> 
> Should we unite this PRs into one?

Updated PR to promote steps to z15 so its in sync with footways.

2022-03-03 09:20 UTC, biodranik approved these changes

2022-03-03 09:20 UTC, merged