[android] Fixed RTL zoom buttons covered by Search and Bookmarks in Routing mode
organicmaps/organicmaps pull request #2307
Opened 2022-03-28 19:28 UTC by biodranik

Надо протестить, фиксил без теста.

2022-03-29 11:51 UTC, pastk requested changes
Хм, ты пофиксил в ландшафтной компоновке по ошибке?

Там получается так:
![rtl-land1](https://user-images.githubusercontent.com/18434508/160604460-87f6d225-43a2-41f9-90ff-96765cf10018.png)

Если фикс убрать, то так (компас и кнопка слоёв накладываются):
![rtl-land2](https://user-images.githubusercontent.com/18434508/160604542-cb9881fb-67c8-492b-a5d2-54adecd9173f.png)
Твой предыдущий фикс для компаса был только для портретки, может?

Если добавить фикс (`layoutDirection="ltr"`) в портретку, то в ней всё хорошо выглядит:
![rtl-port](https://user-images.githubusercontent.com/18434508/160604892-28115e43-7e15-4f9d-95ea-98700f1adcae.png)

Тестил только на эмуле 5.0 пока.

2022-03-29 12:27 UTC, biodranik commented
Спасибо! Пофиксил. Надо будет вообще эти плавающие кнопки переделать по-другому.

2022-03-29 17:37 UTC, pastk approved these changes
Now portrait mode is fixed.

And the landscape mode looks good too except that in nav mode the next turn sign covers zoom buttons partly - dependent on screen size / resolution.
However if it was in left upper corner (as it is LTR layouts) then it would cover the layers button.

![rtl-land3](https://user-images.githubusercontent.com/18434508/160671826-84a30048-4e45-4404-8b2a-f13d26fdc714.png)

2022-03-29 22:17 UTC, biodranik commented
All these cases obviously need UI redesign. Let's create an issue for that.

2022-03-29 22:18 UTC, merged

2022-03-30 11:14 UTC, pastk commented
In the meantime maybe the next turn sign should be moved to the left as well?

2022-03-30 13:20 UTC, biodranik commented
You can try it.