Fixed internet_access.
organicmaps/organicmaps pull request #2316
Opened 2022-03-29 13:45 UTC by vng

@biodranik Added classifier tests, but the main reason was in meta. There is no need to store separate internet_access=no IMHO, WDYT?

https://github.com/organicmaps/organicmaps/issues/2314
https://github.com/organicmaps/organicmaps/issues/1726

2022-03-29 22:03 UTC, biodranik commented
У большинства фич доступ в инет неизвестен. No и Yes важные сигналы, которые точно нужны, они отличаются от "неизвестно". Я когда-то был в швейцарском отеле без интернета. Ещё важный для здоровья тег — только кабельный интернет, хорошо бы его тоже поддержать.

2022-03-29 22:07 UTC, biodranik commented on generator/osm2meta.cpp
> -  if (v == "wlan" || v == "wired" || v == "yes" || v == "no")
Получается no будет то же самое, что и "неизвестно". Это не очень хорошо.

2022-03-30 13:29 UTC, biodranik commented
И сразу же добавить эти строчки и варианты в редактор, а то мы про него постоянно забываем.

2022-03-30 16:34 UTC, biodranik approved these changes
Хотя бы сделай Good first issue и опиши подробно, что там надо сделать.

2022-03-30 17:39 UTC, vng commented
Давайте так: у гас уже есть строки:
- redirect_route_yes (которое по сути просто Yes)
- redirect_route_no (которое по сути просто No)
- WiFi_available (которое по сути просто Yes)

Я заиспользую строки redirect_route_yes и redirect_route_no для WiFi. Ok? Можно их просто переименовать в Yes, No.

Так же там надо будет вставить аля TextView, я попробую повоевать.

2022-03-31 06:33 UTC, biodranik approved these changes

2022-03-31 09:33 UTC, pastk requested changes

2022-03-31 09:33 UTC, pastk commented on generator/generator_tests/osm_type_test.cpp
> +    };
maybe add a test for 
```
{"wifi", "free"},
{"internet_access", "yes"}
```
will it lead to types duplication?

and
```
{"wifi", "free"},
{"internet_access", "terminal"}
```
should lead to wlan type present

2022-03-31 09:33 UTC, pastk commented on generator/osm2meta.cpp
>    if (v == "wlan" || v == "wired" || v == "yes" || v == "no")
terminal?

2022-03-31 09:42 UTC, vng commented on data/strings/strings.txt
> +  [no_available]
comment добавлю
no_available сделал нарочно, тут не про грамматику, а уточнить какое no ..

2022-03-31 10:14 UTC, pastk commented on data/strings/strings.txt
> +    tr = Var
fa = بلی
he = כן
ещё верни/добавь, пожалуйста

2022-03-31 10:38 UTC, pastk approved these changes

2022-03-31 11:16 UTC, merged