[styles] Add area style for amenity=school
organicmaps/organicmaps pull request #2341
Opened 2022-04-03 18:46 UTC by dvdmrtnz

I added an area rendering for `amenity=school`. This will fix https://github.com/organicmaps/organicmaps/issues/1221. I used the style from `amenity=university`. This is how it will look like:

![](https://user-images.githubusercontent.com/47610359/161443260-1a5c5332-c0eb-44fc-bbd8-0fb218878ed9.jpg)

2022-04-03 22:07 UTC, biodranik commented
Isn't it also needed for a kindergarten?

2022-04-04 16:38 UTC, pastk commented on data/styles/clear/include/Basemap.mapcss
> +area|z14-[amenity=school],
School grounds are usually much smaller compared to universities, so makes sense to render them at higher zoom levels.
E.g. in Icons.mapcss schools icons are rendered starting from z17-. I'd keep the area fill and icons either in sync or add the fill one zoom level earlier maybe.

2022-04-04 19:24 UTC, dvdmrtnz commented
Thanks for your feedback! I will add `amenity=kindergarten`, `amenity=college` and `landuse=education` and will set the zoom levels to be the same as the icons.

2022-04-04 20:08 UTC, dvdmrtnz commented
There is a problem with these changes. Adding an area rendering for `amenity=school` is hiding the area rendering for `leisure=pitch`. 

I checked `Basemap.mapcss` and the z-index of `leisure=pitch` is 5 while the z-index of `amenity=school` is 1, so the pitch should be rendering on top of the school area, right? There must be something that I am missing. 

How can I make the pitch render on top of the school area?

See example (https://www.openstreetmap.org/way/32672009)

Before:

![Screenshot_20220404-215255](https://user-images.githubusercontent.com/47610359/161622142-4b07a144-d5d3-4ab5-bc38-2d8b33da2141.jpg)

After:

![Screenshot_20220404-210749](https://user-images.githubusercontent.com/47610359/161622163-de0027e2-f944-4341-874d-d4b8ef202b35.jpg)

2022-04-04 20:27 UTC, pastk commented
This is because school's z-index is overriden in Icons.mapcss to 2500..
We had the same issue with hospital grounds, there the solution was to remove z-index from Icons, see https://github.com/organicmaps/organicmaps/pull/2166/files#diff-1f979d5595296f97800fd57537b1becb9d74af23f71f5aa3cc5e3c2989fc0ba7

(However now I'm not 100% sure using `-x-me-text-priority:` hack makes sense there, as it looks like captions are using parent icon's priority anyway (in runtime displacement code at least), but should be OK to go this way for now).

2022-04-06 22:46 UTC, dvdmrtnz commented
I think it should be good now. This is how it will look:

![](https://user-images.githubusercontent.com/47610359/162084765-1b8ce10a-bb0d-4890-a3c5-492da3ae6210.jpg)

I also added `landuse=education` with same style.

2022-04-07 11:35 UTC, pastk requested changes
A little more changes, please!

2022-04-07 11:35 UTC, pastk commented on data/styles/clear/include/Basemap.mapcss
> +area[landuse=education],
More specific area like school, university, should have a priority over more generic "education".
I suggest let's move education to z-index:1 and move university, college, etc. to 2.

2022-04-07 11:35 UTC, pastk commented on data/strings/types_strings.txt
> +    fr = Zone éducative
en = Educational Facilities
be = Адукацыйныя ўстановы
? es = Instalaciones educacionales
ru = Образовательные учреждения
uk = Освітній заклади

2022-04-09 10:22 UTC, pastk commented on data/styles/clear/include/Basemap.mapcss
> +area|z17-[amenity=college],
college is z16- now

2022-04-09 14:37 UTC, vng commented
Merge conflict. Please, rebase and make 2 commits: first with style changes, second - regenerated styles.

2022-04-09 23:28 UTC, dvdmrtnz commented
Should be good now

2022-04-10 07:29 UTC, vng approved these changes

2022-04-10 08:52 UTC, pastk approved these changes
LGTM. Thanks a lot!!

2022-04-10 09:39 UTC, merged