Tune amenity=townhall and sightseeings searches
organicmaps/organicmaps pull request #2416
Opened 2022-04-17 19:36 UTC by pastk

2022-04-18 06:11 UTC, vng approved these changes

2022-04-18 14:53 UTC, biodranik requested changes

2022-04-18 14:53 UTC, biodranik commented on data/strings/types_strings.txt
> +    ru = Администрация
Нет, это НЕ администрация. Корректно переводить именно как Ратуша, и брать все переводы с Википедии.

2022-04-18 17:26 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Администрация
Ратуша это функционально городская администрация и есть. 
Но сейчас "ратуша" в русском языке практически не используется, только в историческом контексте.
http://gramota.ru/slovari/dic/?word=%D1%80%D0%B0%D1%82%D1%83%D1%88%D0%B0&all=x

И де факто `amenity=townhall` используется по всему миру для обозначения администраций населённых пунктов разного уровня, сёл, городов, райнов... Иногда шире как community centre.
https://taginfo.openstreetmap.org/tags/amenity=townhall#map

Небольшую выборку этих пои (в европейском, историческом и туристическом контексте в основном) было бы и правда хорошо именовать ратушами.
Но использовать специфический термин для распространённого ПОИ совсем некорректно. Люди будут удивляться, увидев "ратуши" на месте всяческих сельсоветов, городских администраций, управлений муниципальных образований и т.п. где-нибудь в азии, населённых пунктах экс-СССР и т.п. А многие даже толком значение этого слова определить не смогут.

"Администрация" - это наиболее подходящий нейтральный и понятный термин, который для подавляющего большинства кейзов подходит.

2022-04-18 17:36 UTC, biodranik commented on data/strings/types_strings.txt
> +    ru = Администрация
A townhall is not necessarily used (or having ever been used) for administrative function. [link](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dtownhall)

Никто из десятков миллионов пользователей мапсми и из наших пользоваетелй не жаловался, что мы используем неправильный перевод для термина. Предлагаю оставить как есть, рассмотреть возможность нормализации перевода для некоторых языков типа en-US, en-UK и т.п.

2022-04-18 18:58 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Администрация
> A townhall is not necessarily used (or having ever been used) for administrative function.

Основная функция именно административная
"In local government, a city hall, town hall, [...], is the chief administrative building of a city, town, or other municipality. It usually houses the city or town council, its associated departments, and their employees. It also usually functions as the base of the mayor of a city, town, borough, county or shire, and of the executive arm of the municipality." [wiki](https://en.wikipedia.org/wiki/Town_hall)

Остальное опционально (в 3м абзаце только) и преимущественно на западе. Но у нас же карты всего мира.

Вот кому из русскоговорящих придёт в голову это ратушами называть?
https://www.openstreetmap.org/node/8156800729
https://www.openstreetmap.org/way/231743574
https://www.openstreetmap.org/node/1007095933
https://www.openstreetmap.org/node/4092055005
https://www.openstreetmap.org/way/964463597
Посмотри сам примеры на оверпассе.

Что касается пользователей, то вот как раз намедни и жаловались. https://t.me/OrganicMapsRu/16878 и далее комменты.
После чего я собственно и решил проверить вопрос.

"Ратуша" не подходит, это устаревший и специфический термин, не отражающий фактического использования тега.

2022-04-18 19:26 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Администрация
кстати, в веб-редакторе OSM тоже переведено как "Администрация"

2022-04-18 19:49 UTC, biodranik commented on data/categories.txt
> +be:4Адміністрацыя|4ратуша
Ну много же объектов, которые не имеют отношения к администрации. Ратуша нормально. Можно синонимы оставить в принципе, поменяв местами.

2022-04-18 20:05 UTC, pastk commented on data/categories.txt
> +be:4Адміністрацыя|4ратуша
Какие есть примеры `amenity=townhall` без административной функции? Тем более, чтобы много.

Не нравится "Администрация" - предложи какой-нибудь широкий актуальный термин, который лучше будет включать второстепенную коммьюнити функцию, но и чтобы и сельсовет, и акимат, и мэрию им тоже можно было обозначить. Мне в голову не пришло пока.

2022-04-18 20:11 UTC, pastk commented on data/categories.txt
> +be:4Адміністрацыя|4ратуша
"Административно-общественное учреждение" очень длинно и канцелярно

2022-04-18 21:07 UTC, biodranik commented on data/strings/types_strings.txt
> +    ru = Администрация
Русскоговорящий турист офигеет в Европе от зданий "Администрации".

Этот перевод гораздо хуже, чем Ратуша.

Пока мы не умеем динамически использовать разные переводы в зависимости от карты, лучше не ломать экспириенс.

По ссылке из телеги основная проблема в том, что ратуша попала в достопримечательности. Без этого никто бы и не жаловался.

2022-04-18 21:18 UTC, biodranik commented on data/categories.txt
> +be:4Адміністрацыя|4ратуша
Поэтому Ратуша гораздо лучше. Это и администрация, и не только.

Уже понятно, что идеальное решение будет только для России переводить эти здания как "администрация", для UK как "Town Hall" или "City Hall" в зависимости от размера города. И т.д. 
Можно начать думать о таком механизме для подобных случаев. С ним пересекается и различная интерпретация уровней административных границ в разных странах (и их названия соответственно).

2022-04-19 08:30 UTC, pastk commented on data/categories.txt
> +be:4Адміністрацыя|4ратуша
В том то и дело, что "ратуша" в русском языке не может быть без административной функции.
"Дом культуры" нельзя назвать "ратушей". В русском у "ратуши" очень узкое значение и оно неразрывно связано с правлением, я уже приводил ссылку на толковый словарь, вот ещё из [словаря Ожегова](https://onlinedic.net/ozhegov/page/word29794.php):

> РАТУША, р’атуша, -и, ж. В средневековой Европе и в России 18 нач. 19 в., в нек-рых странах Западной Европы: орган городского самоуправления, а также здание такого самоуправления.

И там по ссылке ещё 3 словаря с аналогичным определением. Или вот [вики](https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D1%82%D1%83%D1%88%D0%B0).

У англоязычного "town hall" определение гораздо шире (хотя, как ты верно заметил, даже оно на все кейсы использования `amenity=townhall` натягивается не очень). Поэтому перевод "ратуша" подходит только для небольшого подмножества использований `amenity=townhall`.

"Администрация", как и "ратуша", тоже не подходит для "дома культуры", но закрывает неизмеримо больше других кейсов, вбирает в себя кучу вариантов названий органов местного самоуправления разных уровней и в разных странах, где "ратуша" вообще не в тему.

Условно, "ратуша" закрывает 20% кейсов, а "администрация" 80%.

2022-04-19 17:36 UTC, biodranik commented on data/categories.txt
> +be:4Адміністрацыя|4ратуша
Дом культуры в ОСМе мапится как amenity=community_centre

Устал спорить. Будет удобно россиянам в России, но неудобно Россиянам в Европе. Ну ок.

2022-04-21 21:22 UTC, biodranik approved these changes

2022-04-21 21:22 UTC, merged