[android] Ignore possible false-positive location availability.
organicmaps/organicmaps pull request #2447
Opened 2022-04-23 09:43 UTC by vng

2022-04-24 12:39 UTC, biodranik commented on android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
> +      if (!availability.isLocationAvailable()) {
Нужно здесь фильтровать false-positives:

```
fun isLocationEnabled(): Boolean {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            val lm = context.getSystemService(Context.LOCATION_SERVICE) as LocationManager
            lm.isLocationEnabled
        } else {
            val mode = Settings.Secure.getInt(
                context.contentResolver, Settings.Secure.LOCATION_MODE,
                Settings.Secure.LOCATION_MODE_OFF
            )
            mode != Settings.Secure.LOCATION_MODE_OFF
        }
```

2022-04-24 12:39 UTC, biodranik commented on drape/overlay_tree.cpp
> +  /// @todo Fires when updating country (delete-add) ?!
Только на десктопе? Или на других платформах тоже?

2022-04-24 13:05 UTC, vng commented on android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
> +  private final static String TAG = "GoogleFusedLocationProvider";
Тут психанул, можно вернуть. Я видел в логе странные строки и решил что отсюда.

2022-04-24 13:07 UTC, vng commented on android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
> +      if (!availability.isLocationAvailable()) {
Я видел это в SoF но тогда надо прокидывать контекст (я даже не верен что он permanent) и решил забить ибо оно тут не решает абсолютно.

2022-04-24 13:08 UTC, vng commented on drape/overlay_tree.cpp
> +  /// @todo Fires when updating country (delete-add) ?!
Будет везде, этот assert я когда-то экспериментально добавлял, теперь вижу что надо дорабатывать.

2022-04-25 05:42 UTC, biodranik commented on android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
> +      if (!availability.isLocationAvailable()) {
В конструкторе сохрани или LM service или ContentResolver, и не нужен тебе будет context постоянно.

2022-04-25 21:55 UTC, biodranik commented
```
/home/runner/work/organicmaps/organicmaps/base/base_tests/small_set_test.cpp:268:54: error: macro "TEST_LESS" requires 3 arguments, but only 2 given
  268 |   TEST_LESS(BenchmarkTimeLessOrNear(t3, t2, 0.05), ());
      |                                                      ^
```

2022-04-25 21:56 UTC, biodranik commented on android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
> +      if (!availability.isLocationAvailable()) {
Так а тут чего не пофиксил?

2022-04-26 04:41 UTC, vng commented on android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
> +      if (!availability.isLocationAvailable()) {
Я внутренне против этих бубнов, потому что мы это даже не протестим у нас (за месяцы даже не воспроизвели). А хотим покрыть какой-то странный кейз (пользователь зашел и пользует карты, потом явно пошел выключил позицию, потом вернулся в карты и все забыл что выключил).

2022-04-26 04:43 UTC, vng commented on android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
> +      if (!availability.isLocationAvailable()) {
Мы предупреждаем пользователя при нажатии на позицию, этого более чем достаточно.

2022-04-26 04:47 UTC, vng commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    if (LocationState.nativeGetMode() != LocationState.NOT_FOLLOW_NO_POSITION)
Там уже сыпется подробный лог:
mLogger.d(TAG, "onMyPositionModeChanged mode = " + LocationState.nameOf(newMode));
т.е. текущий режим виден всегда

2022-04-26 06:16 UTC, rtsisyk requested changes
Можно и нужно заливать удаление `onLocationError(ERROR_GPS_OFF)` в `if (!availability.isLocationAvailable())`. Остальные части патча требуют доработки и заливать пока рано (креши).

https://github.com/organicmaps/organicmaps/blob/f6662b5e634d7a84cd747b75ec1a2df3b16ad6c9/android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java#L45-L51

2022-04-26 06:16 UTC, biodranik commented on android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
> +      if (!availability.isLocationAvailable()) {
Это стандартная API, которая должа работать, и всегда работала. Если я правильно понимаю, в ней появился баг из-за бага в Google Play Services (после их очередного обновления). Код выше просто фильтрует false-positive срабатывания. Уж точно не делает хуже. Что тебя не устраивает?

2022-04-26 06:21 UTC, biodranik commented on android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
> +  private final static String TAG = "GoogleFusedLocationProvider";
Верни.

2022-04-26 06:23 UTC, biodranik commented on android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
> +      if (!availability.isLocationAvailable()) {
@rtsisyk чем плох вариант фильтровать, как я предлагаю? Он же должен сработать в твоём кейзе.

2022-04-26 06:52 UTC, vng commented on android/jni/com/mapswithme/maps/Framework.cpp
> +  return m_work.GetMyPositionMode();
Предидущая логика хранила и пыталась держать актуальным состояние, которое уже хранится в core.

2022-04-26 06:54 UTC, vng commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    if (LocationState.nativeGetMode() != LocationState.NOT_FOLLOW_NO_POSITION)
Самый первый старт будет PENDING_LOCATION. Здесь не надо ничего стартовать, если пользователь вышел без позиции в предидущей сессии.
Логика такая: Как закончил предидущую, так начинать и текущую и ничего не додумывать за юзера.

2022-04-26 06:55 UTC, vng commented on routing/routing_tests/opening_hours_serdes_tests.cpp
> +  OHSerDesTestFixture()
простой отдельный коммит релевантного переименования тестов

2022-04-26 07:01 UTC, biodranik commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    if (LocationState.nativeGetMode() != LocationState.NOT_FOLLOW_NO_POSITION)
На первом старте точно должно стартовать, иначе не понятно, зачем мы пермишн у пользователей спрашиваем :)

2022-04-26 07:07 UTC, biodranik commented on android/jni/com/mapswithme/maps/Framework.cpp
> +  return m_work.GetMyPositionMode();
Что значит "наверх"? Предыдущая логика была "накручена" поверх исторической, вместо того, чтобы аккуратно отрефакторить, как сейчас сделал Витя. Была "обёртка" над ядром, вместо просто правильного пробрасывания методов ядра.

2022-04-26 07:49 UTC, vng commented on android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
> +  private final static String TAG = "GoogleFusedLocationProvider";
Вернул же

2022-04-26 07:51 UTC, vng commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    if (LocationState.nativeGetMode() != LocationState.NOT_FOLLOW_NO_POSITION)
Я про то и пишу. Первый старт - позиция стартует сама автоматом. Последующий старты - только если вышли с позицией и в режиме следования. Иначе NOT_FOLLOW_NO_POSITION - ничего не стартуем как мы и хотели. Показывается карта там где вышел.

2022-04-26 13:16 UTC, biodranik commented on drape_frontend/my_position_controller.cpp
> +    m_mode = (params.m_isRoutingActive || df::IsModeChangeViewport(m_desiredInitMode)) ?
Тут бы комментариев, почему так.

2022-04-26 13:30 UTC, vng commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +        LocationUtils.areLocationServicesTurnedOn(mContext) &&
- Этот фикс именно здесь ибо: Если добавить "туда", то потом все равно "здесь" произойдет fallback на AndroidManager. А так мы попросим включить location service и останемся на GoogleManager - что логичнее.
- Там вызывался onLocationError(ERROR_NOT_GPS)

2022-04-26 13:32 UTC, biodranik commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +      // first before notifying the user and restart service.
If location service is enabled, try to downgrade to the native provider first and restart the service before notifying the user.

2022-04-26 13:33 UTC, biodranik commented on android/src/com/mapswithme/util/LocationUtils.java
> +      return lm.isLocationEnabled();
На андроидах 28+ можно ловить нотификацию, когда юзер включает/выключает локацию: https://developer.android.com/reference/android/location/LocationManager#MODE_CHANGED_ACTION

2022-04-26 16:18 UTC, vng commented
Добавил коммментов.

2022-04-26 20:21 UTC, biodranik approved these changes

2022-04-26 20:21 UTC, merged