[android] Public API for choosing location by using the app
organicmaps/organicmaps pull request #2675
Opened 2022-06-05 10:59 UTC by rtsisyk

```java
Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse("om://location"));
startActivityForResult(intent, REQ_CODE_LOCATION);
```

Closes #2674

2022-06-05 11:05 UTC, rtsisyk commented
https://user-images.githubusercontent.com/1799054/172047530-11e1d868-2a13-473a-bedb-ba601b70da0b.mp4

2022-06-05 11:38 UTC, rtsisyk commented
https://user-images.githubusercontent.com/1799054/172048632-5b9f9549-5a95-491c-9efe-94c55cea7054.mp4

2022-06-05 14:03 UTC, biodranik requested changes

2022-06-05 14:03 UTC, biodranik commented on api/example/android/build.gradle
> +  id 'com.android.library' version '7.2.1' apply false
А зачем либу?

2022-06-05 14:03 UTC, biodranik commented on map/mwm_url.cpp
> +  if (type == "location")
Название неудачное, наверняка понадобится отдельное api для получения текущей позиции пользователя. Лучше назвать coordinates, и предусмотреть больше одного возвращаемого значения, плюс к каждому значению доп. инфу, как минимум имя.

2022-06-05 14:03 UTC, biodranik commented on map/mwm_url.cpp
> +    {
Скобки не нужны

2022-06-05 14:03 UTC, biodranik commented on map/mwm_url.hpp
> +    Location = 8,
Выпилить то, что выше, сделать Coordinates = 4, Location = 5 на будущее, для GPS координат пользователя.

2022-06-05 18:13 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +            double[] center = Framework.nativeGetScreenRectCenter();
Есть какое-то научное подтверждение необходимости написания final в каждой строчке? Если хочется immutable, то есть другие языки программирования для этого.

2022-06-05 18:13 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +            setResult(Activity.RESULT_OK, apiResult);
Да

2022-06-05 18:14 UTC, rtsisyk commented on android/src/com/mapswithme/maps/SplashActivity.java
> +public class SplashActivity extends Activity implements BaseActivity
Попробую вернуть назад. Там какое-то deprecated вылезает на startAcitvityForResult, хотя в основном классе это никто не запрещал.

2022-06-05 18:14 UTC, rtsisyk commented on api/example/android/app/build.gradle
> +  implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
Удалю

2022-06-05 18:14 UTC, rtsisyk commented on api/example/android/build.gradle
> +  id 'com.android.library' version '7.2.1' apply false
По умолчанию так генерится.

2022-06-05 18:15 UTC, rtsisyk commented on map/mwm_url.hpp
> +    Location = 8,
Это сломает совместимость, наверное?

2022-06-06 09:56 UTC, vng commented on android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
> +      finish();
- No need in break here?
- Why not to write simple if instead of switch?

2022-06-06 09:56 UTC, vng commented on android/src/com/mapswithme/maps/SplashActivity.java
> +  }
Есть ли смысл заморочится чтобы не было копипаста в DownloaderActivity, SplashActivity, ... ?

2022-06-06 09:56 UTC, vng commented on api/example/android/app/src/main/java/app/organicmaps/api/example/MainActivity.java
> +      break;
Хм, выше в _вроде бы_ в такой же ситуации break не было и вызывался super.onActivity ...

2022-06-13 21:59 UTC, biodranik commented
@rtsisyk поправишь?

2022-07-03 11:57 UTC, rtsisyk commented
Closing in favor of https://github.com/organicmaps/organicmaps/pull/2907

2022-07-03 11:57 UTC, closed without merging

2022-07-03 12:01 UTC, rtsisyk commented on android/src/com/mapswithme/maps/SplashActivity.java
> +public class SplashActivity extends Activity implements BaseActivity
Вернул назад. Показывает, что deprecated. Предлагаемое решение от гугла выглядит слишком сложным.

2022-07-03 12:01 UTC, rtsisyk commented on map/mwm_url.hpp
> +    Location = 8,
Здесь в итоге ничего не стал добавлять, ограничился существующими вариантами.

2022-07-03 12:02 UTC, rtsisyk commented on android/src/com/mapswithme/maps/SplashActivity.java
> +  }
Да в целом можно всегда этот setResult звать без каких либо последствий. Будет 1 строчка, а не 5.

2022-07-03 12:02 UTC, rtsisyk commented on api/example/android/app/src/main/java/app/organicmaps/api/example/MainActivity.java
> +      break;
Этот код убит.

2022-07-03 12:02 UTC, rtsisyk commented on map/mwm_url.cpp
> +    {
Этого кода больше нет.

2022-07-03 12:03 UTC, rtsisyk commented on map/mwm_url.cpp
> +  if (type == "location")
Этого больше нет.