Refactor logging for simplification
organicmaps/organicmaps pull request #2700
Opened 2022-06-09 19:47 UTC by pastk

More refactoring in a follow up to #2666.

The logging system is over-engineered IMO. E.g. there are pluggable LogStrategies and therefore a necessity to keep a registry of all loggers to be able to update the strategies when logging is switched between files and logcat.

This PR significantly simplifies the logging code and adds some features.

Logging API changes:
- its no longer necessary to copy TAG into every log call, its passed into the logger constructor once
- a logger object is instantiated by users directly w/o use of a factory
- all classes that use logging are updated accordingly

Other changes:
- add DEBUG system logging for betas;
- don't create a logs folder until necessary
- add a free space check for the logging folder
- write scope (STORAGE/LOCATION/etc.) to system log too
- rename a MISC scope to MAIN

Refactoring:
- merge pluggable LoggerStrategies and BaseLogger into a single Logger class
- remove unnecessary interfaces
- remove excess 'synchronized' usage
- encapsulate TAG into Logger
- rename LoggingFactory to LogsManager
- merge MemLogging into LogsManager

2022-06-09 22:41 UTC, biodranik reviewed
Отличный рефакторинг!

2022-06-09 22:41 UTC, biodranik commented on android/src/com/mapswithme/maps/routing/NavigationService.java
> +                                                              NavigationService.class.getSimpleName().toLowerCase();
Я не понимаю, зачем такие сложные "бубны" в подобных случаях, если проще просто вбить строку "NavigationService"? И зачем lowercase?

2022-06-09 22:41 UTC, biodranik commented on android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
> +  private static final Logger LOGGER = new Logger(Logger.Scope.MAIN, RichPlacePageController.class);
Чем хуже?
```suggestion
  private static final Logger LOGGER = new Logger(Logger.Scope.MAIN, "RichPlacePageController");
```

2022-06-09 22:41 UTC, biodranik commented on android/src/com/mapswithme/util/log/Logger.java
> +    final String logsFolder = LogsManager.INSTANCE.getEnabledLogsFolder();
На каждую запись в лог обязательно дёргать? Может лучше static?

2022-06-09 22:41 UTC, biodranik commented on android/src/com/mapswithme/util/log/Logger.java
> +    else if (!BuildConfig.BUILD_TYPE.equals("release") || level >= Log.INFO)
А можно как-нибудь прогуардом выпилить в релизе все строчки вызова логов, если они всё равно не выводятся?

2022-06-09 22:41 UTC, biodranik commented on android/src/com/mapswithme/util/log/Logger.java
> +      Log.println(level, mScopedTag, msg + (tr != null ? '\n' + Log.getStackTraceString(tr) : ""));
Операция склейки с пустой строкой в жаве небесплатная? Может лучше тогда явный if сделать?

2022-06-09 22:41 UTC, biodranik commented on platform/platform.hpp
> +  /// @TODO remove as its not used anywhere?
Используется же. Тут имеется ввиду, видимо, реализация для десктопов.

2022-06-09 22:41 UTC, biodranik commented on android/src/com/mapswithme/util/log/LogsManager.java
> +    assert mApplication != null : "mApplication must be initialized first by calling initFileLogging()";
А нельзя ли не хранить mApplication, а передавать контекст параметрами функций из мест их вызова? А для путей к логам, например, если передать параметром нельзя, сразу в конструкторе сохранять варианты путей.

2022-06-09 22:41 UTC, biodranik commented on android/src/com/mapswithme/util/log/LogsManager.java
> +        (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
Почему тут в две строки? Вроде же помещается.

2022-06-09 22:41 UTC, biodranik commented on android/src/com/mapswithme/util/log/LogsManager.java
> +    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN)
У нас же всегда больше 4.3

2022-06-10 06:46 UTC, rtsisyk commented on android/src/com/mapswithme/maps/routing/NavigationService.java
> +                                                              NavigationService.class.getSimpleName().toLowerCase();
Да пусть будет как был, а то там где-нибудь в другом месте уши отвалятся. Надо этот большой PR залить без semantic changes, а потом можем это место попробовать поменять.

2022-06-10 06:46 UTC, rtsisyk commented on android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
> +  private static final Logger LOGGER = new Logger(Logger.Scope.MAIN, RichPlacePageController.class);
Пусть будет через имя класса. Так при переименовываниях в IDE само обновляется.

2022-06-10 06:48 UTC, rtsisyk approved these changes

2022-06-10 12:26 UTC, pastk commented on android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
> +  private static final Logger LOGGER = new Logger(Logger.Scope.MAIN, RichPlacePageController.class);
да, чтобы было явно привязано к названию класса, а строку могут и забыть обновить

2022-06-10 12:59 UTC, pastk commented on android/src/com/mapswithme/util/log/Logger.java
> +    final String logsFolder = LogsManager.INSTANCE.getEnabledLogsFolder();
1. getEnabledLogsFolder() не может быть статик, он использует переменные из инстанса
2. можно текущий logsFolder кэшировать в логгере и дёргать тут только isFileLoggingEnabled, чтобы на каждую запись не делать проверок существования и writability пути и делать их (и попытку создать новый logsFolder) только если произошла ошибка записи - но я не думаю, что это усложнение логики (особенно с поведением блокировок тредов) стОит небольшого выигрыша в прозводительности (по сравнению со "стоимостью" операции записи), ведь режим логгирования в файлы это исключение, нужное для отладки

2022-06-10 13:11 UTC, pastk commented on android/src/com/mapswithme/util/log/Logger.java
> +    else if (!BuildConfig.BUILD_TYPE.equals("release") || level >= Log.INFO)
навскидку (для релиза)
```
-assumenosideeffects class com.mapswithme.util.log.Logger {
    public *** v(...);
    public *** d(...);
}

-assumenosideeffects class android.util.Log {
   public static *** v(...);
   public static *** d(...);
}
```
(системный `android.util.Log` тоже выпилить на случай, если какие-то сторонние либы его используют)

Только тут осторожно надо - теоретически в вызове лог-методов могут использоваться какие-то важные методы типа
`LOGGER.d("Bookmark saved: " + saveBookmark())`
Тогда оптимизатор сохранение метки выпилит, я так понимаю?

2022-06-10 13:44 UTC, pastk commented on android/src/com/mapswithme/util/log/Logger.java
> +      Log.println(level, mScopedTag, msg + (tr != null ? '\n' + Log.getStackTraceString(tr) : ""));
хотелось бы верить, что оптимизатор умеет такой простой случай оптимизировать
но можно и явно сделать

2022-06-10 14:24 UTC, biodranik commented on android/src/com/mapswithme/util/log/Logger.java
> +    else if (!BuildConfig.BUILD_TYPE.equals("release") || level >= Log.INFO)
Выпилит, но мы такой код не пропускаем на код ревью. Если вдруг увидишь, дай знать. И проверь, действительно ли выпиливается, это мелочь, но приятная и бесплатная.

2022-06-10 16:29 UTC, pastk commented on android/src/com/mapswithme/util/log/LogsManager.java
> +    assert mApplication != null : "mApplication must be initialized first by calling initFileLogging()";
1. тогда контекст надо будет хранить в местах вызова, например, в ZipLogsTask и в Logger, а откуда они его возьмут?

2. если путь хранить в логгере, то как его обновлять, если путь сменился? у каждого класса свой объект логгера

2022-06-10 17:24 UTC, pastk commented on android/src/com/mapswithme/util/log/Logger.java
> +    final String logsFolder = LogsManager.INSTANCE.getEnabledLogsFolder();
1. оно и раньше включалось по умолчанию в бетах (я добавил только логгинг DEBUG level НЕ в файлы)
2. в моих тестах я (на глаз) не заметил разницы в скорости с включенными логами и без
3. допускаю, что кто-то всё же заметит - можно выпустить бету и послушать отзывы

2022-06-10 17:25 UTC, pastk commented on android/src/com/mapswithme/util/log/Logger.java
> +    else if (!BuildConfig.BUILD_TYPE.equals("release") || level >= Log.INFO)
Конечно. Но давай сначала просто включение оптимизации оттестируем, а потом уже будем там правила дополнять.

2022-06-10 17:37 UTC, pastk commented on android/src/com/mapswithme/util/log/Logger.java
> +    final String logsFolder = LogsManager.INSTANCE.getEnabledLogsFolder();
хм, вообще, если смотреть на бету как на максимально приближенный к релизу вариант, который просто распространяется менее широко между юзерами, подготовленными к возможным багам, то правильно было бы логи по умолчанию в бетах не включать (и ограничить системный логгинг >=INFO)...

2022-06-10 18:40 UTC, pastk commented
@biodranik I made some minor changes as per your review.

2022-06-10 20:14 UTC, biodranik commented on android/src/com/mapswithme/util/log/Logger.java
> +    final String logsFolder = LogsManager.INSTANCE.getEnabledLogsFolder();
Ага.

2022-06-11 06:29 UTC, vng requested changes

2022-06-11 06:29 UTC, vng commented on android/src/com/mapswithme/util/log/Logger.java
> +      Log.println(level, mScopedTag, msg);
Здесь же нужны скобки блока, или Log.println(level, mScopedTag, msg) вызывается всегда?
Даже если всегда, добавить скобки и выровнять блоки.

2022-06-11 06:29 UTC, vng commented on android/src/com/mapswithme/util/log/Logger.java
> +        Log.e(TAG, "Failed to write to " + mFilePath + ": " + mData, e);
Всю mData логировать? Может только размер

2022-06-11 08:12 UTC, pastk commented on android/src/com/mapswithme/util/log/Logger.java
> +        Log.e(TAG, "Failed to write to " + mFilePath + ": " + mData, e);
mData это одна строчка лога

2022-06-11 08:25 UTC, pastk commented
Disabled file logging by default for beta builds. So for all builds its off by default now.

2022-06-12 07:51 UTC, vng approved these changes

2022-06-12 12:16 UTC, biodranik reviewed
Так может всё-таки статик функциями с тэгами оставить, чтобы не хранить состояние и не создавать каждый раз объекты, которые может и не нужны в штатном рантайме?

2022-06-12 13:02 UTC, pastk commented
> Так может всё-таки статик функциями с тэгами оставить, чтобы не хранить состояние и не создавать каждый раз объекты, которые может и не нужны в штатном рантайме?

Да, я уберу несколько файлов и переделаю в статик с тегами. Наверное лучше в отдельном пр.

2022-06-12 13:05 UTC, pastk commented
Rebased.

2022-06-12 14:48 UTC, biodranik commented
@pastk Просто если переделывать, то уже без промежуточных результатов, чтобы историю и откат (мало ли) не усложнять.

2022-06-12 16:01 UTC, vng commented
Так красиво же TAG поместили в конструктор вместо подстановки при каждом вызове, или какой статик вы обсуждаете?

2022-06-12 16:04 UTC, biodranik commented
> Так красиво же TAG поместили в конструктор вместо подстановки при каждом вызове, или какой статик вы обсуждаете?

"Красота" плохо выпиливается и несёт ненужный оверхед. Речь о переписывании а-ля у нас в C++, когда можно будет выпиливать оптимизатором те строки, которые не нужны, целиком из Java для релизных билдов. И не создавать теги, когда, например, класс не вызывает логгирующие функции (например, только случаи ошибок).

2022-06-12 16:44 UTC, pastk commented
> Так красиво же TAG поместили в конструктор вместо подстановки при каждом вызове, или какой статик вы обсуждаете?

Красиво, удобно, но создавать и держать объет ради хранения всего одного аттрибута это как-то перебор. Вот для двух аттрибутов (тег и logging scope) уже больше смысла (две константы на каждый вызов копировать это уже перебор :) Поэтому я так изначально и сделал. Но посколько от scope и нескольких лог файлов решили уйти #2713, то лучше сделать статик вызовы с подстановкой одного тега - будет как в родном андроид логгере.

2022-06-12 17:33 UTC, vng commented
Мне кажется мы уже совсем за спичками гоняемся.
Вроде сейчас если включить режим логирования в файл, то будут писаться и Log.d(), а так мы хотим чтобы оптимизатор в релизе все это выбросил?

Не вижу проблем, чтобы повсюду были логи типа Log.d, проверялись на вывод в рантайме и если надо, могли все записать в файл, чтобы мы потом легче понимали ошибки.

2022-06-12 18:00 UTC, pastk commented
Да, сами лог-вызовы со строчками выпилить не получится, т.к. лог файлы полными должны быть. Оптимизатором можно разве что выпилить вызовы com.android.util.Log.d() (DEBUG в релизе в сислог всё равно не идёт) - просто чуток меньше байт-кода будет.

2022-06-12 18:32 UTC, pastk commented
> Так красиво же TAG поместили в конструктор вместо подстановки при каждом вызове, или какой статик вы обсуждаете?

О, есть идея, как не таскать за собой теги, но чтобы они были и чтобы батарейку сохранить!

- теги вообще не объявляем и в лог вызовы не передаём
- имя вызывающего класса определяет сам логгер через `new Thгowable().getStacktrace()` (так делает либа Timber, например - куча людей пользуется)
- чтобы не было оверхеда в релизе определяем тег только при включенном файл-логгинге и для ERR, идущих в андроид сислог (ну и для дебаг билдов всегда, само собой)

Будет только немного менее информативный релизный логкат, но не принципиально, тем более что вытягивать логи через логкат приходится относительно редко.

@biodranik @vng @rtsisyk

2022-06-12 21:41 UTC, biodranik commented
> Будет только немного менее информативный релизный логкат, но не принципиально, тем более что вытягивать логи через логкат приходится относительно редко.

Я против, логи должны выглядеть одинаково везде, закопаемся отлаживаться и разбираться.

2022-06-12 23:58 UTC, pastk commented
> > Будет только немного менее информативный релизный логкат, но не принципиально, тем более что вытягивать логи через логкат приходится относительно редко.
> 
> Я против, логи должны выглядеть одинаково везде, закопаемся отлаживаться и разбираться.

Хм, а тот разнобой в формате логов, который сейчас есть, что, прям правда сильно мешает? Я на это даже внимания не обращаю, просто видно же, какая инфа есть в строчке, ей и пользуюсь.

2022-06-13 04:32 UTC, biodranik commented
Теги по-умолчанию хранят классы, что позволяет быстро сообразить, что к чему.

2022-06-13 19:32 UTC, strump commented on android/src/com/mapswithme/maps/sound/TtsPlayer.java
> +        LOGGER.w("Failed to initialize TextToSpeach");
Был уровень Error, стал - Warning. Так и должно быть?

2022-06-13 19:32 UTC, strump commented on android/src/com/mapswithme/util/log/LogsManager.java
> +    assert mApplication != null : "mApplication must be initialized first by calling initFileLogging()";
Этот assert несколько раз повторяется в файле. Может сделать геттер для mApplication?

2022-06-13 21:58 UTC, biodranik commented
@pastk поправишь сразу как нужно логи, пожалуйста?

2022-06-13 23:16 UTC, pastk commented on android/src/com/mapswithme/maps/sound/TtsPlayer.java
> +        LOGGER.w("Failed to initialize TextToSpeach");
поправил, спасибо

2022-06-13 23:17 UTC, pastk commented on android/src/com/mapswithme/util/log/LogsManager.java
> +    assert mApplication != null : "mApplication must be initialized first by calling initFileLogging()";
поправил, спасибо

2022-06-13 23:26 UTC, pastk commented
Переделал на статик вызовы, всё теперь идёт в один файл `app.log`.

Также:
- add details to logged system info
- add source point info "file:line method()" to file logging, debug builds and ERRORs
- make logcat, core and file logging formats more similar

Обновил заглавный пост с обзором изменений.

2022-06-14 06:15 UTC, strump commented on android/src/com/mapswithme/maps/sound/TtsPlayer.java
> +        Logger.w(TAG, "Failed to get usable languages " + ignored.getMessage());
Здесь тоже Error превратился в Warning

2022-06-14 08:59 UTC, pastk commented on android/src/com/mapswithme/maps/sound/TtsPlayer.java
> +        Logger.w(TAG, "Failed to get usable languages " + ignored.getMessage());
это я намеренно снизил - в логах постоянно такие "ошибки"
я так понимаю, что это просто ттс не поддерживает конкретный язык

2022-06-14 17:06 UTC, pastk commented
Rebased onto latest master.
Added Build.DEVICE to sys info and a `@Keep` annotation for a jni called method.

2022-06-14 22:07 UTC, biodranik approved these changes

2022-06-14 22:07 UTC, biodranik commented on platform/platform.hpp
> +  /// @TODO remove as its not used anywhere?
```
➜  omim git:(android/ndk-upgrade) rg GetMemoryInfo
android/jni/com/mapswithme/platform/Platform.cpp
21:std::string Platform::GetMemoryInfo() const

platform/platform.hpp
274:  std::string GetMemoryInfo() const;

platform/platform_ios.mm
124:std::string Platform::GetMemoryInfo() const
```

2022-06-14 22:17 UTC, pastk commented on platform/platform.hpp
> +  /// @TODO remove as its not used anywhere?
так это она объявляется, а её вызовов - нет

2022-06-15 05:11 UTC, vng commented on android/src/com/mapswithme/util/log/LogsManager.java
> +    if (mLogsFolder != null && createWritableDir(mLogsFolder))
Так и задумывается что мы будем каждый раз при вызове getEnabledLogsFolder (который вызывается на каждый лог в файл), делать проверку createWritableDir и всю внутрянку типа dir.exists, canWrite ... ?

Может мы сделаем логику что если (mLogsFolder != null) то все проверки уже пройдены?

Единственное что может изменится - это getUsableSpace.

2022-06-15 05:12 UTC, vng commented
Может мы при мерже сквошнем все коммиты в один? Они с разных сторон ковыряют по сути одно и то же.

2022-06-15 10:48 UTC, pastk commented on android/src/com/mapswithme/util/log/LogsManager.java
> +    if (mLogsFolder != null && createWritableDir(mLogsFolder))
Пользователь может удалить папку с логами, или карточку вынуть или ещё что.

Вот тут уже обсуждали https://github.com/organicmaps/organicmaps/pull/2700#discussion_r894007527

С т.з. эффективности можно запускать проверки только если при записи строчки ошибка произошла. Ценой возможной потери нескольких строк лога и усложнения логики. Но поскольку логи включаются редко и ненадолго, да и проверки эти по сравнению с операцией записи должны быть недорогими - оставил так.

2022-06-15 10:51 UTC, pastk commented
> Может мы при мерже сквошнем все коммиты в один? Они с разных сторон ковыряют по сути одно и то же.

Последний коммит (с getStackTrace()) я бы точно отдельным оставил - посмотрим, как он с оптимизацией r8 работать будет.

2022-06-15 11:13 UTC, vng commented
Ok, тогда реорганизуй коммиты (2 или как считаешь логичным) и я помержу.

2022-06-15 13:39 UTC, pastk commented
> Ok, тогда реорганизуй коммиты (2 или как считаешь логичным) и я помержу.

Ребейзнул и сделал из 6 коммитов 4 - мне видится важным/удобным их оставить отдельными.

2022-06-15 14:21 UTC, merged