[strings] Added italian translations
organicmaps/organicmaps pull request #2757
Opened 2022-06-16 14:51 UTC by FinixFighter

Signed-off-by: Luca Finizio <luca.finizio@protonmail.com>

2022-06-16 20:50 UTC, biodranik requested changes

2022-06-16 20:50 UTC, biodranik commented on data/strings/types_strings.txt
> +    it = Impianti HVAC | Impianti di climatizzazione
Alternate translations are not allowed in types strings

2022-06-17 17:58 UTC, FinixFighter commented
The "Merge branch 'organicmaps:master' into master" can be skipped!

2022-06-18 21:00 UTC, biodranik commented on data/strings/types_strings.txt
> +    it = Fabbro
Sort?

2022-06-20 09:09 UTC, FinixFighter commented on data/strings/types_strings.txt
> +    it = Apicoltore
> Sort?

Sorry, I don't understand what you mean with "sort".

2022-06-20 09:15 UTC, biodranik commented on data/strings/types_strings.txt
> +    it = Apicoltore
It means:
- en always goes first
- All other languages are sorted in the English alphabet order.

2022-06-20 10:52 UTC, closed without merging