Allow less width dialogs.
organicmaps/organicmaps pull request #2769
Opened 2022-06-17 23:42 UTC by programmin1

On phones and devices with smaller screens, the dialogs should be allowed to be smaller.
Without this it oddly goes all the way off the screen.
I tested this on desktop resizing the windows smaller.

2022-06-18 20:56 UTC, biodranik requested changes
The proper fix should get the width and height of the screen and use them for creating windows. I'm sure there should be some other way to do it properly in an automated manner.

Your current fix will make the About dialog very small for example on larger screens.

2022-07-17 09:41 UTC, rtsisyk commented
This QT code is not used on phones and tablets (Android/iOS). Could you please show a screenshot with the problem you have on your device(s)?

2022-07-17 15:48 UTC, programmin1 commented
Since it only shows once and doesn't continue that could be problematic. The Linux version will be the one that runs on Linux phones - Pinephone, Librem phone etc.

2022-07-18 23:01 UTC, programmin1 commented
Unfortunately Organicmaps does not run on Linux phone as of yet, but the first screen that showed was way off and this should fix that issue.

2022-07-19 11:50 UTC, biodranik commented
OM should work on a Linux phone. Please provide a proper fix instead of this one.

2022-10-19 06:40 UTC, biodranik commented
Please
1. Rebase these changes.
2. Implement them appropriately by taking the current screen size into a consideration.

2024-03-04 09:41 UTC, Jean-BaptisteC commented
@programmin1 any news, did you have need helps to finish PR?

2024-04-02 15:49 UTC, closed without merging