[strings] - Some russian an armenian (hy) lines added
organicmaps/organicmaps pull request #2771
Opened 2022-06-18 15:49 UTC by friedcucumber

2022-06-18 18:49 UTC, biodranik reviewed
Запускали tools/python/clean_strings_txt.py ?
@pastk надо где-то вставить комментарий об этом, может прямо в файлы переводов?

2022-06-18 18:49 UTC, biodranik commented on data/strings/strings.txt
> +    ru = Нет
ref = no означает, что все переводы берутся оттуда. Если там правильный перевод, то тут "переделывать" не требуется. В беларуском отличается отрицание и аналог слова "нету".

2022-06-18 20:09 UTC, pastk commented
> Запускали tools/python/clean_strings_txt.py ? 

Имеется в виду `strings_utils.py`, наверное, который ссылки-рефы резолвит?
Впрочем, оба включены в запуск `generate_localizations.sh`
@friedcucumber у Вас есть возможность запускать скрипты?

> @pastk надо где-то вставить комментарий об этом, может прямо в файлы переводов?

В твайн файлах комменты в шапке не поддерживаются, увы. Надо твайн патчить.

2022-06-18 20:19 UTC, pastk commented
Если будете добавлять армянский - сделайте отдельный PR, пожалуйста.
Там ведь свой алфавит используется? Тогда всё может быть сильно сложнее, может надо будет добавлять шрифт или ещё что, посмотрите, например, #2247 и #2587

2022-06-19 12:47 UTC, pastk requested changes

2022-06-19 12:47 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Дорожный туннель для лошадей
по возможности лучше подбирать краткие варианты и сообразные с переводом основого типа;
основной bridleway у нас это "Конная дорожка", поэтому тут лучше подойдёт "Конный тоннель", имхо (ну или может "Тоннель для всадников")

2022-06-19 12:47 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Дорожный туннель для велосипедов
аналогично - "Велотоннель"

2022-06-19 12:47 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Пешеходная тропа
почему бы не просто "Тропа", как и highway.path?
аналогично все остальные "Пешеходные тропы"

2022-06-19 12:47 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Автомобильный тоннель
если хочется добавить именно "автомобильный", то лучше сделать это один раз в type.highway.road.tunnel и оно подтянется во все остальные дороги через уже прописанную ссылку (ref)

2022-06-19 12:47 UTC, pastk commented on data/strings/types_strings.txt
> +    ru = Тоннель
дублирует type.highway.road.tunnel

2022-06-20 20:57 UTC, biodranik reviewed
@pastk доделаешь, пожалуйста? Надо вместо "сложных троп" вставить уровни сложности T1-T6 прямо в переводы, отсюда, будет удобно выбирать хайк.
https://wiki.openstreetmap.org/wiki/Key:sac_scale

2022-06-20 20:57 UTC, biodranik commented on data/strings/types_strings.txt
> +    ru = Дорожный туннель для лошадей
```suggestion
    ru = Конный тоннель
```

2022-06-20 20:57 UTC, biodranik commented on data/strings/types_strings.txt
> +    ru = Дорожный туннель для велосипедов
```suggestion
    ru = Велотоннель
```

2022-06-20 20:57 UTC, biodranik commented on data/strings/types_strings.txt
> +    ru = Пешеходная тропа
```suggestion
    ru = Тропа
```

2022-06-21 08:58 UTC, pastk commented
> @pastk доделаешь, пожалуйста? Надо вместо "сложных троп" вставить уровни сложности T1-T6 прямо в переводы, отсюда, будет удобно выбирать хайк. https://wiki.openstreetmap.org/wiki/Key:sac_scale

На переводы пока нет времени, сорри.

Эта классификация не является широко распространённой, поэтому подавляющее большинство хайкеров просто не поймёт, что это за T1-T6. Без слов не обойтись.

2022-06-23 12:31 UTC, pastk commented
> 
> Можно писать так: 1/6, 4/6, 6/6, один раз увидев вживую, можно будет сопоставить сложность и понять. Ну и текстом сопроводить тоже можно. Или явно писать "сложность 5"

В первом приближении предлагаю вот так:

`hiking`
Hiking Trail (difficulty 1/6)
Туристическая тропа (сложность 1/6)

`mountain_hiking`
Hiking Trail (difficulty 2/6)
Туристическая тропа (сложность 2/6)

`demanding_mountain_hiking`
Mountain Route (difficulty 3/6)
Горный маршрут (сложность 3/6)

`alpine_hiking`
Mountain Route (difficulty 4/6)
Горный маршрут (сложность 4/6)

`demanding_alpine_hiking`
Alpine Route (difficulty 5/6)
Альпийский маршрут (сложность 5/6)

`demanding_alpine_hiking`
Alpine Route (difficulty 6/6)
Альпийский маршрут (сложность 6/6)

2022-06-24 15:11 UTC, biodranik commented
Норм, только 4-й тоже должен быть Альпийский :)

2022-06-25 09:56 UTC, pastk commented
@friedcucumber вставите переводы для троп?

2022-10-16 13:57 UTC, rtsisyk commented
@friedcucumber up

2023-11-23 08:12 UTC, rtsisyk commented
@pastk what changes are we waiting for here? I would like to merge or close this PR. Please help me with understanding what needs to be changed.

2023-12-29 15:37 UTC, pastk commented
> There might be a few better translated strings here which someone could cherry-pick and integrate (probably easier in a separate PR).

- #7014

2023-12-29 15:37 UTC, closed without merging