[android] Refactor: Move saving of StoragePath setting to android code
organicmaps/organicmaps pull request #2783
Opened 2022-06-19 22:05 UTC by pastk

- don't use jni loopback
- single source for "StoragePath" setting name

2022-06-20 09:21 UTC, biodranik requested changes
Это очень стрёмные изменения. В чём суть?
CC @rtsisyk

2022-06-20 10:03 UTC, pastk commented
> Это очень стрёмные изменения. В чём суть? CC @rtsisyk

Настройка "StoragePath" используется только в андроиде. Грузится она через Config.java (там константа "StoragePath").
А сохраняется через отдельный native код (там своя дублирующая константа "StoragePath").
Я сделал, чтобы всё было логчино через одно место и одну константу в Config.java.

2022-06-20 10:03 UTC, pastk commented on android/jni/com/mapswithme/platform/Platform.cpp
> -  settings::Set("StoragePath", m_writableDir);
Platform::SetWritableDir() используется только на андроиде, остальные платформы напрямую читают/пишут m_writableDir

2022-06-20 10:04 UTC, pastk commented on android/src/com/mapswithme/maps/MwmApplication.java
>      Config.setStatisticsEnabled(SharedPropertiesUtils.isStatisticsEnabled(this));
не знаю, не трогал

2022-06-21 13:21 UTC, vng commented on android/jni/com/mapswithme/platform/Platform.cpp
> -  settings::Set("StoragePath", m_writableDir);
Если есть Setm то логично что где-то еще сидит Get("StoragePath")? А в PR правок нет

2022-06-21 13:22 UTC, vng commented on android/src/com/mapswithme/util/Config.java
> +  }
А что раньше возвращало getStoragePath(), когда не было setStoragePath и соотвественно зачем ее добавили?

2022-06-21 13:23 UTC, vng approved these changes
Почитал коммент, все стало понятно.

2022-06-23 05:59 UTC, vng commented
@biodranik По сути ничего не поменялось в поведении, но стало логично в коде.

2022-06-23 06:10 UTC, biodranik approved these changes
После логичных изменений у нас уже перестали работать SD у некоторых пользователей самсунгов :) Это к тому, что старый код написан слишком сложно, и любые изменения могут поломать какую-то скрытую логику или "халяву", из-за которой раньше работало.

2022-06-23 06:10 UTC, merged