[android] Rework Public API
organicmaps/organicmaps pull request #2907
Opened 2022-07-03 11:57 UTC by rtsisyk

2022-07-03 11:58 UTC, rtsisyk commented
See PickPoint example in https://github.com/organicmaps/api-android/pull/2

2022-07-04 21:30 UTC, biodranik commented
```
2022-07-04T12:07:59.1767080Z In file included from /Users/runner/work/organicmaps/organicmaps/iphone/CoreApi/CoreApi/DeepLink/DeepLinkParser.mm:5:
2022-07-04T12:07:59.1768290Z /Users/runner/work/organicmaps/organicmaps/iphone/CoreApi/CoreApi/DeepLink/Data/DeeplinkUrlType.h:8:11: warning: enumeration value 'Coordinates' not handled in switch [-Wswitch]
2022-07-04T12:07:59.1769030Z   switch (type)
2022-07-04T12:07:59.1769510Z           ^
2022-07-04T12:07:59.1770170Z /Users/runner/work/organicmaps/organicmaps/iphone/CoreApi/CoreApi/DeepLink/Data/DeeplinkUrlType.h:8:11: note: add missing switch cases
2022-07-04T12:07:59.1770830Z   switch (type)
2022-07-04T12:07:59.1773320Z           ^
2022-07-04T12:07:59.1774680Z /Users/runner/work/organicmaps/organicmaps/iphone/CoreApi/CoreApi/DeepLink/Data/DeeplinkUrlType.h:15:1: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]
2022-07-04T12:07:59.1776120Z }
2022-07-04T12:07:59.1777070Z ^
2022-07-04T12:08:04.4029950Z 1 warning and 1 error generated.
```

2022-07-04 21:42 UTC, biodranik requested changes

2022-07-04 21:42 UTC, biodranik commented on android/AndroidManifest.xml
> -        <action android:name="com.mapswithme.maps.api.request"/>
Сложно ли нам пока это оставить и поддержать? Какие плюсы от выпиливания?

2022-07-04 21:42 UTC, biodranik commented on android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
> -      new Factory.ShowOnMapProcessor(),
Зачем всё выпиливать? Как оно сейчас будет работать?

Может просто сделать ApiProcessor и там все наши штуки с om и mwm обрабатывать?

2022-07-04 21:42 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +  enum PositionChooserMode {
Плохое название Position, кажется что это связано с текущей позицией пользователя. А нам надо, если я правильно понял, любая точка на карте. PointChooserMode более универсально.

2022-07-04 21:42 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +            Intent apiResult = new Intent();
```suggestion
            final Intent apiResult = new Intent();
```

2022-07-04 21:42 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +            double[] center = Framework.nativeGetScreenRectCenter();
```suggestion
            final double[] center = Framework.nativeGetScreenRectCenter();
```

2022-07-04 21:42 UTC, biodranik commented on android/src/com/mapswithme/maps/api/Const.java
> +  /* Common */
Не люблю когда однострочные комментарии в сишном стиле, неудобно блоки кода коммментить.

2022-07-04 21:42 UTC, biodranik commented on android/src/com/mapswithme/maps/api/ParsingResult.java
> +  //public static final int TYPE_SUBSCRIPTION = 7;
Удаляй.

2022-07-04 21:42 UTC, biodranik commented on android/src/com/mapswithme/maps/search/FloatingSearchToolbarController.java
> +              request.getTitle()
Зачем в сёрч баре отображать тайтл аппы, как будто оно было в поиске вбито? Надо тогда двойной режим для сёрчбара делать, то он апи, то он поиск, и визуально различать, например цветом. Но лучше может для апи свой тулбар сверху показывать, отдельный? На нём можно будет лепить любые кастомные апи штуки тогда.

2022-07-04 21:42 UTC, biodranik commented on map/mwm_url.cpp
> +  if (type == "coordinates")
crosshair?

2022-07-04 21:42 UTC, biodranik commented on android/src/com/mapswithme/maps/intent/Factory.java
> -  public static class ShowPointTask implements MapTask
Ты эти классы выпилил, как теперь они обрабатываются?

2022-07-05 06:09 UTC, rtsisyk commented on android/AndroidManifest.xml
> -        <action android:name="com.mapswithme.maps.api.request"/>
Зачем поддерживать 3 разные версии одного и того же? Какой смысл?

2022-07-05 06:09 UTC, rtsisyk commented on android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
> -      new Factory.ShowOnMapProcessor(),
Данные intents дублируют om:// urls. Просто еще один способ.

2022-07-05 06:09 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +  enum PositionChooserMode {
В текущем коде элемент называется PositionChooser. Мне еще и этот код переименовывать весь?

2022-07-05 06:09 UTC, rtsisyk commented on android/src/com/mapswithme/maps/api/Const.java
> +  /* Common */
И чего делать надо?

2022-07-05 06:09 UTC, rtsisyk commented on android/src/com/mapswithme/maps/api/ParsingResult.java
> +  //public static final int TYPE_SUBSCRIPTION = 7;
Ну ок.

2022-07-05 06:09 UTC, rtsisyk commented on android/src/com/mapswithme/maps/intent/Factory.java
> -  public static class ShowPointTask implements MapTask
Через OpenUrlTask. Данный код дублирует om:// URLs чуть более, чем полностью.

2022-07-05 06:09 UTC, rtsisyk commented on android/src/com/mapswithme/maps/search/FloatingSearchToolbarController.java
> +              request.getTitle()
Мне тоже кажется это странным. Но как можно видеть, здесь я просто не стал удалять старое. Могу, наверное, удалить эту часть.

2022-07-05 06:09 UTC, rtsisyk commented on map/mwm_url.cpp
> +  if (type == "coordinates")
Ок

2022-07-06 00:12 UTC, biodranik reviewed
Позже проверю на устройстве. Все тестовые ссылки на https://omaps.app/test работают? Надо туда добавить crosshair.

2022-07-06 00:12 UTC, biodranik commented on android/AndroidManifest.xml
> -        <action android:name="com.mapswithme.maps.api.request"/>
Например, какие-то сторонние аппы, которые уже использовали ту старую апи.

2022-07-06 00:12 UTC, biodranik commented on android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
> -      new Factory.ShowOnMapProcessor(),
Так если через интенты вызывать, всё будет сейчас работать?

2022-07-06 00:12 UTC, biodranik commented on android/src/com/mapswithme/maps/api/Const.java
> +  /* Common */
Использовать //

2022-07-06 00:12 UTC, biodranik commented on android/src/com/mapswithme/maps/api/ParsedMwmRequest.java
> +  public boolean isPickPointMode() { return mPickPoint; }
Если переименовывать, то лучше уже везде crosshair, будет проще отлаживаться.

2022-07-08 22:36 UTC, biodranik commented
```
registerForActivityResult.launch(request)

    private val request = Intent(Intent.ACTION_VIEW, Uri.parse("om://crosshair")).apply {
        putExtra(PICK_POINT, true)
        putExtra(TITLE, "Select an area")
    }
```

1. Посылаюю запрос (на онклике кнопки)
2. Открывается органик, всё хорошо работает
3. Выбросить Органик из стека
4. Попадаю в тестовое приложение снова
5. Снова посылаю запрос - меня сразу возвращает обратно в приложение

2022-07-17 18:44 UTC, rtsisyk commented on android/src/com/mapswithme/maps/api/Const.java
> +  /* Common */
Поменял.

2022-07-17 18:46 UTC, rtsisyk commented on android/AndroidManifest.xml
> -        <action android:name="com.mapswithme.maps.api.request"/>
1. По данной апишке вызывалось om://map и om://route соответственно. 
2. Они просто дублировали om:// API, используя другой способ передачи параметров.
3. Можно, но зачем здесь две дублирующие друг друга апишки?

2022-07-18 20:57 UTC, biodranik approved these changes
Мелкие комментарии и можно мержить и тестить.

2022-07-18 20:57 UTC, biodranik commented on android/AndroidManifest.xml
> -        <action android:name="com.mapswithme.maps.api.request"/>
Ладно, если кто-то использовал, то напишут нам в поддержку.

2022-07-18 20:57 UTC, biodranik commented on android/AndroidManifest.xml
> -        <action android:name="com.mapswithme.maps.api.request"/>
Но нам разве по аналогии не нужно прописывать подобные интент-фильтры? Почему?

2022-07-18 20:57 UTC, biodranik commented on android/jni/com/mapswithme/maps/Framework.cpp
> +  using namespace url_scheme;
Зачем эта строка здесь?

2022-07-18 20:57 UTC, biodranik commented on android/jni/com/mapswithme/maps/Framework.cpp
> +Java_com_mapswithme_maps_Framework_nativeGetParsedAppTitle(JNIEnv * env, jclass clazz)
```suggestion
Java_com_mapswithme_maps_Framework_nativeGetParsedAppTitle(JNIEnv * env, jclass)
```

2022-07-18 20:57 UTC, biodranik commented on android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
> -      new Factory.ShowOnMapProcessor(),
Это точно поддерживается везде, начиная с API 21 (Android 5)?

2022-07-18 20:57 UTC, biodranik commented on map/mwm_url.cpp
> +  }
```suggestion
    m_appTitle = value;
```

2022-07-18 20:57 UTC, biodranik commented on map/mwm_url.hpp
> +    Incorrect = 0,
Зачем явные цифры? В плюсах всегда всё с нуля.

2022-07-21 17:40 UTC, biodranik requested changes
@rtsisyk Исправь ошибки компиляции:

```
In file included from /Users/runner/work/organicmaps/organicmaps/iphone/CoreApi/CoreApi/DeepLink/DeepLinkParser.mm:5:
/Users/runner/work/organicmaps/organicmaps/iphone/CoreApi/CoreApi/DeepLink/Data/DeeplinkUrlType.h:8:11: warning: enumeration value 'Crosshair' not handled in switch [-Wswitch]
  switch (type)
          ^
/Users/runner/work/organicmaps/organicmaps/iphone/CoreApi/CoreApi/DeepLink/Data/DeeplinkUrlType.h:8:11: note: add missing switch cases
  switch (type)
          ^
/Users/runner/work/organicmaps/organicmaps/iphone/CoreApi/CoreApi/DeepLink/Data/DeeplinkUrlType.h:15:1: error: non-void function does not return a value in all control paths [-Werror,-Wreturn-type]
}
^
1 warning and 1 error generated.
```

2022-07-23 06:20 UTC, rtsisyk commented on map/mwm_url.hpp
> +    Incorrect = 0,
Да пусть будет явно чтобы сигнализировать, что эти значения что-то значат.

2022-07-23 06:23 UTC, rtsisyk commented on android/jni/com/mapswithme/maps/Framework.cpp
> +  using namespace url_scheme;
Артефакт

2022-07-23 06:23 UTC, rtsisyk commented on android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
> -      new Factory.ShowOnMapProcessor(),
Открытие URL в любой версии поддерживается.

2022-07-23 11:02 UTC, biodranik reviewed
1. Как title передать из урла? Зачем переименовывать из name?
2. Склеишь некоторые коммиты, чтобы было логично и удобно откатываемо?

2022-07-23 11:02 UTC, biodranik commented on android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
> +          .putExtra(Const.EXTRA_POINT_NAME, mMapObject.getTitle())
title и appid всегда не null? Не будет креша если пустые?

2022-07-23 11:47 UTC, rtsisyk commented on android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
> +          .putExtra(Const.EXTRA_POINT_NAME, mMapObject.getTitle())
Просто приходит null.

2022-07-23 12:28 UTC, rtsisyk reviewed
Squashed && Rebased

2022-07-23 12:28 UTC, rtsisyk commented on android/src/com/mapswithme/maps/DownloadResourcesLegacyActivity.java
> -      new Factory.ShowOnMapProcessor(),
Текущий код должен работать вообще в любой версии Android.

2022-07-23 12:28 UTC, rtsisyk commented on map/mwm_url.cpp
> +
Убрал.

2022-07-23 12:28 UTC, rtsisyk commented on map/mwm_url.hpp
> +    Incorrect = 0,
Цифры в любом случае надо просинхронизировать с Android кодом.

2022-07-23 12:29 UTC, rtsisyk commented
> Как title передать из урла?

?apptitle=xxx

> Зачем переименовывать из name?

Везде в коде и по сути это Title, лишь сам параметр назывался Name.

2022-07-23 17:51 UTC, biodranik commented
> Везде в коде и по сути это Title, лишь сам параметр назывался Name.

Это сломает старые апишки, какие бы они ни были, и усложнит миграцию.

2022-07-23 17:53 UTC, biodranik requested changes
@rtsisyk Почини, пожалуйста, сломанный тест
```
FAILED
map_tests/mwm_url_tests.cpp:356 TEST(api.GetAppTitle() == "Google")  Google 
```

2022-07-25 14:23 UTC, biodranik approved these changes

2022-07-25 14:23 UTC, merged