[android]: Remove unused permissions
organicmaps/organicmaps pull request #295
Opened 2021-04-05 05:09 UTC by rtsisyk

2021-04-05 10:54 UTC, biodranik requested changes

2021-04-05 10:54 UTC, biodranik commented on android/AndroidManifest.xml
> -  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
По этому пермишну запускался фоновый сервис. Этот сервис выпилен?

2021-04-05 10:54 UTC, biodranik commented on android/AndroidManifest.xml
> -  <uses-permission android:name="android.permission.WAKE_LOCK"/>
Надо грепнуть функции, которым был нужен этот пермишн. Можно гуглянуть.

2021-04-05 10:54 UTC, biodranik commented on android/src/com/mapswithme/util/BatteryState.java
> -  // Called from JNI.
Нативную часть тоже надо выпилить целиком. Зачем был нужен мониторинг батареи?

2021-04-10 08:17 UTC, rtsisyk commented on android/AndroidManifest.xml
> -  <uses-permission android:name="android.permission.WAKE_LOCK"/>
С этим я поразбираюсь отдельно. Пока что удалил из PR.

2021-04-10 08:18 UTC, rtsisyk commented on android/src/com/mapswithme/util/BatteryState.java
> -  // Called from JNI.
Походу какие-то концы все еще есть там. Удалил из PR пока. Отдельно разбираться буду.

2021-04-10 08:34 UTC, rtsisyk commented on android/AndroidManifest.xml
> -  <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
Данный пермишен добавлялся коммитом 2ff60a4f148abcf7ee32288bbc0f840122af35f0 для работы FirebaseJobService. Сервис FirebaseJobService был выпилен в 8a921f8dd84d66ecc189fff7b965fd3f4c2ae1ef, а остатки его объявления довыпилены в этом PR. Объединил в один коммит выпиливание сервиса и удаление пермишена для него.

2021-04-10 08:35 UTC, rtsisyk commented
Все вызывающие вопросы коммиты удалены из этого PR и я буду с ними разбираться отдельно в рамках отдельных PR. Лейте.

2021-04-10 08:42 UTC, vng approved these changes

2021-04-10 13:08 UTC, biodranik approved these changes
LGTM

2021-04-10 14:31 UTC, merged