[ios] Add "Open"/"Opens in"/"Closes in" marker in search results
organicmaps/organicmaps pull request #2999
Opened 2022-07-20 20:37 UTC by dvdmrtnz

Continuing from https://github.com/organicmaps/organicmaps/pull/2403, this PR will add the "Open"/"Opens in"/"Closes in" marker to the search results in the iOS app

By the way, I noticed that the "minute" string in https://github.com/organicmaps/organicmaps/blob/master/data/strings/strings.txt#L13488 is tagged as android only, so I cannot get it from the iOS project. Is there a specific reason why this string is Android only? 

This is how it will look:

![](https://user-images.githubusercontent.com/47610359/180076284-378091b5-6a12-4e55-a443-827a314aace8.png)

2022-07-21 19:54 UTC, biodranik commented
> By the way, I noticed that the "minute" string in https://github.com/organicmaps/organicmaps/blob/master/data/strings/strings.txt#L13488 is tagged as android only, so I cannot get it from the iOS project. Is there a specific reason why this string is Android only?

Use this string in the iOS code, and then run tools/unix/generate_localizations.sh

2022-07-21 20:09 UTC, biodranik requested changes
Thanks! Do colors match Android ones?

2022-07-21 20:09 UTC, biodranik commented on iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
> +  self.openLabel.hidden = true;
Move it below into the final (missing) default switch clause, to avoid unnecessary hiding/showing.

2022-07-21 20:09 UTC, biodranik commented on iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
> +    int minutes = result.GetMinutesUntilClosed();
```suggestion
    int const minutes = result.GetMinutesUntilClosed();
```

2022-07-21 20:09 UTC, biodranik commented on iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
> +  if (result.IsOpenNow() == osm::Yes)
Convert it to a switch to avoid unnecessary second IsOpenNow() call.

2022-07-21 20:09 UTC, biodranik commented on iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
> +    int minutes = result.GetMinutesUntilOpen();
```suggestion
    int const minutes = result.GetMinutesUntilOpen();
```

2022-07-21 20:09 UTC, biodranik commented on iphone/Maps/UI/Search/TableView/MWMSearchCommonCell.mm
> +      self.openLabel.text = L(@"closed");
Cells are reused, right? So label colors should be also reset.

2022-07-21 20:12 UTC, biodranik commented
Also, how it will look like if the type label will have many types (a long string)? Check on some popular restaurants with many cuisines, wifi, etc.

2022-07-21 22:47 UTC, dvdmrtnz commented
> Also, how it will look like if the type label will have many types (a long string)? Check on some popular restaurants with many cuisines, wifi, etc.

If the description was too long, it was showing on top of the "Open"/"Closed" marker. Also if it was really long it was going offscreen and getting cropped. I modified the description now to be multiline.  This is how it will look now:

![](https://user-images.githubusercontent.com/47610359/180327285-a210abd7-c4e7-419f-80b0-e1ed177356b6.PNG)

![](https://user-images.githubusercontent.com/47610359/180327522-052e213e-e876-4d87-9648-dfe069d0a09a.PNG)

2022-07-23 08:43 UTC, biodranik approved these changes
Thanks! Looks like it works now. In the future, we can think about a better UI/UX, including Open Now filters.

2022-07-23 08:44 UTC, merged