[search][ranking] POIs ranking from scratch.
organicmaps/organicmaps pull request #3035
Opened 2022-07-27 17:02 UTC by vng

Affected issues:

https://github.com/organicmaps/organicmaps/issues/3026
https://github.com/organicmaps/organicmaps/issues/2530
partial: https://github.com/organicmaps/organicmaps/issues/2470
https://github.com/organicmaps/organicmaps/issues/2133
https://github.com/organicmaps/organicmaps/issues/1997
https://github.com/organicmaps/organicmaps/issues/1949
partial: https://github.com/organicmaps/organicmaps/issues/1376
https://github.com/organicmaps/organicmaps/issues/678

2022-07-27 18:37 UTC, biodranik commented
FAILED
search_integration_tests/processor_test.cpp:2417 TEST(results[1].GetRankingInfo().GetLinearModelRank() > results[0].GetRankingInfo().GetLinearModelRank()) 0.104256 0.106698

2022-07-30 11:45 UTC, biodranik requested changes
Предлагаю быстро вынести из этого PR простые и очевидные коммиты с мелкими улучшениями и переписываниями кода, и быстро их помержить. Чтобы PR не разрастался.

2022-07-30 11:45 UTC, biodranik commented on indexer/search_string_utils.cpp
> +      "allee", "alley", "autoroute", "aut", "bypass", "byway", /*"carrefour", "carref",*/ "chemin", "cercle", "circle", "côte", "crossing", "cross", "expressway", "freeway", "fwy", "line", "link", "l
Может хранить их как constexpr string_view для ускорения инициализации и избежания ненужных аллокаций далее?

2022-07-30 11:45 UTC, biodranik commented on map/search_mark.cpp
> +  std::string const * symbolName = nullptr;
Может string_view таки?

2022-07-30 11:45 UTC, biodranik commented on map/search_mark.cpp
> +//    m_unavailable.clear();
Это точно не нужно? Комментарий бы хотя бы.

2022-07-30 11:45 UTC, biodranik commented on map/search_mark.hpp
> +  SearchMarkType m_type{};
Зачем тут фигурные скобки?

2022-07-30 11:45 UTC, biodranik commented on search/features_layer_path_finder.hpp
> +                             FnT &&fn);
```suggestion
                             FnT && fn);
```
И в других местах ниже тоже, не по стилю же.

2022-07-30 11:45 UTC, biodranik commented on search/intermediate_result.cpp
> +uint32_t RankerResult::GetBestType(vector<uint32_t> const * preferredTypes /* = nullptr */) const
Семантику вызова с nullptr хорошо бы задокументировать в комментарии.

2022-07-30 11:45 UTC, biodranik commented on search/pre_ranker.cpp
>    vector<PreRankerResult> filtered;
Не надо тут reserve()?

2022-07-30 11:45 UTC, biodranik commented on search/pre_ranker.cpp
> +    nth_element(m_results.begin(), m_results.begin() + numResults, m_results.end(),
Может стоит вынести m_results.begin() и end() в переменные?

Кстати, вспомнил, что в С++17 порядок вычисления аргументов функции строго гарантирован слева направо, но ты наверное это знаешь :)

2022-07-30 11:45 UTC, biodranik commented on search/pre_ranker.cpp
> +    nth_element(m_results.begin(), m_results.begin() + numResults, m_results.end(), comparator);
Вообще, конечно, хорошая реализация поиска продолжит тихонько лупить в фоне после выдачи первоначального лимита результатов, чтобы можно было скроллить дальше. Ну или хотя бы будет дальше запускать поиск явно, если юзер доскроллит в низ списка результатов.

2022-07-30 11:45 UTC, biodranik commented on search/pre_ranker.cpp
> +    // Interesting, is it possible when there is no center for a search result?
Это мог быть какой-то edge-case, когда движок не инициализируется нормально, например (протести!) вызов поиска из апишки. Но его нужно тогда системно исправлять, а не ненужной проверкой тут, конечно же.

2022-07-30 11:45 UTC, biodranik commented on search/pre_ranker.cpp
> +    m_currEmit.insert(result.GetId());
small_set? Тут же динамическая аллокация на каждый айдишник, верно?

2022-07-30 11:45 UTC, biodranik commented on search/pre_ranker.hpp
> +  /// to results that were on map previously, to avoid result's annoying blinking/flickering on map.
Это означает, что наш лимит на количество фич, выданных поиском, может на самом деле быть больше, верно? kMax + m_currEmit.size() ?
Потому что если нет, то будет моргать. Или я не прав?

2022-07-30 11:45 UTC, biodranik commented on search/ranking_info.cpp
> + -0.0725383 /* Village */,
Так вот почему плохо ищутся деревни )

2022-07-30 11:45 UTC, biodranik commented on search/ranking_info.cpp
> +     os << DebugPrint(info.m_classifType.poi);
```suggestion
    os << DebugPrint(info.m_classifType.poi);
```

2022-07-30 11:45 UTC, biodranik commented on search/ranking_info.hpp
> +  bool m_exactMatch : 1;
Инициализировать точно не нужно по-умолчанию?

2022-07-30 11:45 UTC, biodranik commented on search/ranking_info.hpp
> +  bool m_pureCats : 1;
m_purrCats :)

Уже лучше тогда полностью слово )

2022-07-30 11:45 UTC, biodranik commented on search/ranking_info.hpp
> +  bool m_falseCats : 1;
Фальшивые коты! 🤣

2022-07-30 11:45 UTC, biodranik commented on search/ranking_utils.cpp
> +      for (char const * s : {"a", "de", "di", "da", "la", "le", "де", "ди", "да", "ла", "ля", "ле"})
Тут же явно не все языки. Откуда взялись эти строки?

И уточняющий вопрос: если юзер вбил явно "de La Feature", у него 1 к одному заматчится и будет в топе эта фича? Или стопворды заматчат только Feature?

2022-07-30 11:45 UTC, biodranik commented on search/ranking_utils.cpp
> +    set<UniString> m_set;
Давно мучаюсь вопросом: можно ли заменить наш UniString на char32_t? Тогда можно было бы создавать при компиляции constexpr строки `U"это будет unicode 32 строка"` и избегать рантайм оверхеда.

Хочется, чтобы у всех юзеров ОМ запускался мгновенно и работал везде и во всём быстрее всех, судя по всему, это одна из наших killer-features сейчас )

2022-07-30 11:45 UTC, biodranik commented on search/ranking_utils.cpp
> +  static StopWordsChecker swChecker;
const

2022-07-30 11:45 UTC, biodranik commented on search/search_integration_tests/processor_test.cpp
> +    builder.Add(cafe1);
Полотенца тестов получаются, может удобнее было бы builder.Add(cafe1).Add(cafe2).Add(cafe3)? Или что-то вроде builder.Add({cafe1, cafe2, cafe3})?

2022-07-30 11:45 UTC, biodranik commented on search/search_integration_tests/processor_test.cpp
> +  auto wonderlandId = BuildCountry("Wonderland", [&](TestMwmBuilder & builder)
kWonderland = "Wonderland"?

2022-07-30 11:45 UTC, biodranik commented on search/search_integration_tests/processor_test.cpp
> +  auto countryId = BuildCountry("Wonderland", [&](TestMwmBuilder & builder)
Если тут одно и то же везде, то лучше сразу BuildWonderland(lambda).

2022-07-30 11:45 UTC, biodranik commented on search/search_integration_tests/processor_test.cpp
> +      vector<strings::UniString> tokens = { strings::MakeUniString(query) };
const?

2022-07-30 11:45 UTC, biodranik commented on search/search_tests/ranking_tests.cpp
> +} // namespace
Если весь тест внутри своего namespace, можно анонимные внутри и не делать, зачем?

2022-07-30 11:45 UTC, biodranik commented on search/search_tests/ranking_tests.cpp
> +  {
Кажется тут скоуп не нужен )

2022-07-30 11:45 UTC, biodranik commented on search/search_tests/ranking_tests.cpp
> +  {
А тут зачем скоуп? :)

2022-07-30 13:20 UTC, vng commented on indexer/ftypes_matcher.cpp
> -  // data/categories.txt, so, it's worth it to generate or parse it
Есть категории, есть улицы. Можно зависимость искать, можно нет. Нет смысла тут натягивать.

2022-07-30 13:20 UTC, vng commented on indexer/search_string_utils.cpp
>        "булевард", "бул", "площад", "пл", "улица", "ул", "квартал", "кв",
Дубликаты не страшны

2022-07-30 13:21 UTC, vng commented on map/search_mark.cpp
> +std::string const & GetSymbol(SearchMarkType searchMarkType)
Зачем?

2022-07-30 13:21 UTC, vng commented on indexer/search_string_utils.cpp
> +      "allee", "alley", "autoroute", "aut", "bypass", "byway", /*"carrefour", "carref",*/ "chemin", "cercle", "circle", "côte", "crossing", "cross", "expressway", "freeway", "fwy", "line", "link", "l
Они хранятся как UniString в итоге

2022-07-30 13:21 UTC, vng commented on map/search_mark.cpp
> +  std::string const * symbolName = nullptr;
зачем?

2022-07-30 13:21 UTC, vng commented on map/search_mark.cpp
> +//    m_unavailable.clear();
неиспользуемый код

2022-07-30 13:22 UTC, vng commented on map/search_mark.hpp
> +  SearchMarkType m_type{};
default = 0 initialization

2022-07-30 13:24 UTC, vng commented on search/pre_ranker.cpp
>    vector<PreRankerResult> filtered;
там неизвестно кол-во, в целом можно - да, можно - нет

2022-07-30 13:26 UTC, vng commented on search/pre_ranker.cpp
> +    nth_element(m_results.begin(), m_results.begin() + numResults, m_results.end(),
можно, а что с порядком не так?

2022-07-30 13:26 UTC, vng commented on search/pre_ranker.cpp
> +    nth_element(m_results.begin(), m_results.begin() + numResults, m_results.end(), comparator);
она так и работает, и это хорошо и не очень одновременно

2022-07-30 13:27 UTC, vng commented on search/pre_ranker.cpp
> +    // Interesting, is it possible when there is no center for a search result?
протести, assert покажет

2022-07-30 13:28 UTC, vng commented on search/pre_ranker.cpp
> +    m_currEmit.insert(result.GetId());
он тут не small, _возможно_ (не уверен) стоит заменить на unordered

2022-07-30 13:30 UTC, vng commented on search/pre_ranker.hpp
> +  /// to results that were on map previously, to avoid result's annoying blinking/flickering on map.
Тут не про лимит. Храним предидущий выхлоп, чтобы на следующем он тоже по максимуму остался.

2022-07-30 13:30 UTC, vng commented on search/ranking_info.cpp
> + -0.0725383 /* Village */,
нет

2022-07-30 13:31 UTC, vng commented on search/ranking_info.hpp
> +  bool m_exactMatch : 1;
в конструкторе, для битов = семантика не работает

2022-07-30 13:32 UTC, vng commented on search/ranking_info.hpp
> +  bool m_pureCats : 1;
purr?

2022-07-30 13:34 UTC, vng commented on search/ranking_utils.cpp
> +      for (char const * s : {"a", "de", "di", "da", "la", "le", "де", "ди", "да", "ла", "ля", "ле"})
- были всегда, латинское - понятно, де ди, .. - не совсем
- они исключаются, будто их нет

2022-07-30 13:35 UTC, vng commented on search/ranking_utils.cpp
> +    set<UniString> m_set;
Мы всегда делаем NormalizeAndSimplify, потому constexpr тут не будет, а тем более в set

2022-07-30 13:36 UTC, vng commented on search/search_integration_tests/processor_test.cpp
> +  auto wonderlandId = BuildCountry("Wonderland", [&](TestMwmBuilder & builder)
зачем?

2022-07-30 13:38 UTC, vng commented on search/search_tests/ranking_tests.cpp
> +  {
предполагается что тесты будут добавляться

2022-07-30 13:38 UTC, vng commented on search/search_tests/ranking_tests.cpp
> +  {
предполагается что тесты будут добавляться

2022-07-30 13:39 UTC, vng commented on search/search_integration_tests/processor_test.cpp
> +    builder.Add(cafe1);
мне не удобнее

2022-07-30 13:40 UTC, vng commented on search/intermediate_result.cpp
> +uint32_t RankerResult::GetBestType(vector<uint32_t> const * preferredTypes /* = nullptr */) const
тут код - лучший комментарий :) есть - передай, нет - не непердавай

2022-07-30 14:33 UTC, biodranik commented on indexer/search_string_utils.cpp
> +      "allee", "alley", "autoroute", "aut", "bypass", "byway", /*"carrefour", "carref",*/ "chemin", "cercle", "circle", "côte", "crossing", "cross", "expressway", "freeway", "fwy", "line", "link", "l
А могли бы храниться как std::u32string_view

2022-07-30 14:36 UTC, biodranik commented on map/search_mark.hpp
> +  SearchMarkType m_type{};
Нифига не очевидно, это же enum. Напиши лучше явно 
```suggestion
  SearchMarkType m_type = SearchMarkType::Default;
```

2022-07-30 14:40 UTC, biodranik commented on search/ranking_utils.cpp
> +      for (char const * s : {"a", "de", "di", "da", "la", "le", "де", "ди", "да", "ла", "ля", "ле"})
1. Были всегда понятно, по какому принципу их кто-то нагенерил когда-то давно?
2. Так разве это правильно? Вообще, я сомневаюсь, что надо такие стопворды в поиске применять. Если пользователь вбивает артикль, значит он уверен, что этот артикль нужен в названии, и нам надо его матчить. Да, приоритет может понизить, если плохо работает.

2022-07-30 14:41 UTC, biodranik commented on search/ranking_utils.cpp
> +    set<UniString> m_set;
Скорее всего нормализацию можно сделать compile-time constexpr при желании )

2022-07-30 16:47 UTC, vng commented on indexer/search_string_utils.cpp
> +      "allee", "alley", "autoroute", "aut", "bypass", "byway", /*"carrefour", "carref",*/ "chemin", "cercle", "circle", "côte", "crossing", "cross", "expressway", "freeway", "fwy", "line", "link", "l
Там все равно вызовается нормализация. Ну нет тут практической выгоды

2022-07-30 16:48 UTC, vng commented on map/search_mark.hpp
> +  SearchMarkType m_type{};
enum определяется в cpp

2022-07-30 16:50 UTC, vng commented on search/ranking_utils.cpp
> +      for (char const * s : {"a", "de", "di", "da", "la", "le", "де", "ди", "да", "ла", "ля", "ле"})
Это можно экспериментировать потом. Но вообще логика скипания stopword в поиске вполне стандартная.

2022-07-30 16:50 UTC, vng commented on search/ranking_utils.cpp
> +    set<UniString> m_set;
Вот так жизнь зря и проходит в войне с мельницами :)

2022-07-30 20:50 UTC, biodranik commented on search/ranking_utils.cpp
> +    set<UniString> m_set;
Кто-то интегралы считал шаблонами во время компиляции, когда constexpr ещё не было )

2022-07-30 23:04 UTC, biodranik commented on search/pre_ranker.cpp
> +  filtered.insert(iBeg, iMiddle);
Тут получается всего 3*iMiddle*2 копирований (мув в конце на самом деле копирует, там нечего мувать).
Если в сете будут не сами результаты, а указатели на vector результатов, то копирований будет в два раза меньше.

2022-07-30 23:07 UTC, biodranik reviewed
Если реально фиксятся ишью по ссылкам в описании, поправь его сразу чтобы там было Fixes #xxx

2022-07-31 03:07 UTC, vng commented on search/pre_ranker.cpp
>    set<PreRankerResult, LessFeatureID> filtered;
не могу сказать определенно, по комментам звучит разумно, потом можно экспериментировать

2022-07-31 03:16 UTC, vng commented on search/pre_ranker.cpp
> +  filtered.insert(iBeg, iMiddle);
- nth_element переорганизует порядок, просто на указатели не перепишешь
- если очень хочется повыжимать спичек, можно оставить на потом, будешь играться :) там больше копирований в nth_element

2022-07-31 03:17 UTC, vng commented
Они фиксятся, но я не хочу чтобы issues автоматом (наверное?), это для меня самого потом написание тестов

2022-07-31 03:19 UTC, vng commented on search/pre_ranker.cpp
> +  filtered.insert(iBeg, iMiddle);
можно попробовать хранить только feature id в set

2022-07-31 05:53 UTC, vng commented on search/pre_ranker.cpp
>    set<PreRankerResult, LessFeatureID> filtered;
Другое дело, что там идет шаффл для результатов, которые _точно_ равны по расстоянию. Врядли мы будем иметь хоть несколько результатов, которые double: distM1 == distM2

Если уж делать, то для интервала с каким-то допуском ..

2022-07-31 06:33 UTC, vng commented on search/pre_ranker.cpp
> +  filtered.insert(iBeg, iMiddle);
Вот что получилось: https://github.com/organicmaps/organicmaps/pull/3035/commits/2bca386ce39ca512ec094d4a81c75705dd4e97d9

2022-07-31 08:34 UTC, biodranik commented on search/pre_ranker.cpp
>    set<PreRankerResult, LessFeatureID> filtered;
О, видишь, а я это недоглядел. Конечно надо поправить. Давай попробуем может вообще без этого шафла?

2022-07-31 08:35 UTC, biodranik commented on search/pre_ranker.cpp
> +  filtered.insert(iBeg, iMiddle);
Выглядит вроде норм, юнит тест бы мелкий.

2022-07-31 08:53 UTC, vng commented on search/pre_ranker.cpp
> +  filtered.insert(iBeg, iMiddle);
Он есть, там небольшой вопрос по порядку исходных элементов nth_element ибо в этом искусственном тесте генерятся куча пои с уже _одинаковым_ расстоянием :)

2022-07-31 08:54 UTC, vng commented on search/pre_ranker.cpp
>    set<PreRankerResult, LessFeatureID> filtered;
Я уже добавил правки с ассертом в Review fixes комит.

2022-08-01 22:50 UTC, biodranik reviewed
Ох накодякал... Будет быстрее если правки поверх накинешь, и перед мержем сольёшь.
Почти готово, надо только погонять на девайсе перед мержем.

2022-08-01 22:50 UTC, biodranik commented on indexer/feature_data.cpp
> -using namespace std::placeholders;
Креатор ещё и неюзаемые неймспейсы детектит?

2022-08-01 22:50 UTC, biodranik commented on search/intermediate_result.cpp
> +    base::StringIL arr[] = {
const?

2022-08-01 22:50 UTC, biodranik commented on search/pre_ranker.cpp
> +  CompT m_cmp;
const &

2022-08-01 22:50 UTC, biodranik commented on search/pre_ranker.cpp
> +                                 2 * kPedestrianRadiusMeters;
Не заметил вторую скобку в конце.

```suggestion
    comparator.m_detailedScale = 2 * kPedestrianRadiusMeters >
        mercator::DistanceOnEarth(m_params.m_viewport.LeftTop(), m_params.m_viewport.RightBottom());
```

2022-08-01 22:50 UTC, biodranik commented on search/pre_ranker.cpp
> +    m_currEmit.insert(result.GetId());
Если порядок айдишников не важен, то конечно замени на unordered.

2022-08-01 22:50 UTC, biodranik commented on search/pre_ranking_info.hpp
> +  // True iff all tokens retrieved from search index were matched without misprints.
Я вот твои iff не понимаю. Чем бы отличался смысл, если бы тут была одна буква f?

2022-08-01 22:50 UTC, biodranik commented on search/query_params.cpp
> +  static AdditionalCommonTokens s_addCommonTokens;
const

2022-08-01 22:50 UTC, biodranik commented on search/query_params.cpp
> +  static AdditionalCommonTokens s_addCommonTokens;
Что-то ты часто стал пропускать. А тут будет много оверхеда без const.

2022-08-01 22:50 UTC, biodranik commented on search/ranking_info.cpp
> +      CHECK_NOT_EQUAL(m_classifType.poi, PoiType::Count, ());
ASSERT не прокатит?

2022-08-01 22:50 UTC, biodranik commented on search/ranking_info.hpp
> +  // Do not change this constant, it uses to normalize distance and playing with distance factor rank.
```suggestion
  // Do not change this constant, it is used to normalize distance and for playing with distance factor rank.
```

2022-08-01 22:50 UTC, biodranik commented on search/ranking_info.hpp
> +  bool m_pureCats : 1;
фыркающие коты )

2022-08-02 03:15 UTC, vng commented on search/pre_ranker.cpp
> +  CompT m_cmp;
нет

2022-08-02 03:17 UTC, vng commented on search/pre_ranker.cpp
> +                                 2 * kPedestrianRadiusMeters;
тут не понял

2022-08-02 03:17 UTC, vng commented on search/pre_ranking_info.hpp
> +  // True iff all tokens retrieved from search index were matched without misprints.
Эти комменты были и писались не мной

2022-08-02 03:19 UTC, vng commented on search/query_params.cpp
> +  static AdditionalCommonTokens s_addCommonTokens;
- это ты стал придираться где не надо :)
- const чисто семантическая штука, никакой разницы для кода нет

2022-08-02 03:20 UTC, vng commented on indexer/feature_data.cpp
> -using namespace std::placeholders;
нет

2022-08-02 03:34 UTC, vng commented on search/ranking_info.cpp
> +      CHECK_NOT_EQUAL(m_classifType.poi, PoiType::Count, ());
assert и check разница понятна, выбор всегда на "а чего хотим"

2022-08-02 04:22 UTC, vng commented on search/pre_ranking_info.hpp
> +  // True iff all tokens retrieved from search index were matched without misprints.
unordered просто заменить не получится, иначе заменил бы уже
там надо придумывать hash для FeatureID

2022-08-02 05:30 UTC, vng commented on search/ranking_info.hpp
> +  bool m_pureCats : 1;
отличная пасхалочка :)

2022-08-02 06:54 UTC, biodranik approved these changes
Хэш точно будет так эффективнее, чем сет ранее?

2022-08-02 06:54 UTC, biodranik commented on search/pre_ranker.cpp
> +                                 2 * kPedestrianRadiusMeters;
Кривое форматирование было.

2022-08-02 06:59 UTC, vng commented
В целом unordered эффективнее чем set на _не очень_ маленьких размерах. Несмотря на _вроде-бы тяжелый_ hash, лучше он чем алоцировать память на каждую ноду. Не говоря уже про сложность.

2022-08-02 07:04 UTC, biodranik commented on search/query_params.cpp
> +  static AdditionalCommonTokens s_addCommonTokens;
Хм, в этом кейзе нет. Но const важен для чтения кода.

2022-08-03 10:38 UTC, biodranik approved these changes
Ты запускаешь интеграционные тесты перед каждым новым релизом данных?

2022-08-03 10:38 UTC, biodranik commented on search/ranking_info.cpp
> +    // when we're looking for a "cafe", cafes "Cafe Pushkin" and
Мы умеем отличать `cafe` от `cafe `? Во втором случае юзер вполне может ожидать Cafe Pushkin.

2022-08-03 10:38 UTC, biodranik commented on search/ranking_info.cpp
> +    // Its better for ranking when POIs would be equal by name score. Some examples:
It's

2022-08-03 10:38 UTC, biodranik commented on search/ranking_info.cpp
> +    // The reason behind that is that user usually does search for _any_ shop within some commercial network.
А мы можем вываливать какие-то специальные подсказки/саджесты для юзера, когда наматчит и того и того, чтобы например уточнить, он ищет только категории (все магазины), или по названию (конкретные имена пои, не обязательно магазины)?

2022-08-03 10:38 UTC, biodranik commented on search/search_quality/search_quality_tests/real_mwm_tests.cpp
> +    std::vector<uint32_t> res;
С++17 умеет тут auto? Или только если выше, в функции?

2022-08-03 10:49 UTC, vng commented on search/ranking_info.cpp
> +    // when we're looking for a "cafe", cafes "Cafe Pushkin" and
Это не мой коммент, тут остается без изменений.

2022-08-03 10:53 UTC, vng commented on search/ranking_info.cpp
> +    // The reason behind that is that user usually does search for _any_ shop within some commercial network.
Здесь не про это. Тут все магазины, но без фикса по запросу "rewe", магазин "REWE City" будет далеко внизу даже если он рядом, потому что все забьет _точный_ матчинг из магазинов с именем "REWE".

2022-08-03 10:54 UTC, vng commented on search/search_quality/search_quality_tests/real_mwm_tests.cpp
> +    std::vector<uint32_t> res;
auto res; И выводит тип из конструкции return? Сомневаюсь :)

2022-08-03 10:56 UTC, vng commented
Я тесты только добавил и буду запускать каким-то скриптом после генерации данных вместе с routing_integration_tests.

2022-08-03 14:38 UTC, merged

2022-08-03 20:25 UTC, biodranik commented on search/search_quality/search_quality_tests/real_mwm_tests.cpp
> +    std::vector<uint32_t> res;
Да, только наоборот можно.