New versioning scheme - WIP
organicmaps/organicmaps pull request #309
Opened 2021-04-11 05:42 UTC by rtsisyk

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2021-04-11 09:50 UTC, biodranik commented on .github/workflows/android-beta.yaml
>             # Sic: Firebase App Distribution doesn't support splits
Коммент нужен?

2021-04-11 09:51 UTC, biodranik commented on android/build.gradle
> +  def cal = Calendar.getInstance(Locale.ENGLISH);
Нет, надо дата последнего коммита в гите, + его короткий хеш или таки минуты/номер коммита в этот день по порядку, если несколько сборок в один день.

2021-04-11 09:52 UTC, biodranik commented on android/build.gradle
> +          apkPath = "./build/outputs/apk/" + appName + "-" + defaultConfig.versionCode + "-web-arm64-v8a-beta.apk"
Мы апк со всеми архитектурами не собираем больше?

2021-04-11 09:53 UTC, rtsisyk commented
Да.

Что думаешь про саму схему?

On Sun, 11 Apr 2021, 12:50 Alexander Borsuk, ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In .github/workflows/android-beta.yaml
> <https://github.com/organicmaps/organicmaps/pull/309#discussion_r611161613>
> :
>
> > @@ -107,5 +106,4 @@ jobs:
>
>          run: |
>
>             git --no-pager show -s --format='%s%n%n%b' HEAD > RELEASE
>
>             # Sic: Firebase App Distribution doesn't support splits
>
>
> Коммент нужен?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/organicmaps/organicmaps/pull/309#pullrequestreview-632993430>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANXHDS2RHWF2SWDMBVEGBTTIFWIDANCNFSM42XJCJPQ>
> .
>

2021-04-11 09:55 UTC, rtsisyk commented on android/build.gradle
> +          apkPath = "./build/outputs/apk/" + appName + "-" + defaultConfig.versionCode + "-web-arm64-v8a-beta.apk"
Для AppDistribution нет. Там только одну можно загружать..  Для маркета собираем bundle (.aab) со всеми, а дальше маркет уже каждому конкретному юзеру делает кастомную упаковку под его девайс.

2021-04-11 09:55 UTC, rtsisyk commented on android/build.gradle
> +  def cal = Calendar.getInstance(Locale.ENGLISH);
С цифрами что делать? Там маловато, не влазит.

2021-04-11 09:56 UTC, biodranik commented on android/build.gradle
> +          apkPath = "./build/outputs/apk/" + appName + "-" + defaultConfig.versionCode + "-web-arm64-v8a-beta.apk"
Так можно же в одну apk всунуть сразу все архитектуры, и вопрос закрыт.

2021-04-11 10:01 UTC, biodranik commented on android/build.gradle
> +  def cal = Calendar.getInstance(Locale.ENGLISH);
Давай упрощать тогда. Цифрой версии может быть номер коммита на бранче с начала (типа `git rev-list --count HEAD`). А в тексте будем нормальную версию писать YYMMDD-<краткий хэш>.

2021-04-11 14:22 UTC, rtsisyk commented on .github/workflows/android-beta.yaml
>             # Sic: Firebase App Distribution doesn't support splits
Перемещую в другое место ниже.

2021-04-11 14:23 UTC, rtsisyk commented on android/build.gradle
> +  def cal = Calendar.getInstance(Locale.ENGLISH);
Максимальное число - 21_00_00_00_00. Тут 2, максимум 3 цифры под инкрементальный номер.

2021-04-11 14:24 UTC, rtsisyk commented on android/build.gradle
> +          apkPath = "./build/outputs/apk/" + appName + "-" + defaultConfig.versionCode + "-web-arm64-v8a-beta.apk"
Раньше получалась APK на 120 мегабайт, которая устанавливалась через раз. В маркете лимит на 100 мегабайт, руками можно ставить больше, но у меня такие большие через раз работали.

2021-04-12 17:25 UTC, biodranik commented on android/build.gradle
> +  def cal = Calendar.getInstance(Locale.ENGLISH);
Думаешь, мы в день настрочим >99 коммитов?

2021-04-12 17:26 UTC, biodranik commented on android/build.gradle
> +          apkPath = "./build/outputs/apk/" + appName + "-" + defaultConfig.versionCode + "-web-arm64-v8a-beta.apk"
Погоди, в маркет мы отправляем bundle. А для всех остальных надо единую apk сделать с как минимум двумя архитектурами (x86 девайсы вроде не популярны уже?)

2021-04-23 20:35 UTC, biodranik requested changes

2021-04-23 20:35 UTC, biodranik commented on .github/workflows/android-beta.yaml
> +        description: 'THe release notes'
The

2021-04-23 20:35 UTC, biodranik commented on .github/workflows/android-beta.yaml
> +          ./gradlew -x lint -x lintVitalWebBeta assembleWebBeta uploadCrashlyticsSymbolFileWebBeta
А гугловая версия не тут собирается?

2021-04-23 20:35 UTC, biodranik commented on android/build.gradle
> +  def increment = Integer.parseInt(run(['git', 'rev-list', '--after="0:00"', '--all', '--count']).trim())
У меня 0:00 выдаёт много старых коммитов, для сегодня видимо надо другой подход (и чтобы в UTC было).

2021-04-23 20:35 UTC, biodranik commented on android/build.gradle
> +  assert increment >= 0 && increment < 100 // No more than 100 commits per day!
Можно пробовать брать остаток от деления на 100, тогда будет собираться, и не так много вариантов будет коммитов, куда смотреть )

2021-04-23 20:35 UTC, biodranik commented on android/build.gradle
> +  def day = cal.get(Calendar.DAY_OF_MONTH);
Дата нужна последнего коммита, с которого собирается.

2021-04-23 20:35 UTC, biodranik commented on android/build.gradle
> +  // - XX - the number of commits today
Эта штука по большому нужна только когда мы будем пушить больше одного релиза в сутки. Это редкий кейз, возможно, на такой случай можно предусмотреть какое-то простое ручное решение? Типа передать при сборке какой-то ключ?

2021-04-23 20:35 UTC, biodranik commented on android/build.gradle
> +project.ext.appName = 'OrganicMaps'
Поищи в проекте ещё где поменять, в отдельном PR.

2021-04-24 06:39 UTC, rtsisyk commented on .github/workflows/android-beta.yaml
> +          ./gradlew -x lint -x lintVitalWebBeta assembleWebBeta uploadCrashlyticsSymbolFileWebBeta
Гугловую для стора руками собираем:

```
./gradlew assembleGoogleRelease bundleGoogleRelease
```

------------------------

Давай обсудим отдельно что делать с applicationId. Гугл просит всех перейти на bundle. В случае bundle сам стор компонует уменьшенные версии под конкретный девайс и сам подписывает эти APK. В таком раскладе в Google Play всё подписано гугловым ключем, доступа к которому мы не имеем. Если же я соберу app.omaps вручную и попробую поставить, то будет облом из-за несоответствия ключей. Завтра в самсунге решат тоже подписывать и т.п. Есть предложение добавить в applicationId название стора, чтобы не было пересечения.

2021-04-24 06:41 UTC, rtsisyk commented on .github/workflows/android-beta.yaml
> +          ./gradlew -x lint -x lintVitalWebBeta assembleWebBeta uploadCrashlyticsSymbolFileWebBeta
Вообщем я предлагаю убрать там матрицу flavor + buildType и оставить только одно изменение:

app.omaps - гугл релиз = googleRelease сейчас
app.omaps.debug = googleDebug сейчас
app.omaps.appdistribution - бета через firebase app distribution = googleBeta сейчас
app.omaps.samsung - самсунг релиз = samsungRelease
app.omaps.huawey - самсунг = huaweiRelease
app.omaps.fdroid - fdroid релиз = fdroidRelease

2021-04-24 06:42 UTC, rtsisyk commented on android/build.gradle
> +  def increment = Integer.parseInt(run(['git', 'rev-list', '--after="0:00"', '--all', '--count']).trim())
Идеи?

2021-04-24 06:43 UTC, rtsisyk commented on android/build.gradle
> +  def day = cal.get(Calendar.DAY_OF_MONTH);
Я это переделал это, посмотри новую версию.

2021-04-24 06:44 UTC, rtsisyk commented on android/build.gradle
> +  // - XX - the number of commits today
Предлагаешь убрать инкремент совсем?

2021-04-24 06:44 UTC, rtsisyk commented on android/build.gradle
> +project.ext.appName = 'OrganicMaps'
Ага, давай отдельно это всё переименуем. Кстати без пробела стрёмно смотрится.

2021-04-24 06:45 UTC, rtsisyk commented
- 21042401 - version code
- 2021.04.24-1-gae0bcb54f9-Google - version name

2021-04-24 06:45 UTC, rtsisyk commented on android/build.gradle
> +  assert increment >= 0 && increment < 100 // No more than 100 commits per day!
Так и было раньше =)

2021-04-24 08:37 UTC, biodranik commented on .github/workflows/android-beta.yaml
> +          ./gradlew -x lint -x lintVitalWebBeta assembleWebBeta uploadCrashlyticsSymbolFileWebBeta
Я не против, но для поисковиков нам гораздо важнее переименовать в app.organicmaps

2021-04-24 08:38 UTC, biodranik commented on .github/workflows/android-beta.yaml
> +          ./gradlew -x lint -x lintVitalWebBeta assembleWebBeta uploadCrashlyticsSymbolFileWebBeta
и с гуглом лучше app.organicmaps.google и app.organicmaps.google.debug
плюс ещё чистая версия без ничего app.organicmaps app.organicmaps.debug
(тогда fdroid не надо будет, там будет обычная чистая apk)

2021-04-24 08:40 UTC, biodranik commented on .github/workflows/android-beta.yaml
> +          ./gradlew -x lint -x lintVitalWebBeta assembleWebBeta uploadCrashlyticsSymbolFileWebBeta
без дебаг-релиз флейворов может быть сложнее отлаживать какие-то отдельные версии потом, но их наверное можно будет вручную добавить по надобности.

2021-04-24 08:40 UTC, biodranik commented on android/build.gradle
> +  assert increment >= 0 && increment < 100 // No more than 100 commits per day!
кул )

2021-04-24 08:40 UTC, biodranik commented on android/build.gradle
> +  // - XX - the number of commits today
Если у тебя есть идеи, как вручную потом это обойти, тогда да, можно убрать.

2021-04-24 08:41 UTC, biodranik commented on android/build.gradle
> +project.ext.appName = 'OrganicMaps'
нормально, и ищется хорошо )

2021-04-24 11:05 UTC, rtsisyk commented on android/build.gradle
> +  assert increment >= 0 && increment < 100 // No more than 100 commits per day!
Так что делать тут? Задавать инкремент вручную?

2021-04-24 12:35 UTC, rtsisyk commented on android/build.gradle
> +project.ext.appName = 'OrganicMaps'
я этот кусок удалил из патча, запустим sed потом.

2021-04-24 20:02 UTC, merged