WIP: Removed everything.
organicmaps/organicmaps pull request #311
Opened 2021-04-11 23:43 UTC by biodranik

2021-04-13 05:38 UTC, vng commented
Вылет при нажатии на кнопку роутинга (справа от поиска):
```
[NSBundle.mainBundle loadNibNamed:kRoutePreviewIPhoneXibName owner:self options:nil];
```

2021-04-17 14:35 UTC, biodranik commented on android/jni/com/mapswithme/maps/UserMarkHelper.cpp
> +  jni::TScopedLocalRef jServerId(env, jni::ToJavaString(env, ""));
TODO: выкосить

2021-04-17 14:42 UTC, biodranik commented on android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
> +  jni::TScopedLocalRef serverIdRef(env, jni::ToJavaString(env, ""));
TODO: выпилить

2021-04-17 14:45 UTC, biodranik commented on android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
> -Java_com_mapswithme_maps_bookmarks_data_BookmarkManager_nativeAreAllCategoriesInvisible(
Вернуть это и ниже, это валидные методы. Может поэтому не отображаются закладки. Категории не имеют отношения к гайдам, категориями у нас называются сеты букмарок.

2021-04-17 15:55 UTC, biodranik commented on android/res/layout-sw600dp-land/info_page.xml
> -<?xml version="1.0" encoding="utf-8"?>
Эти info_page точно не нужны? Вроде в пермишн диалогах использовались?

2021-04-17 16:22 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
>    private static final int REQ_CODE_SHOW_SIMILAR_HOTELS = 3;
Выпилить

2021-04-17 16:22 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    BookmarkCategoriesActivity.start(this);
Почему именно start?

2021-04-17 16:27 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> -               NativeSearchListener,
Это точно ненужный листенер?

2021-04-17 16:34 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> -  private boolean showBookmarkCategory(@NonNull BookmarkCategory category)
Вернуть, это кошерный метод.

2021-04-17 16:49 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> -  private boolean showBookmarkCategory(@NonNull BookmarkCategory category)
А нет, я не прав, надо будет выпилить и потроха тоже.

2021-04-17 16:50 UTC, rtsisyk commented on android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
> -Java_com_mapswithme_maps_bookmarks_data_BookmarkManager_nativeAreAllCategoriesInvisible(
Это вернул.

2021-04-17 16:51 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    BookmarkCategoriesActivity.start(this);
Раньше был кейс, когда из MwmActivity запускалась BookmarkCategoriesActivity для скачивания каталога букмарков. Для этого использовался startForResult. Кажется, что сейчас там ничего скачивать не надо.

2021-04-18 08:41 UTC, vng requested changes

2021-04-18 08:41 UTC, vng commented on android/src/com/mapswithme/maps/MwmActivity.java
> -    mSearchController.closeBottomMenu();
Это тоже hotel специфик?

2021-04-18 08:41 UTC, vng commented on android/src/com/mapswithme/maps/MwmActivity.java
> -      return;
отель - специфик ?

2021-04-18 08:41 UTC, vng commented on android/src/com/mapswithme/maps/bookmarks/BookmarkHeaderView.java
> +    /*
Хм, так все таки category - это не список букмарок ?! Или черт ногу сломит ..

2021-04-18 08:41 UTC, vng commented on android/src/com/mapswithme/maps/bookmarks/Holders.java
>      private static class ToggleShowAllChildCategoryClickListener implements View.OnClickListener
Непонятна откуда тут show all childs. Список букмарок линейный, наверное это тоже надо вырезать ..

2021-04-18 08:41 UTC, vng commented on android/src/com/mapswithme/maps/intent/Factory.java
> -  public static class ShowTutorialTask implements MapTask
Это нам не понадобится?

2021-04-18 08:41 UTC, vng commented on android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
> -  public void turnOffCurrentView()
Это не надо? Это разве не кнопка выключения изолиний или метро?

2021-04-18 08:41 UTC, vng commented on android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
> -                                                      @NonNull View.OnClickListener dialogClickListener)
А кто раньше был листенером сигналов и почему сейчас это не надо?

2021-04-18 08:41 UTC, vng commented on android/src/com/mapswithme/maps/search/SearchFragment.java
> -      public void onShowOnMapClick()
Опять вот тут сомнения ..

2021-04-18 08:41 UTC, vng commented on android/src/com/mapswithme/maps/widget/menu/MainMenu.java
> -  public void updateMarker()
А что это за маркер?

2021-04-18 08:41 UTC, vng commented on android/src/com/mapswithme/maps/widget/placepage/Sponsored.java
>  public final class Sponsored
Удалить полностью весь модуль?

2021-04-18 08:41 UTC, vng commented on android/src/com/mapswithme/util/SharedPropertiesUtils.java
> -  private static final String USER_AGREEMENT_PRIVACY_POLICY = "user_agreement_privacy_policy";
Точно нам не надо?

2021-04-18 08:43 UTC, vng commented on android/src/com/mapswithme/maps/MwmActivity.java
> -  private boolean showBookmarkCategory(@NonNull BookmarkCategory category)
Тут большой вопрос. Видимо "category" стал гибридным. Это и что-то скачиваемое - что надо удалить, и текущий список букмарок - что надо оставить.

2021-04-18 09:07 UTC, vng commented
iOS вылет при удалении списка букмарок:
Exception	NSException *	"Tried to pop to a view controller that doesn't exist."	0x00000002836860a0
```
extension BMCViewController: BookmarksListDelegate {
  func bookmarksListDidDeleteGroup() {
    guard let parentVC = parent else { return }
    navigationController?.popToViewController(parentVC, animated: true)
  }
}
```

2021-04-18 10:33 UTC, rtsisyk commented on android/AndroidManifest.xml
> -      android:label="@string/description_guide"/>
Ты прав. Восстановил под именем BookmarkCategorySettingsActivity, вычистив всё, кроме имени и описания.

2021-04-18 10:34 UTC, rtsisyk commented on android/jni/CMakeLists.txt
> +  com/mapswithme/core/ScopedLocalRef.hpp
Случайно, удалил.

2021-04-18 10:34 UTC, rtsisyk commented on android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
>  }
Я не понял что такое child, но такой фичи я никогда в приложении не видел.

2021-04-18 10:35 UTC, rtsisyk commented on android/src/com/mapswithme/maps/Framework.java
>    public static final int ROUTER_TYPE_TRANSIT = 4;
ОК

2021-04-18 10:40 UTC, rtsisyk commented on android/src/com/mapswithme/maps/widget/placepage/Sponsored.java
>  public final class Sponsored
Так точно. Оставались какие-то артефакты, которые мешали удалить этот файл. Вычистил.

2021-04-18 10:41 UTC, rtsisyk commented on android/src/com/mapswithme/util/SharedPropertiesUtils.java
> -  private static final String USER_AGREEMENT_PRIVACY_POLICY = "user_agreement_privacy_policy";
Я вынес эти стартовые экраны еще месяц назад... :)
Если вдруг кому-то они будут нужны, вернем назад.

2021-04-18 10:42 UTC, rtsisyk commented on android/src/com/mapswithme/maps/widget/menu/MainMenu.java
> -  public void updateMarker()
Черт знает, но выглядит подозрительно и надо разбираться.

2021-04-18 10:58 UTC, rtsisyk commented
@biodranik 

Вот это еще вычисти из категорий букмарков плз:

 authorIdRef.get(),
authorNameRef.get(),
data.m_accessRules
manager.IsMyCategory(data.m_id)

2021-04-18 13:40 UTC, vng commented
Android:
- Delete List не работает из вьюшки Категории
- ПОсле переименования категории и возврата на предидущую вьюшку, вверху еще рисуется старое имя

2021-04-20 05:10 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> -  private boolean showBookmarkCategory(@NonNull BookmarkCategory category)
Я починил.

2021-04-20 05:27 UTC, rtsisyk commented on android/src/com/mapswithme/maps/maplayer/MapLayerCompositeController.java
> -                                                      @NonNull View.OnClickListener dialogClickListener)
Да, тут действительно удалил полезный обработчик. Спасибо за внимательность!

2021-04-20 07:41 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> -               NativeSearchListener,
Он использовался чтобы скрывать кнопки букинга при получении результата. Нет кнопок - нет проблем.

2021-04-20 16:24 UTC, vng requested changes

2021-04-20 16:24 UTC, vng commented on android/src/com/mapswithme/maps/search/SearchFragment.java
> -    fadeView.setListener(this::onFadeViewTouch);
1. Почему это удалено?

2021-04-20 16:24 UTC, vng commented on android/src/com/mapswithme/maps/search/SearchFragment.java
> -  private boolean onFadeViewTouch()
2. Почему это удалено?

Это случаем не кнопка на карте внизу, в режиме интерактивного поиска?

2021-04-20 16:24 UTC, vng commented on android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
> -    mPlacePage.attach(activity);
Почему здесь и ниже это убрано?

2021-04-20 16:28 UTC, rtsisyk commented on android/src/com/mapswithme/maps/search/SearchFragment.java
> -  private boolean onFadeViewTouch()
Это она. Только onFadeTouch ничего не делал после удаления фильтров букинга. Поэтому и удалил.

2021-04-20 16:28 UTC, rtsisyk commented on android/src/com/mapswithme/maps/search/SearchFragment.java
> -    fadeView.setListener(this::onFadeViewTouch);
Смотри ниже.

2021-04-21 05:28 UTC, rtsisyk commented on android/res/layout-sw600dp-land/info_page.xml
> -<?xml version="1.0" encoding="utf-8"?>
Они были в пермишен диалогах, но а пермишен диалоги я выпилил уже давно :)

2021-04-21 05:31 UTC, rtsisyk commented on android/jni/com/mapswithme/maps/Framework.cpp
> -}
Оно вызывалось из единственного места - handleDownloadedCategoryResult(), который вызывался из handleDiscoveryResult()

2021-04-21 05:31 UTC, rtsisyk commented on android/src/com/mapswithme/maps/search/SearchFragment.java
> -      public void onShowOnMapClick()
Я это вчера восстановил.

2021-04-21 05:36 UTC, rtsisyk commented on android/src/com/mapswithme/maps/widget/menu/MainMenu.java
> -  public void updateMarker()
Это использовалось, чтобы сообщать новости о новой версии. Пока я выпилил эти news совсем, но предлагаю попробовать потом восстановить точечно.

2021-04-21 05:46 UTC, rtsisyk commented on android/res/layout/item_search_result.xml
> -      android:layout_toStartOf="@id/cost"
Я вернул назад cost, т.к. там всё равно нужен какой-то placeholder для выравнивания.

2021-04-21 05:49 UTC, rtsisyk commented on android/res/layout/place_page_details.xml
> -    <include layout="@layout/place_page_more"/>
Единственное, для чего там это использовалось, был букинг:

```
-    mHotelMore = findViewById(R.id.ll__more);
```

```
-      case R.id.ll__more:
-        onSponsoredClick(false /* book */, true /* isMoreDetails */);
-        break;
```

2021-04-21 05:57 UTC, rtsisyk commented on android/res/layout/place_page_preview.xml
> -    android:layout_below="@id/popular_rating_view"
Починил.

2021-04-21 05:57 UTC, rtsisyk commented on android/res/layout/place_page_preview.xml
> -    android:layout_below="@id/preview_rating_info"
Починил.

2021-04-21 09:24 UTC, vng commented
@biodranik Тестанул iOS iPad:
- вместо description для bookmarks set пишется DESCRIPTION_GUIDE всегда
- не работает кнопка Export из Bookmarks Set view (More -> Export). Показывает какую-то шляпу в виде схлопнутого виджета ..

2021-04-22 05:10 UTC, rtsisyk approved these changes
Let's move on.

2021-04-22 05:11 UTC, merged