[search] Match and rank fixes.
organicmaps/organicmaps pull request #3128
Opened 2022-08-08 12:08 UTC by vng

2022-08-08 21:42 UTC, biodranik approved these changes

2022-08-08 21:42 UTC, biodranik commented on search/search_quality/matcher.cpp
> +  ForEachNormalizedToken(str, [&res](strings::UniString const & token)
Тут разве нельзя && и ниже мув?

2022-08-08 21:42 UTC, biodranik commented on search/search_quality/matcher.cpp
> +  std::vector<std::string> res;
Никаких предикшнов тут для reserve нет?

2022-08-08 21:42 UTC, biodranik commented on search/utils.hpp
> +    if (!locales.Contains(static_cast<uint64_t>(categorySynonym.m_locale)))
Зачем сделано с кастом?

2022-08-09 03:10 UTC, vng commented on generator/search_index_builder.cpp
> +    m_Str = strings::MakeUniString("str");
Без причин, просто оставил как в пред коде.

2022-08-09 03:10 UTC, vng commented on generator/search_index_builder.cpp
> +    m_Strasse = strings::MakeUniString("strasse");
FeatureNameInserter создается один раз, ну и контекст мембера более _узкий_, чем все эти static.

2022-08-09 03:12 UTC, vng commented on generator/search_index_builder.cpp
>        /// @todo Avoid creating temporary std::string.
Не фиксится сейчас, когда завезут расширенный unordered_map

2022-08-09 03:14 UTC, vng commented on indexer/search_string_utils.cpp
> +  ForEachNormalizedToken(s, base::MakeBackInsertFunctor(tokens));
Тут не понял, выпилить NormalizeAndTokenizeString? Я специально фиксил, чтобы клиентский код был чистым.

2022-08-09 03:14 UTC, vng commented on indexer/search_string_utils.cpp
> +  SplitUniString(uniString, base::MakeBackInsertFunctor(tokens), delims);
Вероятно нет, надо посмотреть.

2022-08-09 03:20 UTC, vng commented on indexer/search_string_utils.hpp
> +    // Keep leading hashtag symbol.
Тут я оставил функциональность как было.
Вот есть какие-то концы :) https://github.com/mapsme/omim/pull/3212

2022-08-09 03:22 UTC, vng commented on search/search_quality/matcher.cpp
> +  ForEachNormalizedToken(str, [&res](strings::UniString const & token)
там же нечего мувать, вызывается ToUtf8(token)

2022-08-09 03:22 UTC, vng commented on search/search_quality/matcher.cpp
> +  std::vector<std::string> res;
нет

2022-08-09 03:24 UTC, vng commented on search/utils.hpp
> +    if (!locales.Contains(static_cast<uint64_t>(categorySynonym.m_locale)))
видимо Contains принимает uint64_t

2022-08-09 03:28 UTC, vng commented on generator/search_index_builder.cpp
> +    /// @todo No problem here if we will have duplicating tokens? (POI name like "Step by Step").
Все будет работать, тут больше для меня коммент, потом глубже посмотреть в код, сэкономить спичек возможно.

2022-08-09 06:29 UTC, vng commented on indexer/search_string_utils.hpp
> +    // Keep leading hashtag symbol.
Полагаю, можно порезать со спокойной душой. Или например предполагается по запросу "#osm" матчить только "#osm" и никак не "osm" ?

2022-08-09 10:09 UTC, vng commented
PTAL

2022-08-09 21:59 UTC, biodranik commented on indexer/search_string_utils.cpp
> +  ForEachNormalizedToken(s, base::MakeBackInsertFunctor(tokens));
Выпилить ForEachNormalizedToken

2022-08-09 22:02 UTC, biodranik commented on indexer/search_string_utils.hpp
> +    // Keep leading hashtag symbol.
Хештеги применялись, чтобы искусственно ограничить поиск только категориями. Ты же специально для этого впилил флаг, выставляемый из UI категорий. Думаю можно выпилить, какая польза в такой отладке?

Юзер по хештегу ожидает полный матч, конечно же, иначе смысл вбивать доп. символ?

2022-08-09 22:02 UTC, biodranik commented on indexer/search_string_utils.cpp
> +  SplitUniString(uniString, base::MakeBackInsertFunctor(tokens), delims);
Много где применяются, можно сэкономить аллокаций.

2022-08-09 22:05 UTC, biodranik commented on search/utils.hpp
> +    if (!locales.Contains(static_cast<uint64_t>(categorySynonym.m_locale)))
И там и там вроде локали, странно, что типы разные получились. Может одинаковыми надо сделать вместо кастов?

2022-08-09 22:13 UTC, biodranik requested changes

2022-08-09 22:13 UTC, biodranik commented on qt/search_panel.cpp
> +  //QString const normalized = str.normalized(QString::NormalizationForm_KC);
эээ, зачем?

2022-08-09 22:13 UTC, biodranik commented on base/stl_helpers.hpp
> +  template <class T> void operator()(T && t) const { m_Container.push_back(std::forward<T>(t)); }
А почему тут нельзя было заюзать Container::value_type ?

2022-08-10 03:30 UTC, vng commented on indexer/search_string_utils.cpp
> +  ForEachNormalizedToken(s, base::MakeBackInsertFunctor(tokens));
И она делает код лаконичнее. Что с ней не так? Тут все заинлайнится.

2022-08-10 03:30 UTC, vng commented on indexer/search_string_utils.cpp
> +  SplitUniString(uniString, base::MakeBackInsertFunctor(tokens), delims);
Теперь там есть и move.

2022-08-10 03:32 UTC, vng commented on indexer/search_string_utils.hpp
> +    // Keep leading hashtag symbol.
# будет скипатся как разделитель

2022-08-10 03:33 UTC, vng commented on search/utils.hpp
> +    if (!locales.Contains(static_cast<uint64_t>(categorySynonym.m_locale)))
locales - это обобщенный контейнер

2022-08-10 03:34 UTC, vng commented on qt/search_panel.cpp
> +  //QString const normalized = str.normalized(QString::NormalizationForm_KC);
Я хочу тестить поиск на десктопе как на любой платформе. У нас нет нормализаций входа, кроме как внутри алгоритма. А это начинает мне заменять № на No.

2022-08-10 03:35 UTC, vng commented on base/stl_helpers.hpp
> +  template <class T> void operator()(T && t) const { m_Container.push_back(std::forward<T>(t)); }
Тогда надо было делать 2 перегрузки
(value_type const &)
(value_type &&)
Для этого и существует xvalue ref + forward.

2022-08-10 04:11 UTC, vng commented on qt/search_panel.cpp
> +  //QString const normalized = str.normalized(QString::NormalizationForm_KC);
UPD:
- iOS тоже вызывает бубен precomposedStringWithCompatibilityMapping
- Android передает строку as-is
Это ломает поиск (iOS, NormalizationForm_KC). Надо это убирать и отдавать в ядро строку как передали. Только ядро знает как правильно нормализовать, потому что ядро нормализует строки в построении индекса.

2022-08-10 07:35 UTC, vng commented
@biodranik PTAL last 2 commits.

2022-08-11 12:19 UTC, biodranik commented on indexer/search_string_utils.hpp
> +    // Keep leading hashtag symbol.
?

2022-08-11 12:23 UTC, biodranik commented on qt/search_panel.cpp
> +  //QString const normalized = str.normalized(QString::NormalizationForm_KC);
Тогда надо и в iOS выпилить. И в комментарий это пояснение обязательно добавь.

2022-08-11 12:35 UTC, biodranik approved these changes

2022-08-11 12:35 UTC, biodranik commented on qt/update_dialog.cpp
> +      [this, timestamp](DownloaderSearchResults results)
Тут копирование норм?

2022-08-11 12:35 UTC, biodranik commented on iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
> +    locale.precomposedStringWithCompatibilityMapping.UTF8String,
Тут бы тоже хорошо комментом указать, что за поля инициализируются.

2022-08-11 12:35 UTC, biodranik commented on iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
> +    [completion](storage::DownloaderSearchResults results)
Копирование?

2022-08-11 12:35 UTC, biodranik commented on iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
> +      completion([resultsArray copy], results.m_endMarker);
Зачем тут копирования?

2022-08-11 12:35 UTC, biodranik commented on iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
> +      completion([result copy]);
И тут копия зачем?

2022-08-11 12:35 UTC, biodranik commented on android/jni/com/mapswithme/maps/SearchEngine.cpp
> +  vector<jlong> const tmp(results.cbegin(), results.cend());
А зачем тут копия вектора?

2022-08-11 13:03 UTC, vng commented on qt/update_dialog.cpp
> +      [this, timestamp](DownloaderSearchResults results)
Сюда и в остальные функторы приходит через move. Мы внутри не забираем и не модифицируем, то могу для наглядности оставить const &, но это никак не повлияет.

2022-08-11 13:04 UTC, vng commented on iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
> +    locale.precomposedStringWithCompatibilityMapping.UTF8String,
По названиям же понятно.

2022-08-11 13:06 UTC, vng commented on iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
> +    [completion](storage::DownloaderSearchResults results)
Как говорил выше, поиск в функторы отдает результаты через move. Для наглядности оставлю const &

2022-08-11 13:07 UTC, vng commented on iphone/CoreApi/CoreApi/Framework/MWMFrameworkHelper.mm
> +      completion([resultsArray copy], results.m_endMarker);
Тут так и было, я какие-то ObjC заморочки.

2022-08-11 13:07 UTC, vng commented on iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
> +      completion([result copy]);
Тут так и было, я какие-то ObjC заморочки.

2022-08-11 13:16 UTC, vng commented on indexer/search_string_utils.hpp
> +    // Keep leading hashtag symbol.
при вводе "#osm" фича с именем "osm" тоже будет матчится

2022-08-11 14:00 UTC, vng commented on iphone/CoreApi/CoreApi/Bookmarks/MWMBookmarksManager.mm
> +      completion([result copy]);
Пожалуй, попробую это убрать и посмотреть completition, потому что Core уже отдает результаты как GetPlatform().RunTask(Platform::Thread::Gui, ...);

2022-08-11 15:46 UTC, merged