[drape] Disable Vulkan for Mali-G71.
organicmaps/organicmaps pull request #3162
Opened 2022-08-12 15:07 UTC by vng

2022-08-13 22:13 UTC, biodranik requested changes

2022-08-13 22:13 UTC, biodranik commented on drape/support_manager.cpp
> +      // Samsung Galaxy S8
Там в логах была другая модель. И мы не спрашивали про багу с dashed lines. Там моргала отрисовка маршрута (именно это надо в комменты).

2022-08-13 22:13 UTC, biodranik commented on iphone/Maps/Core/Search/MWMSearch.mm
> +        self.suggestionsCount = results.GetSuggestsCount();
Я тоже это нашёл, прогнав analyzer )

2022-08-13 22:15 UTC, biodranik commented on drape/support_manager.cpp
> +      // Samsung Galaxy S8
Там довольно [много](https://www.phonebunch.com/phone-filter/gpu/mali-g71/page/1/) девайсов... Надо бы тудушку и расковырять, что мы не так используем с этими мали.

2022-08-14 03:32 UTC, vng commented on drape/support_manager.cpp
> +      // Samsung Galaxy S8
- Ну если погуглить samsung SM-G950F (dreamlte) то это именно S8 для азиатского рынка.
- Тут еще блок зависит от версии драйвера, др фиксов у меня нет

2022-08-14 12:17 UTC, biodranik commented on drape/support_manager.cpp
> +      // Samsung Galaxy S8
S8 моделей очень много, с разными чипами. Ты отключаешь одну конкретную, напиши об этом чётко в комменте.

2022-08-14 12:31 UTC, vng commented on drape/support_manager.cpp
> +      // Samsung Galaxy S8
написал

2022-08-14 19:36 UTC, biodranik approved these changes

2022-08-14 19:36 UTC, merged