[iPhone] Side buttons UI fixes
organicmaps/organicmaps pull request #3201
Opened 2022-08-18 09:09 UTC by AntonM030481

Fixes: #3145, #3199.

2022-08-18 16:29 UTC, biodranik requested changes
Not sure if these fixes are working properly in all cases.

2022-08-18 16:29 UTC, biodranik commented on iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
> +    auto availableAreaMaxX = self.availableArea.origin.x + self.availableArea.size.width;
const

2022-08-18 16:29 UTC, biodranik commented on iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
> +    // Visibility should be detemined by alpha, not self.hidden.
Are you sure about it? Alfa means that buttons will be rendered on EACH OpenGL frame rendering. Hidden will exclude buttons completely.

2022-08-18 16:29 UTC, biodranik commented on iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
> +  // More elegant way is to check if x values are changed.
More reliable approach is to recalculate the proper position at the end of the animation. Or disable animation completely. Or animate buttons only with alpha, without changing their positions (so they will be relayout properly on landscape/portrait changes).

2022-08-19 07:18 UTC, AntonM030481 commented on iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
> +    // Visibility should be detemined by alpha, not self.hidden.
В этом весь смысл. Hidden можно и нужно делать только когда кнопка скрылась за экраном.
Во время всей анимации движения hidden должно быть NO, иначе мы не увидим анимацию, или увидим только её часть.

2022-08-19 07:52 UTC, AntonM030481 commented on iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
> +  // More elegant way is to check if x values are changed.
Тут проблема в том, что updateAvailableArea вызывается (в связи с тем, что прячется тулбар внизу) тогда, когда анимация только началась. self.hidden еще имеет старое значение.

2022-08-19 08:33 UTC, AntonM030481 commented
Я проверил все виды кручения для аппаратов с челкой и без.

2022-08-19 08:35 UTC, AntonM030481 commented on iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
> +    // Visibility should be detemined by alpha, not self.hidden.
Тул логика не менялась, просто я немного упростил, убрав лишние if.
Результат один и тот же.

2022-08-19 08:39 UTC, AntonM030481 commented on iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
> +    auto availableAreaMaxX = self.availableArea.origin.x + self.availableArea.size.width;
OK

2022-08-19 12:43 UTC, vng approved these changes
Прекрасно, работает как надо красиво!

2022-08-19 20:34 UTC, biodranik requested changes

2022-08-19 20:34 UTC, biodranik commented on iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
> +    self.availableArea = frame;
Это повторяется в else, надо вынести из if.

2022-08-19 20:36 UTC, biodranik approved these changes

2022-08-19 20:36 UTC, biodranik commented on iphone/Maps/Classes/CustomViews/MapViewControls/SideButtons/MWMSideButtonsView.mm
> +    self.availableArea = frame;
А, вижу, тут сложно будет.

2022-08-19 20:36 UTC, merged