Support downloadable countries.txt
organicmaps/organicmaps pull request #322
Opened 2021-04-20 17:57 UTC by vng

Signed-off-by: vng <viktor.govako@gmail.com>

2021-04-20 21:54 UTC, biodranik commented on storage/map_files_downloader.cpp
> +  m_quarantine.Append(std::move(queuedCountry));
Зачем? Оно не будет ли навеки забиваться в длинном списке?
Кстати, там дубликаты фильтруются?

2021-04-20 21:56 UTC, biodranik commented on storage/map_files_downloader.cpp
> +      // Reset flag to invoke servers list downloading next time if current request was failed.
nit: has failed or failed

2021-04-20 21:59 UTC, biodranik commented on storage/map_files_downloader.cpp
> +  /// @todo Implement logic if m_serversList is "outdated"?
Это что за случай? По идее метасервер будет возвращать списки сервачков.

2021-04-20 22:00 UTC, biodranik commented on storage/map_files_downloader.hpp
> +  /** @brief This method is blocking and should be called on network thread.
Три слеша выглядели лучше…

2021-04-20 22:12 UTC, biodranik commented on storage/storage.cpp
> +    /// @todo Make json parsing like [ {start app version : data version}, ... ].
Для случая, когда надо сначала обновить приложение, а потом качать карты? Тогда лучше в UI оповещать об этом.

2021-04-20 22:12 UTC, biodranik commented on storage/storage.cpp
> +      std::shared_ptr<Storage> storage(new Storage(7 /* dummy */));
dummy?

2021-04-20 22:12 UTC, biodranik commented on storage/storage.cpp
> +      /// @todo Or use simple but reliable strategy: download new file and ask to restart the app?
Так действительно может быть проще. Только не все могут знать, как аппы "прибивать" и перезапускать.
А какие проблемы могут всплыть сейчас?

2021-04-20 22:12 UTC, biodranik commented on storage/storage.cpp
> +  m_affiliations = std::move(storage.m_affiliations);
Может лучше это вынести в operator=(&&)?

2021-04-21 05:53 UTC, vng commented on storage/map_files_downloader.cpp
> +  /// @todo Implement logic if m_serversList is "outdated"?
Сейчас мы забираем список url только один раз при первом обращении. Пришла мысль, что со временем ситуация меняется и было бы неплохо по какому-то критерию "пересчитывать" список урлов.

2021-04-21 05:53 UTC, vng commented on storage/storage.cpp
> +    /// @todo Make json parsing like [ {start app version : data version}, ... ].
Оно наверное как-то будет и в UI, но ядро должно быть безопасным в этом контексте. Тут будет json, который говорит начиная с какой версии аппы подходят те или иные данные. Чтобы если у кого старая версия, все в один момент не сломалось ..

2021-04-21 05:53 UTC, vng commented on storage/storage.cpp
> +      std::shared_ptr<Storage> storage(new Storage(7 /* dummy */));
Да, явно указываем что мы зовем приватный Storage(int) ctor здесь, который просто ничего не делает.

2021-04-21 05:53 UTC, vng commented on storage/storage.cpp
> +      /// @todo Or use simple but reliable strategy: download new file and ask to restart the app?
Я потому и написал коммент, что это не совсем удобный, но самый безопасный путь. Сейчас же я буду идти по пути подмены "на лету". Так как у нас Storage обладаем большим числом состояний (а countries грузились только на старте), проблемы могут вылезать со всех сторон, где сразу и не угадаешь. Будем реализовывать и смотреть. Может получится избавиться от многих состояний ..

2021-04-21 05:53 UTC, vng commented on storage/storage.cpp
> +  m_affiliations = std::move(storage.m_affiliations);
Не совсем понял, тут и вызывается operator=(&&) для vector или map

2021-04-21 10:28 UTC, biodranik commented on storage/storage.cpp
> +  m_affiliations = std::move(storage.m_affiliations);
Обернуть эти мувы в оператор стораджа, потом может ещё какие мемберы добавятся.

2021-04-21 20:42 UTC, vng commented on storage/storage.cpp
> +  m_affiliations = std::move(storage.m_affiliations);
Собственно, функция Storage::ApplyCountries и есть эта самая обертка, непонятно зачем еще что-то ..
Тут важно что мы муваем не все состояние, а только зависимое от countries.txt

2021-04-27 17:22 UTC, biodranik requested changes

2021-04-27 17:22 UTC, biodranik commented on iphone/Maps/UI/Editor/MWMEditorViewController.mm
> +    self.offscreenCells[(id)cls] = cell;
WTF? Там же Class в дикшнари, что за ошибка компиляции?

2021-04-27 17:22 UTC, biodranik commented on storage/background_downloading/downloader_adapter_ios.mm
>  BackgroundDownloaderAdapter::BackgroundDownloaderAdapter()
= default ?

2021-04-27 17:22 UTC, biodranik commented on storage/country_tree.cpp
> +    LOG(LWARNING, (e.Msg()));
По LERROR свалится дебаг, это же предпочтительное поведение. Зачем ворнинг?

2021-04-27 17:22 UTC, biodranik commented on storage/http_map_files_downloader.cpp
> +  if (m_queue.Count() == 1)
Если больше 1 то видимо загрузка уже идёт, не надо её стартовать опять.

2021-04-27 17:22 UTC, biodranik commented on storage/http_map_files_downloader.cpp
> -      subscriber->OnFinishDownloading();
Это не нужно? Почему?

2021-04-27 17:22 UTC, biodranik commented on storage/map_files_downloader.cpp
> +      m_quarantine.Clear();
Переименуй во что-то понятное, я мозг сломал, при чём тут карантин.

2021-04-27 17:22 UTC, biodranik commented on storage/map_files_downloader.cpp
> +        auto const & buffer = request.GetData();
Нужна какая-то минимальная валидация, что за фигня прилетела в буфере. Крешить не будет? Какашку обработает код нормально?

2021-04-27 17:22 UTC, biodranik commented on storage/map_files_downloader.cpp
> +  /// @todo Implement logic if m_serversList is "outdated"?
Раз при запуске проги? Это запрос списка с метасервера? Раньше он дёргался перед каждой загрузкой карты, кажется, чтобы не создавать DDOS.

2021-04-27 17:22 UTC, biodranik commented on storage/map_files_downloader.hpp
> +   * Callback will be skipped if download error.
on download error

2021-04-27 17:22 UTC, biodranik commented on storage/map_files_downloader.hpp
> +  void DownloadAsString(std::string url, bool firstPass, std::function<bool (std::string const &)> && callback);
1) Не понятно, что за firstPass.
2) Возможно, лучше сделать универсальный метод, загружающий что угодно по полному урлу, а формировать урл для стран внутри другого метода. Тогда мы сможем его реюзать и для других целей.

2021-04-27 17:22 UTC, biodranik commented on storage/map_files_downloader.hpp
> +   * @brief This method is blocking and should be called on network thread.
Тройные слеши были милее )

2021-04-27 17:27 UTC, vng commented on storage/map_files_downloader.cpp
> +  /// @todo Implement logic if m_serversList is "outdated"?
Ну сейчас это вызов функции в EnterForeground, вставлено для теста. Можно поставить его куда угодно, давайте придумаем правило.

2021-04-27 17:27 UTC, vng commented on defines.hpp
> +#define SERVER_INDEX_FILE "index.json"
data_index.json ?

2021-04-27 17:30 UTC, vng commented on iphone/Maps/UI/Editor/MWMEditorViewController.mm
> +    self.offscreenCells[(id)cls] = cell;
Cannot initialize a parameter of type 'id<NSCopying> _Nonnull' with an rvalue of type 'Class'

2021-04-27 17:31 UTC, biodranik commented on defines.hpp
> +#define SERVER_INDEX_FILE "index.json"
Что за дата? Если это страны, то назови current_countries.json, или countries_index.json

2021-04-27 17:31 UTC, vng commented on storage/country_tree.cpp
> +    LOG(LWARNING, (e.Msg()));
Потому что ошибка парсинга именно тут - это штатная ситуация, когда с сервера скачалось говно. При парсинге из бандла, используется другой обрамляющий вызов и там остался честный ERROR.

2021-04-27 17:33 UTC, vng commented on storage/map_files_downloader.cpp
> +        auto const & buffer = request.GetData();
Если не смогли распарсить как index.json или countries.txt - какашка скипается.

2021-04-27 17:33 UTC, vng commented on storage/map_files_downloader.hpp
> +   * Callback will be skipped if download error.
Да, только раз и кжщируется в m_serversList

2021-04-27 17:34 UTC, biodranik commented on storage/map_files_downloader.cpp
> +  /// @todo Implement logic if m_serversList is "outdated"?
Надо будет вернуть, как было, когда будет метасервер. Вставь @TODO: call before downloading any country from the metaserver

2021-04-27 17:34 UTC, vng commented on storage/map_files_downloader.hpp
> +   * @brief This method is blocking and should be called on network thread.
Ну тут на вкус :) Мне многострочный коммент нравится так ..

2021-04-27 17:40 UTC, biodranik commented on iphone/Maps/UI/Editor/MWMEditorViewController.mm
> +    self.offscreenCells[(id)cls] = cell;
А как раньше собиралось? Дебаг или релиз? Симулятор или девайс?

2021-04-27 17:54 UTC, vng commented on storage/http_map_files_downloader.cpp
> -      subscriber->OnFinishDownloading();
Это дублирующая нотификация. Все они уже есть в QueuedCountry - нотификации для каждой отдельной страны.

2021-04-27 18:21 UTC, biodranik commented on iphone/Maps/UI/Editor/MWMEditorViewController.mm
> +    self.offscreenCells[(id)cls] = cell;
У меня твоя ветка собирается без этого фикса. Как воспроизвести?

2021-04-27 18:38 UTC, vng commented on defines.hpp
> +#define SERVER_INDEX_FILE "index.json"
Вкратце, на выходе будет последняя доступная версия данных, например 210419.

2021-04-27 18:39 UTC, vng commented on iphone/Maps/UI/Editor/MWMEditorViewController.mm
> +    self.offscreenCells[(id)cls] = cell;
Девайс, XCode 12.5 от сегодня обновленный.

2021-04-27 18:42 UTC, vng commented on storage/map_files_downloader.cpp
> +  /// @todo Implement logic if m_serversList is "outdated"?
Ок, мой предидущий ответ тут не по теме, я перепутал строки ..

2021-04-27 18:43 UTC, vng commented on storage/map_files_downloader.cpp
> +  /// @todo Implement logic if m_serversList is "outdated"?
Запрос на метасервер происходит один раз при первой загрузке и потом все это кэшируется в m_serversList

2021-04-27 18:43 UTC, vng commented on storage/map_files_downloader.hpp
> +  void DownloadAsString(std::string url, bool firstPass, std::function<bool (std::string const &)> && callback);
Ок, дал норм имя параметру.

2021-04-27 20:34 UTC, vng commented
PTAL

2021-04-28 06:46 UTC, biodranik commented on defines.hpp
> +#define SERVER_INDEX_FILE "index.json"
latest_countries_version?

2021-04-28 07:07 UTC, vng commented on 3party/kdtree++/allocator.hpp
> +        __p->~_Node_();
- Это 3party, потому вопрос не ко мне :) Выше construct_node вызывает placement new (p) Node, значит в destroy_node логично вызывать ~Node(). 
- _M_node_allocator.destroy(__p) делает то же самое, но allocator::construct/destroy уже deprecated
- кастомных алокаторов не используется

2021-04-28 13:02 UTC, biodranik commented
Вот правильный фикс компиляции:
```
diff --git a/iphone/Maps/UI/Editor/MWMEditorViewController.mm b/iphone/Maps/UI/Editor/MWMEditorViewController.mm
index 6fa79ca59d..7051789b59 100644
--- a/iphone/Maps/UI/Editor/MWMEditorViewController.mm
+++ b/iphone/Maps/UI/Editor/MWMEditorViewController.mm
@@ -342,15 +342,15 @@ void registerCellsForTableView(std::vector<MWMEditorCellType> const & cells, UIT
   if (!cell)
   {
     cell = [NSBundle.mainBundle loadWithViewClass:cls owner:nil options:nil].firstObject;
-    self.offscreenCells[(id)cls] = cell;
+    self.offscreenCells[(id<NSCopying>)cls] = cell;
   }
   return cell;
 }
 
 - (void)configTable
 {
-  self.offscreenCells = [NSMutableDictionary dictionary];
-  self.invalidCells = [NSMutableArray array];
+  [self.offscreenCells removeAllObjects];
+  [self.invalidCells removeAllObjects];
   m_sections.clear();
   m_cells.clear();
 
@@ -796,7 +796,7 @@ void registerCellsForTableView(std::vector<MWMEditorCellType> const & cells, UIT
 
 - (void)cell:(MWMNoteCell *)cell didChangeSizeAndText:(NSString *)text
 {
-  self.offscreenCells[(id)cellClass(MWMEditorCellTypeNote)] = cell;
+  self.offscreenCells[(id<NSCopying>)cellClass(MWMEditorCellTypeNote)] = cell;
   self.note = text;
   [UIView setAnimationsEnabled:NO];
   [self.tableView refresh];
```

2021-04-28 13:03 UTC, biodranik approved these changes
LGTM + fix

2021-04-28 13:04 UTC, biodranik commented on 3party/kdtree++/allocator.hpp
> +        __p->~_Node_();
А ты гуглил самую свежую версию этого файла?

2021-04-28 13:07 UTC, biodranik commented on 3party/kdtree++/allocator.hpp
> +        __p->~_Node_();
Народ фиксит вот так: https://github.com/nvmd/libkdtree/commit/73965a08c02d04149be2ec4e8e2cf418ddb2c762

2021-04-28 14:26 UTC, vng commented on 3party/kdtree++/allocator.hpp
> +        __p->~_Node_();
По хорошему, это не верно. Как я писал, рах мы явно зовем placement new (p), то тут лучше явно звать деструктор. Если окажется что destroy (не важно от алокатора или от traits) начнет делать что-то другое, будет косяк.

2021-04-28 16:09 UTC, biodranik approved these changes
LGTM

2021-04-28 16:59 UTC, merged