[[strings]] Add Catalan translation
organicmaps/organicmaps pull request #3274
Opened 2022-08-27 15:44 UTC by jmontane

2022-08-27 19:06 UTC, biodranik requested changes
Please edit data/countries_names.txt
The file you have edited is autogenerated from that file.

2022-08-27 19:13 UTC, jmontane commented
Thanks! I'll try it

2022-08-28 12:22 UTC, jmontane commented
@biodranik, I reverted commit with .json file and committed a first translation of countries_names.txt file. Translations of descriptions are missing, but I won't be working on it for the next few days. So, merge current PR, please. Thanks.

2022-08-28 21:21 UTC, biodranik approved these changes
Thank you for your contribution! I'll try to fix merge conflicts.

2022-08-28 21:21 UTC, biodranik commented on data/strings/strings.txt
> +    be = Няма сігналу GPS. Перамясціцеся на адкрытую прасторуz
```suggestion
    be = Няма сігналу GPS. Перамясціцеся на адкрытую прастору
```

2022-08-28 21:46 UTC, biodranik commented
@jmontane to finish localization, please translate data/categories.txt file. Note that it should match data/strings/types_strings.txt + add some synonyms if necessary (what users may type in the search field).

2022-08-29 06:19 UTC, closed without merging