Switched to KML instead of KMB (old bookmarks will be lost)
organicmaps/organicmaps pull request #336
Opened 2021-04-24 16:34 UTC by biodranik

Now bookmarks are again saved in GetPlatform().SettingsDir() (binary kmb were in "./bookmarks" subfolder.

2021-04-24 17:13 UTC, vng requested changes

2021-04-24 17:13 UTC, vng commented on map/bookmark_manager.cpp
> +  return base::JoinPath(GetPlatform().SettingsDir());
А давай писать в папку.

2021-04-24 19:16 UTC, biodranik commented on map/bookmark_manager.cpp
> +  return base::JoinPath(GetPlatform().SettingsDir());
Тогда будет гораздо сложнее вытягивать букмарки на айфоне, и втягивать их туда копированием файлов. Какие преимущества у папки?

2021-04-24 19:43 UTC, vng commented on map/bookmark_manager.cpp
> +  return base::JoinPath(GetPlatform().SettingsDir());
Папка копируется локально, потом целиком заливается назад.
- Чтобы не мусорить в корень
- Там ниже по коду есть где вся папка с букмарками процесится

2021-04-24 19:43 UTC, vng commented on map/bookmark_manager.cpp
>        return true;  // Allow to load any files from the bookmarks directory.
Вот тут

2021-04-24 19:52 UTC, rtsisyk requested changes

2021-04-24 19:52 UTC, rtsisyk commented on map/bookmark_manager.cpp
> +  return base::JoinPath(GetPlatform().SettingsDir());
На ведре в этой папке будут еще всякие settings.ini, карты и прочее. Помойка, одним словом. Настроить бэкап тут не представляется возможным.

2021-04-25 05:47 UTC, biodranik commented on map/bookmark_manager.cpp
>        return true;  // Allow to load any files from the bookmarks directory.
Всегда так работало. Внутри LoadBookmarks код
```
  Platform::FilesList files;
  Platform::GetFilesByExt(dir, ext, files);
```

2021-04-25 05:48 UTC, biodranik commented on map/bookmark_manager.cpp
> +  return base::JoinPath(GetPlatform().SettingsDir());
Там выбор файлов по расширению, всегда работал )
Мне не нравится копировать целиком и потом назад заливать, я с этим несколько раз сталкивался, гемор полный.

2021-04-25 05:48 UTC, biodranik commented on map/bookmark_manager.cpp
> +  return base::JoinPath(GetPlatform().SettingsDir());
Хотя бэкапить удобнее папкой вручную, но мы же потом автоматизируем…

2021-04-25 08:17 UTC, vng commented
Выбор файлов по расширению - это конечно хорошо, но я все равно настаиваю на папке. Профитов тут будет больше, чем неудобно вручную в ios подкладывать ..

2021-04-25 08:57 UTC, rtsisyk commented
Оставьте папку, пожалуйста.

On Sun, 25 Apr 2021, 11:18 Viktor Govako, ***@***.***> wrote:

> Выбор файлов по расширению - это конечно хорошо, но я все равно настаиваю
> на папке. Профитов тут будет больше, чем неудобно вручную в ios
> подкладывать ..
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/organicmaps/organicmaps/pull/336#issuecomment-826281003>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANXHDVMCN7OSMU2YPKEZJLTKPF4FANCNFSM43QJT6CQ>
> .
>

2021-04-25 11:21 UTC, rtsisyk commented on map/bookmark_manager.cpp
> +  return base::JoinPath(GetPlatform().SettingsDir());
Оставьте папку, не страдайте фигней.

2021-04-25 11:23 UTC, rtsisyk commented on android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
> -void OnFinishKmlConversion(JNIEnv * env, bool success)
Что это за метод вообще? Что делал раньше?

2021-04-25 11:23 UTC, rtsisyk commented on android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
> -  public boolean isEditableMapObject()
Почему это не нужнор больше?

2021-04-25 11:23 UTC, rtsisyk commented on map/bookmark_manager.cpp
>  void BookmarkManager::EditSession::SetCategoryTags(kml::MarkGroupId categoryId, std::vector<std::string> const & tags)
А что за тэги вообще? Я порывался выпилить еще в предыдущий заход.

2021-04-25 11:23 UTC, rtsisyk commented on map/map_tests/bookmarks_test.cpp
> +  return KmlFileType::Text;
Зачем этот enum то нужен вообще?

2021-04-25 12:00 UTC, biodranik commented on android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
> -void OnFinishKmlConversion(JNIEnv * env, bool success)
Превращал kml в kmb

2021-04-25 12:01 UTC, biodranik commented on android/src/com/mapswithme/maps/widget/placepage/PlacePageView.java
> -  public boolean isEditableMapObject()
Потому что у нас все букмарки теперь editable. Не редактируемыми были загружаемые с инета гайды.

2021-04-25 12:01 UTC, rtsisyk commented
Вот делать то нефиг было

On Sun, 25 Apr 2021, 15:01 Alexander Borsuk, ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In android/jni/com/mapswithme/maps/bookmarks/data/BookmarkManager.cpp
> <https://github.com/organicmaps/organicmaps/pull/336#discussion_r619804372>
> :
>
> > @@ -184,15 +181,6 @@ void OnAsyncLoadingFileError(JNIEnv * env, std::string const & fileName, bool is
>
>    jni::HandleJavaException(env);
>
>  }
>
>
>
> -void OnFinishKmlConversion(JNIEnv * env, bool success)
>
>
> Превращал kml в kmb
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/organicmaps/organicmaps/pull/336#discussion_r619804372>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AANXHDSC4BH7IJQPFMVEBVDTKQAADANCNFSM43QJT6CQ>
> .
>

2021-04-25 12:02 UTC, biodranik commented on map/bookmark_manager.cpp
>  void BookmarkManager::EditSession::SetCategoryTags(kml::MarkGroupId categoryId, std::vector<std::string> const & tags)
Не нужны они. От гайдов остались. Видимо, доя удобной группировки разных гайов в маркетплейсе.

2021-04-25 12:03 UTC, biodranik commented on map/map_tests/bookmarks_test.cpp
> +  return KmlFileType::Text;
Уже не нужен, я потом выпилю. Главное это вмержить.

2021-04-25 19:26 UTC, biodranik commented
Фиг с вами, вернул директорию bookmarks.

2021-04-26 05:45 UTC, vng approved these changes

2021-04-26 05:51 UTC, rtsisyk approved these changes

2021-04-26 05:51 UTC, merged