[search] Fixed categories.
organicmaps/organicmaps pull request #3360
Opened 2022-09-06 13:58 UTC by vng

Closes https://github.com/organicmaps/organicmaps/issues/3317
Closes https://github.com/organicmaps/organicmaps/issues/3318

2022-09-07 14:42 UTC, biodranik requested changes

2022-09-07 14:42 UTC, biodranik commented on search/search_quality/search_quality_tests/real_mwm_tests.cpp
> +  SetViewport(center, 3000);
Зачем загружать всё USA а тестить только Hilo?

2022-09-07 14:42 UTC, biodranik commented on search/search_quality/features_collector_tool/features_collector_tool.cpp
> +  auto engine = InitSearchEngine(dataSource, "en" /* locale */, FLAGS_num_threads);
Эта тула работает всегда только для en? Зачем она вообще?

2022-09-07 14:42 UTC, biodranik commented on search/search_integration_tests/processor_test.cpp
> +  Rules rules{ExactMatch(wonderlandId, cafe1),
const?

2022-09-07 14:42 UTC, biodranik commented on search/search_integration_tests/processor_test.cpp
> +    auto request = MakeRequest("gelato");
const здесь и в других местах.

2022-09-07 14:42 UTC, biodranik commented on search/ranking_info.cpp
> +  // Do not increment score for category-only-matched results or subways will be _always_ on top.
```suggestion
  // Do not increment score for category-only-matched results or otherwise subways will be _always_ on top.
```

2022-09-07 14:42 UTC, biodranik commented on search/ranking_info.cpp
> +// - On the other hand, when search for "subway", do we usually prefer famous fast food or metro?
Наверное надёжнее будет составить ручной список исключений типа subway. Их вряд ли очень много будет в мире.

2022-09-07 14:42 UTC, biodranik commented on search/ranker.cpp
> +      totalLength = 1;
Почему форсится в единицу? Коммент бы.

2022-09-07 16:34 UTC, vng commented on search/ranking_info.cpp
> +// - On the other hand, when search for "subway", do we usually prefer famous fast food or metro?
Я специально хочу настроить без исключений, а этот коэффициент давал какую-то конскую поправку. subway - это то что явно на виду. У нас очень fancy (на мой взгляд) список категорий и добавляем мы их абы как (на мой взгляд). "where to eat" ?! Значит всегда вводя токен "where" он будет интерпретироваться в первую очередь как категория еды, а потом надо будет еще долго медитировать почему поиск ранжирует очень странно ..

2022-09-07 16:40 UTC, vng commented on data/categories_cuisines.txt
> -uk:Морська їжа|Рибний ресторан
Все эти cuisine тогда начнут матчится по запросу "ресторан". Не работает так поиск, чтобы вписывать категории fancy словосочетаниями и скорее всего очень нескоро будет так работать ..

Категории должны быть точными, желательно уникальными синонимами, как теги, очень! желательно однословными. Тогда будет и четко и быстро и объяснимо работать. А не матчить еду по запросу "where" как сейчас :)

2022-09-07 16:42 UTC, vng commented on data/categories_cuisines.txt
> -pt-BR:Sanduíche|sanduíches
Нет. Тут я грубо говоря _нормализовал_, потому что все остальное всегда задается в единственном числе.

s вполне может обрабатываться через fuzzy, либо как-то по другому алгоритмически. Если их вписывать, тогда надо лопатить весь список ..

2022-09-07 16:43 UTC, vng commented on data/categories_cuisines.txt
> +pt-BR:Lámen|rāmen
Я очень подозреваю что надо, проверь.

2022-09-07 16:43 UTC, vng commented on data/categories_cuisines.txt
> +ru:Хот-доги|хотдог
да

2022-09-07 16:46 UTC, vng commented on data/categories_cuisines.txt
> -ru:Соба|лапша|лапшичная
лапшичную? как в анекдоте про хуячечную :) Ну не понравилось мне ..

2022-09-07 16:47 UTC, vng commented on qt/search_panel.cpp
> +      locale = "ru";
я не нашел, бубен мне для работы

2022-09-07 16:48 UTC, vng commented on search/search_quality/search_quality_tests/real_mwm_tests.cpp
> +  SetViewport(center, 3000);
чем больше загружено, тем больше inference, лучше проверяется четкость

2022-09-07 16:48 UTC, vng commented on search/search_quality/features_collector_tool/features_collector_tool.cpp
> +  auto engine = InitSearchEngine(dataSource, "en" /* locale */, FLAGS_num_threads);
не знаю

2022-09-07 16:49 UTC, vng commented on qt/search_panel.cpp
> +    size_t cyrillic = 0;
здесь максимально локальный скоуп, переменная понятная и так имхо

2022-09-10 08:56 UTC, biodranik commented on search/search_quality/search_quality_tests/real_mwm_tests.cpp
> +  ms::LatLon const center(21.3045470, -157.8556760);
```suggestion
  ms::LatLon const honolulu(21.3045470, -157.8556760);
```

И тогда комментарий не нужен.

2022-09-10 08:56 UTC, biodranik commented on search/search_quality/search_quality_tests/real_mwm_tests.cpp
> +  ms::LatLon const center(55.74988, 37.59240);
vpCenterMoscowArbat
Можно ещё так

2022-09-10 08:56 UTC, biodranik commented on search/search_quality/search_quality_tests/real_mwm_tests.cpp
> +  /// @param[in] street, house May be empty.
std::optional<std::string> оверхед?

2022-09-10 08:56 UTC, biodranik commented on search/search_quality/search_quality_tests/real_mwm_tests.cpp
> +      if (r.GetResultType() == search::Result::Type::Feature &&
Визуально влезет в строку на гитхабе.

2022-09-10 08:56 UTC, biodranik commented on search/search_integration_tests/processor_test.cpp
> +  auto wonderlandId = BuildCountry("Wonderland", [&](TestMwmBuilder & builder)
const?

2022-09-10 08:56 UTC, biodranik commented on search/processor.cpp
>      string s = query;
1. Модификация строки s в EatFid здесь и дальше игнорится. Значит можно избежать копирования.
2. Внутри EatFid наверное тоже можно избежать аллокации в substr, заменив её на erase. (хотя может в реальности там и нет аллокации, если умная строка видит маленькую длину).

2022-09-10 08:56 UTC, biodranik commented on search/mwm_context.hpp
> +    CHECK(m_type, ());
Это в продакшне точно 1) нужно? 2) не замедлит?

2022-09-10 08:56 UTC, biodranik commented on search/geocoder.cpp
> +  std::vector<DistCentreFeatureT> dist_streets;
```suggestion
  std::vector<DistCentreFeatureT> distStreets;
```

2022-09-10 08:56 UTC, biodranik commented on data/categories_cuisines.txt
> -pt-BR:Sanduíche|sanduíches
Зачем нормализовывать, если явный матч точно будет лучше? Какой выигрыш?

2022-09-10 08:56 UTC, biodranik commented on data/categories_cuisines.txt
> -ru:Морепродукты|Рыбный ресторан|рыба
Какие минусы тут матчиться на "ресторан"? И в других подобных случаях тоже? Если слово в части запроса, то матчинг подразумевается, нет?

2022-09-10 08:56 UTC, biodranik commented on data/categories_cuisines.txt
> -ru:Соба|лапша|лапшичная
Ну мало ли кто-то так будет искать. Чем плохо лишний синоним? Медленнее работает?

2022-09-10 08:56 UTC, biodranik commented on data/categories_cuisines.txt
> -uk:Морська їжа|Рибний ресторан
Написал выше, если только именно эти типы кухонь заматчатся, ничего страшного. Кухни как раз и лепят на рестораны )

2022-09-10 08:56 UTC, biodranik commented on qt/search_panel.cpp
> +      locale = "ru";
Лучше сразу сделать правильно на Qt, на линуксах будет лучше работать и венде потом:
https://doc.qt.io/qt-5/qinputmethod.html#locale-prop

Ну или в крайнем случае хотя бы https://stackoverflow.com/a/62868602

2022-09-10 08:56 UTC, biodranik commented on search/geocoder.cpp
> +  // Find first (after m_maxStreetsCount) street that out of rect's bounds.
```suggestion
  // Find the first (after m_maxStreetsCount) street that is out of the rect's bounds.
```

2022-09-10 08:56 UTC, biodranik commented on search/geocoder.hpp
> +    // Max number of street cadidates for matching POI(Building) with Street.
POI or Building? POI and Building? POI in a building? POI/Building?

2022-09-10 08:56 UTC, biodranik commented on search/geocoder.hpp
> +    size_t m_maxStreetsCount = 100;
1. constexpr kMaxStreetsCount ?
2. Пояснишь подробнее суть в комментарии?

2022-09-10 08:56 UTC, biodranik commented on search/geocoder.hpp
> +    void Process(std::vector<uint32_t> & streets, Geocoder & geocoder) const;
Можно более говорящее название метода о том, что там происходит? Process подходит под почти всё )

2022-09-10 08:57 UTC, vng commented on search/geocoder.hpp
> +    void Process(std::vector<uint32_t> & streets, Geocoder & geocoder) const;
Ну так это же в скоупе класса CentersFilter.

2022-09-10 08:59 UTC, vng commented on search/search_quality/search_quality_tests/real_mwm_tests.cpp
> +  ms::LatLon const center(21.3045470, -157.8556760);
Мне нравится именно так, как по шаблону с др тестами.
В первую очередь это центр поиска.

2022-09-10 08:59 UTC, vng commented on search/search_quality/search_quality_tests/real_mwm_tests.cpp
> +  ms::LatLon const center(55.74988, 37.59240);
Это центр поиска для чтения и понимания дальнейшего кода.

2022-09-10 08:59 UTC, vng commented on search/search_quality/search_quality_tests/real_mwm_tests.cpp
> +  /// @param[in] street, house May be empty.
Зачем? Пустая строка.

2022-09-10 09:01 UTC, vng commented on search/processor.cpp
>      string s = query;
1 нет
2 нет

2022-09-10 09:04 UTC, vng commented on search/mwm_context.hpp
> +    CHECK(m_type, ());
нет

2022-09-10 09:12 UTC, vng commented on search/geocoder.hpp
> +    size_t m_maxStreetsCount = 100;
Вероятно, эта переменная будет динамически устанавливаться в зависимости от окружения потом.

2022-09-10 09:23 UTC, vng commented on qt/search_panel.cpp
> +      locale = "ru";
Тут соль в том как получить правильный нужный QInputMethod. У меня не получилось, если получится у тебя, сделай отдельный коммит.

2022-09-10 09:52 UTC, vng commented on data/categories_cuisines.txt
> -pt-BR:Sanduíche|sanduíches
Тут целью было сделать как у нас везде. Если кто-то, смотря на эти строки, начнет везде заполнять синонимы множественного числа, это будет уже не хорошо на мой взгляд.

2022-09-10 10:22 UTC, biodranik commented on qt/search_panel.cpp
> +      locale = "ru";
https://doc.qt.io/qt-5/qguiapplication.html#inputMethod ?

2022-09-10 10:23 UTC, biodranik commented on data/categories_cuisines.txt
> -pt-BR:Sanduíche|sanduíches
Внутри дерево не эффективно хранит категории с разными окончаниями? Если поиск начнёт искать лучше после небольшого ручного редактирования, это только плюс. Какие минусы?

2022-09-10 10:24 UTC, biodranik commented on data/categories_cuisines.txt
> -uk:Морська їжа|Рибний ресторан
Я так и не понял, чем тут плох рыбный ресторан. Ну кухни же всё равно в основном на ресторанах налеплены.

2022-09-10 10:36 UTC, vng commented on data/categories_cuisines.txt
> -uk:Морська їжа|Рибний ресторан
- Запрос "рыбный ресторан" будет работать
- Он лишний и чтобы контриьбюторы/переводчики не начали его плодить

2022-09-10 10:38 UTC, biodranik commented on data/categories_cuisines.txt
> -uk:Морська їжа|Рибний ресторан
Я не согласен, что лишний. Это устоявшееся словосочетание, известное многим людям, которое так могут вбить в поиске. По сути как раз синоним для кухни и заведения сразу. Ну вот как ты называешь место, где в основном морская кухня?

2022-09-10 11:47 UTC, vng commented on data/categories_cuisines.txt
> -uk:Морська їжа|Рибний ресторан
Запрос "рыбный ресторан" будет работать. И именно для amenity=restaurant с cuisine=fish.
Если оставим ресторан тут, то тогда будет работать и для amenity=fast_food, cuisine=fish.

2022-09-10 14:39 UTC, vng commented on data/categories_cuisines.txt
> -pt-BR:Sanduíche|sanduíches
С поиском внутри проблем нет, только то что я написал раньше: "Если кто-то, смотря на эти строки, начнет везде заполнять синонимы множественного числа, это будет уже не хорошо на мой взгляд."

2022-09-11 06:18 UTC, vng commented
@biodranik PTAL

2022-09-11 06:43 UTC, biodranik approved these changes
Исправь и проверь QLocale и можно мержить.

2022-09-11 06:43 UTC, biodranik commented on qt/search_panel.cpp
> +  std::string const normalized = str.toStdString();
Но тут же не нормализованная строка )

2022-09-11 06:43 UTC, biodranik commented on qt/search_panel.cpp
> +}
```suggestion
  return QGuiApplication::inputMethod()->locale().name().first(2);
```

[QString](https://doc.qt.io/qt-6/qstring.html) QLocale::name() const

Returns the language and country of this locale as a string of the form "language_country", where language is a lowercase, two-letter ISO 639 language code, and country is an uppercase, two- or three-letter ISO 3166 country code.

2022-09-11 08:25 UTC, merged