[edits] Fixed exception type.
organicmaps/organicmaps pull request #3375
Opened 2022-09-09 02:38 UTC by vng

2022-09-10 11:11 UTC, biodranik requested changes
Надо тщательно поревьюить TrianglesToPolygon, там может быть ошибка. Исключение в #3373 вылезло после обновления данных, и судя по коду, "неправильная" геометрия именно в наших данных.

Можно сделать брут форс или юнит тест: пробежаться по всему Sweden_Vastra Gotaland и для всех FeatureType::Area вызвать TrianglesToPolygon. Должно словить косяк.

2022-09-10 11:11 UTC, biodranik commented on editor/edits_migration.cpp
> +          LOG(LWARNING, (ex.Msg()));
Надо залогать точки вот тут:
```
    if (!boost::geometry::is_valid(polygon))
      MYTHROW(geometry::NotAPolygonException, ("The triangle is not valid"));
```

2022-09-10 11:11 UTC, biodranik commented on editor/edits_migration.cpp
> +          LOG(LWARNING, (ex.Msg()));
Заодно там причесать код (constexpr, вместо resize сразу вектор создавать с одним элементом, можно и вообще убрать исключения а возвращать optional).

Блин, этот метод может и пустой полигон вернуть. Тогда точно надо подумать над сигнатурой.

2022-09-10 11:23 UTC, vng commented
- Этот фикс не зависит от возможных дальнейших ошибок.
- Даже на основе наших _правильных_ полигонов, boost::geometry может давать отлуп, просто потому что он вот такой.

2022-09-11 08:46 UTC, biodranik approved these changes
Этот фикс скрывает проблему. Может дальше по catch будет непредсказуемый мерж ерунды в осм. Сделай хотя бы ишью на будущее, заменить на буст полигон.

2022-09-11 09:14 UTC, merged