[github] Add timeouts for all jobs
organicmaps/organicmaps pull request #3397
Opened 2022-09-13 08:01 UTC by rtsisyk

To avoid situation when Fastlane waited for 6h.

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2022-09-13 08:01 UTC, rtsisyk commented
https://github.com/organicmaps/organicmaps/actions/runs/3031256826

2022-09-13 22:19 UTC, biodranik requested changes
Посмотрел, под iOS на самом деле все билды корректно появились в TestFlight, даже где Fastlane не дождался таймаута и зафейлился. Думаю что это бага в Testflight, которую надо поисследовать и возможно как-то потюнить.

2022-09-13 22:19 UTC, biodranik commented on .github/workflows/linux-check.yaml
> -      fail-fast: false
Надо вернуть, это специально сделано, чтобы удобнее ловить баги на разных компиляторах и быстрее их фиксить.

2022-09-14 05:20 UTC, rtsisyk commented on .github/workflows/linux-check.yaml
> -      fail-fast: false
Это просто невалидный синтаксис. Никакой роли не несет.

2022-09-25 12:56 UTC, biodranik commented on .github/workflows/linux-check.yaml
> -      fail-fast: false
В смысле невалидный синтаксис? Это официальный способ не отменять все джобы если одна завалилась, а ждать до конца:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

2022-10-16 06:25 UTC, closed without merging