Update release notes
organicmaps/organicmaps pull request #3405
Opened 2022-09-14 05:46 UTC by rtsisyk

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

##

[strings] add missing translations for craft=*
[styles] Add driving_school, music_school and language_school
[editor] Fixed exception type.
[search] Better street's FeaturesLayer filtering logic.
[search] Decrease score for numeric streets like "2-й ...".
[search] Increased penalty for error; increased city rank factor.
[search] Added Shop POI type for ranking.
[search] Fixed category results ranking.
[search] Cleanup debug features fetching.
[search][tests] Correct affiliations initialization.
[desktop] Added "ru" locale and category checkbox.
[search] Fixed categories.
[strings] Add @501Ghost's NL translations
[android] set bottom map buttons max width to 300dp
[android] Adjust ruler and copyright to transparent nav bar
[android] Adjust compass to transparent nav bar
[android] Make navigation bar transparent on map
[android] Make splash screen navigation bar follow background color
[android] Add themed icon for Android 13
[symbols] Added norating-bg-l.png mask.
[android] Fix displaying hotel rating in search results
[styles] Add icon for archaeological_site
[android] remove custom search activity fade
[symbols] Removed background circles from icons used for tag historic and cemetery-m.svg
[generator] Fixed castle_type.
[styles] Added castle_type castrum, fortified_church, fortress, hillfort, kremlin, manor, palace & shiro
[android] Minor search wheel clean up
[drape] Fixed dropped metalines.
[styles] Increased visibility of education and some sports
[android] try to match previous map buttons layout
[android] make buttons layout react to screen height
[android] use separate buttons layout for each map mode
[android] make all map buttons independent
[android] remove main menu bar
[android] replace custom map buttons by FloatingActionButton
[android] remove layers selection from main menu
[android] improve map buttons moving behavior
[android] unify handling of map buttons
[android] simplify layers button
[strings] Add nl-Dutch translations
[ios] Use default mail app on iOS 14 to report a bug
[search] Always process viewport MWM first (after World).
[android] Note to OSM editors
[styles] Tweaks for leisure=track
[strings] Beach volleyball in English is 2 words
[strings] Fixed not working pt-BR bowling transloation for iOS
[categories] Improve german category word coverage
[bookmarks] Fixed last modified time categories order.
[altitudes] Simplify loading checks.
[string] Fix Italian generic "Stop": set "Bus stop" + "Bus tram"
[styles] Change icon of vending=fuel
[android] Increased the font size of exit number
[android] improve osm login page
[strings] update osm strings
[android] refactor profile and add changes loading indicator
[android] rework OSM login UX
[direction] Fixed some bugs for next street name
Enabled Catalan translations for iOS
Enabled Catalan TTS
[strings] Add Catalan translation
Add cross-platform system fonts in CSS for copyright.html
Add cross-platform system fonts in CSS for faq.html
[ios] Change UI font from Helvetica to system
[strings] Added missing Turkish translations
[strings] Added Telegram and Instagram links
[strings] Added additional Belarusian names of countries
Separate furniture & kitchen types
[android] Fixed possible crash.

2022-09-14 07:01 UTC, csidirop commented on android/src/fdroid/play/release-notes/de-DE/default.txt
> +• Neue Benutzeroberfläche für Kartenschaltflächen
Better something like "Neue Tasten/Knöpfe/Buttons auf der Kartenoberfläche"

2022-09-14 07:12 UTC, csidirop commented on android/src/fdroid/play/release-notes/de-DE/default.txt
> +• Neue Benutzeroberfläche für Kartenschaltflächen
Oh I misunderstood the English version. We changed the UI/look of the buttons, am I right (see #3398)? So maybe something like 
"Neue Oberfläche für die Tasten/Knöpfe/Buttons auf der Karte" or 
"Neues Aussehen für die Tasten/Knöpfe/Buttons auf der Karte"

2022-09-14 09:51 UTC, matheusgomesms commented
I added PT-BR translation (#3409).

2022-09-14 10:10 UTC, biodranik requested changes
No no no, please wait until a properly prepared release notes PR. That one is not good.

2022-09-14 11:47 UTC, biodranik commented
Please check updated release notes, translated with DeepL.

2022-09-14 12:28 UTC, csidirop commented on iphone/metadata/de-DE/release_notes.txt
> +Übersetzt mit www.DeepL.com/Translator (kostenlose Version)
This line should be removed

2022-09-14 12:28 UTC, csidirop commented on iphone/metadata/tr/release_notes.txt
> +Translated with www.DeepL.com/Translator (free version)
This line should be removed

2022-09-14 12:37 UTC, MetehanOzyurek approved these changes

2022-09-14 19:49 UTC, j5k commented on android/src/fdroid/play/release-notes/de-DE/default.txt
> +• Fixierte Übersetzungen
Verbesserte Übersetzungen ('Fixierte' is nonsense in this way)

2022-09-15 07:41 UTC, biodranik commented
@csidirop should we wait until you improve the German translation?

2022-09-15 08:10 UTC, csidirop commented
> @csidirop should we wait until you improve the German translation?

Sorry had no time yesterday. I will look over it in my break time. In about two hours ok?

2022-09-15 08:13 UTC, csidirop commented on android/src/fdroid/play/release-notes/de-DE/default.txt
> +• Entfernte untere Symbolleiste für bessere UX und Sichtbarkeit der Karte
"Entfernte untere Symbolleiste ..." sounds somehow wrong for me. Use "Untere Symbolleiste entfernt ..." instead.

2022-09-15 08:38 UTC, csidirop approved these changes

2022-09-15 08:56 UTC, csidirop approved these changes

2022-09-15 09:15 UTC, biodranik approved these changes

2022-09-15 09:15 UTC, biodranik commented on iphone/metadata/en-US/release_notes.txt
> +• Added missing translations for craft=*
```suggestion
• Added missing translations for craft=* and residential gardens
```

2022-09-15 09:36 UTC, matheusgomesms approved these changes

2022-09-15 20:28 UTC, merged