[android] Streamline SplashScreen
organicmaps/organicmaps pull request #341
Opened 2021-04-25 17:50 UTC by rtsisyk

- Fix a crash if location permission is not granted.
- Use exceptions instead of boolean for I/O errors.
- Handle the first run properly.

Closes #340

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2021-04-25 19:26 UTC, biodranik requested changes

2021-04-25 19:26 UTC, biodranik commented on data/strings/strings.txt
> +  [enable_location_services_long_text]
Всегда надо смотреть существующие строчки перед добавлением новых. Уже есть location_is_disabled_long_text

2021-04-25 19:26 UTC, biodranik commented on android/src/com/mapswithme/maps/SplashActivity.java
> -    if (Counters.getFirstInstallVersion(getApplicationContext()) < BuildConfig.VERSION_CODE)
Раньше мы сохраняли номер версии при первом запуске, и считали запуски, чтобы всякую логику можно было включить, типа "нравится прога? напиши отзыв", может ещё что-то.

2021-04-25 19:26 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmApplication.java
> +    SharedPropertiesUtils.emulateBadExternalStorage(this);
Добавь коммент "throws if enabled in preferences"

2021-04-26 05:46 UTC, rtsisyk commented on android/src/com/mapswithme/maps/SplashActivity.java
> -    if (Counters.getFirstInstallVersion(getApplicationContext()) < BuildConfig.VERSION_CODE)
Это всё осталось в Counters.java, ничего не удалял. Сам `boolean isFirstLaunch()` тоже перенес туда.

2021-04-26 06:04 UTC, vng requested changes

2021-04-26 06:04 UTC, vng approved these changes

2021-04-26 06:11 UTC, rtsisyk commented on android/src/com/mapswithme/util/SharedPropertiesUtils.java
> +      throw new IOException("External etorage error injection");
Пофиксил.

2021-04-26 06:11 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmApplication.java
> +    SharedPropertiesUtils.emulateBadExternalStorage(this);
Добавил.

2021-04-26 06:12 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmApplication.java
> +    log.i(TAG, "Framework initialized");
Поменял на getLogger().i()

2021-04-26 06:12 UTC, rtsisyk commented on data/strings/strings.txt
> +  [enable_location_services_long_text]
Я искал, но почему-то это сообщение не нашел. Поменял на него.

2021-04-26 06:12 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmJobIntentService.java
> +    try {
Случайно, поменял.

2021-04-26 08:04 UTC, rtsisyk commented
@biodranik PTAL

2021-04-26 11:50 UTC, biodranik approved these changes
LGTM

2021-04-26 17:39 UTC, merged