[ios] Consistently remove grey bar below header in place pages
organicmaps/organicmaps pull request #3454
Opened 2022-09-19 12:59 UTC by nojus297

This is even more a hack than the previous code, which was marked as a workaround. However, it works - I have not seen the problem described in #3082 with this fix and the lag is not noticeable.

There is probably a better way to do this, but since my bug report issue was not fixed, I decided to give it a try (although I have no experience  developing iOS apps).

2022-09-19 23:15 UTC, biodranik requested changes
Please, no hacks :) It would be great to understand the root cause of this issue, and properly fix it. I know, it could be very hard and may require some refactoring. But this issue actually appeared because someone else didn't implement it properly. Let's not continue doing the same mistakes.

2022-09-20 08:07 UTC, nojus297 commented
Although I would argue that this doesn't introduce anything new (the async queue also has a delay, albeit lower one), I can understand your position as maintainer :)

Anyway, it would be helpful to get a hint from someone familiar with the ios codebase, where/when the visibility of place page subviews might change.

2022-09-24 20:36 UTC, biodranik commented
@nojus297 When I debugged it, I used breakpoints in different places. The current implementation is complex, so you'll need some time to understand it.
The good news is that we want/plan to refactor the place page anyway and improve it. So if you invest your time into this issue, it may be useful for future ;-)

2022-09-24 21:03 UTC, nojus297 commented
I did spend quite some time trying to figure this out, but have not managed to fix it. All I figured out was that the header view of place page has some trailing spacing, but I could not find where it comes from (storyboard or any of the controllers), but the other views resizing in the stack are not the only problem.

Not sure how helpful breakpoints are there, as all the arrangements are made before it is even rendered (I think, haven't debugged properly as it's not very pleasant on a VM and a small resolution window).

2022-09-24 21:42 UTC, biodranik commented
Wow, why are you using a VM for debug?

2022-09-25 12:44 UTC, nojus297 commented
VM is the only way I can run the Xcode, required to build Organic maps for ios.

2023-10-08 15:46 UTC, closed without merging