[android] Fix my position arrow during navigation
organicmaps/organicmaps pull request #3462
Opened 2022-09-20 08:25 UTC by rtsisyk

Closes #3441

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2022-09-22 09:09 UTC, biodranik requested changes

2022-09-22 09:09 UTC, biodranik commented on android/jni/com/mapswithme/maps/Framework.cpp
> +  NativeFramework()->UpdateMyPositionRoutingOffset(false, offsetY);
Why is this line can't be called directly from MapFragment.cpp? Why is another wrapper layer needed?

2022-09-22 09:09 UTC, biodranik commented on android/src/com/mapswithme/maps/MapFragment.java
> +    Logger.w("TEST", "nativeSetupMyPosition: " + offsetY);
?

2022-09-22 09:09 UTC, biodranik commented on android/src/com/mapswithme/maps/widget/menu/NavMenu.java
> +  public interface OnMenuSizeChangedListener
Why listener? Isn't `mMapFragment.setupBottomWidgetsOffset` a proper place to update the C++ arrow position?

2022-09-22 09:09 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    mNavigationController = new NavigationController(this, mMapButtonsController, v -> onSettingsOptionSelected(), this::adjustBottomWidgets);
How adjustBottomWidgets receives the argument from the new listener code below?

2023-03-25 18:51 UTC, rtsisyk commented
This patch is not possible to rebase on the latest master.

2023-03-25 18:51 UTC, closed without merging