[android] Add `cll=lat,lon` argument to Crosshair API
organicmaps/organicmaps pull request #3463
Opened 2022-09-20 09:44 UTC by rtsisyk

```
adb shell am start -a android.intent.action.VIEW -d '"om://crosshair?appname=qqqqqqq&cll=35.174897,33.363857"'
```

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2022-09-21 08:57 UTC, biodranik requested changes
@vng помоги, пожалуйста.

2022-09-21 08:57 UTC, biodranik commented on android/src/com/mapswithme/maps/intent/Factory.java
> +                                       false);
Чёт поплыло форматирование.

2022-09-21 08:57 UTC, biodranik commented on android/src/com/mapswithme/maps/intent/Factory.java
> +            LocationHelper.INSTANCE.setStopLocationUpdateByUser(true);
Погоди, поиск позиции выключать не надо. Пользователям полезно видеть, где они находятся. Тут надо выключить только автоматическое центрирование на найденной позиции, если оно до этого было включено.

@vng подскажешь, как правильнее?

2022-09-21 08:57 UTC, biodranik commented on android/src/com/mapswithme/maps/intent/Factory.java
> +            LocationHelper.INSTANCE.setStopLocationUpdateByUser(true);
То же самое. Надо отключить только автоцентрирование, а не поиск позиции. Напомню, что у нас автопоиск позиции сейчас может и не включаться при запуске приложения. Кстати, логичнее тогда было бы проверку на апи делать именно там, а не здесь. 

cc @vng

2022-09-21 08:57 UTC, biodranik commented on android/src/com/mapswithme/maps/intent/Factory.java
> +                false);
Ну в одну же строчку на гитхабе влазит, зачем перенос?

2022-09-21 08:57 UTC, biodranik commented on map/mwm_url.cpp
> +char const * kCenterLatLon = "cll";
```suggestion
char constexpr kAppName[] = "appname";
char constexpr kCenterLatLon[] = "cll";
```

2022-09-21 08:57 UTC, biodranik commented on map/mwm_url.cpp
> +    }
else print warning and bad value.

2022-09-21 08:59 UTC, rtsisyk commented on android/src/com/mapswithme/maps/intent/Factory.java
> +            LocationHelper.INSTANCE.setStopLocationUpdateByUser(true);
Там нигде не показывает кнопки с позициями. Ситуация тут такая, что после вызова API сразу же стартует location helper и карта прыгает на текущую локацию. Почему не помогает nativeStopLocationFollow() я не понял. Видимо, надо где-то в settings.ini режим менять прям.

2022-09-21 09:02 UTC, rtsisyk commented on map/mwm_url.cpp
> +char const * kCenterLatLon = "cll";
Давай отдельно всякую косметику. Там еще 50 таких строчек, не хочу патч раздувать.

2022-09-22 07:36 UTC, biodranik commented on android/src/com/mapswithme/maps/intent/Factory.java
> +            LocationHelper.INSTANCE.setStopLocationUpdateByUser(true);
Я именно об этом и пишу. @vng знает, где что поправить. У нас сохраняется предыдущий режим при сворачивании приложения, и он же восстанавливается автоматом. Код восстановления режима должен учитывать, что это запуск апишки, и не включать автоцентрирование карты.

2022-09-22 07:38 UTC, biodranik commented on map/mwm_url.cpp
> +char const * kCenterLatLon = "cll";
Давай сразу, чтобы по два раза не вставать. Я уже потратил время. И ты уже тратишь время. Это наш самый ценный ресурс.

2022-10-04 13:04 UTC, vng commented
To clarify why we _should_ use animations. Calling enable point chooser invokes animation process:

Calling MwmActivity.showPositionChooser -> Framework::EnableChoosePositionMode -> FrontendRenderer::SetAddNewPlaceMode -> SetCenterEvent(isAnim = true).

2022-10-04 13:09 UTC, vng commented
Probably, a better fix is to pass destination point into showPositionChooserForAPI -> ...

2022-10-05 05:33 UTC, rtsisyk commented on android/src/com/mapswithme/maps/intent/Factory.java
> +                                       false);
Пофикшено.

2022-10-05 05:34 UTC, rtsisyk commented on android/src/com/mapswithme/maps/intent/Factory.java
> +            LocationHelper.INSTANCE.setStopLocationUpdateByUser(true);
Пофикшено уже.

2022-10-05 05:34 UTC, rtsisyk commented on android/src/com/mapswithme/maps/intent/Factory.java
> +                false);
Пофикшено.

2022-10-05 05:43 UTC, rtsisyk commented on map/mwm_url.cpp
> +    }
done

2022-10-05 05:43 UTC, rtsisyk commented on android/src/com/mapswithme/maps/intent/Factory.java
> +            LocationHelper.INSTANCE.setStopLocationUpdateByUser(true);
Поправлено.

2022-10-05 05:47 UTC, rtsisyk commented on map/mwm_url.cpp
> +char const * kCenterLatLon = "cll";
Не понял чем это лучше, чем то, что есть.

2022-10-05 05:49 UTC, rtsisyk commented
> Probably, a better fix is to pass destination point into showPositionChooserForAPI -> ...

I think that keeping `case ParsingResult.TYPE_SEARCH:` and `case ParsingResult.TYPE_CROSSHAIR:` together is better than moving `nativeSetViewportCenter` calls into MwmActivity.

2022-10-06 09:28 UTC, biodranik requested changes
Please fix iOS and replace Point2D with ms::LatLon

2022-10-06 09:28 UTC, biodranik commented on map/mwm_url.hpp
> +  m2::PointD GetCenterLatLon() const { return m_centerLatLon; }
Use ms::LatLon instead.

2022-10-07 07:38 UTC, biodranik requested changes
@vng Поправь лучше ты, пожалуйста, если есть возможность.

2022-10-07 07:38 UTC, biodranik commented on android/src/com/mapswithme/maps/intent/Factory.java
>            return true;
Этот ретурн надо выше внутрь if проверки latlon

2022-10-07 07:38 UTC, biodranik commented on drape_frontend/user_event_stream.cpp
> +    double const kEps = 1e-5;
```suggestion
    double constexpr kEps = 1e-5;
```

2022-10-07 07:38 UTC, biodranik commented on map/mwm_url.cpp
> +char const * kCenterLatLon = "cll";
Зачем вынес в глобальный namespace? Не надо его забивать. И сделать `std::string_view constexpr kCenterLatLon = "cll";`, такие константы в рантайме будут быстрее проверяться в operator==

2022-10-07 07:38 UTC, biodranik commented on map/mwm_url.cpp
>        return;
Почему ParseMapParam не возвращает ошибку? Ворнинги проигнорятся.

2022-10-07 07:38 UTC, biodranik commented on map/mwm_url.cpp
>        return;
То же самое: почему не возвращает ошибку? Родительский метод ParsedMapApi::Parse возвращает bool, надо его туда сразу пробрасывать, чтобы не огребать потом сюрпризов, отлаживая апишку.

2022-10-07 07:38 UTC, biodranik commented on map/mwm_url.cpp
> +      return;
То же самое, лучше возвращать сразу ошибку. Для этого можно модифицировать ForEachParam, чтобы он возвращался с ошибкой, если fn вернёт false.

2022-10-07 07:47 UTC, vng commented on android/src/com/mapswithme/maps/intent/Factory.java
>            return true;
Я хз как тут задумывалось, но по аналогии с др АПИ вызовами рядом, он может быть без координат - crosshair на центр экрана.

2022-10-07 08:01 UTC, rtsisyk commented on android/src/com/mapswithme/maps/intent/Factory.java
>            return true;
Оно же сейчас без этого параметра используется. Весь патч чтобы этот опциональный параметр добавить. Если он не передается, то в центр экрана ничего не крутилось и сейчас не крутится.

2022-10-07 08:03 UTC, rtsisyk commented on map/mwm_url.cpp
> +char const * kCenterLatLon = "cll";
Вынес, потому что в двух разных местах используется. Зачем там вообще эти namespaces не очень понятно. 

`std::string_view constexpr` чем-то лучше, чем старый добрый `const char *`?

2022-10-07 18:17 UTC, biodranik commented on map/mwm_url.cpp
> +char const * kCenterLatLon = "cll";
Лучше, он в компайл тайме считает и хранит длину строки. И использует её потом для ускорения различных операций как константу, вместо проверки на конец строки (на ноль).

2022-10-07 18:47 UTC, biodranik commented on map/mwm_url.cpp
> +string_view constexpr kAppName = "appname";
Какие причины держать это в глобальном неймспейсе?

2022-10-07 18:59 UTC, vng commented on map/mwm_url.cpp
> +string_view constexpr kAppName = "appname";
Он не глобальный, а url_scheme, тот самый в котором лежит ParseMapApi, в котором эти константы и используются. Уточненные внутренние namespace map, route, search - для конкретных типов запросов.

2022-10-07 21:44 UTC, biodranik approved these changes

2022-10-07 21:45 UTC, biodranik commented
@rtsisyk задокументируй, пожалуйста, этот метод в репо апишки, и сделай тестовых ссылок в https://github.com/organicmaps/url-processor/blob/master/public/test.html

2022-10-08 04:34 UTC, merged