[android] Enable lint and codestyle checks
organicmaps/organicmaps pull request #3524
Opened 2022-10-03 08:10 UTC by rtsisyk

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

##

The current configuration reports about ~300 issues that can be resolved easily.

[reports.zip](https://github.com/organicmaps/organicmaps/files/9695716/reports.zip)

2022-10-03 08:33 UTC, biodranik requested changes

2022-10-03 08:33 UTC, biodranik commented on android/build.gradle
> +    ignoreWarnings true
Почему не false?

2022-10-03 08:33 UTC, biodranik commented on .github/workflows/android-check.yaml
> +        run: gradle lintWebDebug
1. После мержа все PRы будут красными? Сначала надо внимательно исправить ошибки, потом включать чек.
2. Надо линтить каждый флавор и debug/release для надёжности. Там есть отличия. Т.е. просто `lint`

2022-10-03 08:33 UTC, biodranik commented on android/build.gradle
> +  showViolations = false
Для чего эти параметры и кем они используются?

2022-10-03 08:33 UTC, biodranik commented on android/build.gradle
> +  options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
Зачем нужны именно эти параметры? Почему мы не можем исправить или временно но явно пометить эти места сразу в коде?

2022-10-03 08:33 UTC, biodranik commented on android/build.gradle
> +  toolVersion = "10.3.4"
Что за тул? Почему версия хардкодится? Нам всегда нужна самая свежая и актуальная.

2022-10-03 08:33 UTC, biodranik commented on tools/android/formatter/checkstyle.xml
> +<!DOCTYPE module PUBLIC
Этот файл лучше положить в корень android и назвать lint.xml, будет проще его поддерживать и нам и другим контрибуторам.

2022-10-03 08:33 UTC, biodranik commented on android/build.gradle
> +  description 'Runs Checkstyle inspection against Android sourcesets.'
Зачем нужен этот кастомный таск? Для какой тулы?

2022-10-03 08:33 UTC, biodranik commented on android/build.gradle
> +  options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
У линтера есть даже baseline для этого, если я правильно понял. Но правильный подход — исправить сразу код.

2022-10-03 08:33 UTC, biodranik commented on tools/android/formatter/checkstyle.xml
> +    <module name="SuppressWithNearbyCommentFilter">
Это все возможные настройки самой актуальной версии линтера?

2022-10-03 08:50 UTC, rtsisyk commented on .github/workflows/android-check.yaml
> +        run: gradle lintWebDebug
Конечно же сначала починить надо, а потом этот PR мержить. Сейчас это больше для фиксации scope что именно будем фиксить. Можно ведь и не 300, а 30000 warnings включить.

2022-10-03 08:51 UTC, rtsisyk commented on android/build.gradle
> +  options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
Это при компиляции врубает проверки на unchecked и deprecated. Без этого данные проблемы не находятся.

2022-10-03 08:51 UTC, rtsisyk commented on android/build.gradle
> +  toolVersion = "10.3.4"
Я попробую убрать.

2022-10-03 08:51 UTC, rtsisyk commented on tools/android/formatter/checkstyle.xml
> +<!DOCTYPE module PUBLIC
Я положил туда же, где остальные форматтеры лежат.

2022-10-03 08:51 UTC, rtsisyk commented on android/build.gradle
> +  description 'Runs Checkstyle inspection against Android sourcesets.'
Для тулы checkstyle.

2022-10-03 08:52 UTC, rtsisyk commented on tools/android/formatter/checkstyle.xml
> +    <module name="SuppressWithNearbyCommentFilter">
Далеко не все возможные, а лишь те, на которые у меня хватило усидчивости попробовать вставить. 

https://checkstyle.sourceforge.io/checks.html

2022-10-03 08:54 UTC, rtsisyk commented on android/build.gradle
> +  showViolations = false
Для [gradle обёртки для `checkstyle`](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CheckstyleExtension.html). Попробую еще раз с `showViolations = true` чтобы ошибки печатало в консоль еще дополнительно.

2022-10-03 20:56 UTC, biodranik commented on .github/workflows/android-check.yaml
> +        run: gradle lintWebDebug
Огласи весь список, и критерии выбора.

2022-10-03 20:58 UTC, biodranik commented on tools/android/formatter/checkstyle.xml
> +<!DOCTYPE module PUBLIC
Этот файл — часть проекта, не надо его пихать туда, где файлы для IDE лежат.

2022-10-03 21:04 UTC, biodranik commented on android/build.gradle
> +  description 'Runs Checkstyle inspection against Android sourcesets.'
Проверять и энфорсить форматирование — это точно в самую последнюю очередь. Напомню, только после того, как Github научится игнорить формат-коммиты в git blame/git history.

2022-10-03 21:06 UTC, biodranik commented on tools/android/formatter/checkstyle.xml
> +    <module name="SuppressWithNearbyCommentFilter">
Зачем нам сразу две тулы? Предлагаю начать с линтера, он много знает про андроид, и находит критические вещи.

2022-10-04 11:50 UTC, vng commented
Давайте выключим deprecated, пофиксим остаток, помержим. Иначе это все будет висеть в _забытом_ PR очень долго.

2022-10-05 08:44 UTC, rtsisyk commented on tools/android/formatter/checkstyle.xml
> +    <module name="SuppressWithNearbyCommentFilter">
Линтер не умеет трахать мозг про отсутствие final в каждой первой строчке. Всё ведь только ради этого делалось.

2022-10-05 08:45 UTC, rtsisyk commented on android/build.gradle
> +  description 'Runs Checkstyle inspection against Android sourcesets.'
Тут форматирование и не проверяется нигде. Все чеки на форматтинг выключены.

2022-10-06 09:12 UTC, rtsisyk commented on android/build.gradle
> +    ignoreWarnings true
Я включил чтобы печаталось, но фейлится на них не будет. Там 1600 warnings.

2022-10-06 09:12 UTC, rtsisyk commented on android/build.gradle
> +  toolVersion = "10.3.4"
Выношу эту тулзу в отдельный PR.

2022-10-06 09:13 UTC, rtsisyk commented on tools/android/formatter/checkstyle.xml
> +    <module name="SuppressWithNearbyCommentFilter">
Выношу тулзу в отдельный PR.

2022-10-06 09:13 UTC, rtsisyk commented on tools/android/formatter/checkstyle.xml
> +<!DOCTYPE module PUBLIC
В отдельный PR.

2022-10-06 09:41 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +          factory.instantiate(getClassLoader(), MapFragment.class.getName());
Я пока до починки форматтинга не добрался еще.

2022-10-06 09:43 UTC, rtsisyk commented on android/src/com/mapswithme/util/LocationUtils.java
> +    return "fused".equals(location.getProvider());
Это системный класс. Почему-то раньше не было этой константы. По идее это всё равно при компиляции должно разруливаться, но почему-то линтер ругается, что на старых девайсах может не быть такой константы. Явно false-positive тут, т.к. у нас бы крешилось иначе везде. Но пусть подавится.

2022-10-06 09:50 UTC, vng commented on android/src/com/mapswithme/maps/MwmActivity.java
> +          factory.instantiate(getClassLoader(), MapFragment.class.getName());
Длина строк это индивидуальная настройка IDE.

2022-10-06 19:47 UTC, biodranik requested changes
Можно было бы помержить хотя бы однотипные безопасные правки.

Накидывай, пожалуйста, правки отдельными коммитами, чтобы было проще ревьюить. Я где мог делал suggest, чтобы одним кликом добавлялась правка.

2022-10-06 19:47 UTC, biodranik commented on android/build.gradle
> +  namespace 'com.mapswithme.maps'
```suggestion
  // TODO: Rename to app.organicmaps together with all sources.
  namespace 'com.mapswithme.maps'
```

2022-10-06 19:47 UTC, biodranik commented on android/build.gradle
> +    disable 'MissingTranslation','MissingQuantity', 'ByteOrderMark'
```suggestion
    // TODO: Fix these linter warnings too.
    disable 'MissingTranslation', 'MissingQuantity', 'ByteOrderMark'
```

2022-10-06 19:47 UTC, biodranik commented on android/build.gradle
> +  options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
```suggestion
  options.compilerArgs << '-Xlint:unchecked' << '-Xlint:deprecation'
```

2022-10-06 19:47 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +          factory.instantiate(getClassLoader(), MapFragment.class.getName());
```suggestion
      mMapFragment = (MapFragment) factory.instantiate(getClassLoader(), MapFragment.class.getName());
```
+1 к Вите. Не надо лишние строки создавать там, где не нужно.

2022-10-06 19:47 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
> +      intent.putExtra(DocumentsContract.EXTRA_EXCLUDE_SELF, true);
Этот флажок ввели только с M версии.

2022-10-06 19:47 UTC, biodranik commented on android/src/com/mapswithme/maps/downloader/MapManager.java
> +        .setPositiveButton(android.R.string.ok, new DialogInterface.OnClickListener()
А зачем поменял? Там же вопрос "Download over a cellular network connection?" Логичнее да/нет.

2022-10-06 19:47 UTC, biodranik commented on android/src/com/mapswithme/maps/routing/RoutingErrorDialogFragment.java
> +        downloader.show(requireActivity().getSupportFragmentManager(), downloader.getClass().getSimpleName());
Вынести requireActivity().getSupportFragmentManager() в final переменную

2022-10-06 19:47 UTC, biodranik commented on android/src/com/mapswithme/maps/routing/RoutingPlanFragment.java
> +    if (requireActivity() instanceof RoutingBottomMenuListener)
В трёх местах используется, лучше сделать переменную.

2022-10-06 19:47 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
> +          {
Капец, вот это косяк ) Молодец линтер, молодец Рома )

2022-10-06 19:47 UTC, biodranik commented on android/src/com/mapswithme/maps/widget/WheelProgressView.java
> -        .getWrappedDrawable() : mCenterDrawable);
А не надо было заменить getWrappedDrawable на getDrawable (доступен с M и выше)? Почему убрал проверку?

2022-10-06 19:47 UTC, biodranik commented on android/src/com/mapswithme/util/LocationUtils.java
> +    return "fused".equals(location.getProvider());
LocationManager.FUSED_PROVIDER определяется только в API 31

2022-10-07 05:01 UTC, rtsisyk commented on android/build.gradle
> +    disable 'MissingTranslation','MissingQuantity', 'ByteOrderMark'
Пожалуйста, пользуйтесь GitHub в качестве issue трекера, а не записками на полях.

2022-10-07 05:01 UTC, rtsisyk commented on android/build.gradle
> +  namespace 'com.mapswithme.maps'
Пожалуйста, пользуйтесь GitHub в качестве issue трекера, а не записками на полях.

2022-10-07 05:02 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
> +          {
Это косяк кривого codestyle. Надо ставить скобки и не экономить characters на диске.

2022-10-07 05:03 UTC, rtsisyk commented on android/src/com/mapswithme/maps/widget/WheelProgressView.java
> -        .getWrappedDrawable() : mCenterDrawable);
Я тупил в это место очень долго, в итоге я просто не смог найти случая, когда там реально этот DrawableWrapper существует.

2022-10-07 05:09 UTC, rtsisyk commented on android/src/com/mapswithme/maps/routing/RoutingPlanFragment.java
> +    if (requireActivity() instanceof RoutingBottomMenuListener)
Activity? Да там вагон таких мест. В целом не вижу проблемы. Поменял здесь.

2022-10-07 05:11 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +          factory.instantiate(getClassLoader(), MapFragment.class.getName());
Надо format code сделать на все файлы разово и дальше включить эту проверку. После чего проблема уйдет. Изменений там будет немного.

2022-10-07 05:11 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +          factory.instantiate(getClassLoader(), MapFragment.class.getName());
Сейчас пришлось выключить форматтирование при сохранении и каждый раз править руками, потому что иногда в diff попадают formatting изменения, чего происходить не должно.

2022-10-07 05:18 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +          factory.instantiate(getClassLoader(), MapFragment.class.getName());
У меня там стоит 120. Это всё не будет работать до тех пор, пока не будет включено принудительное форматирование кода в IDE. Сейчас приходится отключать, т.к. это создает правки в ненужных местах. Но в целом там почти всё соответствует и изменения будут не очень объемными, git blame не сдохнет.

2022-10-07 05:26 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
> +          {
Нет, это два других косяка: 
1. Того, кто писал код.
2. Того, кто ревьюил код.

2022-10-07 05:26 UTC, vng commented on android/src/com/mapswithme/maps/MwmActivity.java
> +          factory.instantiate(getClassLoader(), MapFragment.class.getName());
Зачем принудительно форматировать в IDE? (remove trailing whitespaces полезно) Я считаю что человек с включенной головой пишет красивее, чем машина, ставящая отступы и переносы по шаблону. Ты конечно можешь включить что угодно, но патчи с полезным изменением одной строки и переформатированием всего модуля - это плохо.

2022-10-07 05:27 UTC, vng commented on android/build.gradle
> +  namespace 'com.mapswithme.maps'
В смысле комментарии в коде это плохо?

2022-10-07 05:27 UTC, biodranik commented on android/build.gradle
> +    disable 'MissingTranslation','MissingQuantity', 'ByteOrderMark'
Там ещё пробел поправлен. Мы оставляем туду там, где надо сделать что-то, в коде. Ты выше такой же удалил. Пожалуйста, вставь. В линтере не должно быть исключений в идеале.

2022-10-07 05:27 UTC, biodranik commented on android/build.gradle
> +  namespace 'com.mapswithme.maps'
Нет, это нужно в код, в релевантное место. Среди issues потеряется.

2022-10-07 07:25 UTC, rtsisyk commented on android/AndroidManifest.xml
> -      </intent-filter>
Ругаются и Android Studio и Android Lint.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/1799054/194496167-3ff546bc-508d-496d-a3f7-80bbaaddb0e8.png">

<img width="859" alt="image" src="https://user-images.githubusercontent.com/1799054/194496364-cd4d83f0-007d-4381-8d77-a3905b720c5b.png">

Lint помечает это как ошибку, хотя это не звучит критично. Судя по всему, в текущем виде оно действительно некорректно. 

Я переделал чтобы не ругалось. Ссылки в gmail и в браузере открываются. Проверял API 21, и Android 12-13. Вроде выглядит нормально теперь.

2022-10-07 07:26 UTC, rtsisyk commented on android/build.gradle
> +  namespace 'com.mapswithme.maps'
Вставил ссылку на GitHub.

2022-10-07 07:28 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
> +          {
Конечно. Наверняка сначала были скобки, а потом ревьювер попросил их убрать, после чего туда случайно добавилась еще одна строчка. Лучше бы сопли по одной строки не оставлять, особенно если else есть. Условный if() return; еще можно, а больше одной строчки или else - нет. Иначе так и будем находить баги ради экономии на спичках.

2022-10-07 07:28 UTC, rtsisyk commented on android/src/com/mapswithme/maps/widget/WheelProgressView.java
> -        .getWrappedDrawable() : mCenterDrawable);
Я протестировал этот контрол на эмуляторе API 21. Вроде всё выглядит норм, всё крутится, ничего не падает.

2022-10-07 07:39 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +          factory.instantiate(getClassLoader(), MapFragment.class.getName());
Разберемся с этим вопросом отдельно. Здесь я поменял.

2022-10-07 07:39 UTC, rtsisyk commented on android/src/com/mapswithme/maps/base/BaseToolbarActivity.java
> +    final FragmentFactory factory = getSupportFragmentManager().getFragmentFactory();
Done.

2022-10-07 07:40 UTC, rtsisyk commented on android/build.gradle
> +    disable 'MissingTranslation','MissingQuantity', 'ByteOrderMark'
> В линтере не должно быть исключений в идеале.

Капитан очевидность. Как только поправим 1600 проблем, так сразу.

2022-10-07 07:40 UTC, rtsisyk commented on android/build.gradle
> +  options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
Поменял, хотя что то, что это одинаково.

2022-10-07 07:40 UTC, rtsisyk commented on android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
> +          {
С этим разберемся отдельно потом.

2022-10-07 07:40 UTC, rtsisyk commented on android/src/com/mapswithme/maps/routing/RoutingErrorDialogFragment.java
> +        downloader.show(requireActivity().getSupportFragmentManager(), downloader.getClass().getSimpleName());
Поменял.

2022-10-07 07:47 UTC, biodranik reviewed
Можно будет мержить, но сначала я проверю на своём Android 5, а то мало ли.

2022-10-07 07:55 UTC, biodranik commented on android/src/com/mapswithme/maps/settings/SettingsPrefsFragment.java
> +          {
Я против делать весь код корявее только потому, что кто-то когда-то косячил в прошлом. Пока мы ревьюим, такие косяки не пройдут. Из-за именно такого подхода сейчас всех пассажиров на самолёты трясут постоянно на секьюрити. А толку мало.

2022-10-07 12:35 UTC, biodranik approved these changes

2022-10-07 21:48 UTC, merged