[android] Show "turn on Google's location service" dialog - NEW
organicmaps/organicmaps pull request #3543
Opened 2022-10-05 08:34 UTC by rtsisyk

[android] Show "turn on Google's location service" dialog

In very rare case Google Location Provider asks user to enable
Wi-Fi for "for a better (?surveillance) experience":

 1. Airplane is OFF;
 2. Wi-Fi is OFF;
 3. GPS is OFF;
 
Before this patch the app just downgraded to use the system location
provider, which waited until HW GPS is found.

With this patch the app dispalys "For a better experience, turn on
device location, which uses Google's location settings". Pressing
"Yes" just enables Wi-Fi without any other changes in the system.
There are no other practical outcomes to users other than reminding
about disabled Wi-Fi.

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2022-10-05 08:43 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> -    if (MapFragment.nativeIsEngineCreated())
I have some doubts heres.

2022-10-05 11:46 UTC, vng requested changes

2022-10-05 11:46 UTC, vng commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    Logger.d(TAG, "");
Имя модуля/класса/функции напишется и с пустой строкой?

2022-10-05 11:46 UTC, vng commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +        mContext.getString(R.string.current_location_unknown_title));
Может как в диалоге выше стоит отдельно вызвать setMessage + setTitle?
Как странно мы это _слили_ в одну строку и назвали message.

2022-10-05 11:46 UTC, vng commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    Logger.d(TAG, "notifyMyPositionModeChanged(): " + LocationState.nameOf(newMode));
Раз уж Logger и так пишет имя функции (как я понял по логам выше), то стоит убрать тавтологию "notifyMyPositionModeChanged"

2022-10-05 11:46 UTC, vng commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    LocationHelper.INSTANCE.attach(this);
Я глянул по коду. LocationHelper.attach вызывает LocationState.nativeGetMode
Наверное стоит там внутри проверить:
```
return g_framework ? g_framework->GetMyPositionMode() : location::PendingPosition;
```

2022-10-05 11:58 UTC, vng commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    LocationHelper.INSTANCE.attach(this);
Даже в дополнение можно добавить ASSERT(g_framework, ()); чтобы крякнулось в дебаге. Это поможет лучше понять наш lifecycle.

2022-10-06 06:36 UTC, rtsisyk commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +        mContext.getString(R.string.current_location_unknown_title));
А черт знает почему так было сделано. Вроде выглядело нормально. Попробую.

2022-10-06 06:36 UTC, rtsisyk commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    Logger.d(TAG, "notifyMyPositionModeChanged(): " + LocationState.nameOf(newMode));
Ага, тут при переносе кода не вычистил.

2022-10-06 06:40 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    LocationHelper.INSTANCE.attach(this);
Вот хочется вычислить все потенциальные места где это может грохаться. Я вижу, что после переделки мы можем показывать диалог пермишенов локации на экране, при этом в фоне будет продолжать отрисовываться карта. Причем после выдачи пермишенов локация на карте обновится. Вот не хочется чтобы где-то упало из-за этого. Например, switchToTheNextMode точно падает. Наверное, надо пройтись по всему стеку и повставлять ассерты.

Моя проблема тут была в том, что установка новых хендлеров на локацию в Activity возможна только до окончания onStart(). В целом абстракция LocationHelper весьма странная. В первом патче я попробовал вынести оттуда всю работу с Activity совсем. Потом показалось, что лучше все же наоборот всё запихать в него, чтобы в MwmActivity осталось только onLocationUpdated и onLocationDenied. Вроде бы вторая версия стала более понятной и менее протекающей.

2022-10-06 07:04 UTC, vng commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    LocationHelper.INSTANCE.attach(this);
Расставь ассерты в nativeGetMode, nativeSwitchToNextMode и для безопасности после ассерта проверяй g_framework как я выше написал. Задокументируем эту логику.

2022-10-06 09:39 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    LocationHelper.INSTANCE.attach(this);
`g_framework` там точно не null везде, мы его создаем в самой первой activity,
Вот nativeSwitchToNextMode() крешится с `ASSERT(IsDrapeEngineCreated(), ());`. Кроме как по клику на кнопку с локацией и в диалоге "продолжить искать локацию" оно не зовется нигде. Добавил на всякий случай проверку.

2022-10-06 09:40 UTC, rtsisyk commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +        mContext.getString(R.string.current_location_unknown_title));
Поменял тут, посмотрю как будет выглядеть.

2022-10-06 12:50 UTC, vng commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    LocationHelper.INSTANCE.attach(this);
Где ты добавил проверку? Я не вижу вообще модифицированных cpp файлов ..

2022-10-06 12:51 UTC, vng commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +      throw new IllegalStateException("Engine is not created yet");
А, вот оно где .. Ты уверен что будет ок, может лучше в cpp поставить ассерт, а не складываться тут намертво?

2022-10-06 20:45 UTC, biodranik requested changes
Это надо хорошо потестить. Попробую позже на своих девайсах.

2022-10-06 20:45 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +        if (!LocationUtils.isFineLocationGranted(getApplicationContext()))
А переключение режима выше не свалится, если пермишна нет?

2022-10-06 20:45 UTC, biodranik commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    if (!LocationUtils.isFineLocationGranted(getApplicationContext()))
А как эти проверки и код будут себя вести, если юзер осознанно дал только неточный пермишн для позиции по сети?

2022-10-06 20:45 UTC, biodranik commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    Logger.d(TAG, "");
Надо сделать Logger.d с одним параметром тогда, пустая строка странно смотрится. А ещё лучше тут печатать текущий режим, и в какой режим переключается.

2022-10-06 20:45 UTC, biodranik commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +      mCompassData = new CompassData();
Лучше создать в конструкторе один раз, чем сто раз в секунду делать if.

2022-10-06 20:45 UTC, biodranik commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    Logger.d(TAG, "");
```suggestion
    Logger.d(TAG);
```

2022-10-06 20:45 UTC, biodranik commented on android/src/com/mapswithme/maps/location/LocationHelper.java
>          !(mLocationProvider instanceof AndroidNativeProvider))
```suggestion
    if (LocationUtils.areLocationServicesTurnedOn(mContext) && !(mLocationProvider instanceof AndroidNativeProvider))
```

2022-10-06 20:45 UTC, biodranik commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    Logger.d(TAG, "");
Оставь это в i тут и ниже, важно будет видеть в логах юзеров.

2022-10-06 20:45 UTC, biodranik commented
И дофиксить все комментарии Вити.

2022-10-07 07:33 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    LocationHelper.INSTANCE.attach(this);
`ASSERT(IsDrapeEngineCreated(), ());` уже стояла в `void Framework::SwitchMyPositionNextMode()` и у меня тарм крешилось, когда я случайно вызвал этот метод не там, где надо. Сейчас он только по кнопкам вызывается, так что должно быть ок.

```
void Framework::SwitchMyPositionNextMode()
{
  ASSERT(IsDrapeEngineCreated(), ());
  m_work.SwitchMyPositionNextMode();
}
```

Касательно g_framework. Мы его инициализируем внутри SplashActivity задолго до запуска LocationHelper. Я могу везде понавставлять `ASSERT(g_framework, ());`, но поверьте, оно и так точно упадет если g_framework == NULL без необходимости дополнительных ассертов.

2022-10-07 07:34 UTC, rtsisyk commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +      throw new IllegalStateException("Engine is not created yet");
Там тоже стоит. Но когда разваливается нативная часть это всё равно менее приятно, чем когда ассерт еще в java вылетает. Но если сильно хочется, то могу удалть тут.

2022-10-07 07:34 UTC, rtsisyk commented on android/flavors/gms-enabled/com/mapswithme/maps/location/GoogleFusedLocationProvider.java
> +        int statusCode = ((ApiException) e).getStatusCode();
фпизду

2022-10-07 07:36 UTC, rtsisyk commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    Logger.d(TAG, "");
Надо в патче с логгером это смотреть. В рамках этого PR делать не буду.

2022-10-07 10:12 UTC, vng commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +      throw new IllegalStateException("Engine is not created yet");
Смотри, я хочу валится в дебаге сразу и видеть хотя бы колстек, но продолжать работать в релизе - я думаю тут это возможно, мы не нарушаем никакой констрейнт. Потому лучше убрать throw. И да, в cpp assert сработает.

2022-10-07 10:20 UTC, vng commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    LocationHelper.INSTANCE.attach(this);
Я уже нашел внизу все ок.

Почему ассерт лучше, если конечно не мусорит излишне код:
Да g_framework-> упадет, но скорее всего молча по SEG fault и ты без отладчика это даже не увидишь.
ASSERT(g_framework) упадет и напишет в лог вменяемое сообщение со строкой и модулем.

Вставлять ничего не надо, убери просто throw, я написал ниже.

2022-10-09 05:38 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    LocationHelper.INSTANCE.attach(this);
Убрал throw. Добавил явные ассерты на g_framework. Удалил лишние прослойки в двух коллбеках. Улучшил логгирование. Пока ничего не падает, но продолжаю тестировать.

2022-10-09 05:38 UTC, rtsisyk commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +      throw new IllegalStateException("Engine is not created yet");
Убрал это.

2022-10-09 05:39 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +        if (!LocationUtils.isFineLocationGranted(getApplicationContext()))
Переключение режима не свалится без пермишена.

2022-10-09 05:40 UTC, rtsisyk commented on android/src/com/mapswithme/maps/MwmActivity.java
> +    if (!LocationUtils.isFineLocationGranted(getApplicationContext()))
Андроид сам перестанет показывать диалог после отказа.

2022-10-09 05:40 UTC, rtsisyk commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    Logger.d(TAG, "");
Добавил это, так уж и быть.

2022-10-09 05:40 UTC, rtsisyk commented on android/src/com/mapswithme/maps/location/LocationHelper.java
> +    Logger.d(TAG, "");
оставил.

2022-10-09 06:04 UTC, vng commented on android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
> +      oldTop, int oldRight, int oldBottom)
Это такое автоформатирование? :) int оставил на одной строке, oldTop имя перенес на следующую ..

2022-10-09 06:05 UTC, vng commented on android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
> +      oldTop, int oldRight, int oldBottom)
Разумно весь блок "int oldLeft, int oldTop, int oldRight, int oldBottom" перенести на новую строку

2022-10-09 06:08 UTC, vng commented on android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
>    }
Хм, а эта правка точно для этого реквеста?? Ты случаем не забирал другой PR или не было хитрого мержа?
Надо просто удалить функцию onLocationError, onLayoutChange ты скорее всего забрал по ошибке.

2022-10-09 06:29 UTC, rtsisyk commented on android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
>    }
Похоже на то. Восстанавливаю.

2022-10-09 06:34 UTC, rtsisyk commented on android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
> +      oldTop, int oldRight, int oldBottom)
Это bad merge.

2022-10-09 06:34 UTC, rtsisyk commented on android/src/com/mapswithme/maps/widget/placepage/RichPlacePageController.java
>    }
Починил.

2022-10-09 06:35 UTC, vng approved these changes

2022-10-10 22:34 UTC, biodranik approved these changes
Давайте активно тестить в мастере.

2022-10-10 22:35 UTC, merged