[classifier] Added several new types.
organicmaps/organicmaps pull request #3557
Opened 2022-10-07 16:04 UTC by vng

Closes https://github.com/organicmaps/organicmaps/issues/3542
https://github.com/organicmaps/organicmaps/issues/3122
Closes https://github.com/organicmaps/organicmaps/issues/2976
https://github.com/organicmaps/organicmaps/issues/2931
https://github.com/organicmaps/organicmaps/issues/2873

Closes https://github.com/organicmaps/organicmaps/issues/3497
Closes https://github.com/organicmaps/organicmaps/issues/3297

2022-10-07 17:23 UTC, biodranik requested changes

2022-10-07 17:23 UTC, biodranik commented on data/strings/types_strings.txt
> +    en = Ditch
en = Ditch
ar = ﻦﻣ ﺺﻠﺨﺘﻳ
be = Канава
bg = Канавка
cs = Příkop
da = Grøft
de = Graben
el = Χαντάκι
es = Abandone
eu = Lubakia
fa = ﻝﺍﺩﻮﮔ
fi = Oja
fr = Fossé
he = שׁוֹטנְלִ
hu = Árok
id = Parit
it = Fosso
ja = 溝
ko = 도랑
nb = Grøft
nl = Gleuf
pl = Rów
pt = Vala
pt-BR = Fosso
ro = Şanţ
ru = Канава
sk = Priekopa
sv = Dike
sw = Shimo
th = คู
tr = Hendek
uk = Канава
vi = Đào mương
zh-Hans = 沟渠
zh-Hant = 溝渠

2022-10-07 17:23 UTC, biodranik commented on data/strings/types_strings.txt
> +  [type.leisure.dance]
Добавить и amenity=dancing_school ?

2022-10-07 17:23 UTC, biodranik commented on data/strings/types_strings.txt
> +    en = Dance Hall
en = Dance Hall
ar = ﺺﻗﺮﻟﺍ ﺔﻟﺎﺻ
be = Танцавальная зала
bg = Зала за танци
cs = Taneční hala
da = Dansesal
de = Tanzsaal
el = Αίθουσα χορού
es = Baile (salón
eu = Dantza Aretoa
fa = ﺺﻗﺭ ﻦﻟﺎﺳ
fi = Tanssisali
fr = Salle de danse
he = םידוקיר םלוא
hu = Táncterem
id = Lantai dansa
it = Sala da ballo
ja = ダンスホール
ko = "댄스홀"
nb = Dansesal
nl = Danszaal
pl = Sala taneczna
pt = Salão de Dança
pt-BR = Salão de dança
ro = Sala de dans
ru = Танцпол
sk = Tanečná hala
sv = Danshall
sw = Ukumbi wa Ngoma
th = แดนซ์ฮอลล์
tr = Dans salonu
uk = Танцювальний зал
vi = Vũ trường
zh-Hans = 舞厅
zh-Hant = 舞廳

2022-10-07 17:23 UTC, biodranik commented on data/styles/clear/include/Basemap.mapcss
> +area|z12-[leisure=garden],
Зачем опускать? Разве это не такой же хороший ориентир, как лес?

2022-10-07 17:23 UTC, biodranik commented on data/styles/clear/include/Icons.mapcss
> -line|z16-[barrier=block],
Но ведь линейные барьеры тоже есть, и их надо рисовать обязательно.

2022-10-07 18:49 UTC, vng commented on data/classificator.txt
> +            motorcar  -
других подтипов в осме нет, ну или я не вижу по taginfo

2022-10-07 18:49 UTC, vng commented on data/classificator.txt
> +        kissing_gate  -
он в replace_tags

2022-10-07 18:50 UTC, vng commented on data/strings/types_strings.txt
> +    en = Ditch
У нас есть waterway-ditch "канава". Это же должен быть "Ров", но я хз как объяснить на английском :)

2022-10-07 18:52 UTC, vng commented on data/styles/clear/include/Basemap.mapcss
> +area|z12-[leisure=garden],
Он уже z12, тут была опечатка, где задается z-order. Правка для консистентности.

2022-10-07 18:53 UTC, vng commented on data/styles/clear/include/Icons.mapcss
> -line|z16-[barrier=block],
Это все - точечные барьеры, которые задаются символом. line тут была опечатка. Правка для консистентности (на стили это в целом не влияет).

2022-10-07 19:55 UTC, biodranik commented on data/classificator.txt
> +            motorcar  -
Проблема в том, что там пачка основных типов (не только для charging_station, но и для обычной заправки, да и вообще для всего):
- motorcar
- bicycle
- motorhome
- hgv
- lhv
- scooter
- наверняка ещё что-то, менее популярное

У каждого этого типа много субтэгов:
<img width="312" alt="image" src="https://user-images.githubusercontent.com/170263/194642034-462a67b1-b6ef-45ba-aac6-f19de847066d.png">

Делать на каждый тип субтип? Только для key=yes? Это потребует слишком много комбинаций типов. Надо какой-то более универсальный механизм, слишком много полезной информации теряется, нужной как для POI, так и для роутинга (например, маршруты для траков, RV, скутеров).

Какие ещё есть варианты, кроме этих? Какой лучше?
1. Как сейчас, подтипы.
2. Сделать отдельные типы motorcar, bicycle, etc. и в них хранить метаинфу в каком-то одном универсальном поле типа values (и там можно список любых значений типа yes, access, maxweight).
3. Не делать отдельные типы, а навешать поля с метаинфой motorcar, bicycle, .. на каждую фичу
4. Не делать отдельные типы, а всю эту инфу хранить пачкой в одном дополнительном метаинфо поле (можно его хранить в сжатом виде для скорости, если нужно)
5. Другие варианты?

2022-10-07 19:58 UTC, biodranik commented on data/strings/types_strings.txt
> +    en = Ditch
Moat - это Ditch с водой. В наших языках и то и то - ров.

en = Ditch
ar = ﻕﺪﻨﺧ
be = Роў
bg = Ров
cs = Hradní příkop
da = Voldgrav
de = Graben
el = Τάφρος
es = Foso
eu = Lubanarroa
fa = ﻕﺪﻨﺧ
fi = Vallihauta
fr = Fossé
he = ןגֵמָ תלַעָתְ
hu = Várárok
id = Parit
it = Fossato
ja = 堀
ko = "해자 외호"
nb = Vollgrav
nl = Gracht
pl = Fosa
pt = Vala
pt-BR = Fosso
ro = Şanţ
ru = Ров
sk = Priekopa
sv = Vallgrav
sw = Moti
th = คูเมือง
tr = Hendek
uk = Рів
vi = Hào nước
zh-Hans = 护城河
zh-Hant = 護城河

2022-10-07 20:03 UTC, vng commented on data/classificator.txt
> +            motorcar  -
Откуда этот скриншот? Для комбинаций тегов, которые присутствуют вместе с charging_station я смотрел это:
https://taginfo.openstreetmap.org/tags/amenity=charging_station#combinations

Ты все правильно описал, но сейчас нам за глаза на пару лет хватит 2х типов: motorcar и все остальное.

2022-10-07 20:08 UTC, vng commented on data/classificator.txt
> +            motorcar  -
Я так понимаю, что скрин из fuel. Собственно, пока EV будут развиваться, так же будет развиваться и система ОСМ тегов к ним. Сейчас самый простой механизм для _дифференцированной_ отрисовки - это типы классификатора. Когда будем наращивать функционал, все это, думаю, будем хранить в метадате или ее аналоге для какой-то быстрой вычитки для отрисовки.

2022-10-08 04:43 UTC, vng commented on data/strings/types_strings.txt
> +  [type.leisure.dance]
Добавлю в replace: https://wiki.openstreetmap.org/wiki/Tag:amenity%3Ddancing_school

2022-10-08 07:58 UTC, biodranik commented on data/strings/types_strings.txt
> +  [type.leisure.dance]
Надо в редакторе же дать будет возможность добавлять. Как там будем делать?

2022-10-08 08:00 UTC, biodranik commented on data/strings/types_strings.txt
> +  [type.leisure.dance]
Возможно танц холлы осмеры и так замапят, надо тогда оставить тип школы, их чаще будут добавлять и удалять.

2022-10-08 08:24 UTC, starsep requested changes

2022-10-08 08:24 UTC, starsep commented on data/strings/types_strings.txt
> +    pl = Fosa
```suggestion
    pl = Rów
```

2022-10-08 09:26 UTC, vng commented on data/strings/types_strings.txt
> +  [type.leisure.dance]
amenity=dancing_school deprecated как видно по ссылке.

2022-10-08 15:58 UTC, biodranik approved these changes

2022-10-09 07:59 UTC, MetehanOzyurek approved these changes

2022-10-09 20:26 UTC, Kazing approved these changes

2022-10-09 21:04 UTC, matheusgomesms requested changes
I made some comments to fix some Portuguese translations.

2022-10-09 21:04 UTC, matheusgomesms commented on iphone/Maps/LocalizedStrings/pt-BR.lproj/Localizable.strings
> +"type.barrier.ditch" = "Fosso";
Vala

2022-10-09 21:04 UTC, matheusgomesms commented on iphone/Maps/LocalizedStrings/pt-BR.lproj/Localizable.strings
> +"type.barrier.kissing_gate" = "Portão";
Quebra-corpo

2022-10-09 21:04 UTC, matheusgomesms commented on iphone/Maps/LocalizedStrings/pt.lproj/Localizable.strings
> +"type.leisure.dance" = "Salão de Dança";
Salão de dança (lowercase 'd')

2022-10-09 21:04 UTC, matheusgomesms commented on iphone/Maps/LocalizedStrings/pt.lproj/Localizable.strings
> +"type.natural.desert" = "Desert";
Deserto

2022-10-09 21:04 UTC, matheusgomesms commented on android/res/values-pt/strings.xml
> +	<string name="type.leisure.dance">Salão de Dança</string>
Salão de dança (lowercase 'd')

2022-10-09 21:04 UTC, matheusgomesms commented on android/res/values-pt-rBR/strings.xml
> +	<string name="type.barrier.ditch">Fosso</string>
Vala

2022-10-09 21:04 UTC, matheusgomesms commented on android/res/values-pt-rBR/strings.xml
> +	<string name="type.barrier.kissing_gate">Portão</string>
Quebra-corpo

2022-10-09 21:05 UTC, matheusgomesms commented
And why isn't Kissing Gate = Kissing Gate in English? Is it on purpose to be just 'Gate'?

2022-10-09 21:38 UTC, dvdmrtnz commented on data/strings/types_strings.txt
> +    es = Baile (salón
Salón de baile

2022-10-10 06:23 UTC, LaoshuBaby reviewed
1. Please add zh-hant translator to zh team
2. ditch don't means 护城河
3. kissing gate can't found Chinese name, If need exact name, maybe you can use original English value directly? I don't know. 😥

2022-10-10 06:23 UTC, LaoshuBaby commented on android/res/values-zh/strings.xml
> +	<string name="type.barrier.ditch">护城河</string>
```suggestion
	<string name="type.barrier.ditch">沟渠</string>
```
护城河 means moat in English, maybe 沟渠 fit barrier=ditch more exactly.

(Please also change in iOS version)

2022-10-10 06:23 UTC, LaoshuBaby commented on android/res/values-zh-rTW/strings.xml
> +	<string name="type.barrier.ditch">護城河</string>
@s8321414 maybe you need ask @rtsisyk add you to [translation-zh](https://github.com/orgs/organicmaps/teams/translations-zh) mentioned in #1489

2022-10-10 06:23 UTC, LaoshuBaby commented on android/res/values-zh/strings.xml
> +	<string name="type.barrier.kissing_gate">门</string>
`kissing gate` don't have a exactly translation name in Chinese, those things are seldom seen in China(This is the first time I know this kind of barrier), I also don't know how to translate it 😥

2022-10-10 09:18 UTC, jimcarst approved these changes

2022-10-10 21:16 UTC, matheusgomesms requested changes

2022-10-10 21:16 UTC, matheusgomesms commented on iphone/Maps/LocalizedStrings/pt-BR.lproj/Localizable.strings
> +"type.barrier.kissing_gate" = "Portão";
This is still missing

2022-10-11 08:48 UTC, matheusgomesms approved these changes

2022-10-14 07:06 UTC, merged