[android][ios] Add GitHub and Telegram links
organicmaps/organicmaps pull request #369
Opened 2021-05-04 08:56 UTC by rtsisyk

I didn't have translation for "Rate us on GitHub" and "Join us on Telegram", so I decided to replace "Like on Facebook" with "Facebook" and "Follow on Twitter" with "Twitter".

<img width="288" alt="Screenshot 2021-05-04 at 11 52 05" src="https://user-images.githubusercontent.com/1799054/116981047-afa58480-accf-11eb-87f7-e357e06abe09.png">

2021-05-04 10:26 UTC, vng requested changes
Это все субъективно, но ИМХО лучше когда есть глагол как побуждение к действию.
Для GitHub тоже можно взять Follow как в Twitter.

Я бы сделал такой порядок:
- Website
- Telegram
- Like on Facebook
- Follow on Twitter
- Follow on GitHub
- OpenStreetMap

2021-05-04 19:08 UTC, biodranik commented
Можно будет улучшать.
Follow us on:
- Telegram
- Github (первыми самые важные для нас каналы)
- Facebook
- Twitter (кто его будет вообще вести? просто новости репостить?)

2021-05-04 19:11 UTC, biodranik commented on android/src/com/mapswithme/util/Constants.java
>      public static final String MWM_PRO_PACKAGE = "com.mapswithme.maps.pro";
Эти две константы тоже выпили.

2021-05-04 19:13 UTC, biodranik approved these changes

2021-05-04 19:34 UTC, vng commented
Как GitHub важнее? Про него то знает всего пару десятков наших пользователей :)

2021-05-05 06:02 UTC, rtsisyk commented
>Это все субъективно, но ИМХО лучше когда есть глагол как побуждение к действию.
> Для GitHub тоже можно взять Follow как в Twitter.

У нас нет строк для этого. Если посмотришь, то название Twitter в половине языков тоже как-то склоняется. Я не особый специалист по языкам чтобы угадать как будет склоняться Telegram или GitHub.

2021-05-05 06:39 UTC, merged