[strings] Add missing translations (historic)
organicmaps/organicmaps pull request #3764
Opened 2022-10-30 13:52 UTC by j13m126

I used wikidata, deepl and google translate to add missing translations to all historic POIs
Further:

- added missing pois to `categories.txt`
- sorted and added languages in `categories.txt`
- removed duplicate pt-BR translations

Signed-off-by: Lukas Kronberger <j13m126@posteo.de>

2022-10-30 14:08 UTC, rtsisyk approved these changes

2022-10-30 14:29 UTC, biodranik requested changes

2022-10-30 14:29 UTC, biodranik commented on data/categories.txt
> +en:City Walls
Should it be City Wall (single vs plural) here and in all derived translations?

2022-10-30 14:29 UTC, biodranik commented on data/categories.txt
> +be:Гарадскія сцены
```suggestion
be:Гарадскі вал
```

2022-10-30 14:29 UTC, biodranik commented on data/categories.txt
> +be:Помнік
```suggestion
be:4Помнік
```

2022-10-30 14:29 UTC, biodranik commented on data/categories.txt
>  bg:Кораб|лодка|туризъм
```suggestion
bg:Кораб|лодка
```

2022-10-30 14:29 UTC, biodranik commented on data/categories.txt
> +be:Магіла
```suggestion
be:Склеп|магіла
```

2022-10-30 15:12 UTC, biodranik commented on data/categories.txt
> +en:City Walls
Reusing with `ref =` is a good idea.

2022-10-31 10:08 UTC, jimcarst approved these changes

2022-10-31 12:36 UTC, matheusgomesms requested changes
Looks good, just made some fix suggestions in Portuguese.

2022-10-31 12:36 UTC, matheusgomesms commented on data/categories.txt
> +pt:Muralha de cidade
Just 'Muralha' is better

2022-10-31 12:36 UTC, matheusgomesms commented on data/categories.txt
>  pt:Forte histórico
Just 'Forte'

2022-10-31 12:36 UTC, matheusgomesms commented on data/categories.txt
> +pt:Escultura memorial
Only 'Escultura'

2022-10-31 12:36 UTC, matheusgomesms commented on data/categories.txt
> +pt:Estátua memorial
Only 'Estátua'

2022-10-31 12:36 UTC, matheusgomesms commented on data/strings/types_strings.txt
>      pt = Histórico
Objeto histórico

2022-10-31 12:36 UTC, matheusgomesms commented on data/strings/types_strings.txt
>      pt = Muralha de cidade
Muralha

2022-10-31 12:36 UTC, matheusgomesms commented on data/strings/types_strings.txt
>      pt = Forte histórico
Forte

2022-10-31 12:36 UTC, matheusgomesms commented on data/strings/types_strings.txt
>      pt = Escultura memorial
Escultura

2022-10-31 12:36 UTC, matheusgomesms commented on data/strings/types_strings.txt
>      pt = Estátua memorial
Estátua

2022-10-31 12:36 UTC, matheusgomesms commented on data/strings/types_strings.txt
>      pt = Barco histórico
Barco

2022-10-31 14:50 UTC, matheusgomesms commented
> thanks @matheusgomesms, I corrected them.

Lovely, thanks!

2022-10-31 14:51 UTC, matheusgomesms approved these changes

2022-11-01 06:15 UTC, vng commented
To complete this PR, we should add drawing styles (mapcss) for historic=battlefield.
For example make it the same as historic=memorial.
Otherwise, this type is not included in generated data and search tests failed.

2022-11-01 12:32 UTC, vng commented
Ok, now please, make:
- commit with generated strings (./tools/unix/generate_localizations.sh)
- commit with generated styles (./tools/unix/generate_drules.sh)

2022-11-01 13:43 UTC, biodranik approved these changes

2022-11-01 13:43 UTC, biodranik commented on android/res/values-ar/strings.xml
> +	<string name="type.barrier.city_wall">جدار المدينة</string>
Was it merged previously, but not regenerated?

2022-11-01 17:09 UTC, merged