[android] Update the list of devices in TestLab
organicmaps/organicmaps pull request #3773
Opened 2022-10-31 07:56 UTC by rtsisyk

Closes #3758
Closes #3759

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2022-10-31 10:53 UTC, biodranik requested changes

2022-10-31 10:53 UTC, biodranik commented on .github/workflows/android-monkey.yaml
> +          gradle -Parm64 -Parm32 -Px86 -Pfirebase assembleGoogleDebug
По-умолчанию должно всё собирать, что нужно.
```suggestion
          gradle -Pfirebase assembleGoogleDebug
```

2022-11-01 05:59 UTC, rtsisyk commented on .github/workflows/android-monkey.yaml
> +          gradle -Parm64 -Parm32 -Px86 -Pfirebase assembleGoogleDebug
Вот и собирает что нужно - arm. А x86 никому не нужен.

2022-11-01 06:14 UTC, rtsisyk commented on .github/workflows/android-monkey.yaml
> +          gradle -Parm64 -Parm32 -Px86 -Pfirebase assembleGoogleDebug
Поменял тут. x86 надо выпилить из fdroid apk. Просто бесполезно занимает место.

2022-11-01 06:41 UTC, rtsisyk commented
Updated.

2022-11-01 07:04 UTC, biodranik approved these changes

2022-11-02 09:38 UTC, rtsisyk commented on .github/workflows/android-beta.yaml
> +          gradle -x lint -x lintVitalGoogleBeta assembleGoogleBeta uploadCrashlyticsSymbolFileGoogleBeta uploadCrashlyticsMappingFileGoogleBeta
Чтобы репорты шли из testlab.

2022-11-02 09:38 UTC, rtsisyk commented on android/build.gradle
> -      ndk.debugSymbolLevel = 'none'
Ну ок.

2022-11-02 21:53 UTC, biodranik commented on .github/workflows/android-beta.yaml
> +          gradle -x lint -x lintVitalGoogleBeta assembleGoogleBeta uploadCrashlyticsSymbolFileGoogleBeta uploadCrashlyticsMappingFileGoogleBeta
Так а бинарник туда не надо аплоадить для тестов?

2022-11-11 21:28 UTC, biodranik commented on .github/workflows/android-beta.yaml
> +          gradle -x lint -x lintVitalGoogleBeta assembleGoogleBeta uploadCrashlyticsSymbolFileGoogleBeta uploadCrashlyticsMappingFileGoogleBeta
@rtsisyk как/когда аплоадится бинарник, соответствующий этим символам?

2022-11-15 08:47 UTC, biodranik commented on .github/workflows/android-beta.yaml
> +          gradle -x lint -x lintVitalGoogleBeta assembleGoogleBeta uploadCrashlyticsSymbolFileGoogleBeta uploadCrashlyticsMappingFileGoogleBeta
?

2022-11-15 08:48 UTC, biodranik commented on .github/workflows/android-beta.yaml
> +          gradle -x lint -x lintVitalGoogleBeta assembleGoogleBeta uploadCrashlyticsSymbolFileGoogleBeta uploadCrashlyticsMappingFileGoogleBeta
@rtsisyk ?

2022-11-17 10:32 UTC, rtsisyk commented
I am merging this PR, but further fixes will be required to get all devices running.

2022-11-17 10:32 UTC, merged