[translations] Update French from an alternative source
organicmaps/organicmaps pull request #3887
Opened 2022-11-15 08:16 UTC by rtsisyk

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

----------

I've got this French translation from a company that wanted to translate our Google Play listings. I am not an expert in French. @organicmaps/translations-fr, could you please review it and tell me if it's better or worse?

2022-11-15 21:11 UTC, Jean-BaptisteC requested changes
Some changes :)

2022-11-15 21:11 UTC, Jean-BaptisteC commented on android/src/fdroid/play/listings/fr-FR/full-description.txt
> +• Simple à utiliser, avec uniquement les fonctions les plus importantes incluses
```suggestion
• Simple d'utilisation, avec uniquement les fonctions les plus importantes incluses
```

2022-11-15 21:11 UTC, Jean-BaptisteC commented on android/src/fdroid/play/listings/fr-FR/full-description.txt
> +Libre de suivis et autres mauvaises choses :
```suggestion
Sans pisteurs et autres mauvaises choses :
```

2022-11-15 21:11 UTC, Jean-BaptisteC commented on android/src/fdroid/play/listings/fr-FR/full-description.txt
> +• Pas de spam par courriel bruyant
```suggestion
• Pas de spam abusif
```

2022-11-15 21:11 UTC, Jean-BaptisteC commented on android/src/fdroid/play/listings/fr-FR/full-description.txt
> +Chez Cartes biologiques, nous pensons que <b>la confidentialité est un droit humain fondamental</b>:
```suggestion
Chez Organic Maps, nous pensons que <b>la vie privée est un droit humain fondamental</b>:
```

2022-11-15 21:11 UTC, Jean-BaptisteC commented on android/src/fdroid/play/listings/fr-FR/full-description.txt
> +• Cartes biologiques est un projet source-ouverte piloté par la communauté indépendante
```suggestion
• Organic Maps est un projet open-source géré par une communauté indépendante
```

2022-11-15 21:11 UTC, Jean-BaptisteC commented on android/src/fdroid/play/listings/fr-FR/full-description.txt
> +Zéro localisateurs de suivi et seules les autorisations minimales requises sont trouvées selon Exodus Privacy Report.
```suggestion
Zéro pisteurs et seules les autorisations minimales requises sont trouvées dans le rapport d'Exodus Privacy.
```

2022-11-15 21:51 UTC, biodranik commented
@Jean-BaptisteC thanks! @rtsisyk I told you that these Google Play translators do not worth their money.

2022-11-15 22:10 UTC, Jean-BaptisteC commented
I think this company have use Google translate to translate this description :(
Because Organic Maps is translated by `Cartes biologiques` and trackers by `localisateurs de suivi` 😂
My main language is french but i think a second review is necessary :)

2022-11-16 06:53 UTC, rtsisyk commented
> I think this company have use Google translate to translate this description :( Because Organic Maps is translated by `Cartes biologiques` and trackers by `localisateurs de suivi` 😂 My main language is french but i think a second review is necessary :)

This is what I thought, but wanted to validate. So, your conclusion that this new translation is substandard?

2022-11-16 07:27 UTC, arnaudvergnet commented
Can confirm those translations are pretty shit

2022-11-16 08:04 UTC, arnaudvergnet requested changes

2022-11-16 08:04 UTC, arnaudvergnet commented on android/src/fdroid/play/listings/fr-FR/full-description.txt
> +• N̶o̶ ̶p̶e̶s̶t̶i̶c̶i̶d̶e̶s̶ Purement biologique
```suggestion
• S̶a̶n̶s̶ ̶p̶e̶s̶t̶i̶c̶i̶d̶e̶s̶ Purement biologique
```

2022-11-16 08:04 UTC, arnaudvergnet commented on android/src/fdroid/play/listings/fr-FR/full-description.txt
> +• Nous protégeons la vie privée des regards indiscrets de Big Tech
```suggestion
• Nous protégeons la vie privée des regards indiscrets des géants de la tech
```

2022-11-16 08:04 UTC, arnaudvergnet commented on android/src/fdroid/play/listings/fr-FR/full-description.txt
> +Zéro localisateurs de suivi et seules les autorisations minimales requises sont trouvées selon Exodus Privacy Report.
```suggestion
Zéro trackers et seules les autorisations minimales requises sont trouvées dans le rapport d'Exodus Privacy.```

2022-11-16 08:05 UTC, arnaudvergnet commented
The old translation was often better than this one, even google translate does a better job.

2022-11-16 08:35 UTC, rtsisyk commented
OK, I am closing this PR then. Thanks for you feedback!

2022-11-16 08:35 UTC, closed without merging