Translations update from Hosted Weblate
organicmaps/organicmaps pull request #3911
Opened 2022-11-17 21:47 UTC by weblate

Translations update from [Hosted Weblate](https://hosted.weblate.org) for [OrganicMaps/FDroid Metadata](https://hosted.weblate.org/projects/organicmaps/fdroid-metadata/).

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widgets/organicmaps/-/fdroid-metadata/horizontal-auto.svg)

2022-11-20 06:51 UTC, rtsisyk approved these changes

2022-11-20 08:50 UTC, biodranik requested changes
```
❌ android/src/fdroid/play/listings/es/: unsupported locale
❌ android/src/fdroid/play/listings/pl/: unsupported locale
```

2022-11-20 08:50 UTC, biodranik commented on android/src/fdroid/play/listings/pl/full-description.txt
> +• Brak 💩 oprogramowania
Do we really want this icon in our description?

2022-11-24 16:06 UTC, LaoshuBaby approved these changes

2022-12-03 09:28 UTC, closed without merging