Update emails
organicmaps/organicmaps pull request #400
Opened 2021-05-12 08:39 UTC by rtsisyk

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2021-05-12 11:34 UTC, biodranik requested changes

2021-05-12 11:34 UTC, biodranik commented on android/res/layout/place_page_email.xml
> +    tools:text="email@organicmaps.app" />
Это где и доя чего используется?

2021-05-12 11:34 UTC, biodranik commented on tools/python/post_generation/setup.py
>          author="The OMaps Project",
Поменять

2021-05-12 11:34 UTC, biodranik commented on tools/python/mwm/setup.py
>          author="The OMaps Project",
Поменять и грепнуть в других местах

2021-05-12 11:34 UTC, biodranik commented on tools/python/post_generation/setup.py
>          url="https://github.com/mapsme",
Поменять и грепнуть

2021-05-12 11:34 UTC, biodranik commented on tools/python/mwm/setup.py
>          url="https://github.com/mapsme",
Поменять

2021-05-12 11:34 UTC, biodranik commented on tools/python/maps_generator/setup.py
>          url="https://github.com/mapsme",
Поменять

2021-05-12 11:34 UTC, biodranik commented on tools/python/descriptions/setup.py
>          author="The OMaps Project",
Поменять

2021-05-12 11:34 UTC, biodranik commented on tools/python/data_files/setup.py
>          url="https://github.com/mapsme",
Можно отдельным коммитом или пр

2021-05-13 07:26 UTC, rtsisyk commented on android/res/layout/place_page_email.xml
> +    tools:text="email@organicmaps.app" />
Это просто placeholder в карточке организации. Поменял на support@organicmaps.app чтобы новые email не плодить.

2021-05-13 07:27 UTC, rtsisyk commented
Всё поменял. Там некоторые вещи с 2014 года не меняли.

2021-05-13 07:40 UTC, rtsisyk commented
Теперь точно всё.

2021-05-13 12:26 UTC, biodranik approved these changes

2021-05-13 18:39 UTC, vng approved these changes

2021-05-13 18:39 UTC, merged