Translated using Weblate (Hungarian)
organicmaps/organicmaps pull request #4010
Opened 2022-12-03 09:21 UTC by rtsisyk

Translate-URL: https://hosted.weblate.org/projects/organicmaps/fdroid-metadata/hu/
Signed-off-by: Babos Gábor <gabor.babos@gmail.com>
Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2022-12-03 09:40 UTC, d4f5409d commented
Okay, the rest of the translation was great, the only thingies I found is where I commented. We'll fix it soon.

2022-12-03 11:36 UTC, rtsisyk commented
> Okay, the rest of the translation was great, the only thingies I found is where I commented. We'll fix it soon.

Sorry, I can't find your comments. Have you sent them?

2022-12-03 12:24 UTC, aronkvh requested changes
Fixed some typos and added some suggestions.

2022-12-03 12:24 UTC, aronkvh commented on android/src/fdroid/play/listings/hu-HU/full-description.txt
> +‣ Ha valami hibás vagy hiányzik a térképen, kérjük, javítsdaki az <b>OpenStreetMap</b> oldalon, és a jövőbeni térképfrissítésekben láthatja a változtatásokat.
‣ Ha valami hibás vagy hiányzik a térképen, kérjük, javítsa az <b>OpenStreetMap</b> oldalon és a jövőbeni térképfrissítésekben látni fogja a változtatásokat.

2022-12-03 12:24 UTC, aronkvh commented on android/src/fdroid/play/listings/hu-HU/full-description.txt
> +<b>A legjobb motivációnk a visszajelzések és az 5 csillagos értékelések!</b>
<b>A legjobb motivációink a visszajelzések és az 5 csillagos értékelések!</b>

2022-12-03 12:24 UTC, aronkvh commented on android/src/fdroid/play/listings/hu-HU/full-description.txt
> +- Nincs zajos e-mail spam
- Nincs zavaró e-mail spam

2022-12-03 12:24 UTC, aronkvh commented on android/src/fdroid/play/listings/hu-HU/full-description.txt
> +- Nincs crapware
Nincsenek hasznavehetetlen funkciók

2022-12-03 12:24 UTC, aronkvh commented on android/src/fdroid/play/listings/hu-HU/full-description.txt
> +- N̶incs növényvédő szer. Teljesen organikus
Növényvédő szerek  nélkül. Teljesen organikus.
`//(nem teljesen szó szerinti, de magyarosabb)`

2022-12-03 12:24 UTC, aronkvh commented on android/src/fdroid/play/listings/hu-HU/full-description.txt
> +- Megvédjük a magánéletet a Big Tech kíváncsi szemeitől.
- Megvédjük magánéletét a Big Tech kíváncsi szemeitől.

2022-12-03 12:24 UTC, aronkvh commented on android/src/fdroid/play/listings/hu-HU/full-description.txt
> +- Maradjon biztonságban, bárhol is van
- Legyen biztonságban, bárhol is van

2022-12-03 12:24 UTC, aronkvh commented on android/src/fdroid/play/listings/hu-HU/full-description.txt
> +Kérjük, látogasson el a <b><i>organicmaps.app</i></b> weboldalra további részletekért és a GYIK-ért, és lépjen kapcsolatba velünk közvetlenül a @OrganicMapsApp-on a Telegramban.
Kérjük, látogasson el a <b><i>organicmaps.app</i></b> weboldalra további részletekért és a GYIK-ért és lépjen kapcsolatba velünk közvetlenül a @OrganicMapsApp-on a Telegramon.

2022-12-03 12:24 UTC, aronkvh commented on android/src/google/play/listings/hu-HU/title.txt
> +Organic Maps offline térképek
Organic Maps offline térkép

2022-12-03 12:24 UTC, aronkvh commented on android/src/fdroid/play/listings/hu-HU/full-description.txt
> +‣ Ha a navigáció vagy a keresés nem működik, kérjük, írjon nekünk e-mailt. <i>MINDEN</i> e-mailre válaszolunk, és azonnal a hibát kijavítjuk!
‣ Ha a navigáció vagy a keresés nem működik, kérjük, írjon nekünk e-mailt. <i>MINDEN</i> e-mailre válaszolunk, és a hibát azonnal kijavítjuk!

2022-12-03 13:31 UTC, biodranik commented on android/src/fdroid/play/listings/hu-HU/full-description.txt
> +- Egyszerűen használható, csak a legfontosabb funkciókat tartalmazza
Let's use `• ` instead of `- ` everywhere, for consistency with other translations.

2022-12-03 20:48 UTC, rtsisyk commented
Updated. Please also give me your `Signed-off-by: ` line, I will add you.

2022-12-03 21:00 UTC, aronkvh approved these changes

2022-12-04 00:33 UTC, biodranik approved these changes

2022-12-04 00:34 UTC, biodranik commented on android/src/google/play/listings/hu-HU/title.txt
> +Organic Maps offline térkép
```suggestion
Organic Maps offline térkép

```

2022-12-04 00:38 UTC, merged