[android] Implement kml/kmb importer
organicmaps/organicmaps pull request #416
Opened 2021-05-16 09:59 UTC by rtsisyk

2021-05-16 10:39 UTC, biodranik requested changes

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +    if (viewType == TYPE_ACTION_IMPORT)
Если завернуть в switch, будет понятнее.

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +    if (type == TYPE_ACTION_IMPORT)
Здесь тоже напрашивается switch.

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +  private void bindImportButtonListHolder(@NonNull RecyclerView.ViewHolder holder)
Эти функции лучше заинлайнить там, где они вызываются по одному разу. Будет понятнее и проще код.

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +    if (position == getItemCount() - 2)
Нужны комментарии по поводу -2 и -1 ниже.

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +  private class ImportButtonClickListener implements View.OnClickListener
Это прошлый век, все эти 11 строчек кода свернутся в три-четыре, если оформить лямбдой в месте вызова.
Студия сама должна подсказать и помочь это сделать, когда курсор наведёшь на место вызова.

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
> +    // TODO: add /sdcard/MapsWithMe/bookmarks hint here.
Не надо отсюда хинтовать, пускай диалог сам везде где нужно сканит.

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
> +      // TODO: this dialog doesn't work
Надо доделать, мержить нерабочую штуку в мастер не стоит.

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
> +    if (requestCode == REQ_CODE_DELETE_CATEGORY)
Можно switch

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +  static final StorageUtils.UriFilter BOOKMARKS_EXTS_FILTER = uri -> {
Свои собственные букмарки отфильтруются?

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        File tempFile = File.createTempFile("bookmarks", ext, tempDir);
Надо сохранить имя файла букмарок, оно должно стать названием сета после импорта.

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
Если этот метод загружает все три формата, его название надо поменять. loadKmzKmlKmbFile например.

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/util/StorageUtils.java
> +  public static ArrayList<Uri> listContentProviderFilesRecursively(ContentResolver contentResolver, Uri rootUri, UriFilter filter)
Все диски будут сканниться?

2021-05-16 10:39 UTC, biodranik commented on android/src/com/mapswithme/util/StorageUtils.java
> +            if (filter.accept(uri))
Может сюда сразу name вставлять, будет проще матчить? А по mime type мы не сможем профильтровать, чтобы быстрее было?

2021-05-16 10:39 UTC, biodranik commented on data/strings/strings.txt
> +    en = Import bookmarks
Поставь тэг что только для андроида, и коммент, где эта кнопка.

2021-05-16 10:39 UTC, biodranik commented on map/bookmark_manager.cpp
> +      return {};
Не удаляется файл. И функция странная, надо переименовать по-другому.

2021-05-16 11:58 UTC, rtsisyk commented on android/src/com/mapswithme/util/StorageUtils.java
> +  public static ArrayList<Uri> listContentProviderFilesRecursively(ContentResolver contentResolver, Uri rootUri, UriFilter filter)
Будет скатиться та директория, которую укажет юзер. Смотри видео.

2021-05-16 11:59 UTC, rtsisyk commented on android/src/com/mapswithme/util/StorageUtils.java
> +            if (filter.accept(uri))
У kmb application/octet-stream..

2021-05-16 11:59 UTC, rtsisyk commented on data/strings/strings.txt
> +    en = Import bookmarks
Ок

2021-05-16 11:59 UTC, rtsisyk commented on map/bookmark_manager.cpp
> +      return {};
А зачем там флажок тогда что temporary?

2021-05-16 12:00 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +    if (viewType == TYPE_ACTION_IMPORT)
Ну можно.

2021-05-16 12:01 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +  private void bindImportButtonListHolder(@NonNull RecyclerView.ViewHolder holder)
Я пытался минимально переписывать существующее чтобы не раздувать патч.

2021-05-16 12:02 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +  private class ImportButtonClickListener implements View.OnClickListener
Все так. Делал в той же стилистике, что там была, чтобы не раздувать патч.

2021-05-16 12:04 UTC, rtsisyk commented on map/bookmark_manager.cpp
> +      return {};
@vng можешь глянуть внимательнее зачем там  temporary? Я могу из Java удалить, го вопросов про флажок будет много.

2021-05-16 12:04 UTC, rtsisyk commented
А мы можем как нибудь при соврвдении имени добавлять букмарки в существующие группы?

2021-05-16 13:42 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +  private class ImportButtonClickListener implements View.OnClickListener
Улучшай и упрощай код, если его трогаешь. Будет нам же дальше проще поддерживать.

2021-05-16 13:43 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +  private void bindImportButtonListHolder(@NonNull RecyclerView.ViewHolder holder)
А по факту раздуваешь, копипастя подходы. Можно компактнее и более читабельно.

2021-05-16 13:44 UTC, biodranik commented on android/src/com/mapswithme/util/StorageUtils.java
> +  public static ArrayList<Uri> listContentProviderFilesRecursively(ContentResolver contentResolver, Uri rootUri, UriFilter filter)
Надо полный скан всего, указание директории не поможет, т.к. 99.9999% юзеров не знают, в каких директориях могут лежать букмарки.

2021-05-16 16:53 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +  private void bindImportButtonListHolder(@NonNull RecyclerView.ViewHolder holder)
Поменял.

2021-05-16 16:53 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +    if (position == getItemCount() - 2)
Добавил.

2021-05-16 16:53 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesAdapter.java
> +  private class ImportButtonClickListener implements View.OnClickListener
Сделали отдельным коммитом.

2021-05-16 16:55 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
> +    if (requestCode == REQ_CODE_DELETE_CATEGORY)
Бесмысленно, но поменял.

2021-05-16 16:56 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        File tempFile = File.createTempFile("bookmarks", ext, tempDir);
Из самого kml/kmb имя как-то берется.

2021-05-16 17:10 UTC, rtsisyk commented on data/strings/strings.txt
> +    en = Import bookmarks
Поставил.

2021-05-16 17:18 UTC, rtsisyk commented on android/src/com/mapswithme/util/StorageUtils.java
> +  public static ArrayList<Uri> listContentProviderFilesRecursively(ContentResolver contentResolver, Uri rootUri, UriFilter filter)
Корневую папку выбрать нельзя.

On Android 11 (API level 30) and higher, you cannot use the ACTION_OPEN_DOCUMENT_TREE intent action to request access to the following directories:

- The root directory of the internal storage volume.
- The root directory of each SD card volume that the device manufacturer considers to be reliable, regardless of whether the card is emulated or removable. A reliable volume is one that an app can successfully access most of the time.
- The Download directory.

Furthermore, on Android 11 (API level 30) and higher, you cannot use the ACTION_OPEN_DOCUMENT_TREE intent action to request that the user select individual files from the following directories:

- The Android/data/ directory and all subdirectories.
- The Android/obb/ directory and all subdirectories.


В целом этот скан по факту будет работать только со старыми приложениями, которые еще пока не успели переехать на приватные папки. У меня таких приложений во всем телефоне не очень много:

- /sdcard/MapsWithMe
- /sdcard/OMapsData/
- /sdcard/Hikingbook
- /sdcard/DJI и прочие кривые китайские приложения

![Screenshot_20210516-200928_Files](https://user-images.githubusercontent.com/1799054/118405952-d1651b00-b682-11eb-8732-cf55dc449b3e.jpg)

2021-05-16 18:00 UTC, rtsisyk commented
У меня нет идей что тут сделать лучше.

2021-05-17 07:44 UTC, vng requested changes

2021-05-17 07:44 UTC, vng commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        throw new AssertionError("The file extension is not supported in " + uri);
Мы внизу подавляем IOException, а тут прям выкидываем наружу AssertionError. То что у файла нет ext - штатная ситуация или я что-то не понимаю?
- если мы где-то фильтруем вне, то зачем дублировать логику? сразу пускать файл на loadKmzFile
- если мы не фильтруем вне, то почему тут тогда выкидываем исключение?

2021-05-17 07:44 UTC, vng commented on android/src/com/mapswithme/util/StorageUtils.java
> +            continue;
continue не нужен

2021-05-17 07:44 UTC, vng commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
> -    if (resultCode == Activity.RESULT_OK && requestCode == REQ_CODE_DELETE_CATEGORY)
nit: resultCode можно проверить один раз до switch

2021-05-17 07:44 UTC, vng commented on map/bookmark_manager.cpp
> +      return {};
Я бы не стал сейчас что-то тут переименовывать. GetKMLPath вызывается через внутренние потроха. Рома сделал аналогично с kmz, инициатор тут loadKmzFile -> nativeLoadKmzFile -> ...

Давайте делать патчи минимальными, а не добавляем функционал, и начинаем попутно резать, переименовывать. Потом не поймешь где мухи, где котлеты.

2021-05-17 07:46 UTC, vng commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
Именно тут да, возможно стоит дать более общее имя, loadAnyFile

2021-05-17 07:55 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        throw new AssertionError("The file extension is not supported in " + uri);
Там UriFilter сверху. Левый экстепшен может залзеть только при несогласованности в коде. Убрать его?

2021-05-17 07:55 UTC, rtsisyk commented on android/src/com/mapswithme/util/StorageUtils.java
> +            continue;
Ага

2021-05-17 07:56 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
> -    if (resultCode == Activity.RESULT_OK && requestCode == REQ_CODE_DELETE_CATEGORY)
Ну а вдруг кому-то надо будет проверять не ОК? Ладно, поменяю.

2021-05-17 08:02 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
@vng можешь подтвердить или опровергнуть, что isTemporary = true удаляет файл за собой? Я не смог быстро разобраться.

2021-05-17 08:41 UTC, rtsisyk commented
Update, PTAL.
Test plan:

1. Try to import kmb bookmarks from /sdcard/MapsWithMe/bookmarks
2. Try to import kml/kmz files from /sdcard
3. Try to download kml/kmz from some web-site and open in Organic Maps.

2021-05-17 08:51 UTC, vng commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        throw new AssertionError("The file extension is not supported in " + uri);
Конечно, убирай эти бубны тут, если фильтр уже пройден.

2021-05-17 08:55 UTC, vng commented
У меня еще одно замечание на обсудить. Если файлы kmz или kmb - мы запускаем парсер и если что-то идет не так (подсунули говно), просто скипаем. kml же файлы теперь (судя по коду) мы принимаем на верочку :) Т.е. можно подсунуть любой хлам и мы скопируем его себе как kml, ну или я не увидел где идет парсинг.

2021-05-17 09:57 UTC, vng commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
Да, после всех перетрубаций управление в итоге приходит на BookmarkManager.onBookmarksFileLoaded

2021-05-17 10:03 UTC, vng commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
Другое дело, что если ты от uri получишь путь (как я понимаю, тут это все равно файл, а не что-то там ..), то можно не создавать тут промежуточный tempFile, а вызывать loadKmzFile(<src path>).

2021-05-17 10:17 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
В случае импорта  uri почти не файл, а что-то мутное (content:// blabla).

2021-05-17 10:18 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
>Да, после всех перетрубаций управление в итоге приходит на BookmarkManager.onBookmarksFileLoaded

Так а временный файл кто-нибудь удаляет в итоге или нет?

2021-05-17 10:18 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        throw new AssertionError("The file extension is not supported in " + uri);
Убрал.

2021-05-17 10:22 UTC, vng commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
Именно в этой функции и удаляется.

2021-05-17 10:27 UTC, vng approved these changes

2021-05-17 10:33 UTC, biodranik commented on android/src/com/mapswithme/util/StorageUtils.java
> +  public static ArrayList<Uri> listContentProviderFilesRecursively(ContentResolver contentResolver, Uri rootUri, UriFilter filter)
В этой фиче тогда мало смысла, если мы не можем автоматически просканить нужные папки. Может можно получить список папок в корне, и по очереди по ним пройтись?

Задача такая: я юзер, ничего не понимаю в файлах, папках, только хочу втянуть свои букмарки из mapsme. Задача со звёздочкой: втянуть свои букмарки из любых других приложений. Одним кликом + подтверждением пермишна.

2021-05-17 10:38 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
> В случае импорта uri почти не файл, а что-то мутное (content:// blabla).

Точно не существует других способов на api 30+ достучаться до файлов? Из апишки точно никак нельзя вытянуть старое имя файла? Это очень ценная информация. Нельзя её терять.

2021-05-17 10:45 UTC, biodranik commented
> А мы можем как нибудь при соврвдении имени добавлять букмарки в существующие группы?

Можно. Но есть риск, что названия файлов совпали случайно (mybookmarks по-умолчанию например с разных устройств). Поэтому проще отдельными сетами импортировать, а юзер дальше если что отредактирует, как ему нужно.

2021-05-18 07:09 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
Имя без проблем вытягивается, только потом оно нигде не используется и берется из самого kml насколько я понял.

2021-05-18 07:11 UTC, rtsisyk commented on android/src/com/mapswithme/util/StorageUtils.java
> +  public static ArrayList<Uri> listContentProviderFilesRecursively(ContentResolver contentResolver, Uri rootUri, UriFilter filter)
>В этой фиче тогда мало смысла, если мы не можем автоматически просканить нужные папки.
> Задача такая: я юзер, ничего не понимаю в файлах, папках, только хочу втянуть свои букмарки из mapsme.

Ну из MAPS.ME получается импортировать kmb. Да, надо выбрать самому /MapsWithMe. Разве это не лучше, чем ничего? Можем инструкцию написать в конце концов.

>Может можно получить список папок в корне, и по очереди по ним пройтись?

Да не дают они читать ничего отличного от пути, выбранного юзером. Предлагаешь в их системе уязвимость поискать?

>Задача со звёздочкой: втянуть свои букмарки из любых других приложений. Одним кликом + подтверждением пермишна.

Давай сначала пермишен на локацию подтвердим у гугла, а потом будем на пермишен на все директории замахиваться.

2021-05-18 07:11 UTC, rtsisyk commented on map/bookmark_manager.cpp
> +      return {};
Я предлагаю забить тут.

2021-05-18 07:12 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
> -    if (resultCode == Activity.RESULT_OK && requestCode == REQ_CODE_DELETE_CATEGORY)
Я поменял это.

2021-05-18 07:15 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
@biodranik прошу обратить внимание, что имя файла вообще никак не влияет на название категории букмарков:

https://github.com/organicmaps/organicmaps/blob/master/map/bookmark_manager.cpp#L1941-L1983

2021-05-18 07:18 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
А не, вру, все же нашел где влияет. Сейчас попробую выковырять тогда имя.

2021-05-18 09:30 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +        loadKmzFile(tempFile.getAbsolutePath(), true);
Сделал чтобы имя файла сохранялось.

2021-05-18 11:17 UTC, vng approved these changes

2021-05-20 07:31 UTC, rtsisyk commented
@biodranik потестируй плз, надо понять что делать тут.

2021-05-24 18:22 UTC, biodranik requested changes

2021-05-24 18:22 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
> +      if (data == null)
Что это за кейз? Давай тут крешить, чтобы не допускать неправильного использования. Или хотя бы логать ошибку.

2021-05-24 18:22 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
> +    // https://stackoverflow.com/questions/65326605/extra-initial-uri-will-not-work-no-matter-what-i-do
Там пишут: But on Android 11 you can start with primary or secondary partition.
Мы можем этим воспользоваться?

2021-05-24 18:24 UTC, biodranik commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +    final String mime = resolver.getType(uri);
А kmb сюда не просочатся? Внизу для них нет if.

2021-05-31 12:15 UTC, biodranik approved these changes
Если все комменты проверил исправил, давай вливать.

2021-06-01 07:18 UTC, rtsisyk commented on android/res/layout/item_bookmark_import.xml
> +    tools:targetApi="jelly_bean" />
Это элемент списка "Import bookmarks".

2021-06-01 07:24 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
> +    // https://stackoverflow.com/questions/65326605/extra-initial-uri-will-not-work-no-matter-what-i-do
Эта опция не игнорируется только если туда передавать URI, полученный ранее вызовом этого же метода. Причем даже если его в строчку сохранить и потом заново создать, то уже игнорируется. Я не смог заставить работать установку начального пути. Ни на каком андроиде это не работает.

2021-06-01 07:25 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/data/BookmarkManager.java
> +    final String mime = resolver.getType(uri);
Там выше сначала по extension пробуем. Если по extension не получилось, то fallback на mime.

2021-06-01 07:28 UTC, rtsisyk commented on android/src/com/mapswithme/maps/bookmarks/BookmarkCategoriesFragment.java
> +    // https://stackoverflow.com/questions/65326605/extra-initial-uri-will-not-work-no-matter-what-i-do
>You can only use an uri that you obtained before with ACTION_OPEN_DOCUMENT

Вот это правда. Ну то есть можно получить url от юзера в диалоге, а при повторном открытии начать с него же. Первоначально никак не установить.

2021-06-01 07:32 UTC, rtsisyk commented on android/jni/com/mapswithme/maps/Framework.cpp
> +  vector<string> exts = { kKmzExtension, kKmlExtension, kKmbExtension };
Этот массив сразу же тут же и утилизируется. Поставил const, но смысла это никакого не имеет.

2021-06-01 07:52 UTC, rtsisyk commented
1. Установить директорию по умолчанию не удалось. Это просто не работает ни на стоковом ведре, ни на самсунге, ни на хуавее. На stackoverflow справедливо замечают, что работают только URL, полученные ранее в этом же методе. Причем если тупо сохранять строчку с url и пересоздавать объект, то тоже не работает. Видимо там внутри Uri объекта какой-то специальный флажок...

2. Удалось добавить отображение SDCard в диалоге через недокументированную опцию. Однако сам диалог на стоковом ведре по прежнему открывается с Recent и ничего не понятно.

3. Сообщение "Импортировано N файлов" добавлено. Строчка уже была в локализации.
4

2021-06-01 07:53 UTC, merged