[editor] Migrate mapsme to omaps
organicmaps/organicmaps pull request #4387
Opened 2023-02-01 19:03 UTC by Jean-BaptisteC

This PR following works started here #4050

2023-02-02 10:45 UTC, biodranik requested changes
The code doesn't load an old config. To reproduce:
1. Build the version from master (desktop or mobile)
2. Run and make an edit (you don't need to upload it to OSM, so no logging in is necessary)
3. Close the app. Build this branch.
4. Run this branch version.
5. Observe the ASSERT crash:
```
LOG TID(1) ERROR     0.29318 editor/config_loader.cpp:154 LoadFromLocal(): Config can not be loaded.
```

Obviously, the loading code should check if either the old or new XML element is present in the root node. And always save a new value.

2023-02-02 21:57 UTC, vng approved these changes

2023-02-02 21:57 UTC, vng commented on editor/osm_editor.cpp
> +    rootNode = doc.child(kXmlOldRootNode);
- I don't mind. Delete kXmlOldRootNode var and put _old_ string manually here?
- add CHECK(rootNode, ());

2023-02-03 22:12 UTC, biodranik commented
@Jean-BaptisteC please test quickly if it works.

2023-02-04 08:33 UTC, Jean-BaptisteC commented
Build failed
```
home/runner/work/organicmaps/organicmaps/editor/osm_editor.cpp:209:36: error: use of undeclared identifier 'kXmlNewRootNode'; did you mean 'kXmlRootNode'?
    xml_node root = doc.append_child(kXmlNewRootNode);
                                     ^~~~~~~~~~~~~~~
                                     kXmlRootNode
  /home/runner/work/organicmaps/organicmaps/editor/osm_editor.cpp:44:24: note: 'kXmlRootNode' declared here
  constexpr char const * kXmlRootNode = "omaps";
```

2023-02-04 09:10 UTC, biodranik commented
Uuups ) fixed.

2023-02-07 20:45 UTC, Jean-BaptisteC commented
Pixel 6 - Android 13 ✅

I have create 2 APK
- One from master branch
- One from this branch

I have installed on my device, the first version, i have update POI without Internet
I have update app with version from this branch, i have enabled Internet -> Change was commit on OSM

I have add contact:facebook on this POI https://www.openstreetmap.org/node/251474108

2023-02-07 21:39 UTC, biodranik approved these changes
Thank you for the PR and for testing!

2023-02-07 21:41 UTC, merged