[strings] Don't intercept OpenStreetMap.org
organicmaps/organicmaps pull request #4415
Opened 2023-02-08 07:15 UTC by rtsisyk

2023-02-08 19:20 UTC, Jean-BaptisteC commented
Open link from html fragment is different ?
When i open OSM link from Copyright Fragment, OM doesn't intercept link

2023-02-08 19:50 UTC, biodranik requested changes
Nobody knows what is osm. The full project name should be used there. It is critically important for us.  Let's find other ways to solve this issue.

2023-02-08 20:17 UTC, Jean-BaptisteC commented
Is not possible to open other link when you touch OpenStreetMap.org ?
Like Github [OpenStreetMap.org](https://osm.org)

2023-02-11 13:20 UTC, biodranik approved these changes

2023-02-11 13:21 UTC, merged