[android] fix "download world" systematic pause after phone rotation
organicmaps/organicmaps pull request #4598
Opened 2023-02-25 00:00 UTC by Emilevillette

As explained in [18023cd](https://github.com/organicmaps/organicmaps/commit/18023cdb5f4c8869d4593ba1d44013e72b60e2a3), this fixes a bug that occured on the "download map" screen, typically on a first launch/after a cache reset.

The solution I found is to track a status variable between the activity destruction and its creation after the rotation.

This PR fixes #4496.

2023-02-25 10:42 UTC, biodranik reviewed
Did you test it? @Jean-BaptisteC can you please help to test?

2023-02-25 11:34 UTC, Emilevillette commented
> Did you test it? @Jean-BaptisteC can you please help to test?
> 
> Please also test other possible cases, when the app is moved to the background, and then killed, or the device is locked, etc.

Hi @biodranik ! Yes I did rerun the scenario mentionned in #4496 and the problem didn't occur anymore. I just ran a few other tests as you suggested here are the outcomes:

- Device rotation: works as expected. 

- App moved to the background then killed: when the app is booted back up, the user is prompted to start downloading the remaining files (i.e. if it had downloaded 8Mo out of 50Mo, it asks to download 42Mo. In my opinion this should stay this way in case the user's context has changed between the killing of the app and the startup (e.g. he went from an unmetered WiFi connection to a limited mobile broadband access).

- Device is locked: OM stays open and download works as expected.

- Device sent to background and to foreground: on the first launch, the app crashes. This is not related to this PR as I have tested the app on 27730a1 revision, and the problem occurs (I will open a separate issue). Otherwise, when it is NOT the first launch, this works as expected.

I will commit the code updated for the review soon.

2023-02-25 15:30 UTC, biodranik commented on android/src/app/organicmaps/DownloadResourcesLegacyActivity.java
> +  private final static String ACTION_KEY = "action";
nit:
```suggestion
  private static final String ACTION_KEY = "action";
```

2023-02-25 15:45 UTC, Emilevillette commented
I'm struggling a bit with the signoff, however, all the commits should be signed off. Had to force push due to some shenanigans on my local machine.

2023-02-25 20:09 UTC, Emilevillette commented
Sorry for the kerfufle. Rebased and pushed, no merge garbage now.

2023-02-25 20:34 UTC, biodranik requested changes
Please squash all commits into one by `git rebase -i origin/master` and force-push it here.

2023-02-25 21:43 UTC, biodranik reviewed
Almost great ) Why are there 2 commits instead of 1?

2023-02-25 21:48 UTC, Emilevillette commented
Oh I'm sorry ! It's fixed, thanks for the guidance. Happy to contribute to the project.

2023-02-25 21:52 UTC, biodranik reviewed
I forgot to ask one question: `orientation` is absent here:
```
    <activity android:name="app.organicmaps.DownloadResourcesLegacyActivity"
        android:configChanges="screenLayout|screenSize"/>
```

So the activity is recreated on rotation. Right? Do we really need this "recreation" behavior? Wouldn't it be better to add `orientation` in the list of configChanges?

2023-02-25 23:03 UTC, Emilevillette commented
> I forgot to ask one question: `orientation` is absent here:
> 
> ```
>     <activity android:name="app.organicmaps.DownloadResourcesLegacyActivity"
>         android:configChanges="screenLayout|screenSize"/>
> ```
> 
> So the activity is recreated on rotation. Right? Do we really need this "recreation" behavior? Wouldn't it be better to add `orientation` in the list of configChanges?

Correct. I just tested it on commit [27730a1](https://github.com/Emilevillette/organicmaps/commit/27730a1469543268a180892fc4e6af74aadd635f), and it works as expected. I'll apply the changes tomorrow.

2023-02-28 23:52 UTC, vng approved these changes

2023-03-03 16:29 UTC, blo0147 approved these changes

2023-03-06 19:23 UTC, vng commented
@Emilevillette So, do we merge it, or will check the Activity orientation setting?

2023-03-06 20:28 UTC, Emilevillette commented
I'm sorry I had a busy week. I will do it right now.

2023-03-06 20:46 UTC, blo0147 approved these changes
Let me check it out!!

2023-03-06 22:21 UTC, biodranik approved these changes
Thank you! Isn't the fix beautiful and simple ;-)?

Let's merge it if it works and the issue is not reproduced.

2023-03-07 18:51 UTC, Jean-BaptisteC commented
<img src="https://user-images.githubusercontent.com/87148630/223521734-3bc9a0a7-0824-4413-ac08-c1a6416e2bc7.png" height=400 />

Wrong layout after rotate screen
Landscape layout is keep when i rotate to portrait

2023-03-07 19:31 UTC, Emilevillette commented
I did not encouter this issue during my testing, is it possible that it is device-specific?

2023-03-11 22:25 UTC, biodranik commented
@Jean-BaptisteC am I right that you've initially launched OM in the landscape to reproduce this issue?

2023-03-11 22:36 UTC, Jean-BaptisteC commented
I have started in portrait -> switch in landscape -> switch in portrait -> layout is incorrect

I have test on Android 8, problem doesn't appears

2023-03-11 22:49 UTC, biodranik commented
@Jean-BaptisteC It is reproduced on Android 13, right?

2023-03-11 22:53 UTC, Jean-BaptisteC commented
Yes :)

2023-03-11 22:56 UTC, biodranik commented
@Emilevillette can you please take a look? How other dialogs are correctly resized on rotation without their recreation?

2023-03-14 13:48 UTC, Emilevillette commented
I'm afraid I have other obligations atm, I will have more time in about 2 weeks.

2023-03-17 18:47 UTC, vng approved these changes

2023-03-17 18:47 UTC, merged

2023-03-17 21:29 UTC, Jean-BaptisteC commented
I have re-tested on master, layout is good when i change screen orientation

2023-03-18 19:29 UTC, biodranik commented
@Jean-BaptisteC can you please create an issue for the rotation bug?

2023-03-18 19:52 UTC, Jean-BaptisteC commented
> @Jean-BaptisteC can you please create an issue for the rotation layout bug?

I have re-tested with latest changes from master, i'm not able to reproduce bug

2023-03-19 10:13 UTC, biodranik commented
Great, thank you very much!