[android] Fix my position arrow during navigation
organicmaps/organicmaps pull request #4863
Opened 2023-03-26 07:57 UTC by biodranik

Reinvocation of #3462

Fixes #4855
Fixes #3441
Fixes #4456

@arnaudvergnet can you please also take a look and help to fix it properly? Looks like R.id.line_frame is not the correct id here:

```
final View navButtonSheet = findViewById(R.id.line_frame);
if (navButtonSheet != null)
  navButtonSheetHeight = navButtonSheet.getHeight();

```

2023-03-26 09:56 UTC, vng commented on android/src/app/organicmaps/Map.java
> +    nativeSetupMyPosition(offsetY);
Should use "y" instead of "offsetY" ?

2023-03-26 09:56 UTC, vng commented on android/src/app/organicmaps/MwmActivity.java
> +        " " + " navButtonSheetHeight = " + navButtonSheetHeight);
navButtonSheetHeight is only for debug print here, or supposed to add additional logic here?
Like use "navButtonSheetHeight" in "y" calculation, no?

2023-03-26 10:07 UTC, vng commented on android/src/app/organicmaps/Map.java
> +    nativeSetupMyPosition(offsetY);
Or
```
if (offsetY > 0)
{
  Logger.w("OFFSET", "nativeSetupMyPosition " + offsetY);
  nativeSetupMyPosition(offsetY);
}
```

2023-03-27 15:56 UTC, vng approved these changes

2023-03-27 15:56 UTC, vng commented on android/src/app/organicmaps/Map.java
> +    Logger.w(TAG, "" + offsetY);
Remove logs before merge

2023-03-27 15:56 UTC, vng commented on android/src/app/organicmaps/MwmActivity.java
> +    int navBottomSheetHeight = 0;
Can simplify like:
```
int offsetY = 0;
if (bar1 != null)
  offsetY = max(offsetY, bar1.height());
if (bar2 != null)
  offsetY = max(offsetY, bar2.height());
...
```

2023-03-27 16:25 UTC, biodranik commented on android/src/app/organicmaps/Map.java
> +  public void setupMyPosition(final Context context, int offsetY)
Лучше назвать adjustMyPosition, adjustMyPositionCoordinates, layoutMyPosition, или repositionMyPosition

2023-03-27 16:25 UTC, biodranik commented on android/src/app/organicmaps/MwmActivity.java
> +    mNavigationController = new NavigationController(this, mMapButtonsController, v -> onSettingsOptionSelected(), this::adjustBottomWidgets);
Тут осталось старое, лучшее название.

2023-03-27 16:25 UTC, biodranik commented on drape_frontend/my_position_controller.cpp
> +  return {m_visiblePixelRect.Center().x, m_visiblePixelRect.maxY() - m_positionRoutingOffsetY};
Does it break carplay or iOS navigation?

2023-03-27 16:34 UTC, vng requested changes
![image](https://user-images.githubusercontent.com/175612/228005062-79fc9550-f0f8-42c9-b4ec-6fa466181ee9.png)

Тут сломался обычный iOS.
Надо в нем константу домножить на visual scale или тоже честно вызывать UpdateRoutingOffsetY

2023-03-27 17:30 UTC, biodranik commented
Надо тогда явно в сигнатурах функций прописать, что передаваться должны не логические пиксели, а реальные, чтобы на айосе это делать перед передачей.

2023-03-27 21:12 UTC, vng commented
Да нет у нас нет "логических" пикселей и не было. И visual scale - это чисто наш баян, который решает задачу: а давайте одной метрикой задавать для всех девайсов иконки, шрифты, толщины, а уже в конкретном девайсе будем сами _высчитывать_ visual scale.

2023-03-28 06:11 UTC, biodranik commented on android/src/app/organicmaps/widget/placepage/PlacePageUtils.java
> +        /// @todo Why top is always == 0? Consider top Navigation toolbar?
Если речь о белой панельке сверху, то она не всегда же видна.

2023-03-28 07:12 UTC, rtsisyk commented on android/src/app/organicmaps/Map.java
> +  public void setupMyPosition(final Context context, int offsetY)
Переименовал

2023-03-28 07:13 UTC, rtsisyk commented on android/src/app/organicmaps/MapFragment.java
> -  public void adjustCompass(int offsetX, int offsetY)
Переименовал в updateCompassOffset чтобы было консистетно с updateMyPositionRoutingOffset

2023-03-28 07:22 UTC, biodranik commented
> Да нет у нас "логических" пикселей и не было. И visual scale - это чисто наш баян, который решает задачу: а давайте одной метрикой задавать для всех девайсов иконки, шрифты, толщины, а уже в конкретном девайсе будем сами высчитывать visual scale.

Всё придумал Apple. Сначала мы писали код под iPhone 3G, там было просто, один к одному. Потом вышел следующий айфон, и понеслась: логическое разрешение осталось как у 3G (чтобы не разломался интерфейс у старых прог), а [scale factor](https://developer.apple.com/documentation/uikit/uiview/1622657-contentscalefactor?language=objc) стал 2x (т.к. разрешение увеличилось).

Наш VisualScale вырос именно оттуда. На айосе до сих пор всё в "логических пикселях" в UI, которые нужно пересчитывать в физические в нашей OpenGL системе координат.

2023-03-28 10:25 UTC, vng commented on android/src/app/organicmaps/widget/placepage/PlacePageUtils.java
> +        /// @todo Why top is always == 0? Consider top Navigation toolbar?
Речь про тулбар навигации с кнопками авто/вело/пеше. Сейчас они не отнимает visible viewport, и кусок маршрута после построения прячется за ней.

2023-03-28 10:27 UTC, vng approved these changes

2023-03-28 10:27 UTC, merged