[android] Fix kmz/kml/kmb registration
organicmaps/organicmaps pull request #491
Opened 2021-06-05 07:13 UTC by rtsisyk

Signed-off-by: Roman Tsisyk <roman@tsisyk.com>

2021-06-05 11:05 UTC, biodranik requested changes

2021-06-05 11:05 UTC, biodranik commented on android/AndroidManifest.xml
> +        <data android:pathPattern="*.kmz"/>
Давай без точки сделаем, и дофильтруем в коде? Или просто проигнорим ошибки парса, если файл будет левый.

2021-06-05 11:05 UTC, biodranik commented on android/AndroidManifest.xml
> +        <data android:pathPattern=".*\\..*\\..*\\..*\\..*\\.kml" />
Я не уверен, что это достаточный уровень вложений. Костыльно.

2021-06-05 14:59 UTC, rtsisyk commented on android/AndroidManifest.xml
> +        <data android:pathPattern="*.kmz"/>
Так приложение всё равно будет триггерится на всякие левые файлы.

2021-06-05 15:00 UTC, rtsisyk commented on android/AndroidManifest.xml
> +        <data android:pathPattern=".*\\..*\\..*\\..*\\..*\\.kml" />
Подсмотрено в другом похожем приложении. Этот костыль работает. Файлы открываются. Есть ли смысл тратить время на переделку - не знаю. Нам важно уметь открывать kmb для миграции.

2021-06-05 15:59 UTC, biodranik commented on android/AndroidManifest.xml
> +        <data android:pathPattern=".*\\..*\\..*\\..*\\..*\\.kml" />
Глубина де фиксированная

2021-06-06 06:08 UTC, rtsisyk commented
Я предлагаю оставить как есть. Работает - файлы открываются.

2021-06-06 13:14 UTC, biodranik requested changes

2021-06-06 13:14 UTC, biodranik commented on android/AndroidManifest.xml
> +        <category android:name="android.intent.category.BROWSABLE" />
Эта категория должна быть везде.

Проверь с ней но без костыля, пожалуйста

2021-06-06 13:43 UTC, rtsisyk commented on android/AndroidManifest.xml
> +        <category android:name="android.intent.category.BROWSABLE" />
Проверил. Если просто добавить категорию в текущий код, то мы не открываем .kmb вообще никак. kmz и kml работают, но там mime type есть и срабатывает другой фильтр.

Следующий вариант работает, если не точек в имени файла:
```
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <data android:scheme="content"/>
        <data android:scheme="file"/>
        <data android:scheme="data"/>
        <data android:host="*"/>
        <data android:mimeType="*/*"/>
        <data android:pathPattern=".*\\.kmb" />
      </intent-filter>
```

My Places.kmb открываются, My.Places.kmb нет.
На StackOverflow правы:
https://stackoverflow.com/questions/3400072/pathpattern-to-match-file-extension-does-not-work-if-a-period-exists-elsewhere-i

2021-06-06 14:16 UTC, biodranik commented on android/AndroidManifest.xml
> +        <category android:name="android.intent.category.BROWSABLE" />
А так пробовал?

```
<intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <data android:scheme="content"/>
            <category android:name="android.intent.category.BROWSABLE"/>
            <category android:name="android.intent.category.DEFAULT" />
            <data android:mimeType="application/kmb" />
</intent-filter>
```

2021-06-06 14:31 UTC, biodranik commented on android/AndroidManifest.xml
> +        <category android:name="android.intent.category.BROWSABLE" />
Можно еще scheme=file вставить вместе с content

2021-06-06 14:32 UTC, biodranik commented on android/AndroidManifest.xml
> +        <category android:name="android.intent.category.BROWSABLE" />
И скорее всего понадобится host="*" или пустой.

2021-06-06 17:37 UTC, rtsisyk commented on android/AndroidManifest.xml
> +        <category android:name="android.intent.category.BROWSABLE" />
Попробовал следующие варианты:

```
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="content"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <category android:name="android.intent.category.DEFAULT" />
        <data android:mimeType="application/kmb" />
      </intent-filter>
```
 
```
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <data android:scheme="content"/>
        <data android:scheme="file"/>
        <data android:scheme="data"/>
        <category android:name="android.intent.category.BROWSABLE"/>
        <category android:name="android.intent.category.DEFAULT" />
        <data android:mimeType="application/kmb" />
      </intent-filter>
```

```
      <intent-filter>
        <action android:name="android.intent.action.VIEW"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <data
            android:host="*"
            android:mimeType="application/kmb"/>
      </intent-filter>
```

Ничего из этого не работает.

Откуда должно появиться application/kmb?  Врядли это где то прописано.

2021-06-10 08:47 UTC, rtsisyk commented
@biodranik

2021-06-10 08:53 UTC, biodranik approved these changes
Мне не нравятся костыли, но что поделать. Убедись только, что ОМ не предлагается сейчас при открытии любых других файлов в других прогах типа файловых менеджеров

2021-06-11 05:01 UTC, merged