fix instructions where to find OM version
organicmaps/organicmaps pull request #5326
Opened 2023-06-13 09:02 UTC by matkoniecz

tested for Android - maybe this instructions are correct for Apple devices?

2023-06-13 11:21 UTC, strump commented
![Screenshot_2023-06-13-14-07-30-95_75d0290a7c00525acd83c0ab8700d64c.jpg](https://github.com/organicmaps/organicmaps/assets/720808/78d1c682-2e35-4b81-8d92-24e4904e4572)

This green button does the same as Help section in the settings. Maybe rewrite as "Tap bottom left button with green OrganicMaps logo"?

2023-06-13 11:59 UTC, matkoniecz commented
@strump So that is what happened! I now seem to remember this button as having question mark icon.

Description rewritten in seemingly (to me) more readable form, special commit incantation added

2023-06-26 20:57 UTC, Mr-Mime requested changes

2023-06-26 20:57 UTC, Mr-Mime commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Organic Maps version: [you can find it by tapping button with green OrganicMaps logo, bottom left of the main screen]
```suggestion
 - Organic Maps version: [you can find it by tapping the button with the green OrganicMaps logo, bottom left of the main screen]
```

I suggest those small grammatical corrections

2023-06-26 21:42 UTC, biodranik commented
On iOS, there is still a question mark button.

2023-06-27 07:24 UTC, matkoniecz commented
So I guess that instructions should mention both? Or is this divergence a bug?

2023-06-27 07:26 UTC, biodranik commented
The plan is to update iOS icon too, but until it's not updated, it's better to keep both.

2023-09-17 06:18 UTC, biodranik commented on .github/ISSUE_TEMPLATE/bug_report.md
> + - Organic Maps version: [you can find it by tapping the button with the green OrganicMaps logo, bottom left of the main screen]
```suggestion
 - Organic Maps version: [you can find it by tapping the button with the green OrganicMaps logo, bottom left of the main screen on Android, or the `?` button on iOS]
```

2023-09-17 06:56 UTC, biodranik approved these changes
Thanks!

2023-09-17 06:56 UTC, merged