[strings] Translate detailed railway types
organicmaps/organicmaps pull request #5490
Opened 2023-07-08 17:50 UTC by pastk

Please send in translations for your language, thanks!

(@biodranik I wanted to try the deepl translation script, but I can't register to get a free deepl api token)

2023-07-08 18:43 UTC, fitojb requested changes
Spanish suggestions below

2023-07-08 18:43 UTC, fitojb commented on data/strings/types_strings.txt
> +    en = High-speed Railway
```suggestion
    en = High-speed Railway
    es = Tren de alta velocidad
```

2023-07-08 18:43 UTC, fitojb commented on data/strings/types_strings.txt
> +    en = Touristic Railway
```suggestion
    en = Touristic Railway
    es = Tren turístico
```

2023-07-08 18:43 UTC, fitojb commented on data/strings/types_strings.txt
> +    en = Railway
```suggestion
    en = Railway
    es = Tren
```

2023-07-08 18:43 UTC, fitojb commented on data/strings/types_strings.txt
> +    en = Railway Branch
```suggestion
    en = Railway Branch
    es = Ramal ferroviario
```

2023-07-08 18:43 UTC, fitojb commented on data/strings/types_strings.txt
> +    en = Utility Railway
```suggestion
    en = Utility Railway
```
```suggestion
    en = Utility Railway
    es = Tren de servicios
```

2023-07-08 18:43 UTC, fitojb commented on data/strings/types_strings.txt
>      et = Rööbastee
```suggestion
    et = Rööbastee
    es = Espolón ferroviario
```

2023-07-08 18:43 UTC, fitojb commented on data/strings/types_strings.txt
> +    en = Service Rail Track
```suggestion
    en = Service Rail Track
    es = Vía de maniobras
```

2023-07-08 18:54 UTC, Wivik reviewed
Here is the French lines.

2023-07-08 18:54 UTC, Wivik commented on data/strings/types_strings.txt
> +    en = High-speed Railway
```suggestion
    en = High-speed Railway
    fr = Train à grande vitesse
```

2023-07-08 18:54 UTC, Wivik commented on data/strings/types_strings.txt
> +    en = Touristic Railway
```suggestion
    en = Touristic Railway
    fr = Ligne touristique
```

2023-07-08 18:54 UTC, Wivik commented on data/strings/types_strings.txt
> +    en = Railway
```suggestion
    en = Railway
    fr = Chemin de fer
```

2023-07-08 18:54 UTC, Wivik commented on data/strings/types_strings.txt
> +    en = Utility Railway
```suggestion
    en = Utility Railway
    fr = Train de fret
```

2023-07-08 18:54 UTC, Wivik commented on data/strings/types_strings.txt
> +    en = Railway Spur
```suggestion
    en = Railway Spur
    fr = Embranchement ferroviaire
```

2023-07-08 18:54 UTC, Wivik commented on data/strings/types_strings.txt
> +    en = Service Rail Track
```suggestion
    en = Service Rail Track
    fr = Service ferroviaire
```

2023-07-09 15:04 UTC, LaoshuBaby reviewed
Here are Chinese (Simplified) translation

2023-07-09 15:04 UTC, LaoshuBaby commented on data/strings/types_strings.txt
> +    en = Railway Spur
```suggestion
    en = Railway Spur
    zh-Hans = 铁路岔线
```

2023-07-09 15:04 UTC, LaoshuBaby commented on data/strings/types_strings.txt
> +    en = Service Rail Track
```suggestion
    en = Service Rail Track
    zh-Hans = 服务性铁路
```

2023-07-09 18:13 UTC, matheusgomesms requested changes
Added PT/PT-BR

2023-07-09 18:13 UTC, matheusgomesms commented on data/strings/types_strings.txt
> +    en = High-speed Railway
en = High-speed Railway
pt = Ferrovia de alta velocidade

2023-07-09 18:13 UTC, matheusgomesms commented on data/strings/types_strings.txt
> +    en = Touristic Railway
en = Touristic Railway
pt = Ferrovia turística

2023-07-09 18:13 UTC, matheusgomesms commented on data/strings/types_strings.txt
> +    en = Railway
en = Railway
pt = Ferrovia

2023-07-09 18:13 UTC, matheusgomesms commented on data/strings/types_strings.txt
> +    en = Railway Branch
en = Railway Branch
pt = Ramal ferroviário

2023-07-09 18:13 UTC, matheusgomesms commented on data/strings/types_strings.txt
> +    en = Utility Railway
en = Utility Railway
pt = Ferrovia de serviços

2023-07-09 18:13 UTC, matheusgomesms commented on data/strings/types_strings.txt
>      pt-BR = Ramal de ferrovia
pt = Ramal de inserção
pt-BR = Ramal de inserção

2023-07-09 18:13 UTC, matheusgomesms commented on data/strings/types_strings.txt
> +    en = Service Rail Track
pt = Linha de serviço

2023-07-09 18:56 UTC, strump commented on data/strings/types_strings.txt
> +    en = High-speed Railway
`uk = Швидкісна залізниця`

2023-07-09 18:56 UTC, strump commented on data/strings/types_strings.txt
> +    en = Touristic Railway
`uk = Туристична залізниця`

2023-07-09 18:56 UTC, strump commented on data/strings/types_strings.txt
> +    en = Railway Branch
`uk = Залізнична гілка`

2023-07-10 00:25 UTC, Supaplextw reviewed
add zh-Hant translation

2023-07-10 00:56 UTC, Supaplextw commented on data/strings/types_strings.txt
>      en = Railway Bridge
zh-Hant = 鐵路橋

2023-07-11 14:10 UTC, matheusgomesms approved these changes

2023-07-11 16:43 UTC, vng approved these changes

2023-07-12 20:12 UTC, merged