[styles] add amenity=brothel and amenity=stripclub icon
organicmaps/organicmaps pull request #5736
Opened 2023-08-16 22:00 UTC by dvdmrtnz

Add amenity=brothel and amenity=stripclub icon

https://github.com/organicmaps/organicmaps/issues/210

2023-08-16 22:09 UTC, biodranik commented
Will it require changes in any age-related restrictions in app stores?

2023-08-16 22:17 UTC, dvdmrtnz commented
> Will it require changes in any age-related restrictions in app stores?

I don't know, but the "brothel" category and POI is already present in the current AppStore version of the app but without an icon.

2023-08-16 22:19 UTC, RedAuburn commented
google maps includes them and is rated PEGI 3, so gplay is probably fine

2023-08-17 01:11 UTC, vng approved these changes

2023-08-17 06:57 UTC, strump approved these changes

2023-08-17 12:07 UTC, pastk requested changes
Please add stripclub and brothel into `data/styles/clear/include/priorities_4_overlays.prio.txt`

2023-08-17 12:07 UTC, pastk commented on data/styles/clear/include/Icons.mapcss
> +area|z16-[amenity=brothel]
I guess make them z17- or z18- even.
For reference, amenity-cinema is z17-, amenity-car_rental is z18-.

2023-08-17 14:07 UTC, dvdmrtnz commented
> Please add stripclub and brothel into `data/styles/clear/include/priorities_4_overlays.prio.txt`

Added to priorities file and moved down to z18-

2023-08-17 15:02 UTC, pastk approved these changes
Merge after the current release is out, as it needs a maps regen.

2023-08-17 15:35 UTC, d4f5409d commented
Someone's in a mood 😏

2023-08-17 16:40 UTC, jimcarst approved these changes

2023-08-18 12:53 UTC, merged