[styles] prevent pedestrian areas from rendered as way and area
organicmaps/organicmaps pull request #5884
Opened 2023-08-31 18:31 UTC by map-per

fixes #1293

- Prevent pedestrian areas from rendered as way and area
- Routing on the outer line of pedestrian areas still works

#### Rendering (now)
[multipolygon](https://www.openstreetmap.org/relation/1951581) on the left and [simple area](https://www.openstreetmap.org/way/500116641) on the right
![Bildschirmfoto vom 2023-08-31 20-17-42](https://github.com/organicmaps/organicmaps/assets/79519062/cd8eb9fa-9d8e-4d21-9d72-73f358f79420)

#### Rendering (before)
![Screenshot (102)](https://github.com/organicmaps/organicmaps/assets/79519062/1aa4c785-cd4a-4732-b6e7-99a1be03b4d5)

2023-09-03 19:32 UTC, vng reviewed
@pastk LGTM here.
- Can we use 'none' or something like that here to delete 'line' entries?
- pathtext keep active?

2023-09-03 19:34 UTC, vng commented
@map-per Routing screenshot is not honest. Could you add one where pedestrian route goes exactly on area's edge?

2023-09-03 20:23 UTC, map-per commented
> @map-per Routing screenshot is not honest. Could you add one where pedestrian route goes exactly on area's edge?

The pedestrian route goes exactly along the edge, there is no additional way mapped

2023-09-03 20:28 UTC, map-per commented
> pathtext keep active?

Yes, missed that

2023-09-03 21:13 UTC, vng commented
I suspect it will not work like that ..
If we remove all linear styles, the generator (by default) will remove a linear feature. But we can add an exception here.

2023-09-04 10:23 UTC, pastk commented
> I suspect it will not work like that .. If we remove all linear styles, the generator (by default) will remove a linear feature. But we can add an exception here.

Yeap, removing the line drule completely will not work afaik.

An invisible line looks like a feasible (though hacky) approach.
It would be good to skip rendering such lines also.
We don't render lines with almost zero width already, `stylist.cpp`:
```
    // Skip lines with zero width. Lines can have zero width only if they have
    // path symbols along.
    /// @todo should never happen, change to assert.
    auto const lineRule = dRule->GetLine();
    if (lineRule != nullptr && (lineRule->width() < 1e-5 && !lineRule->has_pathsym()))
      return;
```
Could add another condition there to check for opacity also?

The only thing I don't like is a hacky feel of it :) But do we have a better (not too complex) solution?

2023-09-04 10:25 UTC, pastk commented
So edge routing doesn't work atm with multipolygon pedestrian areas, right?

2023-09-06 18:26 UTC, pastk approved these changes

2023-09-07 17:03 UTC, pastk requested changes
Exactly. Routing will stop working after maps regen as such lines will not be included into map data.

So let's go back to the transparent color solution for now.

2023-09-07 18:13 UTC, map-per commented
I regenerated the map and routing still works.

![Bildschirmfoto vom 2023-09-07 20-09-01](https://github.com/organicmaps/organicmaps/assets/79519062/05756f1b-f74d-4506-917d-7dfab5991f80)

But multipolygon `highway=pedestrian` areas without `area=yes` like (https://www.openstreetmap.org/relation/1951581) are not in the map data any more.

2023-09-07 18:16 UTC, dvdmrtnz commented
Related to https://github.com/organicmaps/organicmaps/issues/2393

2023-09-25 16:38 UTC, pastk commented
> I regenerated the map and routing still works.
> 
> But multipolygon `highway=pedestrian` areas without `area=yes` like (https://www.openstreetmap.org/relation/1951581) are not in the map data any more.

Ok, so it seems that the logic is more complicated...
If you want to go deeper: Line + Area features are processed around `generator/feature_processing_layers.cpp RepresentationLayer::Handle()`.

2023-09-26 06:16 UTC, map-per commented
I found a more elegant solution using `[!area]` (see: https://github.com/map-per/organicmaps/tree/pedestrian2), but I'm currently waiting for the experimental geneator changes (#5979) because reverse engineering / testing with unknown code is not very efficient.

Besides that I think that it's not true, that the generator automatically romoves linear features without a style, as underground waterways, that are not rendered, still show up in the place page when you select them on the map.

2023-09-26 10:09 UTC, pastk commented
> 
> Besides that I think that it's not true, that the generator automatically romoves linear features without a style, as underground waterways, that are not rendered, still show up in the place page when you select them on the map.

Could you share coords / screenshot of such a case please?

2023-09-28 07:32 UTC, map-per commented
I can't reproduce that now, so that was probably a nearby overground waterway that I confused with the underground one

2024-01-05 09:18 UTC, pastk commented
Let's discuss a solution in
- https://github.com/organicmaps/organicmaps/issues/7075

2025-08-30 16:11 UTC, closed without merging