[Android] Route info panel re-layout
organicmaps/organicmaps pull request #5889
Opened 2023-09-01 09:12 UTC by strump

Closes #3320.

There are 6 dirrefent layouts:
* Pedestrian/Bycicle route Portrait
* Pedestrian/Bycicle route Landscape
* Vehicle route Portrait
* Vehicle route Landscape
* Pedestrian route Tablet
* Vehicle route Tablet

## Pedestrian route Portrait
<img alt="cmp-ped-portrait" src="https://github.com/organicmaps/organicmaps/assets/720808/21c885dc-ebea-48c4-b13b-a81a46600c32" width="300px"/>

## Pedestrian route Landscape
<img alt="cmp-ped-land" src="https://github.com/organicmaps/organicmaps/assets/720808/15c56d09-61c7-4778-bb01-c2b279b6e99c" width="300px" />

## Vehicle route Portrait (No changes)
<img alt="cmp-vh-portrait" src="https://github.com/organicmaps/organicmaps/assets/720808/338a7010-2a34-4c28-af3c-8f90b67abce1" width="300px" />

## Vehicle route Landscape (No changes)
<img alt="cmp-vh-land" src="https://github.com/organicmaps/organicmaps/assets/720808/80bebfd7-ca50-4b74-bf82-4efa07a5bc19" width="300px" />

## Pedestrian route Tablet
<img alt="cmp-tablet-pedestrian" src="https://github.com/organicmaps/organicmaps/assets/720808/ca2e0cac-9e08-4a26-bc17-f7a0dea11f49" width="500px" />

## Vehicle route Tablet
<img alt="cmp-tablet-vh" src="https://github.com/organicmaps/organicmaps/assets/720808/b4fab3e8-0bc3-4d2a-a3c9-e20a06a5ca7d" width="500px" />

#Implementation details
Portrait layout was implemented using simple vertical/horizontal layouts:

<img alt="new-both-portrait" src="https://github.com/organicmaps/organicmaps/assets/720808/d389dff8-8c79-4633-9c86-2cd45e8c34de" width="500px" />

To switch Pedestrian-Vehicle mode we hide some elements:

<img alt="new-schema-portrait" src="https://github.com/organicmaps/organicmaps/assets/720808/3a6db2f1-4dae-4f36-8281-da0960ad7ffc" width="500px" />

Landscape layout was implemented using simple vertical/horizontal layouts:
<img alt="new-both-land" src="https://github.com/organicmaps/organicmaps/assets/720808/60f8885c-1587-43f6-ba77-69152e3343d9" width="500px" />

To switch Pedestrian-Vehicle mode we hide some elements:
<img alt="new-schema-land" src="https://github.com/organicmaps/organicmaps/assets/720808/7ee3f04e-e5a3-4ab4-b9b8-16e4f950914d" width="500px" />

## XML Layouts changes
Instead of multiple files `routing_details.xml`, `start_button.xml`, and `altitude_chart_panel.xml` all layout is located in `altitude_chart_panel.xml`.
But we have `RoutingPlanFragment` class which uses `fragment_routing.xml` and `start_button.xml`. This `RoutingPlanFragment` is never used because we have flag `tabletLayout=false`.

2023-09-01 10:55 UTC, Jean-BaptisteC requested changes
❌ Pixel 6 - Android 13
<img src="https://github.com/organicmaps/organicmaps/assets/87148630/8c9fd60c-6d0b-47c4-8874-bb5ebf92381d" height=400 />

2023-09-01 12:47 UTC, strump commented
@Jean-BaptisteC  I fixed extra space in car route info. Please verify.

2023-09-01 13:11 UTC, Jean-BaptisteC approved these changes
✅ Pixel 6 - Android 13
I have planned to test on tablet later

2023-09-02 23:18 UTC, biodranik reviewed
> Should we delete RoutingPlanFragment and all dependants?

Please remove all unused code. Any refactorings that simplify the implementation are welcome!

One important question: Would it be easy to later enable elevation graphs for other route types like cars and maybe PT?

2023-09-02 23:31 UTC, vng approved these changes

2023-09-04 07:50 UTC, strump commented
> One important question: Would it be easy to later enable elevation graphs for other route types like cars and maybe PT?

It should be easy change. Currently elevation chart is present in vehicle route layout but is hidden. We gonna need to unhide it and feed with elevation data.

2023-09-04 07:52 UTC, biodranik approved these changes
Thank you!

2023-09-04 07:52 UTC, merged