[android] Decouple CompassHelper from LocationHelper
organicmaps/organicmaps pull request #5904
Opened 2023-09-02 08:37 UTC by rtsisyk

Compass and location are two different things. Rename SensorsHelper to CompassHelper and extract it from LocationHelper to the upper level to simplify LocationHelper.

Please note that CompassHelper is still started by LocationHelper to avoid any semantic changes.

2023-09-02 08:39 UTC, rtsisyk commented on android/src/app/organicmaps/widget/placepage/PlacePageView.java
> +    MwmApplication.from(requireContext()).getCompassHelper().removeListener(this);
LocationHelper.INSTANCE and other 11 "enums" can be reworked in the same way.

2023-09-02 11:24 UTC, biodranik commented on android/src/app/organicmaps/location/CompassHelper.java
A more generic Sensor name is more appropriate than Compass IMO. We can later analyze gyro and accelerometer data for more advanced use cases than just "compass".

2023-09-02 17:08 UTC, rtsisyk commented on android/src/app/organicmaps/location/CompassHelper.java
Barometer is also a sensor. FaceID is also a sensor... Very generic name. Anyway, I can keep existing SensorHelper name, no problem.

2023-09-02 17:13 UTC, rtsisyk commented on android/src/app/organicmaps/location/CompassHelper.java
Renamed.

2023-09-02 20:21 UTC, biodranik approved these changes
LGTM considering all compass-related functionality works as before :)

@Jean-BaptisteC can you please quick-test this PR?

2023-09-02 20:35 UTC, Jean-BaptisteC requested changes
❌ Pixel 6 - Android 13

The compass doesn't work on map, when I do rotation arrow doesn't rotate
✅ Compass work on place page

2023-09-03 05:49 UTC, rtsisyk commented
> ❌ Pixel 6 - Android 13
> 
> The compass doesn't work on map, when I do rotation arrow doesn't rotate ✅ Compass work on place page

I forgot to wire this new listener to the main activity. Fixed. Thanks!

2023-09-03 07:15 UTC, rtsisyk commented
Rebased on the new android project structure.

2023-09-03 07:47 UTC, Jean-BaptisteC approved these changes
✅ Pixel 6 - Android 13

2023-09-03 10:16 UTC, merged