Fixed deeplinks for iOS
organicmaps/organicmaps pull request #591
Opened 2021-06-15 19:38 UTC by biodranik

Links on https://omaps.app/test.html should work properly

2021-06-17 06:24 UTC, vng requested changes

2021-06-17 06:24 UTC, vng commented on iphone/Maps/Classes/MapViewController.mm
> +    (void)[DeepLinkHandler.shared handleDeepLink];
А как это все будет работать в случае когда выше по коду выполнится:
[self presentViewController:[MWMAutoupdateController instanceWithPurpose:todo] animated:YES completion:nil];
а потом тут:
(void)[DeepLinkHandler.shared handleDeepLink];

?
Я предлагаю пока не показывать диалоги автообновления в этом патче.

2021-06-17 06:24 UTC, vng commented on iphone/Maps/Classes/MapViewController.mm
> -                                           object:nil];
А это точно не связано с вызовом applicationDidBecomeActive ?

2021-06-17 06:24 UTC, vng commented on iphone/Maps/Core/DeepLink/DeepLinkHandler.swift
> +              if (sd.centerLat != 0.0 && sd.centerLon != 0.0) {
Наверное так было до, но тут логичнее ||
Лондон на нулевом меридиане

2021-06-17 18:21 UTC, biodranik commented on iphone/Maps/Classes/MapViewController.mm
> -                                           object:nil];
Связано, подписка на ивент и вызов didBecomeActive. Но там был код показа welcome, который сейчас не нужен. Я выпилил и метод и подписку.

2021-06-17 18:24 UTC, biodranik commented on iphone/Maps/Classes/MapViewController.mm
> +    (void)[DeepLinkHandler.shared handleDeepLink];
Ну раньше код был именно такой ) Мы закомментили вызов welcome, а welcome из себя потом вызывал этот код.
Дип линк возможно покажется под диалогом автообновления, надо будет протестить.
Давай пока отключу если тебе не нравится. Но у нас есть в настройках опция auto download, она не про это?

2021-06-17 19:46 UTC, biodranik commented on iphone/Maps/Core/DeepLink/DeepLinkHandler.swift
> +              if (sd.centerLat != 0.0 && sd.centerLon != 0.0) {
Разумно, спасибо, поправил.

2021-06-17 20:28 UTC, vng commented on iphone/Maps/Classes/MapViewController.mm
> +    (void)[DeepLinkHandler.shared handleDeepLink];
- Хм, скорее когда был deep link, welcome скипался, не?
- Я честно говоря хз, но скорее всего это когда зумишься на пустую страну на карте - она автоматом начинает качаться ..

2021-06-17 20:30 UTC, vng commented on iphone/Maps/Classes/MapViewController.mm
> -                                           object:nil];
Я имел в виду applicationDidBecomeActive в MapsAppDelegate.mm, я не видел выпиливания в твоем коде. И он там по виду делает нужные инициализации. Он будет вызываться?

2021-06-17 20:31 UTC, vng commented on iphone/Maps/Classes/MapViewController.mm
> -                                           object:nil];
UPD, а я понял. Видимо тут все ок, да.

2021-06-17 20:48 UTC, vng commented
Аккуратно ребейзнуться на мастер. Я там тоже правил в районе MapViewController.

2021-06-18 00:39 UTC, biodranik commented on iphone/Maps/Classes/MapViewController.mm
> +    (void)[DeepLinkHandler.shared handleDeepLink];
Ты прав про скип диплинка, я вставил проверку.
С настройкой надо разобраться и переименовать, чтобы не было многозначно.

2021-06-18 05:40 UTC, vng approved these changes

2021-06-18 05:41 UTC, merged