[android-auto] NavigationController. Refactoring of PlaceScreen and NavigationScreen
organicmaps/organicmaps pull request #5998
Opened 2023-09-10 19:21 UTC by AndrewShkrob

* Created NavigationController for AA
* Moved all logic related to routes into NavigationController
* Simplified logic of PlaceScreen
* Reduced minSdkVersion: 23 -> 21
* Fixes: https://github.com/organicmaps/organicmaps/issues/5759

Demo:

https://github.com/organicmaps/organicmaps/assets/10351358/75d2feca-c48e-4fe7-9f93-a800206b2a62

2023-09-12 18:19 UTC, Jean-BaptisteC requested changes
❌ Pixel 6 - Android 13

- Select POI on the map from AA
- Switch to phone -> Layout is wrong (On my Pixel 6, routing icons are behind camera)
- We have the same problem when you switch to phone when routing is started

On AA, if I select POI and after another POI between switch, search bar + categories appear during 1 second, is it possible to fix?

2023-09-12 18:30 UTC, Jean-BaptisteC commented
Why size app been reduced in this version?

2023-09-13 10:14 UTC, AndrewShkrob commented
> ❌ Pixel 6 - Android 13

These bugs are related to the main app. I am aware of them and will address them later. The current PR only fixes the behavior on AA.

> On AA, if I select POI and after another POI between switch, search bar + categories appear during 1 second, is it possible to fix?

No, this issue is caused by the limitation of AA in terms of screen stack size and the inappropriate implementation of this logic within the car library. Our current solution addresses it, although it results in a "small" disadvantage of screen flickering. This matter was previously discussed here: https://github.com/organicmaps/organicmaps/pull/5045

2023-09-14 18:08 UTC, rtsisyk requested changes
In my opinion, this is a very controversial refactoring. 

There are two screens that need to work with app.organicmaps.routing.RoutingController (already existing in the code, please don't be confused with app.organicmaps.car.NavigationController added by this patch) - PlacePage and NavigationScreen. PlacePage is used to build and show the route. NavigationScreen is for actual navigation logic. Each screen has a different purpose and implements a different subset of app.organicmaps.routing.RoutingController.Container callbacks. 

What was the point of creating one more abstraction level on the top of the existing RoutingController to merge unrelated methods from PlacePage and NavigationScreen? Why can't we keep implementation of callbacks that are necessary for building the route in PlaceScreen and callbacks needed for navigation in NavigationScreen? There may be a slight overlap in the implementation, but it is not critical. The presence of  `screen instanceof PlaceScreen` and `screen instanceof NavigtionScreen` is a good indication that this new app.organicmaps.car.NavigationController is leaking.

2023-09-17 15:23 UTC, AndrewShkrob commented
@rtsisyk PTAL
@Jean-BaptisteC could you please retest? I've updated the logic, but the behavior should remain the same.

2023-09-17 15:32 UTC, AndrewShkrob commented on android/app/src/main/AndroidManifest.xml
> +        android:value="6"/>
We already use an API that is supported only from CarApiLevel >= 6. If we define the min level explicitly in the manifest, our app won't be visible on hosts with lower API. If we don't define it explicitly, the app will fail.

I still don't know how it works. Does the host need to support this CarApiLevel, or is it only related to the Android Auto application? If this value relates to the host, then we're in trouble.

By the way, navigation is supported only from CarApiLevel >= 4.

If there will be some users with hosts that don't support our app, then we can think about supporting older APIs (it's possible).

2023-09-22 15:48 UTC, Jean-BaptisteC approved these changes
✅ Pixel 6 - Android 13 + AA Emulator

Why when I select a place we don't have a progress bar on button start to start routing automatically?

2023-09-22 21:14 UTC, biodranik commented on android/app/src/main/AndroidManifest.xml
> +        android:value="6"/>
1. What API from level 6 are we using?
2. How many cars are supporting API 6 vs API 4?
3. What does it mean "Android Auto without navigation support" on API 1, 2, and 3? What was the point of it?

2023-09-23 10:47 UTC, rtsisyk commented on android/app/src/main/AndroidManifest.xml
> +        android:value="6"/>
This change is not forced by changed added by this PR. Existing code probably already violates API < 6 contract. Let's review things and evaluate what API level should be supported  in https://github.com/organicmaps/organicmaps/issues/6105. I added it to the list of blockers.

2023-09-23 14:53 UTC, closed without merging

2023-09-23 14:58 UTC, AndrewShkrob commented
> Why when I select a place we don't have a progress bar on button start to start routing automatically?

They broke everything again :( 
I think it's better to leave it this way until it's fixed.

| Before | Now |
|--------|--------|
| ![telegram-cloud-photo-size-2-5470138097455976427-x](https://github.com/organicmaps/organicmaps/assets/10351358/c8966eda-b803-4452-bfd0-6932e5d1fc18) | ![telegram-cloud-photo-size-2-5470138097455976429-x](https://github.com/organicmaps/organicmaps/assets/10351358/31abdd70-1b46-4d7e-bade-13c7772d4c13) |
| ![telegram-cloud-photo-size-2-5470138097455976428-x](https://github.com/organicmaps/organicmaps/assets/10351358/d6ffdc5b-4708-4393-b650-75257f8ace11) | ![telegram-cloud-photo-size-2-5470138097455976430-x](https://github.com/organicmaps/organicmaps/assets/10351358/5213427e-94dc-4137-b77d-5a7ece0de773) |