[android-auto] Localization for Android Auto
organicmaps/organicmaps pull request #6207
Opened 2023-10-04 18:19 UTC by AndrewShkrob

2023-10-05 05:20 UTC, rtsisyk approved these changes

2023-10-05 06:26 UTC, biodranik commented on data/strings/strings.txt
> +    bg = Свързан с автомобил
I don't see Belarusian and other languages. Did you use python/tools/translate.py?

2023-10-05 07:34 UTC, strump approved these changes

2023-10-05 22:01 UTC, Mr-Mime requested changes
Suggestions for German translation

2023-10-05 22:01 UTC, Mr-Mime commented on data/strings/strings.txt
> +    de = Erlaubnisse erteilen
```suggestion
    de = Erlaubnis erteilen
```

2023-10-06 00:13 UTC, RicoElectrico requested changes

2023-10-06 00:13 UTC, RicoElectrico commented on data/strings/strings.txt
> +    pl = Kontynuuj w telefonie
pl = Kontynuuj na  telefonie

2023-10-06 00:13 UTC, RicoElectrico commented on data/strings/strings.txt
> +    pl = Podłączony do samochodu
```
    pl = Podłączono do samochodu
```

2023-10-06 03:04 UTC, LaoshuBaby commented on data/strings/strings.txt
> +    zh-Hant = 繼續打電話
```suggestion
    zh-Hant = 繼續打電話
    zh-Hans = 在手机上继续
```

2023-10-06 03:04 UTC, LaoshuBaby commented on data/strings/strings.txt
> +    zh-Hans = 前往汽车屏幕
```suggestion
    zh-Hans = 转到汽车屏幕
```

2023-10-06 15:29 UTC, fitojb commented on android/app/src/main/res/values-ca/strings.xml
> +	<string name="aa_grant_permissions">Concedir permisos</string>
"Concedeix permisos". In Catalan localization guidelines by Softcatalà, commands use the imperative, not the infinitive, as Spanish does. Though I know that some phone OSes use the infinitive nevertheless, like iOS and EMUI.

2023-10-06 15:35 UTC, fitojb reviewed
I tried to use "automóvil" and "coche" consistently for MX and ES localizations, with an exception of the shortening "auto" when there was a note to create a string no longer than 18 characters.

2023-10-06 15:35 UTC, fitojb commented on android/app/src/main/res/values-es-rMX/strings.xml
> +	<string name="aa_used_on_the_phone_screen">Ahora estás usando Organic Maps en la pantalla del teléfono</string>
Ahora usa Organic Maps en la pantalla del teléfono

2023-10-06 15:35 UTC, fitojb commented on android/app/src/main/res/values-es-rMX/strings.xml
> +	<string name="aa_used_on_the_car_screen">Ahora estás usando Organic Maps en la pantalla del auto</string>
Ahora usa Organic Maps en la pantalla del automóvil

2023-10-06 15:35 UTC, fitojb commented on android/app/src/main/res/values-es/strings.xml
> +	<string name="aa_used_on_the_phone_screen">Ahora estás utilizando Organic Maps en la pantalla del teléfono</string>
Ahora usa Organic Maps en la pantalla del teléfono

2023-10-06 15:35 UTC, fitojb commented on android/app/src/main/res/values-es/strings.xml
> +	<string name="aa_used_on_the_car_screen">Ahora utilizas Organic Maps en la pantalla del coche</string>
Ahora usa Organic Maps en la pantalla del coche

2023-10-06 15:35 UTC, fitojb commented on android/app/src/main/res/values-es/strings.xml
> +	<string name="aa_connected_title">Estás conectado a Android Auto</string>
Se ha conectado a Android Auto

2023-10-06 15:35 UTC, fitojb commented on android/app/src/main/res/values-es/strings.xml
> +	<string name="aa_continue_on_the_phone">Continúa en el teléfono</string>
Continuar en el teléfono

2023-10-06 15:35 UTC, fitojb commented on android/app/src/main/res/values-es/strings.xml
> +	<string name="aa_location_permissions_request">Esta aplicación necesita acceder a tu ubicación para navegar.</string>
Esta aplicación necesita acceder a su ubicación para navegar.

2023-10-06 15:35 UTC, fitojb commented on android/app/src/main/res/values-es-rMX/strings.xml
> +	<string name="aa_connected_title">Estás conectado a Android Auto</string>
Se ha conectado a Android Auto

2023-10-06 15:35 UTC, fitojb commented on android/app/src/main/res/values-es-rMX/strings.xml
> +	<string name="aa_continue_in_the_car">A la pantalla del coche</string>
A la pantalla del auto

2023-10-06 15:35 UTC, fitojb commented on android/app/src/main/res/values-es-rMX/strings.xml
> +	<string name="aa_connected_to_car_notification_title">Conectado al coche</string>
Conectado al automóvil

2023-10-06 19:55 UTC, matheusgomesms requested changes
PT and PT-BR reviewed

2023-10-06 19:55 UTC, matheusgomesms commented on data/strings/strings.txt
> +    pt-BR = Continuar no telefone
```suggestion
    pt = Continuar no telemóvel
    pt-BR = Continuar no celular
```

2023-10-06 19:55 UTC, matheusgomesms commented on data/strings/strings.txt
> +    pt = Estás ligado ao Android Auto
```suggestion
    pt = Está ligado ao Android Auto
```

2023-10-06 19:55 UTC, matheusgomesms commented on data/strings/strings.txt
> +    pt = Estás agora a utilizar o Organic Maps no ecrã do automóvel
```suggestion
    pt = Está agora a utilizar o Organic Maps no ecrã do automóvel
```

2023-10-06 19:55 UTC, matheusgomesms commented on data/strings/strings.txt
> +    pt-BR = Para a tela do carro
```suggestion
    pt = Para ecrã do carro
    pt-BR = Para tela do carro
```

2023-10-06 19:55 UTC, matheusgomesms commented on data/strings/strings.txt
> +    pt-BR = Este aplicativo requer acesso à sua localização para fins de navegação.
```suggestion
    pt = Esta aplicação requer acesso à sua localização para fins de navegação.
    pt-BR = Este aplicativo requer acesso à sua localização para fins de navegação.
```

2023-10-06 19:55 UTC, matheusgomesms commented on data/strings/strings.txt
> +    pt-BR = Conceder permissões
```suggestion
    pt = Conceder permissão
    pt-BR = Conceder permissão
```

2023-10-09 11:33 UTC, jimcarst approved these changes

2023-10-29 14:19 UTC, AndrewShkrob commented
@biodranik merge?

2023-10-29 16:02 UTC, rtsisyk approved these changes

2023-10-29 16:02 UTC, merged