[android] Do not show "Enable location services" on every launch
organicmaps/organicmaps pull request #6435
Opened 2023-11-01 05:46 UTC by rtsisyk

LocationState.nativeGetMode() returns garbage until drape is initialized. Postpone kick-start of location dialogs until drape is initialized to check properly that mode is other than NO_FOLLOW_NO_POSITION.

This patch also fixes "location timeout" dialog that doesn't happen anymore in NO_FOLLOW_NO_POSITION_MODE.

Fixes #1128
Fixes #6098

2023-11-01 11:00 UTC, Jean-BaptisteC requested changes
❌ Pixel 6 - Android 14

- Start OM
- Use location button -> Google Play services dialog appears
- Rotate device -> Crash

```
E  vulkan/android_vulkan_context_factory.cpp:428 GetWidth(): CHECK(IsValid()) 
A  /home/runner/work/organicmaps/organicmaps/android/app/src/main/cpp/app/organicmaps/vulkan/android_vulkan_context_factory.cpp:428: int android::AndroidVulkanContextFactory::GetWidth() const: assertion "false" failed
A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4074 (ganicmaps.debug), pid 4074 (ganicmaps.debug)
A  Cmdline: app.organicmaps.debug
A  pid: 4074, tid: 4074, name: ganicmaps.debug  >>> app.organicmaps.debug <<<
A        #02 pc 00000000020a31a4  /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/lib/arm64/liborganicmaps.so (android::AndroidVulkanContextFactory::GetWidth() const+252) (BuildId: 9779bba2ddb5b7f256a597a3097fddfd2774f86d)
A        #03 pc 00000000020a4020  /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/lib/arm64/liborganicmaps.so (android::Framework::Resize(_JNIEnv*, _jobject*, int, int)+92) (BuildId: 9779bba2ddb5b7f256a597a3097fddfd2774f86d)
A        #04 pc 00000000020b39a0  /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/lib/arm64/liborganicmaps.so (Java_app_organicmaps_Map_nativeSurfaceChanged+60) (BuildId: 9779bba2ddb5b7f256a597a3097fddfd2774f86d)
A        #10 pc 000000000000f728  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk!classes4.dex] (app.organicmaps.Map.onSurfaceChanged+0)
A        #15 pc 000000000000f218  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk!classes4.dex] (app.organicmaps.MapFragment.surfaceChanged+0)
A        #74 pc 0000000000253788  [anon:dalvik-classes.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk] (androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild+0)
A        #79 pc 000000000025419c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk] (androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild+0)
A        #84 pc 000000000025411c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk] (androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout+0)
```

Another weird thing
- Start OM
- Accept Google Play Services pop-up
- Disable location
- Move to the map -> Google Play Services pop-up appears

2023-11-01 14:52 UTC, rtsisyk commented
> ❌ Pixel 6 - Android 14
> 
>     * Start OM
> 
>     * Use location button -> Google Play services dialog appears
> 
>     * Rotate device -> Crash
> 
> 
> ```
> E  vulkan/android_vulkan_context_factory.cpp:428 GetWidth(): CHECK(IsValid()) 
> A  /home/runner/work/organicmaps/organicmaps/android/app/src/main/cpp/app/organicmaps/vulkan/android_vulkan_context_factory.cpp:428: int android::AndroidVulkanContextFactory::GetWidth() const: assertion "false" failed
> A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4074 (ganicmaps.debug), pid 4074 (ganicmaps.debug)
> A  Cmdline: app.organicmaps.debug
> A  pid: 4074, tid: 4074, name: ganicmaps.debug  >>> app.organicmaps.debug <<<
> A        #02 pc 00000000020a31a4  /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/lib/arm64/liborganicmaps.so (android::AndroidVulkanContextFactory::GetWidth() const+252) (BuildId: 9779bba2ddb5b7f256a597a3097fddfd2774f86d)
> A        #03 pc 00000000020a4020  /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/lib/arm64/liborganicmaps.so (android::Framework::Resize(_JNIEnv*, _jobject*, int, int)+92) (BuildId: 9779bba2ddb5b7f256a597a3097fddfd2774f86d)
> A        #04 pc 00000000020b39a0  /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/lib/arm64/liborganicmaps.so (Java_app_organicmaps_Map_nativeSurfaceChanged+60) (BuildId: 9779bba2ddb5b7f256a597a3097fddfd2774f86d)
> A        #10 pc 000000000000f728  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk!classes4.dex] (app.organicmaps.Map.onSurfaceChanged+0)
> A        #15 pc 000000000000f218  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk!classes4.dex] (app.organicmaps.MapFragment.surfaceChanged+0)
> A        #74 pc 0000000000253788  [anon:dalvik-classes.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk] (androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild+0)
> A        #79 pc 000000000025419c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk] (androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild+0)
> A        #84 pc 000000000025411c  [anon:dalvik-classes.dex extracted in memory from /data/app/~~Dtmiw6hpPByBS4NUK3WpBw==/app.organicmaps.debug-xMGxbuOUPXCP0zF16tj3FQ==/base.apk] (androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout+0)
> ```
> 
> Another weird thing
> 
>     * Start OM
> 
>     * Accept Google Play Services pop-up
> 
>     * Disable location
> 
>     * Move to the map -> Google Play Services pop-up appears

Are you sure that this issue happens because of the patch? I don't really understand the correlation... I will try to repro locally.

2023-11-01 15:07 UTC, Jean-BaptisteC commented
Yes you're right, I'm able to reproduce on master, not on latest release.

2023-11-01 18:20 UTC, rtsisyk commented on android/app/src/main/java/app/organicmaps/location/LocationState.java
> +    return nativeGetMode();
No, it isn't. In this case any existing or new code that use the function will not work properly. This is the exact reason why we have this bug. autostartLocation() called from onResume() checked nativeGetMode() which returned  bougs mode = 0 (PENDING_POSITION) initially. Further initialization of drape changes the value to NO_FOLLOW_NO_LOCATION... The complain was that people didn't want to see location dialogs if location is "disabled"... We implement "location is disabled" via NO_FOLLOW_NO_POSITION... this is not right...

2023-11-02 20:55 UTC, vng reviewed
Discussed to remove PendingPosition -> NotFollowNoPosition.
Probably, it will solve the issue with ambiguity of NotFollowNoPosition state.

2023-11-04 15:59 UTC, rtsisyk commented
> Discussed to remove PendingPosition -> NotFollowNoPosition transition. Probably, it will solve the issue with the ambiguity of NotFollowNoPosition state.

This part has been extracted to https://github.com/organicmaps/organicmaps/pull/6465.

2023-11-04 16:00 UTC, rtsisyk commented on drape_frontend/my_position_controller.cpp
> +  if (m_listener && IsWaitingForLocation())
This part has been extracted to https://github.com/organicmaps/organicmaps/pull/6465.

2023-11-04 16:29 UTC, Jean-BaptisteC approved these changes
✅ Pixel 6 - Android 14
- Tested with Google Play Services

2023-11-04 17:40 UTC, rtsisyk commented
The PR has been reworked to use Drape as the source of truth of all location mode changes. Please review and test thoroughly.

2023-11-05 09:38 UTC, rtsisyk commented
Fixed false-positive lint error.

2023-11-05 10:14 UTC, Jean-BaptisteC approved these changes
✅ Pixel 6 - Android 14
- With Google Play Services
- Without Google Play Services

I have found a issue not related with this PR #6476

2023-11-05 18:48 UTC, rtsisyk commented
Rebased.

2023-11-18 13:43 UTC, biodranik commented on android/app/src/main/java/app/organicmaps/location/LocationState.java
> +    return nativeGetMode();
Can adding LOCATION_IS_DISABLED location mode solve this issue?

2023-11-19 18:58 UTC, rtsisyk commented
Please test this branch thoroughly using ANDROID_LOCATION_TEST.md. Pay attention to `adb logcat --pid="$(adb shell pidof -s app.organicmaps.debug)"|grep onMyPositionModeChanged` messages.

2023-11-19 19:01 UTC, rtsisyk commented on android/app/src/main/java/app/organicmaps/location/LocationState.java
> +    return nativeGetMode();
After #6465 NO_FOLLOW_NO_LOCATION became closer to LOCATION_IS_DISABLED, but there is still a case when drape changes from NO_FOLLOW_NO_LOCATION to PENDING_LOCATION after ~30h. This patch doesn't address this issue, but makes Android to be aware of any random changes of location mode that happen on the Drape side.

2023-11-20 06:51 UTC, biodranik approved these changes
Let's test it thoroughly in the master, @Jean-BaptisteC I assume that there could be some issues in edge cases with location (including API calls). We had a location test plan somewhere in docs, right?

2023-11-20 06:53 UTC, rtsisyk commented
> We had a location test plan somewhere in docs, right?

https://github.com/organicmaps/organicmaps/blob/master/docs/ANDROID_LOCATION_TEST.md

2023-11-20 06:54 UTC, merged

2023-11-26 08:31 UTC, Jean-BaptisteC reviewed
✅ Pixel 6 - Android 14