add hackerspace type
organicmaps/organicmaps pull request #6630
Opened 2023-11-21 17:46 UTC by RedAuburn

Icon:

<img width="42px" src="https://github.com/organicmaps/organicmaps/assets/26939824/f3f2b308-6fc7-45ee-b1d9-61d44da216e5"/>

fixes https://github.com/organicmaps/organicmaps/issues/6518

using icon from https://fontawesome.com/icons/gear?f=classic&s=solid (already credited)

2023-11-21 18:26 UTC, pastk commented
> <img alt="" width="42px" src="https://user-images.githubusercontent.com/26939824/284670376-f3f2b308-6fc7-45ee-b1d9-61d44da216e5.svg">

I get the idea, but its associated much more with some industry, mechanic or a mill..

Maybe a PCB-like pattern or a microchip? E.g.

![image](https://github.com/organicmaps/organicmaps/assets/18434508/c0545ded-d4a7-46a2-a94c-9ef316737891)

![image](https://github.com/organicmaps/organicmaps/assets/18434508/c7ec70f8-8937-4068-94ac-e0604cb0ed2a)

2023-11-21 18:48 UTC, pastk requested changes

2023-11-21 18:48 UTC, pastk commented on iphone/Maps/LocalizedStrings/es-MX.lproj/Localizable.strings
> +"type.highway.footway.demanding_alpine_hiking" = "Path";
its happening again :/

2023-11-21 18:48 UTC, pastk commented on data/categories.txt
> +cs:Hackerspace
if there is no translation then its better to delete such a row;
`en:` version is used for search always AFAIK

2023-11-21 18:48 UTC, pastk commented on data/editor.config
> +      <type id="leisure-hackerspace" group="shop">
I don't think it belongs to shops..

2023-11-21 18:48 UTC, pastk commented on data/strings/types_strings.txt
> +    da = Hackerspace
better let use the EN version instead of duplicating the string

2023-11-22 07:06 UTC, patepelo commented
I had already been working in some icon design for hackerspace, this is what I had:

![hacker_space-m](https://github.com/organicmaps/organicmaps/assets/23003127/f6d70890-1de8-4f42-8716-2d8f771e0a56)
![hacker_space-m (2)](https://github.com/organicmaps/organicmaps/assets/23003127/8284eeee-91fe-4b5b-bcf5-2a20faf9f25e)
![hacker_space-m (3)](https://github.com/organicmaps/organicmaps/assets/23003127/fc662055-6663-40ba-a873-dd26d67e1e60)

![image](https://github.com/organicmaps/organicmaps/assets/23003127/3bad76f6-add5-493f-83dc-2cd77fe24ea5)

2023-11-22 11:47 UTC, RedAuburn commented
> I had already been working in some icon design for hackerspace, this is what I had:

ah nice! i like the top left, but which one do you think we should use?

2023-11-22 12:58 UTC, pastk commented
TBH the top left doesn't ring a bell for me, I see no association...

I like the idea of a "virtual" cube, but it stops looking like a cube when in small size :/

2023-11-22 13:54 UTC, patepelo commented
Yeah, hackerspaces are a bit abstract and multidisciplinary, so it's hard to represent. Your electronics proposal are hard to put in a tiny size. We may use something inspired in the USB icon. 

![image](https://github.com/organicmaps/organicmaps/assets/23003127/1cd41d51-57a4-48fd-9669-e0838e4b365c)

Or the atom icon?

![image](https://github.com/organicmaps/organicmaps/assets/23003127/18c5fe90-f650-4ab5-8cab-c9e4fd64395b)


Or even a rocket icon

![image](https://github.com/organicmaps/organicmaps/assets/23003127/551446c9-044b-427e-8c75-5118bed86a46)

2023-11-22 14:06 UTC, patepelo commented
![image](https://github.com/organicmaps/organicmaps/assets/23003127/f56daa60-dbaf-4b9c-b4ca-01c41962b2c3)

2023-11-22 16:01 UTC, pastk commented
The light bulb looks alright, I hope it won't be confused with a shop :)

A microchip
![image](https://github.com/organicmaps/organicmaps/assets/18434508/7c0e1195-b381-4d50-8022-ad4e09c69bb6)

https://fontawesome.com/icons/microchip?f=classic&s=solid&sz=2xs&pc=%23000000

2023-11-22 16:07 UTC, pastk approved these changes

2023-11-22 18:42 UTC, biodranik commented
A light bulb means a shop that sells lights.

2023-11-22 18:44 UTC, biodranik commented
There are some interesting icons here: https://www.google.com/search?q=hackerspace+icon

Stylized H and S letters may also be ok. Colors can also be used if necessary.

2023-11-22 22:02 UTC, Misalf-git commented
What about a "terminal console" or "command prompt"-like icon?
`>_`

When I think of "hacking" I think of _mashing on the keyboard_.

I have seen `</>` occasionally to represent any `code` (HTML, as it (I guess) resembles a programming language for a broader range of people than FORTRAN does) and got the idea immediately.

A cube reminds me of a kind of packaging service / post office / parcel locker (i.e. confusable with existing icons).

Light bulb and rocket is just something else. :)

PCB pattern, microchip and USB logo resemble techy things, but I might as well think I can bring there my hardware for repair.

2023-11-22 22:09 UTC, Misalf-git commented
![https://www.hackerspace.gr/wiki/images/thumb/Hackerspace.svg/108px-Hackerspace.svg.png](https://www.hackerspace.gr/wiki/images/thumb/Hackerspace.svg/108px-Hackerspace.svg.png)

2023-11-23 00:01 UTC, biodranik commented
Recognizable command prompt is a good idea to try.

2023-11-23 08:46 UTC, pastk commented
I guess a command prompt will be recognizable by devs and power users mostly :) But could be alright.

Wiki's (shortened) definition for a reference
> A hackerspace is a community-operated workspace where people with common interests, such as computers, machining, technology, science, digital art, or electronic art, can meet, socialize, and collaborate.

2023-11-23 10:56 UTC, patepelo commented
> They click it and learn.

Exactly, most of the icons here are valid.

 We should find a common way to improve new icon design validation. It's hard to convince all and we end up with a pile of stalled discussions and many POIs without icon representations.

2023-11-23 11:42 UTC, biodranik commented
My point is simple:
1. Icons that may be associated with some other shops/types are not good.
2. Icons that can be recognized at least by the target audience but not by the general audience are better than icons that can not be recognized by anyone.

2023-11-23 12:00 UTC, patepelo commented
> My point is simple:
> 
> 1. Icons that may be associated with some other shops/types are not good.
> 2. Icons that can be recognized at least by the target audience but not by the general audience are better than icons that can not be recognized by anyone.

Your point is valid and I agree with it. 

I'm opening a broader topic that it is hard for new icons to find a clear path for design review. I'm not sure how it could be improved but we have a bottle neck. 

Maybe we could have a polling system or a design committee. I'll move this topic into it's own discussion for keeping it off the hacker-space thread.

2023-11-23 16:06 UTC, Misalf-git commented
![prompt_chip.png](https://github.com/organicmaps/organicmaps/assets/72605561/1003fa11-2a63-4a1a-9b44-4bbd5fa34de0)

![prompt_chip_house.png](https://github.com/organicmaps/organicmaps/assets/72605561/781280ca-3c02-4047-8487-44349aa49ca0)

2023-11-23 16:29 UTC, pastk commented
I like the first one :)

2023-11-23 16:34 UTC, RedAuburn commented
> ![prompt_chip.png](https://user-images.githubusercontent.com/72605561/285261293-1003fa11-2a63-4a1a-9b44-4bbd5fa34de0.png)


This is good :) I'll make an SVG of it

2023-11-23 17:58 UTC, RedAuburn commented
![image](https://github.com/organicmaps/organicmaps/assets/26939824/1bc1d128-b18e-43a7-aa34-ff8c493c24f3)

now using this icon 👍️ ptal @pastk

2023-11-23 18:30 UTC, pastk approved these changes

2023-11-23 19:43 UTC, patepelo commented
I like that it also loos like a robot.

Thanks @Misalf-git @RedAuburn

2023-11-24 09:41 UTC, biodranik commented
How are they looking on the map in light/dark styles?

2023-11-24 11:58 UTC, RedAuburn commented
> How are they looking on the map in light/dark styles?

![image1](https://github.com/organicmaps/organicmaps/assets/26939824/1faa3111-91ce-47a4-b1e3-1ee9431961c2)

2023-11-24 12:44 UTC, biodranik commented
Thanks! IMO it looks a bit like a bug (insect) :), and too detailed/complex inside the circle when it's small (check with 18x18 pixels size).

Maybe leaving >_ is cleaner (although it may be associated with anime).

2023-11-24 14:57 UTC, biodranik commented
Need to see it on the map in a smaller size...

2023-11-24 15:29 UTC, RedAuburn commented
> Need to see it on the map in a smaller size...

as you wish :)

![signal-2023-11-24-152907_002](https://github.com/organicmaps/organicmaps/assets/26939824/1868259a-8998-4a5a-80a1-9b7a28fc4668)

2023-11-24 16:11 UTC, biodranik commented
Definitely better without traces. Maybe also try a thinner (out)line and a more monitor-like rectangle?

2023-11-25 12:17 UTC, dvdmrtnz commented
> with no traces:
> <img alt="" width="64px" src="https://private-user-images.githubusercontent.com/26939824/285486469-a51a7985-c1e3-48b5-8fbf-5e4d7eb7af11.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MTQ4NzYsIm5iZiI6MTcwMDkxNDU3NiwicGF0aCI6Ii8yNjkzOTgyNC8yODU0ODY0NjktYTUxYTc5ODUtYzFlMy00OGI1LThmYmYtNWU0ZDdlYjdhZjExLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDEyMTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOGI2NjNiODhmNGFjNTI3YzQ4M2FmZGUxMDZlNmQ4Nzg4OWU5NWE3NzhhZjY1YTM2M2YxZWI4ZjhjNzI0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wjsfcKc99k2tETd6m-QGxo2x66oNDu3CQLShrrKknAo">

I like this one

2023-11-27 13:13 UTC, pastk commented on data/categories.txt
> +zh-Hant:駭客空間
Most langs ended up with the "Hackerspace" translation :)
https://github.com/organicmaps/organicmaps/pull/6630#discussion_r1401018675

2023-11-28 12:30 UTC, RedAuburn commented
fixed comments, icon now using thinner lines:

![image](https://github.com/organicmaps/organicmaps/assets/26939824/66f4c20a-d361-4b43-9664-c9625b7baab0)

2023-11-28 14:05 UTC, vng approved these changes

2023-11-28 14:06 UTC, merged