Belarusian localization
organicmaps/organicmaps pull request #700
Opened 2021-06-22 21:13 UTC by mkatliar

2021-07-01 06:16 UTC, vng requested changes

2021-07-01 06:16 UTC, vng commented on data/strings/strings.txt
> +    comment = Share one specific bookmark using SMS, %1$@ contains om:// and %2$@ http://omaps.app link. @NOTE non-ascii symbols in the link will result in max 70 characters SMS instead of 140.
Здесь и далее (много изменений не про беларуский язык) что-то пошло не так. Вероятно, надо сделать rebase

2021-07-01 06:16 UTC, vng commented on data/strings/strings.txt
> +    vi =  ̉n
А здесь вероятно редактор накоцал?

2021-07-01 06:17 UTC, vng commented
Я бы оставил 3 коммита предварительно ребейзнув:
- vscode
- strings.txt
- regenerated resource files

2021-07-01 11:35 UTC, mkatliar commented on data/strings/strings.txt
> +    vi =  ̉n
Похоже

2021-07-01 11:36 UTC, mkatliar commented on data/strings/strings.txt
> +    comment = Share one specific bookmark using SMS, %1$@ contains om:// and %2$@ http://omaps.app link. @NOTE non-ascii symbols in the link will result in max 70 characters SMS instead of 140.
Проверю

2021-07-01 15:25 UTC, rtsisyk commented on data/strings/strings.txt
> +    be =
А не сломается локализация от пустых строк? Быть может лучше вообще не добавлять, если нечего пока?

2021-07-01 16:37 UTC, mkatliar commented on data/strings/strings.txt
> +    be =
Это не законченный пулл-реквест, draft.

2021-07-01 19:34 UTC, biodranik commented
Многие строчки могут быть уже не актуальны, мы не успели написать тул-сканер на актуальность :(
Как минимум те, что про Lite можно удалять.

2021-07-03 00:24 UTC, mkatliar commented on data/strings/strings.txt
> +    vi =  ̉n
Выправіў

2021-07-03 00:24 UTC, mkatliar commented on data/strings/strings.txt
> +    comment = Share one specific bookmark using SMS, %1$@ contains om:// and %2$@ http://omaps.app link. @NOTE non-ascii symbols in the link will result in max 70 characters SMS instead of 140.
Выправіў

2021-07-10 21:39 UTC, biodranik commented
Как вариант, можно извлечь строчки переводов из apk Google Maps, и там посмотреть некоторые термины, чтобы пользователям было легче.

Есть ещё data/categories.txt и iphone/plist.txt

2021-07-17 13:09 UTC, greshilov commented
> Многие строчки могут быть уже не актуальны, мы не успели написать тул-сканер на актуальность :(
> Как минимум те, что про Lite можно удалять.
> 
> Я могу позже помочь вычистить финальную версию и отребейзить без конфликтов.

Такая тулза есть, если я ничего не путаю. Но обновляли её достаточно давно.

`tools/python/clean_strings.py -s`

2021-07-18 20:33 UTC, biodranik commented
Нужна помощь с rebase? Мы только что вмержили вычищенные строки, возможно, сэкономит время на переводе.

2021-07-24 14:51 UTC, rtsisyk commented
Предлагаю убрать пустые строчки "be = " и вливать. Дальше можно следующим PR улучшить переводы.

2021-07-27 13:45 UTC, mkatliar commented
@rtsisyk давайце я сёння-заўтра даб'ю астатняе, зраблю rebase, і тады замержым.

2021-07-27 20:26 UTC, biodranik commented
@mkatliar добра! Мы выпилили довольно много строчек, а некоторые потом впилили обратно (и не факт что на то же место), так что ребейз будет непростым. Дайте знать, если нужна помощь.

2021-08-02 14:38 UTC, mkatliar commented
> Как вариант, можно извлечь строчки переводов из apk Google Maps, и там посмотреть некоторые термины, чтобы пользователям было легче.
Гэта добрая ідэя, давайце гэта зробім наступным разам. Пакуль што я дабіў як ёсць, стараючыся быць паслядоўным у тэрміналогіі.

2021-08-06 21:19 UTC, biodranik requested changes
Нужно следующим шагом перевести data/categories.txt, iphone/plist.txt и возможно даже strings/types_strings.txt

2021-08-06 21:19 UTC, biodranik commented on data/strings/strings.txt
> +    ru = Пазбягаць грунтовак
Перепутаны языки.

2021-08-06 21:19 UTC, biodranik commented on data/strings/strings.txt
> +    be = Не атрымалася пракласці маршрут. Выберыце іншыя кропкі маршрута.
ВыбЯрыце?

2021-08-06 21:19 UTC, biodranik commented on data/strings/strings.txt
> +    be = Не атрымалася пракласці маршрут да вашага пункту прызначэння. Выберыце іншы пункт прызначэння.
ВыбЯрыце?

2021-08-06 21:19 UTC, biodranik commented on data/strings/strings.txt
> +    be = Клавіятура недасяганьная падчас язды
недасягальная

2021-08-06 21:19 UTC, biodranik commented on data/strings/strings.txt
> +    be = Гэтая налада ўключае запіс журнала падзей для мэтаў дыягностыкі. Гэта можа дапамагчы нашай камандзе вырашаць праблемы з дадаткам. Уключайце гэтую оцыю часова каб запісаць і паслаць нам дэтал
опцыю

2021-08-07 13:05 UTC, mkatliar commented on data/strings/strings.txt
> +    be = Гэй, глядзі маё цяперашняе месцазнаходжанне на мапе Organic Maps!
выпраўлена

2021-08-07 13:06 UTC, mkatliar commented on data/strings/strings.txt
> +    be = Гэй, глядзі маё цяперашняе месцазнаходжанне на мапе! %1$@ альбо %2$@ Няма офлайн-мапаў? Спампуй тут: https://omaps.app/get
выпраўлена

2021-08-07 13:09 UTC, mkatliar commented on data/strings/strings.txt
> +    fr = Ceci vous permet d’enregistrer le chemin emprunté pendant un certain temps et de le voir sur la carte. Veuillez noter : l’activation de cette fonction entraîne une grande utilisation de la b
выправіў

2021-08-07 13:11 UTC, mkatliar commented on data/strings/strings.txt
> +    be = Веб-сайт
выправіў

2021-08-07 13:11 UTC, mkatliar commented on data/strings/strings.txt
> +    be = Абнавіць усе
выправіў

2021-08-07 13:12 UTC, mkatliar commented on data/strings/strings.txt
> +    ru = Пазбягаць грунтовак
выправіў

2021-08-07 13:13 UTC, biodranik commented on data/strings/strings.txt
> +    be = Абнавіць усе
Для удобства, можно лайкать коммент или жать кнопку resolve, или просто всё поправить и одним комментом написать "поправлено".

2021-08-07 13:15 UTC, mkatliar commented on data/strings/strings.txt
> +    be = Не атрымалася пракласці маршрут. Выберыце іншыя кропкі маршрута.
"Е" пераходзіць у "я" у першым складзе перад націскам: https://adukar.by/news/abiturientu/akanne-i-yakanne-pravapis-galosnyh-e-yo-ya-na-palcah

Ва ўсім перакладзе паслядоўна выкарыстоўваецца "выберыце". Можна зняніць усюды на "абярыце" -- менш літар. Як вам такі варыянт?

2021-08-07 13:16 UTC, mkatliar commented on data/strings/strings.txt
> +    be = Не атрымалася пракласці маршрут да вашага пункту прызначэння. Выберыце іншы пункт прызначэння.
гл. вышэй

2021-08-07 13:17 UTC, mkatliar commented on data/strings/strings.txt
> +    be = Клавіятура недасяганьная падчас язды
выправіў

2021-08-07 13:19 UTC, mkatliar commented on data/strings/strings.txt
> +    be = Гэтая налада ўключае запіс журнала падзей для мэтаў дыягностыкі. Гэта можа дапамагчы нашай камандзе вырашаць праблемы з дадаткам. Уключайце гэтую оцыю часова каб запісаць і паслаць нам дэтал
Выправіў. Таксама прыбраў першае "гэтая", каб было менш паўтораў.

2021-08-07 13:52 UTC, biodranik approved these changes

2021-08-07 13:52 UTC, merged

2021-08-08 03:15 UTC, mkatliar commented on data/strings/strings.txt
> +    be = Калі ласка, падрабязна апішыце праблему, каб супульнасць OpenStreetMap магла выправіць памылку.
Супольнасць

2021-08-08 03:18 UTC, mkatliar commented on data/strings/strings.txt
> +    be = Каб дадаць закладку, націсніце на месца на мапе і потым на іконку з зорачкай
Магчыма.

2021-08-08 03:20 UTC, mkatliar commented on data/strings/strings.txt
> +    be = Сартаваць па змоўчанні
"па змаўчанні"

2021-08-08 03:28 UTC, mkatliar commented on data/strings/strings.txt
> +    be = Кара мятро недасягальная
метро )