render amenity=police area
organicmaps/organicmaps pull request #7029
Opened 2023-12-31 00:09 UTC by RedAuburn

basic fix for https://github.com/organicmaps/organicmaps/issues/3445

clear / vehicle
![image1](https://github.com/organicmaps/organicmaps/assets/26939824/073e86f5-130c-48a6-bbd5-9d25ca8e7b3b)

2024-01-03 17:37 UTC, pastk commented
Why this choice of color? Looks similar to airports and industrial areas...

Let's discuss what should it mean. Some kind of restriction? Alert?
Or just highlight amenity's area?

Note that we've added prison areas recently (#6325) in grey-ish. And we use red pattern for military zones.

2024-01-03 17:51 UTC, pastk commented on data/styles/vehicle/include/priorities_4_overlays.prio.txt
> +amenity-police                                      # icon z17- (also has area z12-)
I think the area fill is not needed / not useful for a driver.
E.g. we don't use area fills for unis, hospitals...

2024-01-03 17:51 UTC, pastk commented on data/styles/clear/include/Basemap.mapcss
> +area|z12-[amenity=police]
Let's make it z17- just like the icon.

Re the #2856 idea
1. we haven't decided on it for sure (need more experimentation)
2. when/if we decide it'd be better to migrate all areas at once

2024-01-05 23:38 UTC, biodranik commented
What is the value for map users to see the police area? Does anyone (except OSMers) really need it?

2024-01-06 06:28 UTC, pastk commented
> What is the value for map users to see the police area? Does anyone (except OSMers) really needs it?

- easier to spot when one needs it (to visit a station or to choose a place to stay closer to the station...)
- often such grounds are restricted access, hence to warn (similar to military zones and prisons)

2024-01-06 06:30 UTC, pastk commented
> Why this choice of color? Looks similar to airports and industrial areas...
> 
> Let's discuss what should it mean. Some kind of restriction? Alert? Or just highlight amenity's area?
> 
> Note that we've added prison areas recently (#6325) in grey-ish. And we use red pattern for military zones.

@organicmaps/styles any ideas of a different fill color?

2024-01-08 15:59 UTC, euf commented
In this case I'm not sure about purple color. It's already used for airports, and there is no cognitive links with it or aesthetic reasons to use it again. Also this purple is too eye-catching. While airports are important in terms of city topography and it's okay for them to be prominent, police stations are not that much of a landmarks for most of use cases.

I'd recommend trying the same hatching as for prisons #6325 because
- both prisons and police areas are related to law enforcement 
- hatching already represents somewhat limited access to these areas 
- it's not "dangerous", like military, so using gray instead of read makes more sense
- even if you believe police areas should be easily noticeable, they shouldn't have more visual accent than military areas

2024-01-08 16:00 UTC, euf requested changes
In this case I'm not sure about purple color. It's already used for airports, and there is no cognitive links with it or aesthetic reasons to use it again. Also this purple is too eye-catching. While airports are important in terms of city topography and it's okay for them to be prominent, police stations are not that much of a landmarks for most of use cases.

I'd recommend trying the same hatching as for prisons #6325 because
- both prisons and police areas are related to law enforcement 
- hatching already represents somewhat limited access to these areas 
- it's not "dangerous", like military, so using gray instead of read makes more sense
- even if you police areas should be noticeable, they shouldn't have more visual accent than military 

If gray hatching looks suboptimal, grayish blue tint `#5d729c` could work. 

I got it by starting from Navy Blue `#000080` and adjusting Lightness to `55.21` to match prison `#000080` and adjusting Chroma to `0.07` to be about 1/3 of military `#e53935` in OKLCH color picker:
https://oklch.com/#55.21,0.07,264.05202063805507,100

2024-02-23 13:21 UTC, closed without merging

2024-04-18 19:42 UTC, pastk commented
Many amenities/POIs have areas, not just police stations. And many of them are not rendered by OM. E.g. zoos, resorts, marketplaces, events venues, etc.

The idea is to add a generic "amenity" fill, the actual amenity it belongs to should be clear by map context (e.g. we can tell apart kindergartens and unis, right? :) even though they use the same fill color)
I think we can use `@pedestrian_area`, e.g. its being used for `amenity=place_of_worship` already.

WDYT?

2024-04-18 20:26 UTC, pastk commented
IMO visualized borders could be possibly confused with barriers (like fences) whereas it could be just a territory without borders..