[routing] Fixed invalid camera.
organicmaps/organicmaps pull request #7178
Opened 2024-01-15 18:37 UTC by vng

Closes https://github.com/organicmaps/organicmaps/issues/7093

2024-01-15 19:03 UTC, Jean-BaptisteC requested changes
❌ Pixel 6 - Android 14
Not works with this speed camera in enforcement relation https://www.openstreetmap.org/relation/3378396#map=17/48.16434/6.45473

2024-01-15 19:36 UTC, Jean-BaptisteC commented
|Before|After|
|-|-|
|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/42f11567-e53e-44c1-859e-e8e51970f320" height=400 />|<img src="https://github.com/organicmaps/organicmaps/assets/87148630/e3b8e988-0654-4b7b-9627-f54c06f9ccf9" height=400 />|

2024-01-20 03:17 UTC, vng commented
@Jean-BaptisteC So, approve or not?

2024-01-20 08:14 UTC, Jean-BaptisteC approved these changes

2024-01-20 11:30 UTC, merged