[strings] Updated Portuguese translations
organicmaps/organicmaps pull request #725
Opened 2021-06-25 09:28 UTC by biodranik

Thanks to @laralem, see #723

2021-06-25 09:37 UTC, biodranik commented on data/strings/strings.txt
> +    pt:one = %s objeto
%d here and below

2021-06-25 09:37 UTC, biodranik commented on data/strings/strings.txt
> +    pt:one = %s lugar
%d here and below

2021-06-25 09:37 UTC, biodranik commented on data/strings/strings.txt
> +    pt:one = %s percurso
%d here and below

2021-06-25 09:37 UTC, biodranik commented on data/strings/strings.txt
> +    pt = Respeitamos a sua privacidade: não existem rastreadores na aplicação e o código-fonte é aberto
We historically start translations from en and ru, as our team can read them easily and check/add other (ideally sorted) translations below based on that.

2021-06-25 09:37 UTC, biodranik commented on data/strings/strings.txt
> -    pt-BR = Estamos transferindo os seus mapas baixados do Organic Maps Lite para o Organic Maps. Isto pode demorar alguns minutos.
[move_lite_maps_to_pro]
[move_lite_maps_to_pro_ok]
[move_lite_maps_to_pro_failed]
These translated blocks should be completely removed, they are not used anymore for a long time.

2021-06-27 07:57 UTC, vng commented on data/strings/strings.txt
> +    pt:one = %s objeto
pt:one - это так и надо?

2021-06-27 07:58 UTC, vng commented on data/strings/strings.txt
> +    pt = Respeitamos a sua privacidade: não existem rastreadores na aplicação e o código-fonte é aberto
Тут pt, а выше было pt:one
Стоит сделать единообразно

2021-06-27 22:12 UTC, biodranik commented on data/strings/strings.txt
> +    pt:one = %s objeto
Это перевод для единственного числа аргумента. Twine так умеет )

2021-06-27 22:13 UTC, biodranik commented on data/strings/strings.txt
> +    pt = Respeitamos a sua privacidade: não existem rastreadores na aplicação e o código-fonte é aberto
Не, one это когда параметр равен 1.

2021-07-04 21:35 UTC, Suburbanno commented
hope to see this soon on android

2021-07-04 21:47 UTC, biodranik commented
@Suburbanno can you please check that the Brazilian dialect is properly working now on Android? E.g. that there are some different translations for Portugal and Brazilian versions.

2021-07-04 21:50 UTC, Suburbanno commented
> @Suburbanno can you please check that the Brazilian dialect is properly working now on Android? E.g. that there are some different translations for Portugal and Brazilian versions.

I need an updated build, can you send me? I don't have the necessary means to build...

2021-07-05 06:42 UTC, biodranik commented
@Suburbanno Can you please confirm that the current build at least switches to Brazilian for some text elements in the interface?

Also,  it would be great if someone can take a look at [data/strings/types_strings.txt](../blob/master/data/strings/types_strings.txt) and [iphone/plist.txt](../blob/master/iphone/plist.txt) and add/fix translations there.

2021-07-05 15:27 UTC, Suburbanno commented
> @Suburbanno Can you please confirm that the current build at least switches to Brazilian for some text elements in the interface?
> 
> Also,  it would be great if someone can take a look at [data/strings/types_strings.txt](../blob/master/data/strings/types_strings.txt) and [iphone/plist.txt](../blob/master/iphone/plist.txt) and add/fix translations there.

I'm on version 2021.06.23-9, it's still shown in Portuguese from Portugal.  I checked the files and they really need translations, I will do a PR soon...

2021-07-11 06:15 UTC, vng requested changes

2021-07-11 06:15 UTC, vng commented on iphone/Maps/LocalizedStrings/ro.lproj/Localizable.strings
> +"prefs_languages_information" = "We use system TTS for voice instructions. Many Android devices use Google TTS, you can download or update it from Google Play (https://play.google.com/store/apps/deta
Why translation become English?

2021-07-11 06:15 UTC, vng commented on data/strings/strings.txt
> +    pt = Olá!\n\nSegue em anexo meus favoritos do app Organic Maps. Por favor os abra se você tiver o Organic Maps instalado. Caso não tenha, baixe o app para o seu dispositivo iOS ou Android com o l
Why pt 2 times here?

2021-07-11 06:15 UTC, vng commented on data/strings/strings.txt
> +    pt = Crie uma conta no OpenStreetMap
"OpenStreetMap" is not needed here?

2021-07-11 06:15 UTC, vng commented on data/strings/strings.txt
> +    rro = Pentru instrucțiuni vocale utilizăm sistemul TTS. Multe dispozitive cu Android folosesc Google TTS. Puteți descărca sau actualiza aplicația din Google Play (https://play.google.com/store/ap
ro should remain unchnaged

2021-07-24 16:05 UTC, vng approved these changes

2021-07-24 22:01 UTC, merged