[android] Improve error handling when importing bookmarks
organicmaps/organicmaps pull request #7286
Opened 2024-01-31 11:12 UTC by rtsisyk

See #7149 #6944

2024-01-31 13:33 UTC, biodranik commented on data/strings/strings.txt
> +    comment = Failed to download a bookmark file.
Since when downloading of bookmarks is supported in OM?

2024-01-31 18:12 UTC, Jean-BaptisteC commented
Why not ask users to retry import, if the problem appears always in cold start?

2024-02-01 08:41 UTC, biodranik commented on data/strings/strings.txt
> +    comment = Failed to download a bookmark file.
Does it mean that OM can actually download bookmarks from remote URLs? Are there any proofs that its possible? AFAIU OM can open only local content URLs. Right?

Using the "Download" word now looks very misleading.

2024-02-01 08:42 UTC, biodranik requested changes
What exactly has been improved, and which behavior was changed?

2024-02-17 01:24 UTC, biodranik approved these changes

2024-02-17 01:24 UTC, biodranik commented on data/strings/strings.txt
> +    comment = Failed to recognize the format of a bookmark file.
```suggestion
    comment = Failed to recognize the format of a bookmarks or tracks file.
```
?

2024-02-17 01:24 UTC, biodranik commented on data/strings/strings.txt
> +    comment = Failed to open a bookmark file.
```suggestion
    comment = Failed to open a bookmarks or tracks file in Organic Maps
```

2024-02-17 01:24 UTC, biodranik commented on android/app/src/main/java/app/organicmaps/bookmarks/data/BookmarkManager.java
> +      Logger.e(TAG, "Could not download bookmarks file from " + uri, e);
Will removed `ex.printStackTrace();` help us to decode errors in logs?

2024-03-06 09:56 UTC, merged