Fixed PP and classifier types prio.
organicmaps/organicmaps pull request #7346
Opened 2024-02-09 17:51 UTC by vng

2024-02-09 18:37 UTC, RedAuburn requested changes
emptyTitle is never set to true, so poi with no name display with no title, and type in secondary. maybe invert emptyTitle and set it to false after setting a title?

2024-02-09 20:49 UTC, biodranik approved these changes

2024-02-09 21:11 UTC, RedAuburn approved these changes

2024-02-10 12:33 UTC, pastk approved these changes
IMO a more comprehensive solution would be to sort by line (and area fill) drule priority (in case of feature types that have no overlays).

But this solution solves the particular #6652 bug too.

2024-02-10 12:48 UTC, merged