[android] Implement exporting of all bookmarks files
organicmaps/organicmaps pull request #7357
Opened 2024-02-10 20:39 UTC by rtsisyk

This is a simple and convenient implementation of #995 where all bookmark files are exported separately using ACTION_SEND_MULTIPLE. The further work on #995 may add an alternative option to pack all files into a KMZ archive. Kudos to @cyber-toad for making preliminary refactoring (a535f525).

Two new icons are from Material Design.

See also f1a335949 "Implement kml/kmz/kmb importer"

###

**Organic Maps (Debug, Light Theme) -> Organic Maps (Beta, Dark Theme)**

<img src="https://github.com/organicmaps/organicmaps/assets/1799054/e599ac30-4e44-4fcf-9d76-4d49193d52ec" width="350px" alt="Organic Maps (Debug)">
<img src="https://github.com/organicmaps/organicmaps/assets/1799054/1628ad3e-aac4-49d2-b4e3-2584c4dc2f6d" width="350px" alt="Organic Maps (Beta) before importing files">
<img src="https://github.com/organicmaps/organicmaps/assets/1799054/62fc112d-b67d-4a15-ba0a-a02fca5b1d0a" width="350px" alt="Export KML files dialog">
<img src="https://github.com/organicmaps/organicmaps/assets/1799054/4c7e3e26-52db-44ae-93df-bcf03f58df27" width="350px" alt="Organic Maps (Beta) after importing files">

**Organic Maps -> Google Drive**

<img src="https://github.com/organicmaps/organicmaps/assets/1799054/e010b0d6-eb6a-49ef-ab7f-2c3d1e375791" width="350px">
<img src="https://github.com/organicmaps/organicmaps/assets/1799054/dd7e027f-261d-4d81-b4ba-4e7046a688c3" width="350px">

**Organic Maps -> GMail**, **Organic Maps -> WhatsApp**

<img src="https://github.com/organicmaps/organicmaps/assets/1799054/5ae22770-a041-4592-bdd9-2fa89fecc5f8" width="350px">
<img src="https://github.com/organicmaps/organicmaps/assets/1799054/d318ebed-8279-42bd-a3d4-b538899ba443" width="350px">

**Google Drive (multiple files) -> Organic Maps** - works too

### KNOWN ISSUES

Issue 1. Empty lists

Empty lists are not imported and "Failed to import bookmark" message is displayed. All other files from the batch are imported.  This is a bug of the import code, not of this patch. It should be possible to import empty KML.

=> Fix separately.

Issue 2. **GPS Logger** and **Samsung Files** don't work because they don't set mime-type. Enabling `*/*` fixes them tool, but in this case the app is displayed for files that it can't handle.

```
      <intent-filter>
        <action android:name="android.intent.action.SEND_MULTIPLE"/>
        <category android:name="android.intent.category.DEFAULT"/>
        <data android:mimeType="*/*"/>
      </intent-filter>
```

=> Won't fix.

CC: @cyber-toad

2024-02-10 22:35 UTC, biodranik reviewed
1. How Samsung Files and GPX logger are related to this PR?
2. What is the value of sharing multiple _KMZ_ files instead of one KMZ file with everything inside?
3. The proposed approach may not work well when custom bookmark icons that are shared between different lists are supported.
4. To open these files in OM immediately, the https://github.com/organicmaps/organicmaps/issues/5402 should be implemented first, right?

2024-02-10 22:35 UTC, biodranik commented on map/bookmark_manager.cpp
> +    //SCOPE_GUARD(fileGuard, std::bind(&base::DeleteFileX, filePath));
This line deletes a temporary file on exiting the scope. What is unclear?

2024-02-11 07:45 UTC, Jean-BaptisteC commented
Export empty list:
```
Cmdline: app.organicmaps.debug
pid: 14686, tid: 14686, name: ganicmaps.debug  >>> app.organicmaps.debug <<<
#00 pc 00000000020dc6b0  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#01 pc 00000000020dc65c  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#02 pc 00000000020dc61c  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#03 pc 00000000020b2b88  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#04 pc 00000000020953f8  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (jni::ToJavaString(_JNIEnv*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)+32) (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#05 pc 000000000211dfec  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#06 pc 000000000211ddc8  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#07 pc 000000000211dd98  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#08 pc 000000000211dd48  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#09 pc 000000000211dd1c  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#10 pc 000000000211cdac  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#11 pc 0000000002370bac  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#12 pc 0000000002370b54  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (std::__ndk1::function<void (BookmarkManager::SharingResult const&)>::operator()(BookmarkManager::SharingResult const&) const+28) (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#13 pc 0000000002370aec  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#14 pc 0000000002370ac0  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#15 pc 0000000002370a58  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (std::__ndk1::__bind_return<std::__ndk1::function<void (BookmarkManager::SharingResult const&)>, std::__ndk1::tuple<BookmarkManager::SharingResult>, std::__ndk1::tuple<>, __is_valid_bind_return<std::__ndk1::function<void (BookmarkManager::SharingResult const&)>, std::__ndk1::tuple<BookmarkManager::SharingResult>, std::__ndk1::tuple<> >::value>::type std::__ndk1::__bind<std::__ndk1::function<void (BookmarkManager::SharingResult const&)> const&, BookmarkManager::SharingResult const>::operator()[abi:v170000]<>()+52) (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#16 pc 0000000002370a14  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#17 pc 00000000023709cc  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (void std::__ndk1::__invoke_void_return_wrapper<void, true>::__call<std::__ndk1::__bind<std::__ndk1::function<void (BookmarkManager::SharingResult const&)> const&, BookmarkManager::SharingResult const>&>(std::__ndk1::__bind<std::__ndk1::function<void (BookmarkManager::SharingResult const&)> const&, BookmarkManager::SharingResult const>&)+20) (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#18 pc 00000000023709a8  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#19 pc 000000000236f808  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (std::__ndk1::__function::__func<std::__ndk1::__bind<std::__ndk1::function<void (BookmarkManager::SharingResult const&)> const&, BookmarkManager::SharingResult const>, std::__ndk1::allocator<std::__ndk1::__bind<std::__ndk1::function<void (BookmarkManager::SharingResult const&)> const&, BookmarkManager::SharingResult const> >, void ()>::operator()()+24) (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#20 pc 000000000215acf4  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#21 pc 00000000020cc6b4  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (std::__ndk1::function<void ()>::operator()() const+20) (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#22 pc 00000000020c109c  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (android::GuiThread::ProcessTask(long)+64) (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#23 pc 00000000020c104c  /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/lib/arm64/liborganicmaps.so (Java_app_organicmaps_MwmApplication_nativeProcessTask+28) (BuildId: c0f3023d955e44bc6401bb38dffa3d6ef36ee3d7)
#29 pc 0000000000013f8c  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/base.apk!classes4.dex] (app.organicmaps.MwmApplication.lambda$forwardToMainThread$0+0)
#34 pc 0000000000013918  [anon:dalvik-classes4.dex extracted in memory from /data/app/~~0UpTr_pXdN4HJJuzlO8kuw==/app.organicmaps.debug-gdIKB2h34zOiSMnUyk-m9Q==/base.apk!classes4.dex] (app.organicmaps.MwmApplication$$ExternalSyntheticLambda0.run+0)
```

2024-02-11 12:30 UTC, Jean-BaptisteC commented
Maybe you can use same logic as user export one bookmark list?

2024-02-11 13:27 UTC, biodranik commented on map/bookmark_manager.cpp
> +    //SCOPE_GUARD(fileGuard, std::bind(&base::DeleteFileX, filePath));
Previous code:
1. Saved kml to a temporary file
2. Created kmz from that temporary kml
3. Shared kmz and deleted temporary kml.

2024-02-11 14:09 UTC, Jean-BaptisteC commented
Yes, I know
When you export one empty list, we shown a AlertDialog with text `unable to export empty list`

2024-02-12 16:00 UTC, cyber-toad commented
> @cyber-toad @biodranik let's decide on the next move here. I would like to have the bookmark export button in Android in any form before the end of this week. This PR solves this issue, and it doesn't contradict with the idea of #7365. #7365 can add on top of it by wiring the new code into `GetFileForSharing(BookmarkManager::KMLDataCollectionPtr collection)` without any need to change Android UI part.
> 
> I needed this “Export” button yesterday, but I understand that it will take some time to finish implementation of bundled KMZ and testing of corners cases in #7364. My proposal is to merge this PR for now (assuming that empty lists are fixed) and merge #7365 as soon as it is ready.
> 
> What do you think?

Personally I was a bit surprised to see some alternative implementation after we had a long discussion with a decision to make an export into single kmz file. I'm not sure that I got your idea about merging - so you suggest to initially have an export to multiple files and later change it to single kmz or keep it in parallel? I think that both options could be confusing for a user.

2024-02-13 01:25 UTC, biodranik commented
@cyber-toad the final feature should export only one kmz file, which is exactly what you're working on now. Roman wants an intermediate solution with many files until you finish that task. 


IMO Offering both is also not the OM way of solving issues. And it may not be user-friendly to release one feature and then change it to another. There is a value though in the intermediate solution, so I'm not against it.

2024-02-25 10:15 UTC, d4f5409d requested changes
🇭🇺 needs a small change

2024-02-25 10:15 UTC, d4f5409d commented on data/strings/strings.txt
> +    hu = Könyvjelzők és sávok exportálása
```suggestion
    hu = Könyvjelzők és útvonalak exportálása
```

2024-02-27 10:25 UTC, pastk commented
> @cyber-toad the final feature should export only one kmz file, which is exactly what you're working on now. Roman wants an intermediate solution with many files until you finish that task.
> 
> IMO Offering both is also not the OM way of solving issues.

UI-wise there could be just one button still. But it could save the bookmarks both in a big combined kmz (good for backup) and separate per-list files in a sub-folder perhaps (e.g. good to send only a subset of lists to a friend or edit specific lists using 3-party tools , etc.)

2024-02-28 08:03 UTC, closed without merging