[android] Make Web-Release icon color distinguishable from Google-Release
organicmaps/organicmaps pull request #7363
Opened 2024-02-11 15:07 UTC by rtsisyk

Since #7359 Web-Release can be installed alongside Google-Release. Change the icon color for Web-Release to be distinguishable.

![image](https://github.com/organicmaps/organicmaps/assets/1799054/f4a50bd6-ffab-4236-aeac-23f100b2fa0a)

2024-02-11 17:34 UTC, Misalf-git commented
I'd prefer something not alarmingly red.
Dark green?

2024-02-11 18:40 UTC, biodranik requested changes
Let's change the icon a bit (use a circle at the bottom?) and leave our original color. Red is bad.

2024-02-12 09:32 UTC, biodranik commented
Here is the icon. Can anyone help to invert the color to white, and change the background to the current green one? I always liked that nimbus version, it looks more like a pin on the Earth.

[LogoV_svg.svg.zip](https://github.com/organicmaps/organicmaps/files/14236784/LogoV_svg.svg.zip)

2024-02-12 17:18 UTC, dvdmrtnz commented
Why not invert the colors? Green icon on white background?

2024-02-18 18:58 UTC, biodranik approved these changes

2024-02-18 18:58 UTC, biodranik commented on android/app/src/webRelease/res/values/colors.xml
> +  <!-- Make Web-Release icon color distinguishable from Google-Release. //-->
What about web debug?

2024-02-22 07:32 UTC, merged