Update release notes
organicmaps/organicmaps pull request #7507
Opened 2024-03-03 18:18 UTC by rtsisyk

2024-03-03 18:22 UTC, vng commented
• OpenStreetMap data as of February 28

2024-03-03 18:23 UTC, Jean-BaptisteC commented
Missing to adds line about date of OSM data :)

2024-03-03 19:03 UTC, dvdmrtnz commented on android/app/src/fdroid/play/listings/ar/release-notes.txt
> +• Added recycling and elevation information to search result descriptions
Duplicated

2024-03-03 19:19 UTC, fitojb requested changes

2024-03-03 19:19 UTC, fitojb commented on android/app/src/fdroid/play/listings/ca/release-notes.txt
• Dades de l’OpenStreetMap al 28 de febrer
• Exportació de totes les adreces d’interès en un únic fitxer KMZ
• S’han afegit reciclatge i elevació a les descripcions dels resultats de la cerca
• S’han corregit diverses fallades
• Ja no es mostra «Opcions d’encaminament activades» quan s’usa el regle
• S’assenyalen els llocs accessibles amb cadira de rodes

… llegiu-ne més a: omaps.org/news

2024-03-03 19:19 UTC, fitojb commented on android/app/src/fdroid/play/listings/es-ES/release-notes.txt
• Datos de OpenStreetMap al 28 de febrero
• Exportación de todos los marcadores en un único archivo KMZ
• Agregados reciclaje y elevación a las descripciones de los resultados de búsqueda
• Corregidos varios cierres inesperados
• Ya no se muestra «Opciones de enrutamiento activadas» al usar la regla
• Se indican los lugares accesibles con silla de ruedas

… más información en: omaps.org/news

2024-03-03 19:31 UTC, fitojb commented on iphone/metadata/ca/release_notes.txt
• Dades de l’OpenStreetMap al 28 de febrer
• Exportació de totes les adreces d’interès en un únic fitxer KMZ
• Es permet canviar el color de la ruta
• Pantalla «Quant a» redissenyada
• Diverses fallades han estat corregides
• S’ha actualitzat el color principal de l’aplicació
• Els paràmetres «Mode nocturn» han canviat a «Aspecte»
• Ja no es mostra «Opcions d’encaminament activades» quan s’usa el regle
• Les pàgines dels llocs inclouen informació d’accessibilitat amb cadira de rodes
• Les descripcions als resultats de la cerca tenen informació de reciclatge i elevació

… entre altres correccions i millores. Visiteu https://omaps.org/news per a assabentar-vos-en!

2024-03-03 19:51 UTC, fitojb commented on iphone/metadata/es-ES/release_notes.txt
• Datos de OpenStreetMap al 28 de febrero
• Exportación de todos los marcadores en un único archivo KMZ
• Permite cambiar el color de la ruta
• Pantalla «Acerca de» rediseñada
• Se arreglaron varios cierres inesperados
• Se actualizó el color principal de la aplicación
• La configuración «Modo nocturno» se reemplazó por «Apariencia»
• Ya no aparece «Opciones de enrutamiento activadas» al usar la regla
• Las páginas de lugares incluyen información de accesibilidad con silla de ruedas
• Las descripciones en los resultados de las búsquedas muestran datos de reciclaje y elevación

… entre otros arreglos y mejoras. Visite https://omaps.org/news para conocer más al respecto.

2024-03-04 10:12 UTC, biodranik commented on android/app/build.gradle
> +  releaseStatus.set(ReleaseStatus.DRAFT)
Should it be merged? Let's document here what each value means.

2024-03-04 10:12 UTC, biodranik commented on android/app/src/fdroid/play/listings/ar/release-notes.txt
> +• Export all bookmarks as a single KMZ file
```suggestion
• Export (backup) and import all bookmarks as a single KMZ file
```

2024-03-04 10:12 UTC, biodranik commented on iphone/metadata/da/release_notes.txt
> +• Export all bookmarks as a single KMZ file
```suggestion
• Export (backup) and import all bookmarks as a single KMZ file
```

2024-03-04 10:12 UTC, biodranik commented on iphone/metadata/da/release_notes.txt
> +• Allow changing the track color
```suggestion
• Track colors can be edited
```

2024-03-04 10:12 UTC, biodranik commented on iphone/metadata/en-US/release_notes.txt
> +• OpenStreetMap data as of February 28
This looks too old. @vng can we release a newer, March version?

2024-03-04 11:09 UTC, GreenAloe commented on android/app/src/fdroid/play/listings/uk/release-notes.txt
• Дані OpenStreetMap станом на 28 лютого
• Експорт всіх міток в одному KMZ файлі
• Виправлено декілька помилок
• "Увімкнено налаштування об’їзду" більше не показується при використанні лінійки
• Включено інформацію про доступність інвалідних візків на сторінках місць
• Додано інформацію про переробку та висоту до описів результатів пошуку
…більше на omaps.org/uk/news

2024-03-04 11:24 UTC, GreenAloe commented on iphone/metadata/uk/release_notes.txt
• Дані OpenStreetMap станом на 28 лютого
• Експорт всіх міток в одному KMZ файлі
• Дозволено змінювали колір міршрутів
• Новий "Про Organic Maps" екран

• Виправлено декілька помилок
• Оновлено основний колір програми
• Нічний режим замінено налаштуванням Вигляд
• "Увімкнено налаштування об’їзду" більше не показується при використанні лінійки
• Включено інформацію про доступність інвалідних візків на сторінках місць
• Додано інформацію про переробку та висоту до описів результатів пошуку

…та різні виправлення та покращення, шукайте подробиці за посиланням omaps.org/uk/news

2024-03-04 15:09 UTC, merged