Add smoking information to maps
organicmaps/organicmaps pull request #7580
Opened 2024-03-13 11:05 UTC by wetneb

This is a first step towards displaying the smoking status of venues (#7577).

I added it as a type to make it searchable, following the treatment of `cuisine` and `wheelchair` information, but happy to keep it as a metadata attribute only if you prefer.

I couldn't figure out if I should regenerate `data/classificator.txt` and others myself in this PR, or if it should rather be left as a follow-up. Because I could not figure out how to regenerate those, I have made the changes manually there, by imitation. Happy to discard those changes if needed.

2024-03-13 13:24 UTC, vng commented
- Keep only in metadata. Even if we want to have _smoking_ search, we should invent some other logic (and for cuisine, recycling, ...)
- Take only top-5 tags? https://taginfo.openstreetmap.org/keys/smoking#values
- Make only 3 enum values to show in PP: like Yes, No, Outside (with separated and isolated)?

2024-03-13 15:16 UTC, wetneb commented
Thanks for the review!

> Make only 3 enum values to show in PP: like Yes, No, Outside (with separated and isolated)?

If we are to restrict to three values, then to me "separated" and "isolated" should rather be conflated with "yes", as they all indicate that *indoor* smoking is allowed.

2024-03-13 15:26 UTC, vng commented
>If we are to restrict to three values, then to me "separated" and "isolated" should rather be conflated with "yes", as they all indicate that indoor smoking is allowed.

Ok, of course, we can keep all values, but better to decide when we will show some status in PP. Will it be icons or text?
@dvdmrtnz

2024-03-13 15:30 UTC, vng requested changes

2024-03-13 15:30 UTC, vng commented on data/mapcss-mapping.csv
> +smoking|yes;1600;
These changes are non needed. And others in ./data/

2024-03-13 15:30 UTC, vng commented on generator/osm2meta.cpp
> +    return "yes";
I mean keep outside, yes, no, separated, isolated, dedicated values as-is.

But keep only 3 options when showing the status in the Place Page (not in this PR).

2024-03-14 07:05 UTC, dvdmrtnz commented
> > If we are to restrict to three values, then to me "separated" and "isolated" should rather be conflated with "yes", as they all indicate that indoor smoking is allowed.
> 
> Ok, of course, we can keep all values, but better to decide when we will show some status in PP. Will it be icons or text? @dvdmrtnz

There’s these emojis that could be used: 🚬  for smoking=yes and 🚭 for smoking=no. However if we want to show more values it will have to be in text.

2024-03-14 08:56 UTC, wetneb commented
I agree that an icon-based UI (like for wheelchair accessibility) is probably only doable to show a boolean. I made a mock-up of a text-based UI in the issue (#7577). I wonder to what extent we need to decide on one or another within this PR? Does it have any influence about how we store the metadata in the map?

If we are to use a boolean, then my intuition would be for it to answer the question of whether one can smoke indoors, as I would say that's the most relevant information, both for smokers and non-smokers. That would mean that`no` and `outside` would be displayed as non-smoking and `yes`, `separated`, `dedicated` would be displayed as smoking (`isolated` is a bit tricky, because although it allows indoor smoking, non-smokers will also be able to stay in a smoke-free space, so it feels a bit misleading to advertise the place as just "smoking").

If we go for this boolean scheme, then it would perhaps make sense to hide the icons on places that are outdoors-only. For instance in Germany we often have some "Biergarten" mapped separately from the bar they are associated with, and they are generally mapped with `smoking=yes`. Users could easily be confused by thinking they have looked up the entire place (including the indoor space) and infer from that that indoor smoking is allowed in the bar. If we want to implement this tweak then that's perhaps something that requires adaptations to the map generation (unless there is already sufficient metadata stored for the front-end to determine if a place is outdoors only).

2024-03-14 10:23 UTC, pastk commented
For wheelchair we also use icons for boolean yes/no only, but when its "partial/limited" then a longer text is displayed - I find this logic fine and it could be applied for the smoking case as well.

2024-03-19 18:55 UTC, wetneb commented
Let me know if there is anything that's needed on my side to get this merged. As I understand it, I need to wait for this to get merged before starting work on displaying this information in the Android app.

2024-03-20 19:52 UTC, vng commented
To all interested, please write your opinion here. Do we need this tag in the data?
https://taginfo.openstreetmap.org/keys/smoking#overview

I have doubts because the world almost has become non-smoke. As you can see, no + outside are > 80%, so is it really necessary? And to draw it in PP?

2024-03-20 20:21 UTC, pastk commented
> 
> I have doubts because the world almost has become non-smoke. As you can see, no + outside are > 80%, so is it really necessary? And to draw it in PP?

Its really hard to say without actually looking at the data in more detail...

Options:
- merge, generate new maps w/ that info, add UI (prototype at least), then beta test and rely on users' feedback to see if its useful in different regions
- make some OSM queries (overpass?) in different regions and analyze the tagging and correspondence to local laws and culture

Both seems like quite an effort..

2024-03-20 21:23 UTC, patepelo commented
> To all interested, please write your opinion here. Do we need this tag in the data? https://taginfo.openstreetmap.org/keys/smoking#overview
> 
> I have doubts because the world almost has become non-smoke. As you can see, no + outside are > 80%, so is it really necessary? And to draw it in PP?

I'm not a smoker so I may be biased. I find the enrichment of POI info with tags necessary and OSM data in some regions is starting to be rich enough for many features. The problem is that we're approaching each feature individually. Without looking at longer horizon on how the place page would look like when we add other features such as:

Example:
- Dogs/Pets allowed
- Seating available outside
- Takeaway only
- Reservations accepted
- Cash payment only
- Draft beers available
- [...]
And the list could be very long. 

So yeah, we should start thinking of scaling this UI to start implementing these tags. 

Attached are some screenshots of examples from GMaps and Mapycz. 

- So I would oppose an icon approach for this feature, specially since over 80% of the values are "no" and start thinking of listed values.

- As per the options, I would also oppose "Smoking: Yes" and instead go for "- Smoking allowed"; "-Smoking forbidden", "Smoking allowed outside" (or "Smoking allowed partially"). As per adding the editor feature, I would leave it for a later issue to test first. Maybe adding "Smoke free space" or something alike would be more positive. 

- To the feature of being able to search for this feature, I can't give an opinion on how a user would search for that. Search for smoking allowed and the suddenly a mix of bars and restaurants? Would a user prefer a different place only because they're allowed to smoke? Would a different user prefer a smoke free place because the user is quitting smoking? Maybe these are rare cases. I wouldn't add them at the moment IMO.


I think it's very positive that these meta data is added and really appreciate the volunteering on solving it. This one is a bit complex due to the kind of tag it handles and how OM can resolve adding such info without unintentionally highlighting too much a feature that could potentially send a subliminal message for an unhealthy habit. 

Let's hear more from different perspectives. 😄 

P.S. Screenshots of feature lists:

![Screenshot_20240320-215251](https://github.com/organicmaps/organicmaps/assets/23003127/d44ca3e5-1373-49d1-a1da-88c6a61d7006)
![Screenshot_20240320-215258](https://github.com/organicmaps/organicmaps/assets/23003127/153ac8b9-ecd4-46fa-93d7-539024c2db76)
![Screenshot_20240320-215523](https://github.com/organicmaps/organicmaps/assets/23003127/ac86df31-4796-493c-9557-22b446e492d9)

2024-03-20 21:37 UTC, biodranik commented
It would be great to avoid promoting smoking in any way. We're working on _Organic_ Maps, right?

It would be great to collect important real-world use-cases first, before introducing this feature, so more users can get benefits from it.

2024-03-20 23:28 UTC, wetneb commented
To react to @vng's concisely:

> I have doubts because the world almost has become non-smoke.

I wish you were right! But if you look at this [list of smoking bans from Wikipedia](https://en.wikipedia.org/wiki/List_of_smoking_bans) (in particular the map there) it's far from universal still.

>  As you can see, no + outside are > 80%, so is it really necessary? 

I'd be cautious about drawing conclusions from statistics on tag values, because it is probably far from a representative sample.

> It would be great to collect important real-world use-cases first, before introducing this feature, so more users can get benefits from it.

Let me give you my use case.

In Saxony (Germany) it is quite common for bars and other hospitality spaces to allow smoking. As a non-smoker I am really tired of ending up in bars where I am in contact with indoor smoking (be it `smoking=yes` or `smoking=separated`) because it makes me cough and my clothes stink afterwards. Finding out in advance if a place allows smoking is remarkably hard: it is rarely indicated on the website of the place (if it has one) and street imagery is rarely useful (signage is often absent or not very prominent). Google Maps does not give this information either, as far as I can tell.

So I believe offering this information would give OM a clear added value over Google Maps for people like me (and I think I am far from the only one here).

2024-03-21 09:25 UTC, pastk commented
> 
> In Saxony (Germany) it is quite common for bars and other hospitality spaces to allow smoking. As a non-smoker I am really tired of ending up in bars where I am in contact with indoor smoking (be it `smoking=yes` or `smoking=separated`) because it makes me cough and my clothes stink afterwards. Finding out in advance if a place allows smoking is remarkably hard: it is rarely indicated on the website of the place (if it has one) and street imagery is rarely useful (signage is often absent or not very prominent). Google Maps does not give this information either, as far as I can tell.
> 

That is a great example and a use case, thanks!

I think we'd want to avoid situations like this:
    - most of the places has a smoking status tagged
    - most of the places around allow indoor smoking
    - then a user will end up seeing a "smoking allowed" text or emoji very often while its not being of much use (as its kind of status quo there)
    - what will be useful: seeing a "smoking free/forbidden" text/emoji on a few places (as they are not very common there)

or this:
    - most of the places has a smoking status tagged
    - most of the places around forbid indoor smoking
    - then a user will end up seeing a "smoking forbidden" text or emoji very often while its not being of much use
    - what will be useful: seeing a "smoking allowed" text/emoji on a few places (as they are not very common there)

If just a fraction of places has a smoking status tagged then it doesn't matter that much IMO.

Have you had a chance to research `smoking=*` stats in e.g. Saxony?

2024-05-24 20:23 UTC, wetneb commented
> Have you had a chance to research smoking=* stats in e.g. Saxony?

In Saxony the rates of indoor smoking are pretty high, but I guess you probably want a broader overview to know if it's relevant to your user base at large. So I have started a more comprehensive review country by country:
https://wiki.openstreetmap.org/wiki/User:Pintoch/SmokingCountries#Table
Beyond the raw data I have also described the methodology a little - feedback welcome!

Out of this survey, I would say that smoking information is worth showing in those countries:
* Germany (or only in sub-regions of Germany if your country detector is sufficiently granular, sadly it's not the case for https://github.com/westnordost/countryboundaries which I used)
* Japan
* Indonesia
* Mexico
* Denmark
* Slovakia
* Croatia
* United Arab Emirates
* Serbia
* Belarus
* Bulgaria
* Vietnam
* Nepal
* Ecuador
* Kazakhstan
* Cuba
* Myanmar
* Morocco
* Tunisia
* Uzbekistan

But overall, I am not sure it's worth hard-coding a list of countries where this information should be shown or not. This is bound to be incomplete, prone to interpretation and disagreement and go out of date as the legislation evolve. I think it would be simpler to just show the information when it's provided in OSM - it's delegating the work of determining if it's locally relevant to OSM contributors themselves. After all, we have this:
https://wiki.openstreetmap.org/wiki/Good_practice#Don't_map_local_legislation_if_not_bound_to_specific_objects

If you think it's indeed worth including this information, I would be happy to update this PR and work on getting it merged.

2024-05-24 20:36 UTC, biodranik commented
I would prefer to avoid indirectly advertizing smoking in Organic Maps.

2024-05-24 20:54 UTC, patepelo commented
> I would prefer to avoid indirectly advertizing smoking in Organic Maps.

We could take the opportunity and flip the coin if we present it as a positive feature when a place is **smoke free** 🫁🍃

Think about hard smoking countries where legislation isn't helping and it'd be a positive thing to see in the PP.

I think the major stopping stone here is the previous discussion that we need to set a longer horizon for formatting the place page. We should make some prototypes of how we would fit everything together with all the tags available.

2024-06-04 12:45 UTC, pastk commented
@wetneb Thanks for your research!

> 
> If you think it's indeed worth including this information, I would be happy to update this PR and work on getting it merged.

For sure we can release it as an alpha/experimental build and ask for users' feedback.
So there is always a probability the PR won't be accepted in the end.
If you're fine taking this risk then please go on with the implementation!

And regardless of your choice whether to continue or not - thanks a lot for your effort and raising this up!

2024-06-26 08:40 UTC, wetneb commented
Given the mixed feedback I think this is unlikely to work out, so I will not work on this further.

2024-06-26 08:40 UTC, closed without merging