[generator] Strip the last slash from URLs to beautify them
organicmaps/organicmaps pull request #7693
Opened 2024-03-25 23:52 UTC by biodranik

Also slightly reduces the size of map files

2024-04-04 21:38 UTC, biodranik commented on generator/osm2meta.cpp
> +  auto const first = v.find('/', start);
@rtsisyk It doesn't search from the beginning. It searches from the _start_, which points _to the next symbol_ after `http://` or `https://` pfefixes.

2024-05-23 02:51 UTC, vng commented on generator/osm2meta.cpp
> +  auto const first = v.find('/', start);
Searching from the end can simplify this routine, at least:
```
if (!v.empty() && v.back() != '/')
  return;
```

2024-05-23 02:53 UTC, vng commented on generator/osm2meta.cpp
> +  auto const first = v.find('/', start);
2. ValidateAndFormat_XXX functions better to make like void ValidateAndFormat_XXX(string & v);

2024-05-23 06:27 UTC, biodranik commented on generator/osm2meta.cpp
> +  auto const first = v.find('/', start);
@vng perhaps I wasn't clear. The last slash after the host name, not the last slash at the end of URL:
`www.test.com/ => www.test.com`

Changing the last non-host slash may break the URL and lead to 404:
`www.test.com/folder/ => www.test.com/folder`

2024-05-23 06:35 UTC, biodranik commented on generator/osm2meta.cpp
> +  auto const first = v.find('/', start);
> ValidateAndFormat_XXX functions better to make like void ValidateAndFormat_url(string & v)

@vng Agree, it requires a separate refactoring of all other cases. Does it make sense to do it separately?

2024-06-29 20:56 UTC, vng requested changes

2024-06-29 20:56 UTC, vng commented on generator/osm2meta.cpp
> +  if (strings::StartsWith(v, kHttp))
else if

2024-06-29 20:56 UTC, vng commented on generator/osm2meta.cpp
> +  if (first == v.find_last_of('/') && first + 1 == v.size())
```if (first + 1 == v.size())``` is enough

2024-06-29 21:11 UTC, biodranik commented on generator/osm2meta.cpp
> +  if (strings::StartsWith(v, kHttp))
Good catch!

2024-06-29 21:15 UTC, biodranik commented on generator/osm2meta.cpp
> +  if (first == v.find_last_of('/') && first + 1 == v.size())
Right!

2024-06-29 21:17 UTC, biodranik commented
@vng thanks, fixed. PTAL

2024-06-29 21:32 UTC, vng approved these changes

2024-06-30 09:29 UTC, merged