[WIP] new residential garden colours
organicmaps/organicmaps pull request #7715
Opened 2024-03-28 14:31 UTC by RedAuburn

PR mainly opened to get opinions

before/after

![render](https://github.com/organicmaps/organicmaps/assets/26939824/4c8ebcaa-13f8-4ca6-bc3d-ad13bb25d5b6)

2024-03-28 14:55 UTC, Misalf-git commented
IMO 👍

2024-03-29 09:44 UTC, pastk commented
Actually this PR makes the color of regular gardens much lighter also (prev. they used a forest color), which is logical IMO as gardens are often about grass and garden/flower beds, trees are less common than a typical forest.

2024-03-29 09:45 UTC, pastk commented
But might be good to test on some bigger complex garden areas like around some palaces.

2024-03-29 09:56 UTC, pastk requested changes
ATM colors of various greenery become progressively darker when zooming in.

Fixing color of gardens to just one (quite dark) color might create unwanted/confusing combinations on some zoom levels.

IMO gardens should be a bit lighter than forests, but darker than parks.

2024-03-29 09:56 UTC, pastk commented on data/styles/clear/include/Basemap.mapcss
> +{fill-color: @green5;}
its good that gardens will have colors distinct from the forests now!

but before z15 garden will be darker than forests which is not logical IMO

and on z15 it'll be the same green5 for both

and from z16- a forest will be darker than a garden (which is fine IMO)

2024-03-29 09:57 UTC, pastk commented
Or maybe separate change of regular non-residential gardens color into a different PR..

2024-04-02 12:51 UTC, RedAuburn commented
> Or maybe separate change of regular non-residential gardens color into a different PR..

have removed those changes, i didn't actually mean to do that 😅
should be good now

2024-04-02 13:35 UTC, pastk commented
Maybe makes sense to make it more neutral in vehicle style also?
![image](https://github.com/organicmaps/organicmaps/assets/18434508/feaa6db6-238a-4dd3-bf29-36fa4e70362c)

2024-04-02 13:36 UTC, pastk approved these changes

2024-04-02 20:56 UTC, biodranik commented
The original master version is better than others ) But I won't block the PR, merge if you think it's an improvement.

2024-05-16 15:04 UTC, RedAuburn commented
i do think the colour is too saturated at the moment, but this PR isn't a good fix. ideally it'd be almost like the current display at high zoom, with proper fading through the lower zooms. the main issue is that gardens are still highly visible when they stop being rendered because they're too small.

2024-05-16 15:04 UTC, closed without merging