[store] 2024.06.02 Release Notes
organicmaps/organicmaps pull request #8364
Opened 2024-06-02 07:48 UTC by rtsisyk

-----------

This PR adds texts originally drafted in Etherpad by @pastk.  No editing other than minor re-ordering of iOS items was performed by me.

2024-06-02 08:42 UTC, biodranik requested changes

2024-06-02 08:42 UTC, biodranik commented on android/app/src/fdroid/play/listings/be/release-notes.txt
> +• add, edit, and display web links to menus of restaurants, bars, and other food services
```suggestion
• Дадзеныя OpenStreetMap па стане на 28 мая
• Пошук паштовых індэксаў ЗША і паштовых індэксаў у Вялікабрытаніі (GB)
• Абвяшчэнне вуліцы ў вербальных інструкцыях (уключыце яго ў наладах)
• Экспарт закладак і трэкаў у фармаце файла GPX
• Захавайце закладкі і трэкі ў лакальнае сховішча прылады
• Дадайце, рэдагуйце і адлюстроўвайце спасылкі на меню рэстаранаў, бараў і іншых харчовых паслуг
```

2024-06-02 08:42 UTC, biodranik commented on android/app/src/fdroid/play/listings/be/release-notes.txt
> +…more details at omaps.org/news
```suggestion
… больш падрабязна на omaps.org/news
```

2024-06-02 08:42 UTC, biodranik commented on android/app/src/fdroid/play/listings/fr-FR/release-notes.txt
>  …more details at omaps.org/news
```suggestion
• Données OpenStreetMap en date du 28 mai
• recherche de codes postaux américains et britanniques (GB)
• annonce des noms de rue dans les instructions verbales de changement de direction (veuillez l'activer dans les paramètres)
• exporter les signets et les traces au format GPX et les enregistrer localement
• ajouter, modifier et afficher des liens web vers des menus de restaurants, de bars et d'autres services de restauration

…plus de détails sur omaps.org/fr/news
```

2024-06-02 08:42 UTC, biodranik commented on android/app/src/fdroid/play/listings/fr-FR/release-notes.txt
>  …more details at omaps.org/news
@organicmaps/translations-fr please review the automated translation

2024-06-02 08:42 UTC, biodranik commented on android/app/src/fdroid/play/listings/de-DE/release-notes.txt
>  …more details at omaps.org/news
```suggestion
• OpenStreetMap-Daten, Stand: 28. Mai
• Suche nach US-Postleitzahlen und UK (GB)-Postleitzahlen
• Ansagen von Straßennamen in verbalen TTS-Abbiegeanweisungen (bitte in den Einstellungen aktivieren)
• Lesezeichen und Tracks im GPX-Dateiformat exportieren
• Speichern von Lesezeichen und Tracks auf einem lokalen Gerät
• Hinzufügen, Bearbeiten und Anzeigen von Weblinks zu Speisekarten von Restaurants, Bars und anderen gastronomischen Betrieben

…mehr Details unter omaps.org/de/news
```

2024-06-02 08:42 UTC, biodranik commented on android/app/src/fdroid/play/listings/de-DE/release-notes.txt
>  …more details at omaps.org/news
@organicmaps/translations-de please review the automated translation

2024-06-02 08:42 UTC, biodranik commented on android/app/src/fdroid/play/listings/ru-RU/release-notes.txt
> +• add, edit, and display web links to menus of restaurants, bars, and other food services
```suggestion
• Данные OpenStreetMap от 28 мая
• поиск по почтовым индексам в США и Великобритании
• объявления названий улиц в голосовых TTS-инструкциях при навигации (включается в настройках)
• экспорт меток и треков в формате GPX и сохранение их локально на устройстве
• добавление, редактирование и отображение веб-ссылок на меню ресторанов, баров и других заведений общественного питания
```

2024-06-02 08:42 UTC, biodranik commented on android/app/src/fdroid/play/listings/ru-RU/release-notes.txt
> +…more details at omaps.org/news
```suggestion
…и многое другое на omaps.org/ru/news
```

2024-06-02 08:42 UTC, biodranik commented on android/app/src/fdroid/play/listings/uk/release-notes.txt
> +• add, edit, and display web links to menus of restaurants, bars, and other food services
```suggestion
• Дані OpenStreetMap від 28 травня
• пошук за поштовими індексами в США та Великій Британії
• оголошення назв вулиць у голосових TTS-інструкціях під час навігації (вмикається в налаштуваннях)
• експорт міток і треків у форматі GPX і збереження їх локально на пристрої
• додавання, редагування та відображення веб-посилань на меню ресторанів, барів та інших закладів громадського харчування
```

2024-06-02 08:42 UTC, biodranik commented on android/app/src/fdroid/play/listings/uk/release-notes.txt
> +…more details at omaps.org/news
```suggestion
…і багато іншого на omaps.org/uk/news
```

2024-06-02 08:42 UTC, biodranik commented on android/app/src/fdroid/play/listings/ru-RU/release-notes.txt
> +• add, edit, and display web links to menus of restaurants, bars, and other food services
@rtsisyk any help with translations into the languages you speak is appreciated.

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/de-DE/release_notes.txt
> +• fix the non-business hours button in the Editor to work after midnight
```suggestion
• Synchronisierung von iCloud-Lesezeichen und -Titeln (EXPERIMENTAL, bitte in den Einstellungen aktivieren)
• Ansagen von Straßennamen in verbalen TTS-Abbiegeanweisungen (EXPERIMENTAL, bitte in den Einstellungen aktivieren) 
• Verwendung der Karte, wenn CarPlay verbunden ist
• Suche nach US-Postleitzahlen und UK (GB)-Postleitzahlen
• Lesezeichen und Tracks im GPX-Dateiformat exportieren
• neue OpenStreetMap-Daten ab dem 28. Mai
• Hinzufügen, Bearbeiten und Anzeigen von Weblinks zu Speisekarten von Restaurants, Bars und Lebensmitteldiensten
• fehlende Adressen in den Details von Fitnessstudios korrigiert
• Hinzufügen von "Gebäck" und "Kuchen" als Suchbegriffe
• Korrektur von Wikipedia-Links, die ein Fragezeichen enthalten
• CarPlay Textfarbe im dunklen Modus korrigiert
• mehr TTS-Sprachoptionen
• TTS-Wendeansagen unterbrechen Podcasts, anstatt sie zu unterdrücken
• Behebung einiger Schaltflächen, die beim Hinzufügen eines Ortes zur Karte verschwunden sind
• Fix: Ortsdetails werden nach der Bearbeitung eines Lesezeichens nicht aktualisiert
• die Nicht-Geschäftszeiten-Schaltfläche im Editor funktioniert jetzt auch nach Mitternacht
```

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/de-DE/release_notes.txt
> +Updated Czech, German, Portuguese translations.
```suggestion
Aktualisierte tschechische, deutsche und portugiesische Übersetzungen.

Bitte lesen Sie weitere Einzelheiten unter https://omaps.app/de/news
```

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/fr-CA/release_notes.txt
> +• fix the non-business hours button in the Editor to work after midnight
```suggestion
• synchronisation des signets et des pistes iCloud (EXPÉRIMENTAL, veuillez l'activer dans les paramètres)
• annonce du nom de la rue dans les instructions verbales de changement de direction (EXPÉRIMENTAL, veuillez l'activer dans les paramètres) 
• utilisation de la carte lorsque CarPlay est connecté
• recherche de codes postaux américains et britanniques (GB)
• exporter des signets et des traces au format GPX
• nouvelles données OpenStreetMap à partir du 28 mai
• ajouter, modifier et afficher des liens web vers les menus des restaurants, des bars et des services de restauration
• corriger les adresses manquantes dans les détails des centres de fitness
• ajout des mots-clés de recherche "pâtisseries" et "gâteaux
• Correction des liens Wikipédia contenant un point d'interrogation
• correction de la couleur du texte de CarPlay en mode sombre
• plus d'options vocales TTS
• Les annonces TTS interrompent les podcasts au lieu de les esquiver.
• Correction de certains boutons qui disparaissaient lors de l'ajout d'un lieu sur la carte.
• Correction des détails d'un lieu non mis à jour après la modification d'un signet.
• correction du bouton "heures non ouvrables" dans l'éditeur pour qu'il fonctionne après minuit
```

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/fr-CA/release_notes.txt
> +• fix the non-business hours button in the Editor to work after midnight
@organicmaps/translations-fr please proof-read

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/fr-CA/release_notes.txt
> +Updated Czech, German, Portuguese translations.
```suggestion

Mise à jour des traductions en tchèque, allemand et portugais.

Pour plus de détails, veuillez consulter le site https://omaps.app/fr/news
```

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/fr-FR/release_notes.txt
> +• fix the non-business hours button in the Editor to work after midnight
```suggestion
• synchronisation des signets et des pistes iCloud (EXPÉRIMENTAL, veuillez l'activer dans les paramètres)
• annonce du nom de la rue dans les instructions verbales de changement de direction (EXPÉRIMENTAL, veuillez l'activer dans les paramètres) 
• utilisation de la carte lorsque CarPlay est connecté
• recherche de codes postaux américains et britanniques (GB)
• exporter des signets et des traces au format GPX
• nouvelles données OpenStreetMap à partir du 28 mai
• ajouter, modifier et afficher des liens web vers les menus des restaurants, des bars et des services de restauration
• corriger les adresses manquantes dans les détails des centres de fitness
• ajout des mots-clés de recherche "pâtisseries" et "gâteaux
• Correction des liens Wikipédia contenant un point d'interrogation
• correction de la couleur du texte de CarPlay en mode sombre
• plus d'options vocales TTS
• Les annonces TTS interrompent les podcasts au lieu de les esquiver.
• Correction de certains boutons qui disparaissaient lors de l'ajout d'un lieu sur la carte.
• Correction des détails d'un lieu non mis à jour après la modification d'un signet.
• correction du bouton "heures non ouvrables" dans l'éditeur pour qu'il fonctionne après minuit
```

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/fr-FR/release_notes.txt
> +Updated Czech, German, Portuguese translations.
```suggestion
Mise à jour des traductions en tchèque, allemand et portugais.

Pour plus de détails, veuillez consulter le site https://omaps.app/fr/news
```

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/fr-FR/release_notes.txt
> +• fix the non-business hours button in the Editor to work after midnight
CC @organicmaps/translations-fr

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/ru/release_notes.txt
> +• fix the non-business hours button in the Editor to work after midnight
```suggestion
• экспериментальная синхронизация меток и треков в iCloud (включается в настройках)
• объявление названий улиц во время голосовой навигации (включается в настройках)
• наконец-то можно переключаться между телефоном и CarPlay
• поиск почтовых индексов США и Великобритании (GB)
• экспорт меток и треков в формате GPX
• новые данные OpenStreetMap по состоянию на 28 мая
• добавление, редактирование и отображение веб-ссылок на меню ресторанов, баров и заведений общественного питания
• исправлены ссылки на Википедию, содержащие вопросительный знак
• исправлен цвет текста CarPlay в темном режиме
• больше вариантов выбора языка для голосового сопровождения TTS
• голосовые объявления теперь прерывают подкасты вместо того, чтобы их приглушать
• исправлены кнопки, которые исчезали при добавлении места на карту
• исправлена кнопка нерабочего времени в редакторе, чтобы она работала после полуночи
```

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/ru/release_notes.txt
> +Updated Czech, German, Portuguese translations.
```suggestion
Обновлены переводы на чешский, немецкий и португальский языки.

Подробнее читайте на https://omaps.app/ru/news
```

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/uk/release_notes.txt
> +• fix the non-business hours button in the Editor to work after midnight
```suggestion
• експериментальна синхронізація міток і треків в iCloud (вмикається в налаштуваннях)
• оголошення назв вулиць під час голосової навігації (вмикається в налаштуваннях)
• нарешті можна перемикатися між телефоном і CarPlay
• пошук поштових індексів США та Великої Британії (GB)
• експорт міток і треків у форматі GPX
• нові дані OpenStreetMap станом на 28 травня
• додавання, редагування та відображення веб-посилань на меню ресторанів, барів і закладів громадського харчування
• виправлено посилання на Вікіпедію, що містили знак питання
• виправлено колір тексту CarPlay у темному режимі
• більше варіантів вибору мови для голосового супроводу TTS
• голосові оголошення тепер переривають подкасти замість того, щоб їх приглушати
• виправлено кнопки, які зникали під час додавання місця на карту
• виправлено кнопку неробочого часу в редакторі, щоб вона працювала після опівночі
```

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/uk/release_notes.txt
> +Updated Czech, German, Portuguese translations.
```suggestion
Оновлено переклади чеською, німецькою та португальською мовами.

Докладніше читайте на https://omaps.app/ru/news
```

2024-06-02 08:42 UTC, biodranik commented on iphone/metadata/de-DE/release_notes.txt
> +• fix the non-business hours button in the Editor to work after midnight
@organicmaps/translations-de please review

2024-06-02 10:22 UTC, biodranik commented on android/app/src/fdroid/play/listings/ru-RU/release-notes.txt
> +• add, edit, and display web links to menus of restaurants, bars, and other food services
If I had enough time I would not ask for help. Thanks for your understanding and support.

2024-06-02 13:32 UTC, louwers commented on android/app/src/fdroid/play/listings/nl-NL/release-notes.txt
> +• OpenStreetMap data as of May 28
```suggestion
• OpenStreetMap geüpdatet met data van 28 mei
• zoeken naar postcodes in de VS en het VK
• straatnamen worden aangekondigd tijdens het navigeren met spraakinstructies (in te schakelen in de instellingen), dankzij Will Bradley
• exporteren van bladwijzers en tracks in GPX-bestandsformaat
• bladwijzers en tracks lokaal opslaan
• toevoegen, aanpassen en tonen van links naar menus van restaurants, bars en andere eetgelegenheden
```

2024-06-02 15:42 UTC, matheusgomesms requested changes
PT and PT-BR review

2024-06-02 15:42 UTC, matheusgomesms commented on android/app/src/fdroid/play/listings/pt-BR/release-notes.txt
>  …more details at omaps.org/news
```suggestion
• Dados do OpenStreetMap de 28 de maio
• Pesquisa de CEPs dos EUA e do Reino Unido
• Anúncios de nomes de ruas em instruções verbais TTS (ative-o nas configurações), graças a Will Bradley
• Exporta favoritos e trilhas em formato GPX
• Salva favoritos e trilhas no armazenamento local do dispositivo
• Adiciona, edita e exibe links da web para cardápios de restaurantes, bares e outros serviços de alimentação

…mais detalhes em omaps.org/news
```

2024-06-02 15:42 UTC, matheusgomesms commented on android/app/src/fdroid/play/listings/pt-PT/release-notes.txt
>  …more details at omaps.org/news
```suggestion
• Dados do OpenStreetMap de 28 de maio
• Pesquisa de códigos postais dos EUA e do Reino Unido
• Anúncios de nomes de ruas em instruções verbais TTS (ative-o nas configurações), graças a Will Bradley
• Exporta favoritos e trilhos em formato GPX
• Salva favoritos e trilhos no armazenamento local do dispositivo
• Adiciona, edita e exibe links da web para cardápios de restaurantes, bares e outros serviços de alimentação

…mais detalhes em omaps.org/news
```

2024-06-02 15:42 UTC, matheusgomesms commented on iphone/metadata/pt-BR/release_notes.txt
> +• fix the non-business hours button in the Editor to work after midnight
```suggestion
• Novos dados OpenStreetMap de 28 de maio
• Backup do iCloud para favoritos e trilhas (EXPERIMENTAL, habilite-o nas configurações)
• Anúncios de nomes de ruas em instruções verbais TTS (EXPERIMENTAL, ative-o nas configurações)
• Use o mapa quando o CarPlay estiver conectado
• Pesquise CEPs dos EUA e do Reino Unido
• Exporte favoritos e trilhas em formato GPX
• Adicione, edite e exiba links da web para cardápios de restaurantes, bares e serviços de alimentação
• Correção de endereços ausentes em academias
• Adição de palavras-chave de pesquisa para "pastelaria" e "bolos"
• Correção de links da Wikipédia que contenham um ponto de interrogação
• Correção da cor do texto do CarPlay no modo escuro
• Mais opções de voz TTS
• Os anúncios TTS interrompem os podcasts em vez de evitá-los
• Correção de alguns botões que desapareciam ao adicionar um lugar ao mapa
• Correção de detalhes do local não atualizados após a edição de um favorito
• Correção do botão de horário sem funcionamento no Editor para funcionar depois da meia-noite
```

2024-06-02 15:42 UTC, matheusgomesms commented on iphone/metadata/pt-BR/release_notes.txt
> +Updated Czech, German, Portuguese translations.
```suggestion
Atualizadas as traduções de Alemão, Português e Tcheco.
```

2024-06-02 15:42 UTC, matheusgomesms commented on iphone/metadata/pt-PT/release_notes.txt
> +• fix the non-business hours button in the Editor to work after midnight
```suggestion
• Novos dados OpenStreetMap de 28 de maio
• Backup do iCloud para favoritos e trilhos (EXPERIMENTAL, habilite-o nas configurações)
• Anúncios de nomes de ruas em instruções verbais TTS (EXPERIMENTAL, ative-o nas configurações)
• Use o mapa quando o CarPlay estiver conectado
• Pesquise códigos postais dos EUA e do Reino Unido
• Exporte favoritos e trilhos em formato GPX
• Adicione, edite e exiba links da web para cardápios de restaurantes, bares e serviços de alimentação
• Correção de endereços ausentes em academias
• Adição de palavras-chave de pesquisa para "pastelaria" e "bolos"
• Correção de links da Wikipédia que contenham um ponto de interrogação
• Correção da cor do texto do CarPlay no modo escuro
• Mais opções de voz TTS
• Os anúncios TTS interrompem os podcasts em vez de evitá-los
• Correção de alguns botões que desapareciam ao adicionar um lugar ao mapa
• Correção de detalhes do local não atualizados após a edição de um favorito
• Correção do botão de horário sem funcionamento no Editor para funcionar depois da meia-noite
```

2024-06-02 15:42 UTC, matheusgomesms commented on iphone/metadata/pt-PT/release_notes.txt
> +Updated Czech, German, Portuguese translations.
```suggestion
Atualizadas as traduções de Alemão, Português e Tcheco.
```

2024-06-02 17:25 UTC, louwers commented on android/app/src/fdroid/play/listings/nl-NL/release-notes.txt
> +• search for US zip codes and UK (GB) postcodes
The English sentences need to be removed still and this one added:

```
…voor meer details zie omaps.org/news
```

2024-06-02 17:35 UTC, pastk approved these changes

2024-06-02 17:45 UTC, merged

2024-06-02 17:52 UTC, RicoElectrico commented on android/app/src/fdroid/play/listings/pl-PL/release-notes.txt
> +• add, edit, and display web links to menus of restaurants, bars, and other food services
• dane OpenStreetMap z 28 maja
• wyszukiwanie kodów pocztowych w USA i Wielkiej Brytanii
• zapowiadanie nazw ulic w komunikatach nawigacji (proszę włączyć w ustawieniach), autor Will Bradley
• eksport zakładek i śladów do pliku w formacie GPX
• zapis zakładek i śladów do lokalnej pamięci urządzenia
• dodawanie, edycja i wyświetlanie linków do menu restauracji, barów i pozostałej gastronomii

2024-06-02 17:52 UTC, RicoElectrico commented on android/app/src/fdroid/play/listings/pl-PL/release-notes.txt
>  …more details at omaps.org/news
…więcej szczegółów na omaps.org/news

2024-06-03 08:29 UTC, pastk commented
@organicmaps/translations please add / correct translations to your language!

We will merge them separately in a couple days.

2024-06-04 08:28 UTC, pastk commented
Last call for submitting translations!
- https://github.com/organicmaps/organicmaps/pull/8381

2024-06-04 11:08 UTC, RicoElectrico commented on iphone/metadata/pl/release_notes.txt
> +Updated Czech, German, Portuguese translations.
• synchronizacja zakładek i śladów do iCloud (EKSPERYMENTALNE, proszę włączyć w ustawieniach)
• zapowiadanie nazwy ulicy w komunikatach nawigacji z syntezatora mowy (EKSPERYMENTALNE, proszę włączyć w ustawieniach)
• możliwość używania mapy przy podłączonym CarPlay
• wyszukiwanie kodów pocztowych w USA i Wielkiej Brytanii
• eksport zakładek i śladów do pliku w formacie GPX
• nowe dane OpenStreetMap z 28 maja
• dodawanie, edycja i wyświetlanie linków do menu restauracji, barów i pozostałej gastronomii
• poprawione brakujące adresy w szczegółach centrów fitness
• dodane słowa kluczowe "ciastka" i "ciasta" w wyszukiwarce
• poprawione linki do Wikipedii zawierające znak zapytania
• poprawiony kolor tekstu w trybie ciemnym CarPlay
• więcej opcji syntezy mowy
• komunikaty nawigacji przerywają podcasty zamiast je ściszać
• poprawione niektóre przyciski znikające podczas dodawania miejsca do mapy
• poprawione szczegóły miejsca, które nie aktualizowały się po edycji zakładki
• poprawiony przycisk godzin zamknięcia w edytorze tak, aby działał po północy
Zaktualizowane tłumaczenia na czeski, niemiecki, portugalski.

2024-06-04 11:11 UTC, RicoElectrico reviewed
Done. Please note that people might have translated the "pastry" bit without looking at respective categories.txt - https://github.com/organicmaps/organicmaps/blob/master/data/categories.txt#L1077

2024-06-04 14:06 UTC, pastk commented
Thanks! Relnotes translations are closed now.

(unfortunately last PL updates won't make it to the AppStore probably as the release had been pushed for a review already...)