[ios] Cleaned up Place Page
organicmaps/organicmaps pull request #842
Opened 2021-07-11 17:24 UTC by biodranik

Removed stupid "KEY INFORMATION" label.

2021-07-12 08:42 UTC, vng commented
Нужно пофиксить начальную высоту выезда. Сейчас корявенько.

![image](https://user-images.githubusercontent.com/175612/125257464-1b2a5480-e306-11eb-86df-20f79e4a715e.png)

2021-07-12 09:37 UTC, biodranik commented
Наоборот, удобно, что сразу видно, что можно вытянуть.

1) Сейчас удобнее, чем было раньше с левой ненужной надписью.
2) Можем потом отдельно высоту тюнить. Я кстати попробовал, и не разобрался, как это сделать (серую область как убрать).

2021-07-12 11:35 UTC, vng commented
- То что левая надпись не нудна - я согласен.
- Уродски же смотрятся обрезаные координаты. Надо PP или вниз опустить или вверх дотянуть.

2021-07-12 16:10 UTC, Endem10n commented
Для пользователей понятно, что это BottomSheet, который вытягивается вверх, по иконке маленькой горизонтальной линии вверху View.
Частично открытый вариант с куском координат выглядит ужасно.

2021-07-13 07:36 UTC, vng commented
@Endem10n Такой иконки линии нет в Андроид.

2021-07-13 08:41 UTC, Endem10n commented
@vng D
В ночном режиме есть. Почему нету в обычном, непонятно, похоже на баг.
![Screenshot_20210713-103559](https://user-images.githubusercontent.com/86627724/125420330-50c823bc-3792-4a80-a71b-5e54dfe5d1c0.jpg)
![Screenshot_20210713-103536](https://user-images.githubusercontent.com/86627724/125420381-42f26056-4884-4a02-9f9f-87933d1ec2a7.jpg)

2021-07-13 09:00 UTC, biodranik commented
Белое на белом? :)

2021-07-13 09:31 UTC, Endem10n commented
@biodranik Да, похоже что так))

2021-07-13 16:06 UTC, biodranik commented
Как проще всего поправить? )

2021-07-14 14:05 UTC, Endem10n commented
@biodranik https://github.com/organicmaps/organicmaps/pull/858

2021-07-14 19:33 UTC, biodranik commented
Это ж надо, потратил больше часа времени, и так и не понял, где задаётся высота этих серых полосок между белыми блоками. Чешутся руки эти полотенца кода вычистить и переписать.

2021-07-15 15:58 UTC, vng commented
@biodranik Я даже не про серые/белые полоски писал, а высоту всего выезда PP. Просто увеличить (или уменьшить) ее чтобы координаты не были порезаны.

2021-07-25 20:05 UTC, biodranik commented
@vng Там как-то запутанно, я не смог с двух подходов разобраться с высотой.

2021-07-25 20:10 UTC, biodranik commented
@rtsisyk done

2021-07-27 14:06 UTC, vng commented
![image](https://user-images.githubusercontent.com/175612/127168168-89422df5-268b-44c8-b67d-4b94bdf6a981.png)

Проверь ещё PP букмарки. Вот как оно сейчас выглядит на мастере.

2021-07-28 08:43 UTC, vng commented
@biodranik Ты предлагаешь мержить сейчас с порезаными текстами? Может привлечем iOS повелителей в PR :)

2021-07-28 10:16 UTC, rtsisyk commented
Дайте потестировать прежде чем лить, серьезное изменение для юзера это.

2021-07-28 13:15 UTC, biodranik commented
PP надо в любом случае улучшить, там много корявостей, поэтому лучше до конца разобраться, как оно работает, и где эти отступы и высоты задаются.

2021-07-30 06:53 UTC, rtsisyk requested changes
iOS part [is not ready to push](https://github.com/organicmaps/organicmaps/pull/842#issuecomment-887543058), Android looks great. Let's extract Android part and push separately.

2021-09-15 21:31 UTC, biodranik commented
Посмотрите, стало лучше. @rtsisyk как отсюда нам в тестфлайт собрать, без мержа?

Отступы между секциями пока не нашёл где убрать или хотя бы уменьшить, но это можно потом будет сделать.

2021-09-15 21:33 UTC, biodranik commented
Не понимаю, почему фейлится strings check сейчас. Можете у себя проверить
`./tools/python/clean_strings_txt.py -s` ?

2021-09-22 20:21 UTC, vng approved these changes

2022-01-12 13:39 UTC, vng approved these changes

2022-01-12 13:44 UTC, merged