[strings] More clear hints when building a route
organicmaps/organicmaps pull request #8458
Opened 2024-06-13 10:32 UTC by biodranik

Now some new users are confused and do not understand that they should tap/select something on the map to build a route. This change should provide a better hint.

@Jean-BaptisteC can you please check if the longest translation fits/looks well with the smallest device width?

2024-06-13 10:33 UTC, biodranik commented on data/strings/strings.txt
> +    comment = User selected the destination by pressing Route To, but the current position is unknown. User needs to select a starting point of a route using search or by tapping on the map and then
@organicmaps/translations can you please help with proof-reading this translation in your language (or provide a clearer version)?

2024-06-13 10:33 UTC, biodranik commented on data/strings/strings.txt
> +    comment = User selected the start of a route by pressing Route From. Now the destination of a route should be selected using search or by tapping on the map and then pressing "Route To".
@organicmaps/translations can you please help with proof-reading this translation in your language (or provide a clearer version)?

2024-06-13 10:54 UTC, vgrigoriu commented on data/strings/strings.txt
> +    ro = Utilizați funcția de căutare sau atingeți ușor pe hartă pentru a adăuga un punct de plecare al traseului
You can leave off the "al traseului" at the end, to make it symmetrical with the one below.

2024-06-13 11:14 UTC, NeatNit commented on data/strings/strings.txt
> +    he = השתמש בחיפוש או הקש על המפה כדי להוסיף נקודת התחלה למסלול
```suggestion
    he = יש להוסיף נקודת התחלה למסלול באמצעות חיפוש או בלחיצה על המפה
```

2024-06-13 11:14 UTC, NeatNit commented on data/strings/strings.txt
> +    he = השתמש בחיפוש או הקש על המפה כדי להוסיף נקודת יעד
```suggestion
    he = יש לבחור נקודת יעד באמצעות חיפוש או בלחיצה על המפה
```

2024-06-13 11:38 UTC, jimcarst approved these changes
nl ok

2024-06-13 12:58 UTC, matheusgomesms requested changes
PT and PT-BR reviewed

2024-06-13 12:58 UTC, matheusgomesms commented on data/strings/strings.txt
> +    pt-BR = Use a busca ou toque no mapa para adicionar um ponto de destino
```suggestion
    pt = Use a busca ou toque no mapa para adicionar um ponto de destino
```

2024-06-13 12:58 UTC, matheusgomesms commented on data/strings/strings.txt
> +    pt-BR = Use a busca ou toque no mapa para adicionar um ponto de partida da rota
```suggestion
    pt = Use a busca ou toque no mapa para adicionar um ponto de partida do percurso
    pt-BR = Use a busca ou toque no mapa para adicionar um ponto de partida da rota
```

2024-06-13 14:30 UTC, muralito commented on android/app/src/main/res/values-es/strings.xml
> +	<string name="routing_add_start_point">Utiliza la búsqueda o toca en el mapa para añadir un punto de inicio de ruta</string>
I would keep it simple: "Utiliza la búsqueda o toca en el mapa para añadir el origen de la ruta"

2024-06-13 14:33 UTC, muralito commented on android/app/src/main/res/values-es/strings.xml
> +	<string name="routing_add_start_point">Utiliza la búsqueda o toca en el mapa para añadir un punto de inicio de ruta</string>
Or more simple: "Busca o toca en el mapa para añadir el origen de la ruta"

2024-06-13 14:34 UTC, muralito commented on android/app/src/main/res/values-es/strings.xml
> +	<string name="routing_add_finish_point">Utiliza la búsqueda o toca en el mapa para añadir un punto de destino</string>
I would keep it simple: "Utiliza la búsqueda o toca en el mapa para añadir el destino",
 or "Busca o toca en el mapa para añadir el destino"

2024-06-13 14:36 UTC, muralito commented on data/strings/strings.txt
> +    es = Utiliza la búsqueda o toca en el mapa para añadir un punto de destino
es=Busca o toca en el mapa para añadir el destino

2024-06-13 21:52 UTC, biodranik commented on data/strings/strings.txt
> +    es = Utiliza la búsqueda o toca en el mapa para añadir un punto de inicio de ruta
@fitojb  So what is the final phrase?

2024-06-26 16:45 UTC, Jean-BaptisteC approved these changes
✅ Pixel 6 - Android 14
Text fit properly with max text size

2024-06-26 16:45 UTC, Jean-BaptisteC commented on data/strings/strings.txt
> +    fr = Utilise la recherche ou tape sur la carte pour ajouter un point de départ d'itinéraire
fr = Utilise la recherche ou appuie sur la carte pour ajouter un point de départ

2024-06-26 16:47 UTC, vng approved these changes

2024-06-26 16:47 UTC, merged