[strings] Fix Polish translations
organicmaps/organicmaps pull request #8557
Opened 2024-06-24 17:23 UTC by biodranik

Fixes issue discovered in this comment: https://github.com/organicmaps/organicmaps/commit/0c3eb4f900957e615068c0d43bc2e46f451bc9a8#r143440343

A good example of how translations should work is here: https://localizely.com/language-plural-rules/

The main rule: `other` key should always be present to work. Our twine implementation doesn't handle it properly when `other` is missing. See 37a92fac952cc7f090ab708847a66598a2406b93 for details.

2024-06-24 21:31 UTC, soshial requested changes

2024-06-24 21:31 UTC, soshial commented on data/strings/strings.txt
I think that changing `many` to `other` is a wrong approach, especially that some languages (including Polish) have different wordforms for `many` (obiektów) and `other` (obiektu), see proof at the [Unicode official page](https://www.unicode.org/cldr/charts/45/supplemental/language_plural_rules.html#pl).

2024-06-24 21:40 UTC, biodranik commented on data/strings/strings.txt
Ok, then the right approach is to add _both_ `many` and `other`. Can you please suggest the code changes?

2024-06-24 22:18 UTC, soshial commented on data/strings/strings.txt
But why is `other` mandatory? I don't get it. I think, that Android deals with missing forms without a problem.

2024-06-24 22:36 UTC, biodranik commented on data/strings/strings.txt
You've just written above that other and many have different forms. This is the first reason. The second one I've mentioned before: is an issue in the Twine code. The plural patch was developed in Maps.Me and it doesn't handle the absence of `other`. You (or any other Ruby expert) may [check it out](https://github.com/organicmaps/twine/commit/38f1761ac9ee4207d7c761a8a23640b99f1cfee5) and fix it.

2024-06-26 16:01 UTC, biodranik commented on data/strings/strings.txt
Android definitely deals with only `many` without a problem. Our tool `twine` doesn't deal with it properly.

2024-06-27 16:44 UTC, soshial commented on data/strings/strings.txt
> +    pl:other = %d obiektów
pl:few = %d obiekty
pl:many = %d obiektów
pl:one = %d obiekt
pl:other = %d obiektu

2024-06-27 16:44 UTC, soshial commented on data/strings/strings.txt
> +    pl:other = %d miejsc
pl:few = %d miejsca
pl:many = %d miejsc
pl:one = %d miejsce
pl:other = %d miejsca

2024-06-27 16:45 UTC, soshial commented on data/strings/strings.txt
> +    pl:other = %d tras
pl:few = %d trasy
pl:many = %d tras
pl:one = %d trasa
pl:other = %d trasy

2024-06-27 16:46 UTC, soshial commented on data/strings/strings.txt
Added requested changes in comments

2024-06-27 18:43 UTC, biodranik commented on data/strings/strings.txt
Thanks, fixed!

2024-06-28 17:06 UTC, soshial approved these changes

2024-06-28 17:18 UTC, vng approved these changes

2024-06-28 17:18 UTC, merged