Fixed non-working Wikimedia links with ? character in a title
organicmaps/organicmaps pull request #8618
Opened 2024-07-02 19:09 UTC by alnzrv

Should fix https://github.com/organicmaps/organicmaps/issues/8505

2024-07-02 19:27 UTC, biodranik approved these changes
Thanks!

@vng PTAL

2024-07-02 19:27 UTC, biodranik commented on indexer/feature_meta.cpp
> +      v.insert(i + 1, "3F");  // ? => %3F
nit:
```suggestion
      v.insert(++i, "3F");  // ? => %3F
```

2024-07-02 19:27 UTC, biodranik commented on indexer/feature_meta.cpp
> +string Metadata::ToWikimediaCommonsURL(std::string v)
```suggestion
std::string Metadata::ToWikimediaCommonsURL(std::string v)
```

2024-07-02 21:22 UTC, biodranik commented
Please fix failing generator_tests and make the PR non-draft:

```
Running metadata_parser_test.cpp::Metadata_ValidateAndFormat_wikimedia_commons
FAILED
generator_tests/metadata_parser_test.cpp:216 TEST(md.Get(Metadata::FMD_WIKIMEDIA_COMMONS) == "Category:What If%3F (Bonn)") Category:What If? (Bonn) Category:What If%3F (Bonn) 
Test took 0 ms
```

2024-07-03 08:08 UTC, biodranik commented on generator/generator_tests/metadata_parser_test.cpp
> +  TEST_EQUAL(md.ToWikimediaCommonsURL("Category:What If? (Bonn)"), "https://commons.wikimedia.org/wiki/Category:What If%3F (Bonn)", ());
Are URLs with spaces opened properly on iOS and Android?

2024-07-03 09:59 UTC, biodranik commented on generator/generator_tests/metadata_parser_test.cpp
> +  TEST_EQUAL(md.ToWikimediaCommonsURL("Category:What If? (Bonn)"), "https://commons.wikimedia.org/wiki/Category:What If%3F (Bonn)", ());
Redirect means a slower server response. Does it make sense to replace spaces with underscores too? What other symbols should be escaped? Is there a full list of all category values to test?

2024-07-04 20:57 UTC, biodranik commented on indexer/feature_meta.cpp
> +  for (auto i = 0; i < v.size(); ++i)
If this code is similar/the same as `Metadata::ToWikiURL`, please move it into a reusable static function (or into the anonymous namespace), and call it from both these methods.

2024-08-05 04:58 UTC, biodranik commented on indexer/feature_meta.cpp
> +  for (auto i = 0; i < v.size(); ++i)
I'm not following the logic.
1. Why percent escaping is not needed?
2. Why the same code should not be reused but instead copy-pasted?

2024-08-29 09:02 UTC, biodranik requested changes
Any update here?

2024-08-30 13:22 UTC, biodranik commented
1. The link from (2) above is invalid when clicked from OSM. Is it a bad data issue?
2. Whats the next step?

2024-08-30 19:43 UTC, biodranik commented
Thanks for the detailed responses! Ok, let's remove the percent encoding (and update related tests), and unite this code for both Wikipedia and Wikimedia.

2024-11-07 00:54 UTC, vng commented
How to push forward?

2024-11-09 17:54 UTC, biodranik requested changes
Can you please rebase?

2024-11-09 17:54 UTC, biodranik commented on indexer/feature_meta.cpp
> +std::string Metadata::EncodeWikiURL(std::string v, int startIndex) {
The usage pattern suggests to avoid unnecessary copying:
```suggestion
void Metadata::EncodeWikiURL(int startIndex, std::string & url)
{
```

2026-01-27 12:33 UTC, alnzrv commented on indexer/feature_meta.cpp
> +std::string Metadata::EncodeWikiURL(std::string v, int startIndex) {
Done

2026-01-27 12:45 UTC, alnzrv commented on generator/generator_tests/metadata_parser_test.cpp
> +  TEST_EQUAL(md.ToWikimediaCommonsURL("Category:What If? (Bonn)"), "https://commons.wikimedia.org/wiki/Category:What If%3F (Bonn)", ());
Spaces are replaced with underscores too. I didn't find any more characters to replace.

2026-01-27 22:45 UTC, alnzrv commented on indexer/feature_meta.cpp
> +  for (auto i = 0; i < v.size(); ++i)
1. Because there are no examples where it's needed. I covered it in this comment: https://github.com/organicmaps/organicmaps/pull/8618#issuecomment-2321232587
2. Fixed - now there is only one function.

2026-01-30 08:10 UTC, biodranik commented
@alnzrv squashing commits for a beautiful message may help )

2026-01-30 12:32 UTC, merged