Improved OSM log out text
organicmaps/organicmaps pull request #9056
Opened 2024-08-22 15:09 UTC by map-per

fixes  #9046

Changed the logout text from "Are you sure you want to continue?" to "Are you sure you want to log out of your OpenStreetMap account?"

The `are_you_sure` string is not used anywhere else, so it can be changed safely.

| before | now |
|--------|--------|
|![Screenshot_2024-08-22-17-05-43-286_app organicmaps beta](https://github.com/user-attachments/assets/37f44e16-7665-4ec9-89ff-559b794b92e6)|![Screenshot_2024-08-22-16-59-20-472_app organicmaps debug](https://github.com/user-attachments/assets/2be88278-0f6e-469f-86f5-99d7acf56f9b)|

2024-08-22 16:46 UTC, biodranik commented
Thanks! It would be better to also change the id, as the current translation may be required in some other places later.

2024-08-22 19:19 UTC, map-per commented
:+1: I will change it to `osm_log_out_confirmation`

2024-08-22 19:27 UTC, NeatNit commented
In Hebrew I can't find a way to translate it gender-neutrally. The 'sure' is unavoidably gendered. The auto translation is fine.

2024-08-22 19:36 UTC, muralito commented
> In Hebrew I can't find a way to translate it gender-neutrally. The 'sure' is unavoidably gendered. The auto translation is fine.

Same issue in spanish.

Some gender neutral option in spanish could be: "Quiere cerrar la sesion con la cuenta de OpenStreetMap"  ("Quiere" is more or less in english "Do you want to..."). Maybe that helps...

2024-08-22 19:38 UTC, muralito commented on android/app/src/main/res/values-es/strings.xml
gender neutral, just; "¿Desea salir de su cuenta de OpenStreetMap?" or "¿Quiere salir de su cuenta de OpenStreetMap?"

2024-08-22 19:40 UTC, muralito commented on data/strings/strings.txt
> +    es = ¿Está seguro de que desea salir de su cuenta de OpenStreetMap?
Shorter and gender neutral alternatives "¿Quiere salir de su cuenta de OpenStreetMap?" or "¿Desea salir de su cuenta de OpenStreetMap?"

2024-08-22 20:20 UTC, strump commented
Should we also add **"You local edits will not be shared with the OSM community!"** or simmilar notification to the message?

2024-08-23 04:26 UTC, vgrigoriu commented on data/strings/strings.txt
> +    ro = Sunteți sigur că doriți să vă deconectați din contul OpenStreetMap?
Gender-neutral alternative:
```suggestion
    ro = Sigur doriți să vă deconectați din contul OpenStreetMap?
```

2024-08-23 07:00 UTC, map-per commented
> Should we also add "You local edits will not be shared with the OSM community!" or simmilar notification to the message?

I'm not sure, but I think adding that would be overdoing it. I think it's obvious, at least for most users, that uploading only works with an OSM account.

2024-08-23 09:11 UTC, matheusgomesms commented on data/strings/strings.txt
> +    pt = Tem a certeza de que quer sair da sua conta OpenStreetMap?
```suggestion
    pt = Tem certeza de que deseja sair da sua conta do OpenStreetMap?
```

2024-08-23 16:18 UTC, mpawelski commented on data/strings/strings.txt
> +    pl = Czy na pewno chce się Pan/Pani wylogować ze swojego konta OpenStreetMap?
Definitely too formal, should be:
"Czy na pewno chcesz się wylogować ze swojego konta OpenStreetMap?"

2024-08-26 20:35 UTC, d4f5409d requested changes
Hu needs a little change to apply formal language to make the app translation consistent.

2024-08-26 20:35 UTC, d4f5409d commented on data/strings/strings.txt
> +    hu = Biztos, hogy ki akarsz jelentkezni az OpenStreetMap fiókodból?
```suggestion
    hu = Biztos, hogy ki akar jelentkezni az OpenStreetMap fiókjából?
```

2024-08-28 15:20 UTC, map-per commented
Thank you for the reviews! I updated the translations and changed the id to `osm_log_out_confirmation`

2024-08-28 15:22 UTC, merged