[strings] Trails translations
organicmaps/organicmaps pull request #9095
Opened 2024-08-25 16:38 UTC by biodranik

Please check these translations: https://github.com/organicmaps/organicmaps/commit/eb95b8c5c36f630e1562492e7f2cb143d12ff903

2024-08-25 17:32 UTC, NeatNit requested changes
some changes needed in Hebrew

2024-08-25 18:06 UTC, matheusgomesms reviewed
PT and PT-BR review

2024-08-25 18:06 UTC, matheusgomesms commented on data/strings/types_strings.txt
> +    pt = Percurso difícil ou pouco visível
```suggestion
    pt = Trilho difícil ou pouco visível
```

2024-08-25 18:06 UTC, matheusgomesms commented on data/strings/types_strings.txt
> +    pt = Percurso muito difícil ou indistinguível
```suggestion
    pt = Trilho muito difícil ou indistinguível
```

2024-08-26 10:32 UTC, map-per commented on data/strings/types_strings.txt
> +    en = Expert or indistinguishable Trail
```suggestion
    en = Expert or pathless Trail
```

I'm not a native speaker, but does "indistinguishable" really make sense her? "Indiscernible" or "pathless" are better IMO.

2024-08-26 10:38 UTC, RedAuburn commented on data/strings/types_strings.txt
> +    en = Expert or indistinguishable Trail
pathless sounds strange. Indiscernible makes most sense IMO, but indistinguishable works too

2024-08-26 11:16 UTC, d4f5409d approved these changes
Hu LGTM

2024-08-26 12:15 UTC, jimcarst commented
nl is ok

2024-08-26 15:01 UTC, map-per commented on data/strings/types_strings.txt
> +    en = Expert or indistinguishable Trail
Pathless comes from the [Wiki](https://wiki.openstreetmap.org/wiki/Key:trail_visibility). But yes, a pathless path is to some degree an oxymoron.

2024-08-26 15:27 UTC, Arthur-GYT approved these changes
LGTM for French

2024-08-29 15:56 UTC, mpawelski commented on data/strings/types_strings.txt
> +    pl = Bardzo trudny lub nierozróżnialny szlak
"Bardzo trudny lub niedostrzegalny szlak" sounds better

2024-09-03 17:11 UTC, biodranik commented on data/strings/types_strings.txt
> +    pl = Bardzo trudny lub nierozróżnialny szlak
Thanks! Fixed.

2024-09-03 17:11 UTC, biodranik commented
@vng PTAL

2024-09-19 20:08 UTC, merged