[editor] Fix "outdoor_seating=no is added to all POIs by the editor"
organicmaps/organicmaps pull request #9110
Opened 2024-08-26 10:58 UTC by Arthur-GYT

All is in the title ^^.

Close #9049

2024-08-26 11:48 UTC, biodranik reviewed
Will it work if user selects `No` explicitly? `No` value should be also saved if select explicitly by user (not by default)

2024-08-26 11:48 UTC, biodranik commented on android/app/src/main/java/app/organicmaps/editor/Editor.java
> +    if(switchValue && nativeGetMetadata(id).isEmpty())
```suggestion
    if (switchValue && nativeGetMetadata(id).isEmpty())
```

2024-08-26 13:12 UTC, Arthur-GYT commented
> Will it work if user selects `No` explicitly? `No` value should be also saved if select explicitly by user (not by default)

Not actually. Wouldn't we go for a system similar to self-service with just 2 options?

2024-08-26 14:25 UTC, biodranik commented
self-service is implemented in the wrong way at the core and should be refactored, I mentioned it in one of the comments some days ago.

Can you please remind the current status of this feature? Does the generator filter out everything and leave only YES values, or does it store YES and NO?

2024-08-26 14:55 UTC, biodranik commented
Then your code should do the following:
- Set YES if user selected YES
- Set NO if user selected NO
- Do not set anything if user did not explicitly specified YES or NO

2024-08-26 15:22 UTC, Arthur-GYT commented
@biodranik It should be OK now. When the user interacts with the switch, it detects that there is a change.

2024-08-26 15:41 UTC, biodranik commented
How other editable properties are implemented? Are there other similar to outdoor seating? Should it be a similar approach?

2024-08-27 08:41 UTC, map-per commented
> How other editable properties are implemented?

I tested the implementation of 'Wifi', turns out that 'Wifi' doesn't work: #9126

2024-08-29 08:56 UTC, biodranik commented
@map-per @Arthur-GYT and what about this PR? Does it have the same issue as https://github.com/organicmaps/organicmaps/issues/9126 ?

2024-08-30 06:50 UTC, map-per commented
No, #9126 should not be a problem, because removing outdoor_seating is not possible with this implementation, one can only set yes or no

2024-08-30 07:22 UTC, map-per reviewed
I tested the PR on Android and it works as intended.

I don't like the approach of looking at `onCheckedChanged` though. We should rather use an approach with three options (no, unknown, yes) like in the iOS PR #9117

On the other hand it is also important to solve the problem in time for the next release, because it is not good that OM adds about 10,000 wrong outdoor_seating entries to OSM per month at the moment. So this PR could be a good quickfix.

2024-08-30 08:46 UTC, Arthur-GYT commented
For this PR I've tested [Toogle button](https://m2.material.io/components/buttons#toggle-button) but it doesn't render :/

2024-08-30 08:50 UTC, Arthur-GYT commented
For the code bellow, I have this render

```xml
<RelativeLayout
    android:id="@+id/block_outdoor_seating"
    style="@style/MwmWidget.Editor.MetadataBlock.Clickable">
  <ImageView
      style="@style/MwmWidget.Editor.MetadataIcon"
      app:srcCompat="@drawable/ic_outdoor_seating"
      tools:ignore="ContentDescription" />
  <TextView
      style="@style/MwmWidget.Editor.FieldLayout.EditText"
      android:layout_width="match_parent"
      android:layout_height="wrap_content"
      android:layout_centerVertical="true"
      android:layout_marginStart="@dimen/editor_margin_left"
      android:layout_toStartOf="@+id/sw__outdoor_seating"
      android:text="@string/outdoor_seating"/>
  <com.google.android.material.button.MaterialButtonToggleGroup
      android:id="@+id/sw__outdoor_seating"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:layout_alignParentEnd="true"
      android:layout_centerVertical="true"/>
    <Button
        android:id="@+id/button1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Button 1"
        style="?attr/materialButtonOutlinedStyle"
        />
    <Button
        android:id="@+id/button2"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Button 2"
        style="?attr/materialButtonOutlinedStyle"
        />
  </com.google.android.material.button.MaterialButtonToggleGroup>
</RelativeLayout>
```

![image](https://github.com/user-attachments/assets/90f8debc-941d-4808-b136-a0385436cd7a)

2024-08-30 12:46 UTC, biodranik commented
We can undo the outdoor seating support if it is hard to fix it properly. Breaking OSM data is a blocker, and a hot fix is needed ASAP.

2024-08-30 17:57 UTC, biodranik commented
@map-per @Arthur-GYT please write your detailed opinion on how we should tackle this important bug, and why, in the context of this PR and https://github.com/organicmaps/organicmaps/pull/9165

2024-08-31 10:21 UTC, Arthur-GYT commented
Should be good now

![Screenshot_20240831-122038](https://github.com/user-attachments/assets/30789373-d677-4388-892a-5047886c87cf)

2024-08-31 10:24 UTC, Arthur-GYT commented
Note: The tag is only deleted on the client side, not on OSM. I haven't found how to do it :/

2024-08-31 11:40 UTC, dvdmrtnz commented
> Note: The tag is only deleted on the client side, not on OSM. I haven't found how to do it :/. Maybe a bug ??
> 
> EDIT: I think it's not possible yet to remove tags. I try with email input and it doesn't remove the tag on OSM.

* https://github.com/organicmaps/organicmaps/issues/6292

2024-08-31 11:48 UTC, Arthur-GYT commented
I think it's better with icons.

And thanks @dvdmrtnz ^^

![Screenshot_20240831-134733](https://github.com/user-attachments/assets/cfa941a7-3afe-4e79-ac8f-94d61006b2ea)

2024-08-31 11:52 UTC, dvdmrtnz commented
> I think it's better with icons.
> 
> And thanks @dvdmrtnz ^^
> 
> ![Screenshot_20240831-134733](https://private-user-images.githubusercontent.com/116185937/363411268-cfa941a7-3afe-4e79-ac8f-94d61006b2ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDUyMzAsIm5iZiI6MTcyNTEwNDkzMCwicGF0aCI6Ii8xMTYxODU5MzcvMzYzNDExMjY4LWNmYTk0MWE3LTNhZmUtNGU3OS1hYzhmLTk0ZDYxMDA2YjJlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxMTQ4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWNkNWNjOTc0Zjg0ODE4YWI5ODMxODJkOWM0ZGI3MzZjNDFkN2M3MGIzOTJkZGZhOGI4ZTk5ZjdkMWMzNTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lJwfiNj9Vq71of7jZjxeF2rNZrmvPVUZ8NoUaJSuWl4)

Looking good! Could you switch them around so they match the iOS orientation? "X" on the left and "✓" on the right? Like in https://github.com/organicmaps/organicmaps/pull/7835#issuecomment-2053664755 and https://github.com/organicmaps/organicmaps/pull/9117

2024-08-31 12:08 UTC, Arthur-GYT commented
> > I think it's better with icons.
> > And thanks @dvdmrtnz ^^
> > ![Screenshot_20240831-134733](https://private-user-images.githubusercontent.com/116185937/363411268-cfa941a7-3afe-4e79-ac8f-94d61006b2ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDUyMzAsIm5iZiI6MTcyNTEwNDkzMCwicGF0aCI6Ii8xMTYxODU5MzcvMzYzNDExMjY4LWNmYTk0MWE3LTNhZmUtNGU3OS1hYzhmLTk0ZDYxMDA2YjJlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMVQxMTQ4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OWNkNWNjOTc0Zjg0ODE4YWI5ODMxODJkOWM0ZGI3MzZjNDFkN2M3MGIzOTJkZGZhOGI4ZTk5ZjdkMWMzNTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lJwfiNj9Vq71of7jZjxeF2rNZrmvPVUZ8NoUaJSuWl4)
> 
> Looking good! Could you switch them around so they match the iOS orientation? "X" on the left and "✓" on the right? Like in [#7835 (comment)](https://github.com/organicmaps/organicmaps/pull/7835#issuecomment-2053664755) and #9117

It's done ^^

![Screenshot_20240831-140805](https://github.com/user-attachments/assets/59a2e6dc-32a0-44e8-9c8f-de0661987141)

2024-08-31 13:20 UTC, biodranik commented
What does "X" and "-" mean? Which one is "there is definitely no outdoor seating there" and "I don't know"?

2024-08-31 13:22 UTC, Arthur-GYT commented
> What does "X" and "-" mean? Which one is "there is definitely no outdoor seating there" and "I don't know"?

- "X" -> there is definitely no outdoor seating there
- "-" -> I don't know

2024-08-31 13:23 UTC, biodranik commented
How does this proposed cell look with a longer text translation in some other language, or with a very large system font size?

What was wrong with the text approach like self-service? With empty (or even better, "unknown") value for default state?

2024-08-31 13:39 UTC, Arthur-GYT commented
Simply changing the font size will hide the text on the left.

![Screenshot_20240831-153809](https://github.com/user-attachments/assets/f64a2e97-a82e-41e3-98d6-317c556be58c)

2024-08-31 13:40 UTC, Arthur-GYT commented
And for self-service, we have this result
![Screenshot_20240831-154004](https://github.com/user-attachments/assets/9c6b9937-caa6-482e-a031-590554c9130b)

2024-08-31 14:17 UTC, biodranik commented
That doesn't look good. Implementing it as self-service would be better (but please see https://github.com/organicmaps/organicmaps/issues/9182 )

2024-08-31 19:15 UTC, Arthur-GYT commented
> That doesn't look good. Implementing it as self-service would be better (but please see #9182 )

Even if I do a dialog, I need to use `editMapObject` and it reset the scroll animation.

2024-08-31 19:17 UTC, Arthur-GYT commented
As far as I'm concerned, the current solutioncan be good enough for a corrective version.

2024-09-01 09:30 UTC, map-per requested changes
#### Review

- I would not add a new `RemoveMetadata` function to the editor, but encode the 'unknown' value with an empty string using `SetMetadata`. Then the behavior is similar to when users remove e.g. the instagram link.

- For the space problems in the layout I see two solutions:
   - Stick to the segmented button but move it to the next line (In a new line there would also be enough space to write out the options instead of using symbols. I prefer the 'no' '-' 'yes' approach from iOS, then there is less dis-ambiguity between 'x' and '-' (even in this PR discussion there were already questions about what 'x' and '-' mean))
   - Use a drop down menue (#9182). On the downside this is one click more for the users, but on the upside the meaning of the options is clearer as we can write out all options
   
   I'm indifferent between the two options.

#### Hot fix
For now I would use  #9165 for the hotfix to prevent further `outdoor_seating=no` additions to OSM.

2024-09-01 13:22 UTC, Arthur-GYT commented
You're right, until we find a solution that satisfies everyone, it would be preferable to remove support for the tag while we merge this PR.

2024-09-07 19:31 UTC, map-per commented
No, the bug was fixed in #9165

2024-12-01 16:51 UTC, closed without merging