Added prison to categories.txt
organicmaps/organicmaps pull request #9475
Opened 2024-10-08 14:01 UTC by ProgramminCat

Resolves #9121

2024-10-09 19:56 UTC, vng approved these changes
Can't imagine who cares about the "prison" search category, but technically PR is ok ..

2024-10-09 19:57 UTC, vng commented
Any volunteers to translate?

2024-10-09 20:17 UTC, andergd requested changes

2024-10-09 20:17 UTC, andergd commented on data/categories.txt
> +amenity-prison
Cannot PR but here it is in Spanish:

`es:cárcel`

And I don't know if will be used but also in Basque:

`eu:espetxe`

2024-10-09 20:21 UTC, biodranik commented on data/categories.txt
> +amenity-prison
en:prison
ar:السجن
be:турма
bg:затвор
ca:presó
cs:vězení
da:Fængsel
de:Gefängnis
el:φυλακή
es:cárcel|prisión
et:vangla
eu:espetxe|kartzela
fa:زندان
fi:vankila
fr:prison
he:כֵּלֵא
hi:कारागार
hu:börtön
id:penjara
it:prigione
ja:刑務所
ko:감옥
mr:तुरुंग
nb:fengsel
nl:gevangenis
pl:więzienie
pt:prisão
ro:închisoare
ru:тюрьма
sk:väzenie
sv:fängelse
sw:jela
th:คุก
tr:hapishane
uk:в'язниця
vi:nhà tù
zh-Hans:监狱
zh-Hant:監獄

2024-10-09 20:34 UTC, NeatNit commented on data/categories.txt
> +amenity-prison
Hebrew (he): בית כלא

2024-10-09 20:52 UTC, biodranik commented on data/categories.txt
> +amenity-prison
@NeatNit what's the difference with the autotranslation?

2024-10-09 21:00 UTC, NeatNit commented on data/categories.txt
> +amenity-prison
> @NeatNit what's the difference with the autotranslation?

Removal of Nikkud for one thing (the tiny dots and symbols around the letters), but the bigger difference is, my suggestion is the full term for prison (loosely "house of imprisonment") whereas the auto-translation is just the last word. It *can* be used on its own to mean pretty much the same thing but in my subjective opinion, my suggestion is the clearer term.

If you insist on the one-word name, then at least remove Nikkud: כלא

2024-10-09 21:28 UTC, biodranik commented on data/categories.txt
> +amenity-prison
This is for search, so two or more words/synonyms should be added (what users likely type in the search input box). Can you please write the final he:...|... string with all synonyms?

2024-10-10 00:59 UTC, muralito requested changes
Please add this spanish search terms for "prison" 

es:prisión|cárcel|penal|penitenciaría|presidio|correcional|centro penitenciario|centro de reclusión

2024-10-10 09:34 UTC, pastk commented
@ProgramminCat if you feel inspired please also add search terms for Arts and Crafts shops (`shop-craft`) - better in a separate PR.

2024-10-10 09:36 UTC, pastk commented
A sidenote - do we have a way to list all POI types that don't have search terms yet? Similar to https://github.com/organicmaps/organicmaps/pull/6796

2024-10-10 10:06 UTC, jimcarst commented on data/categories.txt
> +amenity-prison
nl is ok. There are too many synonyms and only this one is suitable for search.

2024-10-10 12:10 UTC, patepelo commented on data/categories.txt
> +es:prisión|cárcel|penal|penitenciaría|presidio|correcional|centro penitenciario|centro de reclusión
Totally agree, wantes to comment on this. This undermines search performance and accuracy.

Plese keep only: prisión|cárcel

2024-10-10 16:03 UTC, muralito commented on data/categories.txt
> +es:prisión|cárcel|penal|penitenciaría|presidio|correcional|centro penitenciario|centro de reclusión
Just remove them if it hurts performance, but the Spanish language is just like it is, with lots of variants and synonyms. I don't know statistics for the everyday use of those terms to choose which ones suits best for the use case. In worst case, the user would try searching for several of them until he gets the results.

2024-10-11 05:40 UTC, soshial commented
lv:cietums

2024-10-11 11:43 UTC, NeatNit commented on data/categories.txt
> +amenity-prison
> This is for search, so two or more words/synonyms should be added (what users likely type in the search input box). Can you please write the final he:...|... string with all synonyms?

Sorry, I missed this message until now. 

he:כלא|בית כלא|בית סוהר

2024-10-11 21:27 UTC, ProgramminCat commented
> @ProgramminCat if you feel inspired please also add search terms for Arts and Crafts shops (`shop-craft`) - better in a separate PR.

https://github.com/organicmaps/organicmaps/pull/9492

2024-10-11 21:46 UTC, Arthur-GYT approved these changes

2024-10-11 21:46 UTC, Arthur-GYT commented on data/categories.txt
> +fr:prison
LGTM

2024-10-12 10:29 UTC, NeatNit commented
Hebrew is out of order - the languages should be sorted alphabetically by language code. Otherwise Hebrew is good.

2024-10-12 15:08 UTC, pastk commented on data/categories.txt
> +zh-Hans:监狱
```suggestion
en:prison
ar:السجن
be:турма
bg:затвор
ca:presó
cs:vězení
da:Fængsel
de:Gefängnis
el:φυλακή
es:prisión|cárcel
et:vangla
eu:espetxe|kartzela
fa:زندان
fi:vankila
fr:prison
he:כלא|בית כלא|בית סוהר
hi:कारागार
hu:börtön
id:penjara
it:prigione
ja:刑務所
ko:감옥
lv:cietums
mr:तुरुंग
nb:fengsel
nl:gevangenis
pl:więzienie
pt:prisão
ro:închisoare
ru:тюрьма
sk:väzenie
sv:fängelse
sw:jela
th:คุก
tr:hapishane
uk:в'язниця
vi:nhà tù
zh-Hans:监狱
```
Re-sorted all lines

2024-10-12 18:38 UTC, pastk approved these changes

2024-10-13 20:23 UTC, pastk commented
@ProgramminCat please remove Latvian `lv:cietums` for now - it causes tests to fail (Latvian should be enabled properly elsewhere, it'll be done in #9486)

2024-10-14 16:13 UTC, merged

2024-10-16 03:16 UTC, Colonel-Dixie commented on data/categories.txt
> +ar:السجن
ar:السجن needs improvement, it translate to "the prison"    
The correct one should be ar:سجن which is just " prison.

2024-10-22 20:36 UTC, pastk commented on data/categories.txt
> +ar:السجن
Thanks!
https://github.com/organicmaps/organicmaps/pull/9555