[android] Add Kayak setting: opt-in on F-Droid and an easy opt-out for other builds
organicmaps/organicmaps pull request #9820
Opened 2024-12-04 18:39 UTC by pastk

Adds a new setting to enable/disable Kayak.com affiliate links.
- based on #6720 

- closes https://github.com/organicmaps/organicmaps/issues/6773
- partially solves https://github.com/organicmaps/organicmaps/issues/7342

![image](https://github.com/user-attachments/assets/2d8f90a1-e122-4f36-9616-17e3cc2018c1)

F-Droid flavor:
- make Kayak links opt-in / disabled by default (unless a user had already accepted the Kayak disclaimer before)
- if explicitly enabled by a user, then no need to display a disclaimer dialog for the first use
- links contain a referral part hence OM will get a referral bonus for bookings (reverts #7262)

Other flavors:
- added a button to easily disable Kayak links from the first-use disclaimer dialog

![image](https://github.com/user-attachments/assets/795950d1-bec6-426d-8fa6-1095380d1c0c)

2024-12-04 19:10 UTC, Misalf-git commented
> - if explicitly enabled by a user, then no need to display a disclaimer dialog for the first use

Maybe I don't get it.
Wouldn't the dialog, especially with its "details ..." button, still be useful for _any_ first time user?
A user might have toggled the setting on/off out of curiosity or even accidentally.

2024-12-04 19:31 UTC, pastk commented
> 
> Maybe I don't get it. Wouldn't the dialog, especially with its "details ..." button, still be useful for _any_ first time user?

(the "Details on Kayak" button just proceeds to kayak.com link)

There is a detailed description of the setting, its more detailed than the disclaimer dialog even. So if a user have explicitly enabled it then I assume they have accepted it and there is no need to show and accept the same disclaimer second time..

> A user might have toggled the setting on/off out of curiosity or even accidentally.

Could happen, but its a niche case. We can also say that a user might have accepted the first-use disclaimer dialog accidentally / out of curiosity... But we won't add another "Are you really-really sure?" dialog, right? :)
Anyway the setting is there still and the user can return to it at any time.

2024-12-05 22:31 UTC, biodranik commented
What about showing a "More information" button and display "Unfortunately, some FDroid folks are against displaying more detailed information about a hotel with a minor referral bonus to support Organic Maps if you book it. You can use Organic Maps from Google Play, AppGallery, or Obtainium to support the project" ?

2024-12-06 11:30 UTC, pastk commented
> I am more inclined to remove it entirely, as it doesn't make sense in its current state.

But what about users who find this feature convenient?

2024-12-06 11:35 UTC, pastk commented
> with a minor referral bonus to support Organic Maps if you book it. You can use Organic Maps from Google Play, AppGallery, or Obtainium to support the project" ?

Actually this PR brings F-Droid OM users a possibility to support OM via referral bookings. There was no such option since https://github.com/organicmaps/organicmaps/pull/7262

2024-12-12 21:50 UTC, merged

2024-12-12 22:04 UTC, pastk commented
@organicmaps/translations please review [strings changes](https://github.com/organicmaps/organicmaps/pull/9820/commits/7821c1d453c748952c8e193163a3f814c41267dd#diff-8e9891f34f779c3f69c75ce68b56207e638f199a26123422c079734a32496c7c) and post amendments here (if any) - I'll submit changes in a separate PR.

2024-12-13 10:27 UTC, matheusgomesms reviewed
PT and PT-BR reviewed

2024-12-13 10:27 UTC, matheusgomesms commented on data/strings/strings.txt
> +    pt-BR = Desativar o Kayak
pt-BR = Desativar Kayak

2024-12-13 10:27 UTC, matheusgomesms commented on data/strings/strings.txt
> +    pt-BR = Fotos, avaliações e links de reserva são exibidos para os hotéis que estão listados no Kayak.com. O bônus de indicação recebido por cada reserva feita por meio desses links é destinado ao
pt = São apresentadas fotografias, críticas e ligações de reserva para os hotéis que estão listados no Kayak.com. O bónus de referência recebido por cada reserva efetuada através destas ligações destina-se ao desenvolvimento do Organic Maps.
    pt-BR = Fotos, avaliações e links de reserva são exibidos para os hotéis que estão listados no Kayak.com. O bônus de indicação recebido por cada reserva feita por meio desses links é destinado ao desenvolvimento do Organic Maps.

2024-12-13 10:27 UTC, matheusgomesms commented on data/strings/strings.txt
> +    pt = Ligações de hotéis Kayak.com
pt = Ligações de hotéis do Kayak.com

2024-12-13 10:49 UTC, andergd requested changes
ES & EU revised

2024-12-17 13:55 UTC, pastk commented
Thanks for translation fixes, I've included them into https://github.com/organicmaps/organicmaps/pull/9882

2025-01-28 09:22 UTC, licaon-kter commented
Glad this is here now

Sad that it took >1 year and resulted in so many angry posts and toots from the team